### ISSUE TITLE
Update NBitcoin with latest bug fixes

### ISSUE THREAD

**Issue by mikedennis** [stratisproject/StratisBitcoinFullNode#1008]
Stratis NBitcoin is currently at 4.0.0.34, there have been several fixes since then. NBitcoin is currently at 4.0.0.51 What is our strategy for incorporating them? Case by case basis?

NOTE: There is already a PR for this fix https://github.com/MetacoSA/NBitcoin/commit/7fd1c358b920fdc6c75417f9f2646f2fc0f59585

**Comment by dangershony** [comment]
Indeed once we migrated away from the NBitcoin repo fork we will need to do it case by case.

**Comment by dangershony** [comment]
@mikedennis lets open an issue every time we need to brings updates instead of keeping an open issue
