### ISSUE TITLE
[NBitcoin] - Remove/Refactor BitcoinUrlBuilder as its only used in unit tests

### ISSUE THREAD

**Issue by fassadlr** [stratisproject/StratisBitcoinFullNode#1011]
We need to investigate removing or refactoring BitcoinUrlBuilder as it is only currently used in NBitcoin's unit tests.

**Comment by bokobza** [comment]
This should be quick and easy.

**Comment by quantumagi** [comment]
https://github.com/stratisproject/StratisBitcoinFullNode/pull/1016

**Comment by mikedennis** [comment]
PaymentTests is the only thing that uses this, which tests functionality in NBitcoin.Payment. Are we suggesting pruning the payment functionality from NBitcoin altogether or just refactoring the tests to use something other than BitcoinUrlBuilder?
