### ISSUE TITLE
[Consensus] Incorrect constant being used for Stratis PoW block reward

### ISSUE THREAD

**Issue by zeptin** [stratisproject/StratisBitcoinFullNode#1027]
In [PosConsensusValidator.cs](https://github.com/stratisproject/StratisBitcoinFullNode/blob/master/src/Stratis.Bitcoin.Features.Consensus/PosConsensusValidator.cs#L503-L509) the following code exists:

```
        public override Money GetProofOfWorkReward(int height)
        {
            if (this.IsPremine(height))
                return this.consensusOptions.PremineReward;

            return this.ConsensusOptions.ProofOfWorkReward;
        }
```

The constants are incorrectly being derived from two different places (consensusOptions vs ConsensusOptions). As a result the code currently considers a block reward of 50 to be correct, which is clearly wrong for the Stratis network.

This error presumably does not cause sync problems because there are no blocks on testnet/mainnet that have a block reward higher than the correct value of 4 (disregarding fees). It is not considered invalid to have a coinbase reward lower than the maximum defined by consensus.

The fix is simple, just change ConsensusOptions to consensusOptions. And introduce consensus tests to catch errors like this going forwards.

**Comment by dangershony** [comment]
Good spot is this solved by your recent PR?
