### ISSUE TITLE
StratisD no longer displays help for the "-help" command line argument

### ISSUE THREAD

**Issue by quantumagi** [stratisproject/StratisBitcoinFullNode#1052]
Exits with `Invalid 'addnode' parameter.`

**Comment by fassadlr** [comment]
@quantumagi will you look at fixing this? Don't want us both to create PRs ;)

**Comment by quantumagi** [comment]
@fassadlr, yes

**Comment by fassadlr** [comment]
@quantumagi awesome 👍

**Comment by bokobza** [comment]
@quantumagi I think this is done?

**Comment by quantumagi** [comment]
This issue is no longer occurring.
