### ISSUE TITLE
[PeerConnector] Node poorly connected when two -addnode used

### ISSUE THREAD

**Issue by Aprogiena** [stratisproject/StratisBitcoinFullNode#1083]
Very hard to say where the problem is, but I'm running three nodes, two of them (say nodes A and B) are well connected and the third has `-addnode` to those two. The thing is that this third (say node C) node is ONLY connected to those two even after very long time (like an hour of running). It seems weird. I would expect node C to get information about other good nodes from nodes A and B, because they are currently connected to some peers and they are happy with them. 

So the question is, is this intentional, if so, why?

Note that the node C starts with empty database.

**Comment by dangershony** [comment]
Check with @noescape00

**Comment by monsieurleberre** [comment]
Let me know if you have a piece of code or anything ready made to reproduce this issue, otherwise, I ll do it from scratch :)

**Comment by Aprogiena** [comment]
The only thing that is needed is to start node with 2 `-addnode` arguments pointed to real nodes. Then leave the node for a while and then check if the node is connected only to those 2 nodes or not.

**Comment by monsieurleberre** [comment]
I did that:
dotnet run -port=16124 -apiport=38021 -addnode="213.153.144.161" -addnode="84.200.92.185" -addnode="188.47.112.251" -datadir="C:\Users\matthieu\AppData\Roaming\StratisNode\stratis0"
dotnet run -port=16125 -apiport=38022 -addnode="213.153.144.161" -addnode="84.200.92.185" -addnode="188.47.112.251" -datadir="C:\Users\matthieu\AppData\Roaming\StratisNode\stratis1"
dotnet run -port=16126 -apiport=38023 -addnode="127.0.0.1:16124" -addnode="127.0.0.1:16125" -datadir="C:\Users\matthieu\AppData\Roaming\StratisNode\stratis2"

then got all these connections within a minute or 2:
=======Connections=======
      ::ffff:75.69.164.251:16178              R:329.10 KB/S     W:4.28 KB/S     QualityScore: 150   PendingBlocks: 0
      ::ffff:77.35.54.95:16178                R:231.62 KB/S     W:1.96 KB/S     QualityScore: 150   PendingBlocks: 0
      ::ffff:189.27.62.67:16178               R:32.85 KB/S      W:0.25 KB/S     QualityScore: 16    PendingBlocks: 1
      ::ffff:127.0.0.1:16124                  R:0.00 KB/S       W:0.00 KB/S     QualityScore: 50        PendingBlocks: 0
      ::ffff:127.0.0.1:16125                  R:0.00 KB/S       W:0.00 KB/S     QualityScore: 50    PendingBlocks: 0
      ::ffff:90.196.193.27:16178              R:0.00 KB/S       W:0.00 KB/S     QualityScore: 50        PendingBlocks: 0
      ::ffff:87.75.58.48:16178                R:367.16 KB/S     W:3.22 KB/S     QualityScore: 150   PendingBlocks: 0
      ::ffff:36.69.233.205:16178              R:154.29 KB/S     W:2.77 KB/S     QualityScore: 150   PendingBlocks: 0
      ::ffff:5.15.34.247:16178                R:230.06 KB/S     W:3.82 KB/S     QualityScore: 150       PendingBlocks: 0
      ::ffff:176.109.148.36:16178             R:263.84 KB/S     W:3.46 KB/S     QualityScore: 150   PendingBlocks: 0
      =================
      Total                                   R:1608.93 KB/S    W:19.76 KB/S
      ==========================


So it seems to be working :)
