### ISSUE TITLE
[PeerConnector + NetworkPeer] Connection to self

### ISSUE THREAD

**Issue by Aprogiena** [stratisproject/StratisBitcoinFullNode#1084]
If `peers.json`  file contains information about the node itself, it will try to connect to itself.

1) PeerConnector - should probably not allow this to happen, it should not open the connection and it should not try to discover other nodes from itself

2) NetworkPeer - should close that connection (at least it seems to me that the code is intended to do that, but it just doesn't work for some reason)

**Comment by dangershony** [comment]
This is the part of the code that detects connection to self.

```
            if (connectedToSelf)
            {
                this.logger.LogDebug("Connection to self detected and will be aborted.");

                VersionPayload versionPayload = this.Parameters.CreateVersion(this.PeerEndPoint, this.Network, this.dateTimeProvider.GetTimeOffset());
                await this.SendMessageAsync(versionPayload, cancellation).ConfigureAwait(false);
                this.Disconnect("Connected to self");

                this.logger.LogTrace("(-)[CONNECTED_TO_SELF]");
                return;
            }
```

We should probably remove the peer from our address manager store to prevent future connections to self.
```
  this.Disconnect("Connected to self");
  // delete the address from address manager
```

**Comment by Aprogiena** [comment]
yes, this code was supposed to do that
I need to test it with PR part 23 whether it works or not

**Comment by fassadlr** [comment]
@Aprogiena I don't think that we can stop the connector connecting to itself because we have no way of knowing who the node is until we have received the nonce from the "other" node. 

Therefore, we must first connect, get the nonce, then disconnect... but also, as @dangershony suggested, we need to, at that point remove the peer from the address list so that we don't connect to it again.

**Comment by Aprogiena** [comment]
yeah, so it really does not work properly, the detection of self connection is done via comparing the nonce in version message and it seems that the nonce is always new if you create connection parameters instead of cloning them, so there can be the problem

**Comment by Aprogiena** [comment]
@fassadlr why can't compare the address to which we are going to connect with our own addresses? we should have list of internal and external network interfaces and ports, so i think we can recognize that

not that this part of the node would be ready, there is an issue about that somewhere (external addresses)

**Comment by fassadlr** [comment]
Yeah, so we probably need to check which of those static constructors and/or clone methods is called when and at what time. Cause some of them creates a new nonce and some of them sets it to another one.

**Comment by Aprogiena** [comment]
ok i found the problem with nonce, that i can fix easily i think

**Comment by fassadlr** [comment]
> why can't compare the address to which we are going to connect with our own addresses? we should have list of internal and external network interfaces and ports, so i think we can recognize that

Yes we also have the Loopback address on PeerAddress which we can compare with... We also set the ConnectionManagerSetting's ExternalEndpoint to the Loopback:

```
if (this.ExternalEndpoint == null)
{
    this.ExternalEndpoint = new IPEndPoint(IPAddress.Loopback, nodeSettings.Network.DefaultPort);
}
```

We can use that?

**Comment by fassadlr** [comment]
Actually, no that is always gonna be 127.0.0.1...

**Comment by Aprogiena** [comment]
basically we should have list of internal and external interfaces and compare against all of those

**Comment by Aprogiena** [comment]
the nonce problem i can resolve, but i can only do that after node job PR part 23 is merged, so i'll wait for that

**Comment by dangershony** [comment]
What is the problem with nonce?
>list of internal and external interfaces 

I assume you mean that would be specified in configuration?

I guess the nonce should be the same for every peer we connect to right?
I can't see a way how we can avoid connecting to get the nonce (we can use ExternalEndpoint ) but that is only specified by the user and can be null.

**Comment by dangershony** [comment]
>but i can only do that after node job PR part 23 

How come PR 23 a dependency?

**Comment by Aprogiena** [comment]
So part 24 should fix the second part of this issue. The peer will now be disconnected as the correct nonce is used and recognized.
