### ISSUE TITLE
nlog max log size configuration

### ISSUE THREAD

**Issue by noescape00** [stratisproject/StratisBitcoinFullNode#1086]
Some weird bugs require setting up logs for a lot of components which leads to generating gigabytes of log data. 
It will be probably a good idea to have an option to automatically remove old log messages when the log file size exceeds a certain threshold.  

Right now this is done by hand by just deleting the log files during the run so they get recreated.

**Comment by D3m0nKingx** [comment]
That could lead to logs getting deleted that might have the bug. I actually was talking about this with @MithrilMan, as he mentioned in slack about modifying it so logs would be deleted automatically.

**Comment by noescape00** [comment]
>That could lead to logs getting deleted that might have the bug.

Yeah. So it can be not a default option. Smth like maxLogData = 0 by default and when we need to debug something massive we set the max size to 1gb so when this limit is exceeded 10% of the oldest logs are cleaned. 
I think this mostly will be used under the developer's supervision so he can stop the node when he sees the bug.

**Comment by D3m0nKingx** [comment]
Yes, if it's under constant supervision then that works out, since he/she can just stop the node or copy over the relevant log files amidst any bugs that occurred. 

It's just when there's sometimes bugs that take hours to happen, and someone may not really want to watch every minute. Ofc I've seen first hand how quickly the log sizes grow to 1gb+ within an hour or less of running a node,  which actually isn't too too bad, especially if a user has Terabytes of storage space anyway.

So better point actually, is setting it to a max percentage of available drive space? rather than user defined size? Or just have both options? :)

**Comment by noescape00** [comment]
>It's just when there's sometimes bugs that take hours to happen, and someone may not really want to watch every minute. 

For those you shouldn't use the size limit 🙂 

The reason why we would like smaller logs is just that very few text editors can open such large files and none of them can perform search quickly. 

>So better point actually, is setting it to a max percentage of available drive space? 
I think available disk space in mb will be the best option.

**Comment by D3m0nKingx** [comment]
>The reason why we would like smaller logs is just that very few text editors can open such large files and none of them can perform search quickly.

Linux does :P Searching the logs from the command line is fairly quick.
 `grep -i <search word> <logfile>`. 
That being the simplest syntax, and using the grep command outputs anything it finds to the console as it searches through.  However, I can't speak for Windows, not sure what's available there. But the app Gedit in Linux handles large files, and displays the content as it's loading the file, there's also sublime and notepadqq (notepad++ for Win).

**Comment by noescape00** [comment]
yeah, I'm using both on windows (notepad and sublime) - they are lagging on scrolling and searching for me.

**Comment by Aprogiena** [comment]
@noescape00 i don't think this should be an issue, by default the node only uses logs that are rotated and small, large logs are only generated on user's demand and they can be rotated as well if the user wishes, that's just how they setup the conf file. so this is not an issue of a node imho
