### ISSUE TITLE
Invalid witness nonce size when syncing bitcoin testnet

### ISSUE THREAD

**Issue by mikedennis** [stratisproject/StratisBitcoinFullNode#1087]
[2018-01-21 19:31:22.0623 15] ERROR: Stratis.Bitcoin.Features.Consensus.ConsensusLoop.AcceptBlockAsync Block '00000000000f8fcaec75f47623ab8226d5b1ad2bdfe6945adf1703cbc7015c7d' rejected: invalid witness nonce size
[2018-01-21 19:31:22.0623 15] INFO: Stratis.Bitcoin.Features.Consensus.ConsensusLoop.AcceptBlockAsync You probably need witness information, activating witness requirement for peers.

My chain is not fully synced still syncing and I am getting this error a lot.

First occurrence of it was here

```[2018-01-21 18:55:22.3550 13] INFO: Stratis.Bitcoin.FullNode.<StartPeriodicLog>b__73_0 ======Node stats====== 01/21/2018 18:55:22 agent StratisBitcoin:1.0.7
Headers.Height:      1259815  Headers.Hash:     00000000554647a97334d85bd751cdf0c925ef300f3871ae763cdeca0d59f6dc
Consensus.Height:    1232928  Consensus.Hash:   000000005aff9fd709099cd3dc6658ae591ea77cec723092f3391fedd3546bc9
BlockStore.Height:   1232928  BlockStore.Hash:  000000005aff9fd709099cd3dc6658ae591ea77cec723092f3391fedd3546bc9
Wallet.Height:       1232927  Wallet.Hash:      00000000d6e36a0b4cef539d1c7a05c620a6f8f6d6b12cbdc117d21e27fd2bd1 
```

Might be related to #1028 #631

**Comment by mikedennis** [comment]
Some further info. After restarting it started downloading blocks again and then I started getting the errors. I restarted a couple of times and finally got all the blocks. Perhaps this is just do to gradually dropping/rejecting peers that are already attached that are non segwit? Maybe we should just require segwit nodes right from the beginning?

**Comment by dangershony** [comment]
Do you need to restart the node to continue downloading the chain?
I think we should just be able to recover and if not its a bug.

**Comment by mikedennis** [comment]
@dangershony I tried again. I was able to successfully sync the whole chain without restarting the node. So it is able to recover so I think this issue can likely be closed.

**Comment by dangershony** [comment]
Ok let me do a full sync myself as well
