### ISSUE TITLE
Persist mempool to disk: Flatfile?

### ISSUE THREAD

**Issue by Derrick-** [stratisproject/StratisBitcoinFullNode#109]
Bitcoin Core uses flat file for memory pool persistence.

Should we do the same, or should we put it in DBreeze?

If flat, should we make it a core compatible file, or use our own format?

**Comment by dangershony** [comment]
Its probably easier to use bdreeze.
This is lower priority though IMO

**Comment by Derrick-** [comment]
For ease, I'm finding flat file better. I started working on this using the same file format as bitcoin core, which is very simple.

Concerns are startup time, and I think a flat file may be faster.

**Comment by Derrick-** [comment]
Bah, I misread the code. mempool.dat is a binary file in bitcoin core.

**Comment by dangershony** [comment]
Yeah it will definitely perform better. It's much faster to write a massive byte array to disk.
