### ISSUE TITLE
Staking with many small outputs takes too much CPU

### ISSUE THREAD

**Issue by dangershony** [stratisproject/StratisBitcoinFullNode#1092]
After @noescape00 sent me many small outputs my CPU is out of control when staking.

![image](https://user-images.githubusercontent.com/7487930/35290665-cbce947a-0062-11e8-847a-26552ec34df1.png)

**Comment by noescape00** [comment]
Hmm. I tried to reproduce that one (700 UTXOs, 300 of them are .0001 tstrat)- no issue encountered.

**Comment by noescape00** [comment]
@dangershony do you encounter 100% CPU only while staking (so it's 100% and after some time it's low again) or all the time during the node run? 
Also what kind of CPU do you have and how many UTXOs you're staking? 
Maybe I didn't recreate some condition that you have .

**Comment by monsieurleberre** [comment]
Looking at this now
as part of issue https://github.com/stratisproject/StratisBitcoinFullNode/issues/1180 "Staking vulnerability", we will change staking algo to not use coins that have a value lower than 0.1 STRAT. This is a first step in helping to fix the issue.
Another step will probably be to put a cap on the number of UTXOs used, regardless of their value, while favouring bigger coins.

**Comment by noescape00** [comment]
@monsieurleberre after 1180 is done this issue can also be closed. 

>Another step will probably be to put a cap on the number of UTXOs used, regardless of their value, while favouring bigger coins.

Not sure if we would need that. Maybe just make threshold value to be configurable but default it to 0.01 or 0.1.
