### ISSUE TITLE
Node time not in sync with the network, display better warring message

### ISSUE THREAD

**Issue by dangershony** [stratisproject/StratisBitcoinFullNode#1097]
My blocks got rejected when my node was an hour behind, we should display this better on the console and the UI (same as X).

```
fail: Stratis.Bitcoin.Features.Consensus.ConsensusLoop[0]
      Block 'e0e61759872e112d67306a9cdd027953ffe4069027931d607cd2e82119bb9688' rejected: block timestamp too far in the future
fail: Stratis.Bitcoin.Features.Consensus.ConsensusLoop[0]
      Marking block 'e0e61759872e112d67306a9cdd027953ffe4069027931d607cd2e82119bb9688' as invalid until 2018-01-19 03:53:04.
fail: Stratis.Bitcoin.Features.Consensus.ConsensusLoop[0]
      Block 'e0e61759872e112d67306a9cdd027953ffe4069027931d607cd2e82119bb9688' rejected: block timestamp too far in the future
fail: Stratis.Bitcoin.Features.Consensus.ConsensusLoop[0]
      Marking block 'e0e61759872e112d67306a9cdd027953ffe4069027931d607cd2e82119bb9688' as invalid until 2018-01-19 03:53:04.
info: Stratis.Bitcoin.Features.BlockStore.BlockStoreLoop[0]
      ====BlockStore Repository Stats(%)====
      Hit Count:          2
```

**Comment by D3m0nKingx** [comment]
Seeing the same thing on Stratis Mainnet:

```bash
node.txt:[2018-01-24 09:04:33.2384 126] ERROR: Stratis.Bitcoin.Features.Consensus.ConsensusLoop.AcceptBlockAsync Block '29947af25f6603d72b14c06cba809ec55d4f04434a7a6538471d4029b5a7ed46' rejected: block timestamp too far in the future
node.txt:[2018-01-24 09:04:33.2384 126] ERROR: Stratis.Bitcoin.Features.Consensus.ConsensusLoop.AcceptBlockAsync Marking block '29947af25f6603d72b14c06cba809ec55d4f04434a7a6538471d4029b5a7ed46' as invalid until 2018-01-19 01:04:48.
```

**Comment by dangershony** [comment]
You need to fix your computers time stamp.

To reproduce this just set the node local time one hour backwards

**Comment by D3m0nKingx** [comment]
```      Local time: Wed 2018-01-24 14:21:24 CET
  Universal time: Wed 2018-01-24 13:21:24 UTC
        RTC time: Wed 2018-01-24 13:21:24
       Time zone: Europe/Amsterdam (CET, +0100)
``` Seems right to me

**Comment by dangershony** [comment]
Do you get this warning?
```
crit: Stratis.Bitcoin.Base.TimeSyncBehaviorState[0]

============================== W A R N I N G ! ==============================
Your system time is VERY different than the time of other network nodes.
Your time difference to the network median time is over the allowed maximum of 1500 seconds.
The time syncing feature has been as it is no longer considered safe.
It is likely that you will now reject new blocks or be unable to mine new block.
You need to adjust your system time or check -synctime command line argument.
=============================================================================
```

**Comment by D3m0nKingx** [comment]
Nothing in the node.txt, does that warning only appear in console? I'm running the node on the server in a screen session. So If that did occur I wouldn't see it (cause the screen has scrolled so much output at this point), unless it reappears again. Guess I need to Log the Screen session too maybe.

**Comment by D3m0nKingx** [comment]
FYI there's no block rejection on TestNet... should happen on both if it's happening on the other right?

**Comment by D3m0nKingx** [comment]
@dangershony 

This block rejection that I posted above, doesn't seem to make sense tho. On the explorer it shows the timestamp is in fact [692874](https://chainz.cryptoid.info/strat/block.dws?29947af25f6603d72b14c06cba809ec55d4f04434a7a6538471d4029b5a7ed46.htm) (unless the explorer is displaying timestamps based on the user's local browser time, but it should be in UTC) However I see it in EST :

2018-01-24 09:04:48 extracted by Proof of Stake
--

but the node says : 
>node.txt:[2018-01-24 09:04:33.2384 126] ERROR: Stratis.Bitcoin.Features.Consensus.ConsensusLoop.AcceptBlockAsync Marking block '29947af25f6603d72b14c06cba809ec55d4f04434a7a6538471d4029b5a7ed46' as invalid until **2018-01-19 01:04:48**.

Correct me if i'm wrong but 2018-01-24 09:04:48 (EST)  == 2018-01-19 01:04:4  (UTC)

So is Stratis **not** using UTC ?

**Comment by D3m0nKingx** [comment]
@dangershony I just ran Stratis on Mainnet on my local pc (Eastern Time Zone - EST, -0500). at same time with my node that is running on the Server (Amsterdam Time Zone - CET, +0100). 

Result is the node running in Amsterdam repeatedly has the Block timestamp is too far in the future.  

So this means that any Node running should be on a system setup with the local time in EST or <= UTC time?

**Comment by D3m0nKingx** [comment]
Confirming that after changing the server's time to EST (New York/america), there is no longer timestamp error.  

However, why does this not occur with testnet?

**Comment by bokobza** [comment]
All fixed now.
