### ISSUE TITLE
Wallet sync speedup

### ISSUE THREAD

**Issue by noescape00** [stratisproject/StratisBitcoinFullNode#1103]
So let's say we have a wallet that is 1000 blocks behind the block store tip. WalletSyncManager will get those block one by one in order to update the wallet. 
And we know that dbreeze stores stuff in sorted order and range selects are very fast (or so the official documentation says). So why don't we just use that and get those missing blocks in just large chanks (lets say, of 100 blocks) instead of getting one block at a time? 
So I propose: 
1) Avoid using block store cache in the WalletSyncManager (that doesn't make much sense to cache old blocks that we will never use after).
2) Adding `GetBlocksAsync` to the `IBlockRepository` and implementing it.
3) Making `WalletSyncManager` utilize that new `GetBlocksAsync` method when wallet tip is behind the block store cache tip by more than 1 block.

**Comment by dangershony** [comment]
This is a good idea but it should be done as part of a bigger job.
I have a long term goal to make the wallet feature stand alone, similar to block store, wallet should do the 3 following things:
- get blocks from the consensus signaler 
- read from store (if not pruned) 
- lastly download from peers (this is essential for the wallet to support pruned nodes).

Currently wallet slows down consensus as consensus will wait for the signaler block to finish before processing the next block, in block store we just put the block in a queue and release the signaler call but in wallet we dont (we processes the wallet logic in the same task flow).

As part of making the wallet stand alone then we can implemented the logic you mentioned above.

**Comment by dangershony** [comment]
Implementer please talk to me @bokobza and @noescape00

**Comment by noescape00** [comment]
@dangershony why was it XL? it's 6 hours of work tops.  Worst case scenario- 3 days.

**Comment by bokobza** [comment]
The first part is done with https://github.com/stratisproject/StratisBitcoinFullNode/pull/1890.
The rest will be dealt with when the activation stuff is in.

**Comment by noescape00** [comment]
@bokobza does this issue still holds or it can be closed?

**Comment by maciejzaleski** [comment]
The issue has been resolved. @bokobza is working on changes that will improve the performance even further.
