### ISSUE TITLE
[PeerAddress] Reset ConnectionAttempts after 1 day and increase filtering interval

### ISSUE THREAD

**Issue by fassadlr** [stratisproject/StratisBitcoinFullNode#1105]
Currently, we filter attempted peers with a 60sec interval. This needs to be increased to 1 hour.

Also, we don't currently reset the connection attempts, which means that if a peer has had more than 10 failed atttempts we will never try and connect to it again.

**Comment by fassadlr** [comment]
This was discussed with @Aprogiena and @dangershony as priority as we currently have too many connection attempts to the same peer within a given time frame.

**Comment by Aprogiena** [comment]
OTOH, this current crazy behavior of the node was very helpful in testing because a lot of bugs appeared much earlier than if it was behaving reasonably ;-)
