### ISSUE TITLE
[Consensus] POW not working on the POS chain

### ISSUE THREAD

**Issue by dangershony** [stratisproject/StratisBitcoinFullNode#1113]
This requires moving over the method to mine a genesis from stratisX and making sure the early stages of POW are correct.

Currently coinbase is not set correctly.

**Comment by stepkillah** [comment]
What steps required to make PoW working with PoS ? I'm trying to run private node with PoS and PoW.
I moved MineGenesis method from stratisX, changed code below in PosBlockAssebmler to make reward available in PoW
`        if (this.options?.IsProofOfStake ?? false)
	        {
		        this.coinbase.Outputs[0].ScriptPubKey = new Script();
		        this.coinbase.Outputs[0].Value = Money.Zero;
			}` 

 and setted `DefaultMaxTipAgeInSeconds` in `Networks.cs`
it seems that PoW mining works correctly, but when I'm trying to do PoS mining, it throws `StakeHashInvalidTarget` exception.
I'm tried to do PoS mining on 2 PC's, on wallets was about 100-300 coins on every, and it displays correct weight on wallets, but not display total network weight. 
But, when I put more coins (about 1 million) into stacking (starting to stack premine) it starting to work, but display some strange network weight.
So, is there some "minimum" network weight value or something like that?

**Comment by dangershony** [comment]
@dev0tion is going to look in to this issue and provide us with feedback.

**Comment by stepkillah** [comment]
or maybe the question is how to mine first PoS block ?

**Comment by dangershony** [comment]
@zeptin will be helping @dev0tion on this as well

**Comment by zeptin** [comment]
Will do

**Comment by dangershony** [comment]
This may very well be a bug indeed if you feel you can create a fix don't hesitate to submit a PR.

**Comment by dangershony** [comment]
@zeptin @dev0tion any update on this?

**Comment by zeptin** [comment]
It looks like the work necessary to resolve this has already been done in PR 1440. The primary issue was that only one of the block assemblers was getting injected at a time, so a Stratis-network node mining from genesis could only make malformed PoW blocks with empty coinbases.

**Comment by dangershony** [comment]
@zeptin so this can be closed?

**Comment by bokobza** [comment]
@fassadlr please close this if possible.

**Comment by fassadlr** [comment]
Fixed with #1634
