### ISSUE TITLE
[peerbanning] Banned peers need to be remove from the peer address store

### ISSUE THREAD

**Issue by dangershony** [stratisproject/StratisBitcoinFullNode#1120]
Banned peers should not be propagated to peers so when a peer is banned it needs to be removed from store.

**Comment by Aprogiena** [comment]
And also when we receive a list of new addresses from a peer, we should check the list against the list of banned nodes, So that we do not introduce those removed nodes again

**Comment by dangershony** [comment]
Perhaps the right way to do this is to add a flag on the address manager file that a peer is banned instead of creating a new store for panned peers

**Comment by Aprogiena** [comment]
You can do that, if you extend the format of that file to include that information and some other information like reason for the ban and duration of that or something, then yes you wouldn't need new store.

**Comment by dangershony** [comment]
Well if this data is anyway going to be stored then we save additional complexity (adding a new store) by reusing the existing store, so unless we will have requirements to delete banned peers (or none banned peers) after a time period I think this is a good approach.

**Comment by Aprogiena** [comment]
The problem with the peer manager file is that it is not a real store as far as I know, so it can get corrupted in case of power failure, unlike Dbreeze database. But that's something else, I'm jumping to another topic.

So yes I agree that you can have one store and it will be fine
