### ISSUE TITLE
Node shows non-existing connection

### ISSUE THREAD

**Issue by noescape00** [stratisproject/StratisBitcoinFullNode#1124]
![err](https://user-images.githubusercontent.com/10259355/35643732-337c0776-06d8-11e8-9a34-2efc28c4ce81.png)

Right after that it disconnect:

```
info: Stratis.Bitcoin.Connection.ConnectionManagerBehavior[0]
      Peer '[::ffff:52.233.33.138]:56354' offline, reason: 'unknown'.
```

This is happening regularly and that 0 height peer with the same address as the server always has a different port on every new connection.

**Comment by fassadlr** [comment]
@noescape00 I'm 99.999% sure this is happening due to this code:

[](https://github.com/stratisproject/StratisBitcoinFullNode/blob/master/src/Stratis.Bitcoin/P2P/Peer/NetworkPeer.cs#L528)

Which I think is correct. We connect, then check the nonce then disconnect if its the same.

**Comment by noescape00** [comment]
@fassadlr looks like it's not the case here- Nonces are different so when the bug happens `connectedToSelf` is false. Instead we have an exception during the attempt to read the magic (ReadMagicAsync => ReadBytesAsync)- the stream contains nothing when we expect it to contain 1 byte. 

At the same time server spawns `Unexpected exception while waiting for a message`. 
So it looks server shouldn't have initiated a connection in the first place (especially taking in count that server already has an inbound connection from the same peer it is trying to connect to).

So the question is: should we allow a 2 way connectivity? (I mean when there are 2 nodes- A and B. If A connects to B should the B be allowed to connect to A so both of them have 2 connections- inbound and outbound one)

I think it we want to forbid scenarios like this (and I see no reason we we wouldn't want to) we can just check on the `ProcessInitialVersionPayloadAsync` if the peer's Nonce is equal to any peer's Nonce that we are already connected to. And if it does- disconnect. 

I think I also should investigate more in depth what is the reason for the server to initiate a connection like this on a regular basis. Maybe it has something to do with the peer discovery.

**Comment by noescape00** [comment]
Ok. So far I've figured out that those connections are produced by the discovery jobs. 
I'm pretty sure that DiscoverPeersAsync() doesn't work as it was intended since it tries to discover the same peer every 10 seconds. Maybe it's something to do with the `Parallel.ForEach` inside it.

**Comment by noescape00** [comment]
I've figured it out. We never wait for the Parallel.ForEach to finish because it [doesn't work properly](https://stackoverflow.com/questions/11564506/nesting-await-in-parallel-foreach) with the awaits. So basically we are running it every 10 seconds and never await for the execution so those discovery jobs start overlapping and we end up with asking the same peers every 10 seconds or so.
