### ISSUE TITLE
-datadir doesn't work properly

### ISSUE THREAD

**Issue by noescape00** [stratisproject/StratisBitcoinFullNode#1144]
When I specify
`-datadir=C:\Users\user\AppData\Roaming\StratisNode\stratis\StratisTest_Second`

node uses this folder:
`C:\Users\user\AppData\Roaming\StratisNode\stratis\StratisTest_Second\stratis\StratisTest`

instead of expected

`C:\Users\user\AppData\Roaming\StratisNode\stratis\StratisTest_Second`

**Comment by bokobza** [comment]
That's the way it's supposed to be @noescape00.
-datadir is the top directory, for example "c:\newtopdirectory" and the coin name and network are added afterwards.
See here: https://en.bitcoin.it/wiki/Data_directory
