### ISSUE TITLE
Allow long reorgs before the last checkpoint is reached

### ISSUE THREAD

**Issue by noescape00** [stratisproject/StratisBitcoinFullNode#1156]
Let's say we are a malicious node and we have an access to the wallet that used to have some coins in the early days. What we can do is: fork main chain up to block 100 000 and mine on top of it at least 500 blocks. 

At some point a fresh node connects to us and syncs to the block 100 500. Even if it will connect to a good peer after that and receives a good chain of headers it wont be able to switch. 

Also even without access to an old wallet an attacker can generate any amount of coins since blocks that are behind the last checkpoint are not validated => attacker can produce a new block every 16 seconds so his chain will always be longer and have more work. 

So we (me and @Aprogiena) propose:

1) before we reach the last checkpoint we should not use the max reorg protection at all.
2) when switching between chains always select one that use more checkpoints. If both chains use the same amount of checkpoints-  choose one with the most chain work as we do now.

**Comment by Aprogiena** [comment]
3. And Move the checkpoint check from consensus to chain headers behaviour, because we want to make checkpoint check as soon as possible which is on headers, not wait until we have the block in our hands in consensus

**Comment by dangershony** [comment]
Yes on point 3, in fact we need to move checkpoints and AssumValid (I am not sure we need both actually) to the Network class so its accessible in the base node functionality.

>access to the wallet that used to have some coins in the early days
As for the this point an attacker can not revert the chain earlier then the latest checkpoint so if last checkpoint is at 90k that the point the attacker can start his fork (even if they have early chains private keys, checkpoints mitigate that)

**Comment by Aprogiena** [comment]
What makes you think that it is not possible to fork  before last checkpoint?

Also the checkpoint validation and the reorg protection might be considered as some kind of special rules, so you may consider how they fit into your rules engine

**Comment by dangershony** [comment]
Ok yes clients that do not frequently upgrade will not have latest checkpoints and may reorg earlier then latest compiled checkpoint.

Rules already use checkpoints to determine validation, but there is not reorg protection in the rules, and I am not sure there needs to be as Consensus will always follow chain headers.

**Comment by Aprogiena** [comment]
it is not really consensus rule, it is kind of node subjective rule, it is weird rule and i even suggest to update it in another issue

however, back to original proposal, we believe that these 3 steps are vital to prevent an attacker to provide you wrong chain on IBD. it is not really mitigated, but with this implemented many risks are lower

**Comment by Aprogiena** [comment]
> Ok yes clients that do not frequently upgrade will not have latest checkpoints and may reorg earlier then latest compiled checkpoint.

Not only those clients, but every client that is you read IBD

**Comment by dangershony** [comment]
Ho I see you mean currently because we only use checkpoints in consensus rules reorgs can happen yes this will be fixed once we move checkpoints (and assumevalid) to headers.

**Comment by Aprogiena** [comment]
Max reorg protection is already in the headers. The proposed fix is not replacement for anything else and anything else is not replacement for that

**Comment by noescape00** [comment]
Fixed by CHT design
