### ISSUE TITLE
[RF] Refactor the BlockStore

### ISSUE THREAD

**Issue by noescape00** [stratisproject/StratisBitcoinFullNode#1160]
1) Get rid of loop steps and BlockStoreLoop
2) Remove block download step from the normal execution flow since we never download the blocks unless node wasn't shutted down properly last time which leaded to consensus tip being initialized ahead of the block store tip
3) Replace async loop with trigger-based calling (instead of checking if new block was processed by the consensus loop every second we will act as soon as new block is signaled)

**Comment by dangershony** [comment]
Implementer to discuss with me @noescape00 and @fassadlr

**Comment by bokobza** [comment]
That's done.
