### ISSUE TITLE
[mining feature] remove POS loop

### ISSUE THREAD

**Issue by Aprogiena** [stratisproject/StratisBitcoinFullNode#1167]
`posLoop` Should be removed

`Dispose` Should call `StopStaking`, Which should use `this.posMinting?.StopStake();`

**Comment by dangershony** [comment]
>`posLoop` Should be removed 

And replaced with what?

**Comment by Aprogiena** [comment]
Nothing, it is disposed elsewhere. Look into the code, the same loop is assigned to 2 variables and there is little bit of mess where one is disposed in the other isn't

**Comment by majikandy** [comment]
I can look at this one

**Comment by dangershony** [comment]
Ah ok yeah (I though you meant replace the loop itself) we don't use that variable any way.
Go for this change @majikandy

**Comment by majikandy** [comment]
Can someone assign it to me? I don’t seem to have that permission

**Comment by Aprogiena** [comment]
I still can't see you on the list, I do see other new developers there, but you seem to be forgotten

**Comment by majikandy** [comment]
@StratisIain is this something you can fix?  apparently I am no on the list to be able to be assigned to github issues
