### ISSUE TITLE
[Node] check if problem on Mac OS is relevant to us

### ISSUE THREAD

**Issue by Aprogiena** [stratisproject/StratisBitcoinFullNode#1173]
We need to check with load is affected by similar issue is discussed here:
https://github.com/MetacoSA/NBitcoin/issues/345
https://github.com/MetacoSA/NBitcoin/commit/6ae1452e8e5252f3ea7aee3028d882199fe8e66a

**Comment by Aprogiena** [comment]
i don't know, that code is completely different, so it might or might not, we need to check that  first before doing anything

**Comment by bokobza** [comment]
* In Bitcoin, the buffer sizes are the same as we have in our code.
For example for the receive buffer we have [ReceiveBufferSize = 1000 * 5000;](https://github.com/stratisproject/StratisBitcoinFullNode/blob/master/src/Stratis.Bitcoin/P2P/Peer/NetworkPeerConnectionParameters.cs#L45)
In bitcoin, the DEFAULT_MAXRECEIVEBUFFER is [5000](
https://github.com/bitcoin/bitcoin/blob/0568dcd67d34728042259dc8b987154d1970bb2c/src/net.h#L80) and the seeting is set to [1000 * DEFAULT_MAXRECEIVEBUFFER](https://github.com/bitcoin/bitcoin/blob/171b03de065dae94ed6beb5db9ba7f08e92e7c7c/src/init.cpp#L1711).
Same values in this doc here: https://en.bitcoin.it/wiki/Running_Bitcoin.

* Also, [we're supporting Sierra and up](https://github.com/dotnet/core/blob/master/release-notes/2.1/2.1-supported-os.md) and this error seems to affect Sierra and previous versions so the range of affected OSes that are affected is smaller.

* From here it seems this is only a problem for VMs with memory < 8 GB: https://github.com/MetacoSA/NBitcoin/issues/345#issuecomment-369000907


My view is that we should close it and readdress if we see it in the wild.

**Comment by Aprogiena** [comment]
Though it wouldn't hurt to just change one constant in the network peer constructor. Would there be any disadvantage of doing so?

**Comment by bokobza** [comment]
> Would there be any disadvantage of doing so?

Not that I can think of. 
The buffers will be bigger so will take more space, but that's about it.
It might be hard to test as we'll need to find a Mac with Sierra and < 8 GB which might be tricky.

Happy either way, should take 5 sec to fix and 1h to test it didn't break anything.

**Comment by mikedennis** [comment]
I can fix it and test with my Windows box but I don't have a Mac to test with

**Comment by mikedennis** [comment]
Should note this change makes the buffers smaller not bigger. 5,000,000 -> 1,048,576 So I would expect if anything it might effect performance. I created a PR if you guys want to give it a whirl. I'm going to run some tests on it myself.

**Comment by Aprogiena** [comment]
I would go for it, it should be trivial and I can't see any disadvantages.

**Comment by bokobza** [comment]
ah yes indeed thanks @mikedennis, we're making the buffer to accommodate more platforms.

> I can't see any disadvantages.
It might affect performance because the buffer is made smaller to cater for old versions of Mac.

Not sure why we need this:
Bitcoin doesn't have this limitation, and we're limiting every platform just to cater for Macs with < 8GB Ram.

**Comment by bokobza** [comment]
I'm ok with that. Let's see what @mikedennis's tests yield.

**Comment by bokobza** [comment]
Assigned myself as I can't assign @mikedennis so people see it's not free to take.
