### ISSUE TITLE
[BlockAssemblers] Implement a better inheritence / abstract pattern

### ISSUE THREAD

**Issue by fassadlr** [stratisproject/StratisBitcoinFullNode#1179]
Currently, PoSBlockAssembler inherits from PowBlockAssembler which implements an abstract BlockAssembler class. Seeing as PosBlockAssembler and in the future the SmartContractBlockAssembler basically utilize most of the code of PoW, we need to move the shared code into the abstract BlockAssembler. Then we implement block assembler specific code in each assembler.

The end result will be that PowBlockAssembler, PosBLockAssembler and SmartContractBlockAssembler all inherit from BlockAssembler but overrides block creation specific logic in each implementation. For example, PoS implements a different UpdateHeader strategy than PoW.

This better facilitates unit testing and modularity. Eventually we can move, for example, all PoS related code into its own assembly / project.

**Comment by bokobza** [comment]
That's done.
