### ISSUE TITLE
Stake splitting vulnerability

### ISSUE THREAD

**Issue by noescape00** [stratisproject/StratisBitcoinFullNode#1180]
## Problem 
Currently `PosMinting.GetSplitStake` decides if coin should be spitted in coinstake tx or not.  
Basically if we have less than 51*3 = 153 non-zero UTXOs we don't split the coin. 

But in fact if we have a large enough coin we always want to split it because large coin will be likely to stake within the `coinstakeAge` window. By not splitting the coin miner's returns will be reduced since he will create less blocks. 

So here is the attack: attacker sees a large coin staking and sends 150 txes (each tx pays 0.0001 in fees and sends 0.0001 to the staker) so the total attack cost is 0.03 STRAT. 
Now staker won't split his large coin and therefore loose money. 

Best time to perform this attack is during C++ stakers migration to C# nodes since those stakers will be sending large amounts to their new Hd wallets consolidating their previously split coins into 1 big happy UTXO. 

## Fix

change PosMinting:527 : 
`if ((utxo != null) && (utxo.Value > Money.Zero) && (hashBock != null))`

instead of Money.Zero use smth like `0.1` so we never pick really small coins for staking
(instead of hardcoded value we might use a % of estimated total staking coins)
Doing that will increase attack cost and will help avoiding wasting CPU resourses on coins that will basically never stake. 

Also reintroduce coin splitting with target coin value of 75k stratis (coins larger than that should be split) and allow splitting in more than 2 outputs (but limit to 10 max outputs)

ps
This problem and fix were discussed with @Aprogiena

**Comment by Aprogiena** [comment]
as no escape said instead of money zero use something higher, I would suggest 0.01, but even 0.1 is probably okay. This will prevent the staking node to consider very small coins, which means saving CPU time

this will also prevent the splitting logic to consider those small coins and therefore one would have to have a lot of UTXOs with nontrivial value in order for the splitting logic to say that no more splitting should be done

this by itself should be good enough. However, we can't possibly add that extra rule that very big UTXOs, such as 75,000, will always split

**Comment by dangershony** [comment]
This is indeed a vulnerability of the miner (and wallet) I would even suggest the coin splinting condition to be 1 STRAT, 0.003 STRAT is a very cheep attack but 150 strat will discourage such attacks even more without effecting the miner (staking with less then 1 STRAT or any other currency is probably not gonna change much for the miner) this should probably be configurable as well.

**Comment by Aprogiena** [comment]
1 Stratis is too much, if you think about it if the limit was 0.01, then we are looking the cause of about 15 Stratis per attack, but the effect of the attack is that the miner would not be able to stake with big coin for half a day, and this would actually cost the miner the profit of those blocks that you would miss, which would very likely be much less then 15 Stratis. Therefore it seems to me that 0.01 is good enough, especially if we say that the coin is split it anyway if its value is over 75 K

**Comment by monsieurleberre** [comment]
so we agreed on the following
1) minimum coin size > 0.01
2) for staking amounts > 100 strats, aim for an even split of the coins up to 501*3 utxos

**Comment by bokobza** [comment]
Fixed in https://github.com/stratisproject/StratisBitcoinFullNode/pull/1769
