### ISSUE TITLE
[RF] [chain behaviour] replace probabilistic finality with real finality

### ISSUE THREAD

**Issue by Aprogiena** [stratisproject/StratisBitcoinFullNode#1181]
This is to fix our theoretical model and it should be done after a headers work. Check with me for details

**Comment by noescape00** [comment]
Imho the situation is so theoretical and hard to create that I'd not spend anyone's time in order to fix this. 
At max maybe just add a comment somewhere that 100% finality is not guaranteed even after the `maxReorg` blocks.

**Comment by Aprogiena** [comment]
i believe this is quite important to fix and super easy to do so

**Comment by noescape00** [comment]
>i believe this is quite important to fix and super easy to do so

1) Why is it important to fix? 
2) Won't that effectively override the consensus rule?

**Comment by Aprogiena** [comment]
1. to have theorethical strong model and avoid later surprises
2. no, this is subjective to each node

**Comment by noescape00** [comment]
Ok, makes sense. 

So the fix you propose would be marking blocks that are behind `tip - maxReorg` as final and never allow such reorgs that would like to replace those?

**Comment by Aprogiena** [comment]
in chain repo, we would save last finalized block and never go over it, it would also be cached in memory

**Comment by dangershony** [comment]
Hmm to summarise the attack:
Our node is at height 1000 if an attacker could fake new headers form block 501 to 1001 and feed us only that new chain this will cause our node to reorg then fake again from block 1 to 501 and so on.

Marking block 500 is final will prevent the second reorg.

**Comment by noescape00** [comment]
>Hmm to summarise the attack:
Our node is at height 1000 if an attacker could fake new headers form block 501 to 1001 and feed us only that new chain this will cause our node to reorg then fake again from block 1 to 501 and so on.

Assuming that proven headers are in place the attack will look more like: 

1) We're on a chain at height 1000, only 1% of stake power supports our chain
2) We receive a chain which was supported by 10% of stake and it's fork point is at 500- we reorg. New chain height is 600 (the chain is smaller but has more work than the old one) 
3) We see 3rd chain which has even more work (supported by 90% of miners) with a fork point at 100 and we reorg again. 

So old blocks removal can happen only in cases where we have a network split for some time and we jump from the smallest chain workwise towards the largest one.

**Comment by dangershony** [comment]
Ah you are referring to stake power only, this is a very unlikely scenario as you say it requires a lot of stake to participate and a lot of stake to be absent.

**Comment by Aprogiena** [comment]
It is kind of low priority, but then it is super simple to fix. And it is a low priority only because we are unaware of any attacks at this moment, but the model currently is so counterintuitive that I would say it is worth fixing so that we are later surprised. Still low priority, but should probably make it into production release, but definitely not for beta

**Comment by noescape00** [comment]
This issue should be resolved in 2 steps: 

1) Introduce finalized chain header + add tests:

FinalizedHeaderHash is a hash of a block that is updated every time Consensus Tip is _moving forward_. 
FinalizedHeaderHash  = ConsensusTip - MaxReorg

This only applies for Stratis networks.
This hash should be persisted to the hard drive (maybe make it as a part of the ChainRepository)

Testing:
1. Mine more than `MaxReorg` and after that mine some block one by one and make sure that FinalizedHeaderHash is moving forward. 
2. Mine more than `MaxReorg + 10` and after that an alternative chain is presented which is shorter but have more chainwork. Miner switches to it. Make sure that FinalizedHeaderHash doesn't change. 

2) Later enforce the finality (as a part of https://github.com/stratisproject/StratisBitcoinFullNode/issues/1322)
