### ISSUE TITLE
[PeerAddressManager] Stop connecting to peers that connected but failed handshake within a certain time frame.

### ISSUE THREAD

**Issue by fassadlr** [stratisproject/StratisBitcoinFullNode#1194]
We should throttle connections to peers that we've connected to but didnt manage to version handshake. 

I.e. if we connected to a peer X but failed version hand shake, that attempt should also be logged and checked when we try and connect to it again. After a certain amount of attempts we shouldn't try and connect to peer X within a certain time frame, possibly a day or so.

**Comment by dangershony** [comment]
We need to extend the time between failed handshake attempts

**Comment by fassadlr** [comment]
@thefazzer we will somehow need to inform the address manager of the fact that version handshake failed. For this I recommend we create a `VersionHandshakeException` which we can then catch when we try and connect. Please see `PeerConnector.ConnectAsync`, I would change this like so:

```
            try
            {
                ...
            }
            catch (OperationCanceledException)
            {
                ...
            }
            catch (VersionHandshakeException exception)
            {
                this.logger.LogTrace("The peer failed to handshake: {0}", exception.ToString());
                peer?.VersionHandshakeFailed();
                peer?.Disconnect("Error while connecting", exception);
            }
            catch (Exception exception)
            {
                ...
            }
```

We can then implement the relevant methods etc and throw the exception in `INetworkPeer.VersionHandshakeAsync`.

@Aprogiena @dangershony do you guys have a better suggestion?

**Comment by Aprogiena** [comment]
```
        /// <exception cref="ProtocolException">Thrown when the peer rejected our "version" message.</exception>
        /// <exception cref="OperationCanceledException">Thrown during the shutdown or when the peer disconnects.</exception>
        Task VersionHandshakeAsync(NetworkPeerRequirement requirements, CancellationToken cancellationToken);
```

We already have these two exceptions and we already handled them both (protocol is caught with Exception class), so we only need to call the logic that will mark it down.

I think we should not try to reconnect to the peer anytime soon even after the first failure. It probably doesn't make sense to try to connect to someone for at least an hour if we just failed establish the connection properly – including handshake. Then of course, as usual, we should try again eventually and if we fail again for multiple times then to mark this node as completely useless and not to try again.

**Comment by fassadlr** [comment]
@Aprogiena Oh yes OK I see now. However, I see that we also use ProtocolException for exceptions in `CoreNode`'s `SynchronizeChain` method:

```
            if (newTip.Height <= oldTip.Height)
                throw new ProtocolException("No tip should have been recieved older than the local one");

            foreach (ChainedHeader header in headers)
            {
                if (!header.Validate(peer.Network))
                {
                    throw new ProtocolException("A header which does not pass proof of work verification has been received");
                }
            }
```

I don't know if this is right or even still in use? 😯 

@thefazzer you can catch `ProtocolException` when trying to version handshake and  then record (in memory) the amount of `HandshakeAttempts`?

Then when you ask the peer selector for peers you filter the connected peers by saying if the peer attempted handshake x times and the last time was 1 day ago then dont try and connect again.

As a spin off to this you will need to ensure that you reset the `HandshakeAttempts` count after one day but we can talk about this further after the first part has been implemented.
