### ISSUE TITLE
Increase status update rate for Bench[0]

### ISSUE THREAD

**Issue by D3m0nKingx** [stratisproject/StratisBitcoinFullNode#12]
After running the SBFN in linux's terminal, I would like to suggest an enhancement to increase the refresh rate of the Bench[0] output to the terminal to 2 seconds or in real-time.

**Comment by dangershony** [comment]
What do you men by "or in real time" ?

**Comment by D3m0nKingx** [comment]
instantaneous. like when I watch the performance monitor of my CPU it shows the stats in that moment, no delays

**Comment by dangershony** [comment]
Ah I see what you mean, its probably harder to achieve on a console app but we could increase the refresh rate for sure

**Comment by D3m0nKingx** [comment]
Very good, ty

**Comment by dangershony** [comment]
This is still an issue?

**Comment by D3m0nKingx** [comment]
Right now the update rate is every 5 seconds. Would be nicer if it was every couple seconds or real-time.

**Comment by dangershony** [comment]
The print screen happens every 5 sec and when a block is validated
I am worried too frequent refresh rate will bloat the screen

**Comment by D3m0nKingx** [comment]
I can test it on my system first, let you know how it performs.  let me know how to change it.

**Comment by dangershony** [comment]
On the full node line 234 change this line to what ever you think best

if((DateTimeOffset.UtcNow - lastSnapshot.Taken) > TimeSpan.FromSeconds(5.0))

**Comment by D3m0nKingx** [comment]
Works great! I changed it to 1 second. No issues. Also there's an option in the terminal in linux to control the number of "scrollback lines" I just reduced it to 500. 

I suppose you could also add code that'll just clear the terminal before outputting the print screen too.

**Comment by dangershony** [comment]
yeah but there are other stuff written to the output not just download stats so ideally we'll keep it rolling down, limiting the console is the best option

**Comment by D3m0nKingx** [comment]
sounds good :) :100:

**Comment by dangershony** [comment]
now with the general logging I am closing this
