### ISSUE TITLE
Mempool cache loading optimization

### ISSUE THREAD

**Issue by noescape00** [stratisproject/StratisBitcoinFullNode#1206]
On bitcoin network it's usual to see 15k txes at max in the mempool so scenario when we load cached mempool on node startup with this amount of transactions is quite possible. 

I've tried to create a mempool with 4.5k transactions and it took 5 minutes to load them. 
Log:
```
[2018-03-14 01:20:18.9797 1] INFO: Stratis.Bitcoin.Features.MemoryPool.MempoolManager.LoadPoolAsync Loading Memory Pool...
[2018-03-14 01:20:19.0270 1] INFO: Stratis.Bitcoin.Features.MemoryPool.MempoolManager.AddMempoolEntriesToMempoolAsync ...loaded 4509 cached entries.
[2018-03-14 01:25:08.9438 7] INFO: Stratis.Bitcoin.Features.MemoryPool.MempoolManager+<AddMempoolEntriesToMempoolAsync>d__36.MoveNext ...4509 entries accepted.
```

The bottleneck is in the `AcceptToMemoryPoolWorkerAsync` so probably it will be a good idea to optimize performance of this method.

**Comment by dangershony** [comment]
As part of this task we should also built in limits to max allowed size of mempool (I am not sure we already have something in place for that)

**Comment by noescape00** [comment]
We do in MempoolValidator.cs

```
        /// <summary>
        /// Default for -maxmempool, maximum megabytes of mempool memory usage.
        /// </summary>
        /// <seealso cref = "MempoolSettings" />
        public const int DefaultMaxMempoolSize = 300;
```

So we have a limit of 300mb but just 1.5mb (that was the size of mempool with 4.5k txes) takes 5 minutes to load.

**Comment by noescape00** [comment]
Upd: 

Mempool accepts txes that pay 0 fee. When it's full we trim it and raise the min fee for a tx to be accepted. This basically leads to the ability to fill the mempool with txes that will never be mined (there is a non 0 threshold for a tx to be included in the block template while mining).

So 300mb of junk txes can be created by attacker at no cost at all. 
Also after trimming and `rollingMinFee` change attacker can raise the fee (unless he hits `tx serialized size / 100000000` for the txes that are used in the attack he won't spend a single coin since those txes won't participate in the mining because of the fee threshold)

**Comment by noescape00** [comment]
It was reported that this is no longer an issue
