### ISSUE TITLE
RPC implementation

### ISSUE THREAD

**Issue by stepkillah** [stratisproject/StratisBitcoinFullNode#1213]
Wanted to ask about RPC implementation, because there are only a few of methods available there. I didn't find any info related to this, are someone working on that? Or it's low priority as far as there are more important things to do?

**Comment by dangershony** [comment]
No we don't have all the RPC methods unfortunately, we only focused on the methods we need and we build a new set of REST api methods for the wallet functionality that can be accessed using swagger, feel free to add more RPS/API methods if you need some or want to.

**Comment by dangershony** [comment]
This projects are the features for RPC/API
Stratis.Bitcoin.Features.Api
Stratis.Bitcoin.Features.RPC

But you can inject controllers in any feature and they will get activated.
