### ISSUE TITLE
-reindex-chainstate not working

### ISSUE THREAD

**Issue by zeptin** [stratisproject/StratisBitcoinFullNode#1215]
I was attempting to retrieve a transaction's details via `getrawtransaction`. It transpires that this needs a transaction index, similarly to stratisX. When I shut down the full node and enabled this via the txindex command line flag, I receive the following message on startup:

`
You need to rebuild the BlockStore database using -reindex-chainstate to change -txindex) ---> Stratis.Bitcoin.Features.BlockStore.BlockStoreException: You need to rebuild the BlockStore database using -reindex-chainstate to change -txindex
`

However, adding the mentioned flag to the command line does not seem to cause the message to go away.

**Comment by dangershony** [comment]
Yeap I think this is the problem
```
            if (this.storeSettings.ReIndex)
                throw new NotImplementedException();

```

**Comment by dangershony** [comment]
And I don't think its `-reindex-chainstate` only `-reindex` what is `chainstate` for I am not sure

**Comment by r3lik** [comment]
`-reindex` doesn't work either:

`fail: Stratis.Bitcoin.Builder.FullNodeFeatureExecutor[0]
stratisd            |       An error occurred starting the application: System.AggregateException: One or more errors occurred. (Re-indexing the block store in currently not supported.) ---> System.NotSupportedException: Re-indexing the block store in currently not supported.
stratisd            |          at Stratis.Bitcoin.Features.BlockStore.BlockStoreQueue.InitializeAsync() in /StratisBitcoinFullNode/src/Stratis.Bitcoin.Features.BlockStore/BlockStoreQueue.cs:line 121`

**Comment by codingupastorm** [comment]
I'll fix the error message to just mention `-reindex`, not `-reindex-chainstate`.

@bokobza @dangershony could you fill me in on roughly what you want reindexing to achieve? I assume it's `for every block in the database, go back and reinsert it and it's transactions according to whether TxIndex is set` ?
