### ISSUE TITLE
Default max block size & weight values that are used in PoSMining are not configurable and different comparing to consensus values

### ISSUE THREAD

**Issue by noescape00** [stratisproject/StratisBitcoinFullNode#1217]
PowMining:34

```
/// <summary>Default for "-blockmaxsize", which controls the maximum size of block the mining code will create.</summary>
public const int DefaultBlockMaxSize = 750000;

/// <summary>
/// Default for "-blockmaxweight", which controls the maximum block weight the mining code can create.
/// Block is measured in weight units. Data which touches the UTXO (What addresses are involved in the transaction, how many coins are being transferred) costs
/// 4 weight units (WU) per byte. Witness data (signatures used to unlock existing coins so that they can be spent) costs 1 WU per byte.
/// <seealso cref="http://learnmeabitcoin.com/faq/segregated-witness"/>
/// </summary>
public const int DefaultBlockMaxWeight = 3000000;
```

Those values are used in the block assembler but the max allowed values by the consensus are 1000000 for the block size and 4000000 for the block weight. 
Also they are not configurable which goes against the comments for those values. 

So effectively without changing them it is not possible to produce blocks larger than 732 kb.

I suggest implementing the configuration of those values and changing default values to be the maximum allowed values by the consensus (those changes are tested and [block ](https://chainz.cryptoid.info/strat-test/block.dws?334566.htm) generated with them is perfectly valid).

**Comment by dangershony** [comment]
Hmm I am not sure why the miner was limited (bellow what consensus allows) perhaps we should find out the reason for that first.

I would suggest to also check how Bitcoin core is configured.

**Comment by noescape00** [comment]
>Hmm I am not sure why the miner was limited (bellow what consensus allows) perhaps we should find out the reason for that first.

I'm pretty sure that it was just copied from btc core implementation- they have it the same but no miner uses default parameters- all of them are maxed out. 

Also btc core is not used to actually mine mainnet blocks but our node's miner is supposed to be used for that.

**Comment by dangershony** [comment]
>I'm pretty sure that it was just copied from btc core implementation

Yes they where, I agree this should be configurable and default to max in that case, just I would like to know why core did not set it to max values.

**Comment by Aprogiena** [comment]
historical reasons, originally miners were creating blocks up to 750kb only and ned to set the cmdkine option to increase

**Comment by codingupastorm** [comment]
@Aprogiena @noescape00 with this:

```
// Limit weight to between 4K and MAX_BLOCK_WEIGHT-4K for sanity.
            this.BlockMaxWeight = (uint)Math.Max(4000, Math.Min(PowMining.DefaultBlockMaxWeight - 4000, this.Options.BlockMaxWeight));
```

Are you cool if we remove the `-4K for sanity`: AKA if we set 1MB it will be 1MB. Not 1MB - 4KB.

**Comment by noescape00** [comment]
Yeah, I'm totally cool with it. 

Block assemblers in general should be reviewed, a lot of stuff is mixed with bitcoin with segwit logic that we dont have.

**Comment by codingupastorm** [comment]
Sorry that was only the first part of the issue in that PR. I thought it might be controversial so did it first.

Reopening.

**Comment by codingupastorm** [comment]
I'm a little confused here  - the const used for DefaultBlockMaxSize is actually used as the MaxSerialized size.

BlockDefinition:550

When someone sets 'blockmaxsize=' I would have assumed they want to set the base size? The 1MB? Instead we only check the SerializedSize in BlockDefinition. So setting 'blockmaxsize=' is setting the serialized size.

Is this right?

**Comment by noescape00** [comment]
There should be 2 limitations- max serialized size according to protocol (1mb) and the size miner is willing to use (750 000 by default). The last one is always maxed out to 1mb on btc. We don't do that for some reason.
