### ISSUE TITLE
Any plans to support other bitcoin family altcoins?

### ISSUE THREAD

**Issue by shtse8** [stratisproject/StratisBitcoinFullNode#1219]
I really love this project. I want to build a full node with C# to connect all bitcoin-family coins. So do you have any plans to support other altcoins in this project?
Or will it have any extension method to let us develop the support ourselves?

**Comment by noescape00** [comment]
>So do you have any plans to support other altcoins in this project?

Not directly but right now @dangershony is working on making consensus rules more abstract so it will be easy to adjust them for different coins. 

Also I think you can add support for other coins right now but it won't be a trivial task to do atm.

**Comment by dangershony** [comment]
Closing this as its not relevant to our current work.
