### ISSUE TITLE
Sync issue

### ISSUE THREAD

**Issue by Igor-san** [stratisproject/StratisBitcoinFullNode#1226]
The process of initial loading was infinite loop on block 642930:

======Connection======
Peer:[::ffff:110.140.196.230]:16178,     connected:outbound,        height:764253,        agent:/Stratis:2.0.0.3/
Peer:[::ffff:78.26.136.12]:16178,        connected:outbound,        height:764255,        agent:/Stratis:2.0.0.3/
Peer:[::ffff:82.42.142.246]:16178,       connected:outbound,        height:764255,        agent:/Stratis:2.0.0.3/
Peer:[::ffff:169.0.232.145]:16178,       connected:outbound,        height:764248,        agent:/Stratis:2.0.0.3/
Peer:[::ffff:67.176.161.183]:16178,      connected:outbound,        height:764254,        agent:/Stratis:2.0.0.3/
Peer:[::ffff:90.77.24.138]:16178,        connected:outbound,        height:764254,        agent:/Stratis:2.0.0.3/
Peer:[::ffff:151.229.223.1]:16178,       connected:outbound,        height:764255,        agent:/Stratis:2.0.0.3/

[2018-03-20 17:16:12.6283 11] ERROR: Stratis.Bitcoin.Features.Consensus.ConsensusLoop+<AcceptBlockAsync>d__40.MoveNext Block 'f89be0f9be2f5787a712a924a7f0765b92b03cd1b34daf90b42afb293d528205' rejected: proof-of-stake hash did not meet target protocol
[2018-03-20 17:16:12.9102 11] ERROR: Stratis.Bitcoin.Features.Consensus.ConsensusLoop+<AcceptBlockAsync>d__40.MoveNext Marking block 'f89be0f9be2f5787a712a924a7f0765b92b03cd1b34daf90b42afb293d528205' as invalid.
[2018-03-20 17:16:14.0871 8] INFO: Stratis.Bitcoin.FullNode.<StartPeriodicLog>b__74_0 ======Node stats====== 03/20/2018 17:16:14 agent StratisBitcoin:1.0.10
Headers.Height:      642930   Headers.Hash:     8c2cf95f9ca72e13c8c4cdf15c2d7cc49993946fb49be4be147e106d502f1869
Consensus.Height:    642930   Consensus.Hash:   8c2cf95f9ca72e13c8c4cdf15c2d7cc49993946fb49be4be147e106d502f1869
BlockStore.Height:   642930   BlockStore.Hash:  8c2cf95f9ca72e13c8c4cdf15c2d7cc49993946fb49be4be147e106d502f1869
Wallet.Height:       No Wallet

======Mempool======
MempoolSize: 0    DynamicSize: 0 kb   OrphanSize: 0 

![642930](https://user-images.githubusercontent.com/30476065/37673459-4ea819da-2c81-11e8-9d21-04b0f22bb4b9.png)

And the test network does not work:

![testnet0](https://user-images.githubusercontent.com/30476065/37675049-4ddf9dee-2c85-11e8-93e1-ce2eee8a60be.png)

**Comment by Aprogiena** [comment]
Could you please provide a copy of your data folder for the mainnet?

**Comment by dangershony** [comment]
Testnet works just the dns seeders are not always up so its hard to discover the first connection try to put this in command line `-addnode=51.140.231.125` 

And yes please also provide any logs you have for mainnet and perhaps a description of how you got this, this you sync from zero? where you staking?

**Comment by Aprogiena** [comment]
Also, if you restart the node on mainnet, does it advance or is it stuck even after restart?

**Comment by Igor-san** [comment]
> Also, if you restart the node on mainnet, does it advance or is it stuck even after restart?
Yes. At the same place.
![642930-3](https://user-images.githubusercontent.com/30476065/37707946-f0bf1d42-2d15-11e8-9354-d07a696c5f15.png)
![642930-2](https://user-images.githubusercontent.com/30476065/37707947-f0e56240-2d15-11e8-9635-e397340fcd1b.png)

> Could you please provide a copy of your data folder for the mainnet?
Archive the entire folder? It's very big, but if necessary, I'll do it.
![stratismain](https://user-images.githubusercontent.com/30476065/37707995-18c9cd82-2d16-11e8-9ff0-3284716f3f43.png)

**Comment by noescape00** [comment]
>Archive the entire folder? 

Yes, that will help 🙂

**Comment by Igor-san** [comment]
StratisMain.zip  https://yadi.sk/d/isNz10gj3Tc4ZR  725 MB

**Comment by dangershony** [comment]
Ah one more question did your node crash anytime before that?

**Comment by Igor-san** [comment]
> Ah one more question did your node crash anytime before that?

The node does not crashed , it continues to try to take block 642930. Can there any parameter change in POS?

**Comment by noescape00** [comment]
@Igor-san which commit you've used for the node compilation? 
Can you reproduce it with the latest master? (recently a bugfix was merged so there is a chance that this bug won't appear anymore)

**Comment by Igor-san** [comment]
> @Igor-san which commit you've used for the node compilation?

I downloaded yesterday from here https://github.com/stratisproject/StratisBitcoinFullNode/archive/master.zip

**Comment by Igor-san** [comment]
I delete old data folder StratisMain and rerun the program - all syncronized. Strange.

**Comment by Igor-san** [comment]
Thank you for your support, this issue is resolved.
