### ISSUE TITLE
[RF] Modify consensus loop to avoid downloading blocks that we already have in the block store

### ISSUE THREAD

**Issue by noescape00** [stratisproject/StratisBitcoinFullNode#1227]
Consensus loop is designed to flush the coinview only when headers tip is equal to consensus tip:

```
// We really want to flush if we are at the top of the chain.
// Otherwise, we just allow the flush to happen if it is needed.
bool forceFlush = this.Chain.Tip.HashBlock == blockValidationContext.ChainedBlock?.HashBlock;
await this.FlushAsync(forceFlush).ConfigureAwait(false);
```

And in the CachedCoinView we have 

```
public const int CacheFlushTimeIntervalSeconds = 60;
```

So the cache is flushed every 60 seconds OR when we are at the tip. 

When the cache is flushed a new instance of RewindData is created and persisted.
RewindData is used for rewinding the consensus in case of a reorg.

When we rewind consensus we may actually rewind several blocks in a single `RewindCoinViewLockedAsync()` call. 

Now here is the problematic scenario:
Let's say that consensus tip is behind headers tip by some blocks and we are advancing. A 1 block reorg happens at the very tip of the chain. Our consensus recognizes it and rewinds itself. After a rewind we may be 3000 blocks behind (actually depends on the syncing speed. Basically we can be as many blocks behind as we are able to download in 60 seconds). 

Now instead of getting 2999 blocks from the block store and downloading 1 new block we will download all of those blocks using the lookahead block puller and signal them again to all the components. 

There are 2 fixes to this that I can think of: 

1) after a reorg check first if we have those blocks in the store and if we do- get them from it instead of the puller
2) create 1 rewind data for every block (but that will require more space on the hard drive and we will need to refactor the coinview)

**Comment by Aprogiena** [comment]
I think elegant way to fix this would be to flush not only at the tip, but when ever we are close to the tip. So I would check if Max reorg rule is in place on the current network. If it is then flush if distance to the tip is less then Max reorg. If it is not, then flush if the currently process the block time is not more than 2 weeks from the tips time

**Comment by Aprogiena** [comment]
This solution would allow us to keep the performance during IBD and only slowdown the sync at the end of the chain

**Comment by dangershony** [comment]
>When we rewind consensus we may actually rewind several blocks in a single RewindCoinViewLockedAsync() call.

What? I did not know this is the behaviour of coinview rewind.
I think apro solution is not bad, during IBD rewinds are not expected so rewinding intervals of two weeks (or even based on the size of the pending rewind, store a rewind point every 10mb or so), close to the tip we can store more frequently.

But perhaps the best solution is to keep a rewind point on every block. 

>after a reorg check first if we have those blocks in the store and if we do- get them from it instead of the puller

This is problematic for pruned nodes but doable.

**Comment by Aprogiena** [comment]
we want that max reorgs blocks anyway for headersEx, so that is why i think it is reasonable to go with that and for bitcoin ... well two weeks should be just fine even for pruned node

**Comment by noescape00** [comment]
>But perhaps the best solution is to keep a rewind point on every block.

That may result in having larger rewind data set (rewind data instance for 10 blocks is smaller than 10 rewind data instances for every block). Though the difference shouldn't be that crucial.
Also we shouldn't do it this way until we fix #5 and refactor the coinview because this fix will slow down advancing a lot.

**Comment by noescape00** [comment]
This issue should be tested (a new integration test should be created):

![issue1227](https://user-images.githubusercontent.com/10259355/39184457-1872624c-47cc-11e8-9631-f8434cffdf8d.jpg)

**Comment by noescape00** [comment]
Fixed with activation merge.
