### ISSUE TITLE
[Wallet Bug] consensus stopes when the wallet looks for a block in store

### ISSUE THREAD

**Issue by dangershony** [stratisproject/StratisBitcoinFullNode#1228]
![image](https://user-images.githubusercontent.com/7487930/37716112-a0384876-2d15-11e8-8857-695b8afb9322.png)

![image](https://user-images.githubusercontent.com/7487930/37716086-908461c6-2d15-11e8-82e0-9f66cd019e9e.png)

**Comment by Aprogiena** [comment]
how do we know this is wallet related? or do we know the cause already?

**Comment by dangershony** [comment]
I think this is not an issue anymore.
