### ISSUE TITLE
Wallet file might not be written correctly to disk when FullNode crushes

### ISSUE THREAD

**Issue by maciejzaleski** [stratisproject/StratisBitcoinFullNode#1230]
My FullNode has been abruptly stopped by Windows restarting to install updates. This has resulted in a incomplete content in the wallet file.
As a result when starting the node again I get an exception  message; [Incomplete wallet file.txt](https://github.com/stratisproject/StratisBitcoinFullNode/files/1834324/Incomplete.wallet.file.txt)

**Proposed solution**
 - Write the content of the wallet file to *.partial file while deserializing
 - Move currently used wallet file to *.bak file
 - Move *.partial file to the correct wallet file name

Since move operation is really a file rename it should be much quicker than writing file to disk it have less chance of failing then the current approach.
In case of the FullNode start issues we can always discard broken wallet file and use backup.

**Comment by bokobza** [comment]
Nice one @maciejzaleski.
I'll have a look.

**Comment by bokobza** [comment]
Fixed in #1351 .
