### ISSUE TITLE
Node is not syncing

### ISSUE THREAD

**Issue by maciejzaleski** [stratisproject/StratisBitcoinFullNode#1231]
This seems to happen in the following scenario:
 - User has started the node for the first time
 - User has restored the wallet
 - Before the wallet restore is completed user stops the FullNode
 - When starting the full node again it will thrown an exception [Wallet with no balance.txt](https://github.com/stratisproject/StratisBitcoinFullNode/files/1834317/Wallet.with.no.balance.txt)
 - The node is connected to peers and peers have higher blockheigh than the tested node

**From Console**
> ======Connection======
> Peer:[::ffff:13.64.76.48]:26178,         connected:outbound,        height:343122,        agent:/Stratis:2.0.0.3/
> Peer:[::ffff:94.102.63.207]:26178,       connected:outbound,        height:343127,         agent:StratisBitcoin:1.0.10
> Peer:[::ffff:54.37.46.84]:26178,         connected:outbound,        height:343127,        agent:/Stratis:2.0.0.3/
> Peer:[::ffff:10.0.0.1]:51150,            connected:inbound,         height:343117,         agent:StratisBitcoin:1.0.10
> Peer:[::ffff:51.141.45.80]:26178,        connected:outbound,        height:343127,        agent:/Stratis:2.0.0.3/
> Peer:[::ffff:40.113.118.138]:26178,      connected:outbound,        height:343127,        agent:/Stratis:2.0.0.3/

**From Swagger**
>  "consensusHeight": 343117,

**Comment by bokobza** [comment]
@maciejzaleski Did this happen when you were using the UI?
> Before the wallet restore is completed user stops the FullNode
How did the full node stop?

**Comment by bokobza** [comment]
Haven't been able to reproduce this.
However, the separation of writing (to a temp file) and reading of a file in #1351 should help with the error described above.
@maciejzaleski feel free to have a lok, test and close if you're happy.

**Comment by maciejzaleski** [comment]
This problem has now been resolved.
