### ISSUE TITLE
FullNode is not syncing with the network while the wallet is being restored

### ISSUE THREAD

**Issue by maciejzaleski** [stratisproject/StratisBitcoinFullNode#1232]
It can take a log time to restore a wallet with large amount of transactions.
While this process is ongoing the FullNode will not update the blockheight from the connected peers.

**Comment by dangershony** [comment]
What do you mean blockheight on one of the features?

**Comment by maciejzaleski** [comment]
I mean the BlockHeight as reported by the API call. It is the 4th API from the Swagger list.

**Comment by dangershony** [comment]
![image](https://user-images.githubusercontent.com/7487930/37774478-343e85a4-2dd8-11e8-8390-1a202c2b6ace.png)

You mean `/api/Node/status `
```
  "agent": "danger-StratisBitcoin",
  "version": "1.0.10.0",
  "network": "StratisTest",
  "consensusHeight": 344028,
```

**Comment by maciejzaleski** [comment]
That is correct

**Comment by dangershony** [comment]
This is currently by design, when the wallet is busy consensus waits. 
We have a refactor coming in this part were wallet will be stand alone and not block consensus (similar to how store works)

**Comment by maciejzaleski** [comment]
Since it is not a defect I’m closing this issue
