### ISSUE TITLE
Transactions are not being relayed by the FullNode

### ISSUE THREAD

**Issue by maciejzaleski** [stratisproject/StratisBitcoinFullNode#1242]
**Setup**
- RelayNode is connected to the network
- OtherNode is connected to RelayNode only

When sending transaction from OtherNode to RelayNode the transaction is received by the RelayNode but it is not propagated to any other node on the network.

**Comment by dangershony** [comment]
@noescape00 you on this right?

**Comment by noescape00** [comment]
Yes. Looks like there are several issues that prevent relaying the transactions in the setup that @maciejzaleski has
