### ISSUE TITLE
[Connection manager] race conditions on connected peer read only collection

### ISSUE THREAD

**Issue by Aprogiena** [stratisproject/StratisBitcoinFullNode#1243]
Almost every usage of `ConnectedPeers` is not designed properly and it is prone to race condition. Most of the code works well just because it is possible to work with disposed object, but it is not very clean and safe design. Sometimes we even call methods of disposed objects, such as network peers or their behaviours.

This design can be improved to avoid such race conditions and using disposed objects. It is probably not a big priority though.

**Comment by dangershony** [comment]
You mean this property of `IConnectionManager`
```
      private readonly NetworkPeerCollection connectedPeers;
```

**Comment by Aprogiena** [comment]
No, the other one, with C

**Comment by dangershony** [comment]
Ah `IConnectionManager.ConnectorPeers` this is widely used indeed
