### ISSUE TITLE
[RF] Transaction relaying is allowed once in 20 years

### ISSUE THREAD

**Issue by noescape00** [stratisproject/StratisBitcoinFullNode#1250]
So we have the `SendTrickleAsync` in `MempoolBehavior` which relays the transactions to the peers. Inside it it has 

```
  if (!this.CanSend)
            {
                this.logger.LogTrace("(-)[NO_SEND]");
                return;
            }
```

And the getter for the CanSend has this: 

```
if (this.NextInvSend < this.manager.DateTimeProvider.GetTime())
                {
                    sendTrickle = true;
                    // Use half the delay for outbound peers, as there is less privacy concern for them.
                    this.NextInvSend = this.manager.DateTimeProvider.GetTime() + TimeSpan.TicksPerMinute;
                }
```

`NextInvSend` is the next timestamp after which we can relay the tx. It is a unix timestamp. 
So this line
` this.NextInvSend = this.manager.DateTimeProvider.GetTime() + TimeSpan.TicksPerMinute;`
is:

NextUnixTime = CurrentUnixTime + 600000000.

600000000 seconds is ~20 years.

**Comment by dangershony** [comment]
Yeah if we already have a delay in the loop we don't need another delay logic in `CanSend` I agree.
And I think this two elements can become ConcurrentDictionaries  `inventoryTxToSend` and `filterInventoryKnown` then we only use the mempool lock when calling the mempool.

**Comment by dangershony** [comment]
@Aprogiena had a good comment on the closed PR us the existing constant

**Comment by dangershony** [comment]
This issue is going to be used for rarefaction mempool behaviour as per comments above.

**Comment by mikedennis** [comment]
@dangershony @noescape00 Just to confirm what's involved here:

In mempool behaviour replace locking done with ```this.manager.MempoolLock.WriteAsync(()```

With individuals locks around access to:
```
this.inventoryTxToSend
this.filterInventoryKnown
```
Question: Are there any existing tests that will test this?

**Comment by noescape00** [comment]
>In mempool behaviour replace locking done with this.manager.MempoolLock.WriteAsync(()
>With individuals locks around access to:

Yes. But also this issue suggests fixing general design problems: 

1) We have 2 different delays- one in async loop and one in CanSend
2) CanSend getter actually changes the value which is not an expected behavior 
3) Potentially the same logic can be used for tx relaying and tx propagation (but that might be a separated task since it's a big one)

**Comment by mikedennis** [comment]
@noescape00 @dangershony What's the next priority with this? The 3 items noescape mentions above? I will start working on the next PR.

**Comment by dangershony** [comment]
What is the next PR?

**Comment by noescape00** [comment]
Yes, after fixing the locks next logical here is to improve on the design. Potential improvements are mentioned in that comment from the 3rd of May

**Comment by mikedennis** [comment]
I'm working on this next:

> Potentially the same logic can be used for tx relaying and tx propagation, currently each of them uses it's own implementation (but that might be a separated task since it's a big one)

**Comment by noescape00** [comment]
>I'm working on this next:

Ok. But that's more like a research. You will need to check out BTC core too. 
The thing is: when we are propagating someone else's tx we can propagate to all the peers and we can delay it a bit to form batches. 
For our txes we wanna do it right away (maybe add to a batch and trigger send?) and maybe we want to send to half of the peers (so we receive it from other part and know for sure it was accepted and propagated). 
So hard to tell, we first need to investigate it.

**Comment by mikedennis** [comment]
Sounds good - will check on BTC core first and see what they are doing 👍

**Comment by mikedennis** [comment]
Regarding propagating someone else's tx: seems btc core is sending it right away just like we are. I didn't see any batching logic unless it's buried in the peer itself.

Looking through ``` ProcessTxPayloadAsync ``` and comparing with btc core a couple of things I noticed:
*  We seem to be missing the whitelisting/whitelistrelay logic but btc has it. Looks like we've  implemented something similar in ProcessInvAsync()  so we could also implement that when processing tx payload.
* There is a piece of empty logic which seems to be in ``` this.orphans.ProcessesOrphansMissingInputs(peer, trx); ``` (Seems like a candidate for removal unless I'm missing something):
``` 
               if (!trx.HasWitness && state.CorruptionPossible)
                {
                }
```

Let me know if you guys think these are worthwhile doing - seems like fairly low hanging fruit. This mempool behavior code is filled with todo's so there is lots of future potential tasks here as well 😉

**Comment by noescape00** [comment]
What whitelisting logic does in BTC? It doesn't validate txes from whitelisted nodes when they are getting to the mempool? 

>Let me know if you guys think these are worthwhile doing

For sure. This component is a mess and we need to fix it sooner or later.

**Comment by mikedennis** [comment]
I think this issue can be closed?

**Comment by noescape00** [comment]
Yes, I think so
