### ISSUE TITLE
Wallet allows to spend not matured/recently staked coins

### ISSUE THREAD

**Issue by maciejzaleski** [stratisproject/StratisBitcoinFullNode#1255]
Wallet will allow user to spend coins before they are mature.
Such transaction will not be accepted by accepted into the mempool.

**Comment by dangershony** [comment]
Is it not enough that the mempool will reject it?
What I mean is the trx still in the wallet even that it got rejected?

**Comment by noescape00** [comment]
@majikandy @dangershony wasn't it already fixed on master a week ago or so?

**Comment by bokobza** [comment]
Closed with https://github.com/stratisproject/StratisBitcoinFullNode/commit/81b6d424e7d0c9658e46b337decc5dfe49a39f03
