### ISSUE TITLE
please adding method of handle payments on API

### ISSUE THREAD

**Issue by clintm90** [stratisproject/StratisBitcoinFullNode#1265]
Please add methods for handle payments like getreceveidbyaddress for implementing FN as payment gateway :+1: 

thanks

**Comment by bokobza** [comment]
Good idea. Thanks @clintm90 .

**Comment by clintm90** [comment]
Maybe you can also do like electrum, i have discovered this : http://docs.electrum.org/en/latest/_images/payrequest.png at http://docs.electrum.org/en/latest/merchant.html

(it's an other things)

**Comment by dangershony** [comment]
Absolutely a good idea, I am not sure we have capacity right now in the team but I think we can get that as a bounty on the foundation @StratisDeveloper

**Comment by clintm90** [comment]
i would like to make a block explorer but i was banned from your discord

**Comment by dangershony** [comment]
>i would like to make a stratis block explorer but i was banned from your discord
Dude what have you done to deserve exile?

Find me on SDF maybe I can fix this.

**Comment by bokobza** [comment]
This has been done by @MSinteur317 in this PR: https://github.com/stratisproject/StratisBitcoinFullNode/pull/1313
