### ISSUE TITLE
Merkle calculation issues

### ISSUE THREAD

**Issue by noescape00** [stratisproject/StratisBitcoinFullNode#1278]
There are 2 issues:

1) `BlockMerkleRootRule` has it's implementation of the merkle tree calculation which is a copy paste from the PowConsensusValidator. So there are 2 copies of the same functionality and the one that is not covered by tests is being used. 

2) `BlockMerkleRootRule` throws in case merkle tree was mutated (`ConsensusErrors.BadTransactionDuplicate.Throw();`). This exception is being handled by `ConsensusLoop.AcceptBlockAsync` and the block is marked as invalid. The problem here is that we can't ban such a block because a valid block with the same hash might exist so there is an attack where invalid block is created in order to force the network to ban a valid block. More info here: https://bitcointalk.org/index.php?topic=102395.0

So instead of banning the block we should just discard it and ban the peer that provided such a block.

Created with @Aprogiena

**Comment by dangershony** [comment]
1. Very good point the tests in `MerkeRootComputationTest` should point to the `BlockMerkleRootRule` rule instead of the methods in PowConsensusValidator, how did get slip by me I am not sure.

2. So we probably need to create a new consensus error type for this behaviour.

Very good @noescape00

**Comment by noescape00** [comment]
>So we probably need to create a new consensus error type for this behaviour.

We can do it like that (create a type of errors that doesn't lead to banning the block) or do it the same way as `InvalidPrevTip` or `BadWitnessNonceSize` errors are handled in the consensus loop. Those 2 have custom handling and do not ban the block or peer so probably we can add there `BadTransactionDuplicate` exception and just ban the peer but avoid banning the block.

**Comment by Aprogiena** [comment]
just add that if for now

**Comment by dangershony** [comment]
>just add that if for now
What?

**Comment by noescape00** [comment]
Also there is one more issue with mutated blocks that was discovered just today: if the block is below the last checkpoint we check the hash but don't check if it's mutated so we will download and save a mutated block.

I suggest we don't allow validation skip for the BlockMerkleRootRule.
