### ISSUE TITLE
staking via Stratis Core stakes the whole wallet not just account 0

### ISSUE THREAD

**Issue by majikandy** [stratisproject/StratisBitcoinFullNode#1284]
Currently the staking isn't provisioned at account level, only at wallet level. This means that even though the wallet currently only supports account 0, it actually stakes the whole of the wallet as this is all the full node can currently do.

**Comment by noescape00** [comment]
Is it an issue? 
I guess it's good that staking supports all accounts- at least we won't need to change that in the future when other components will get support for different accounts.

**Comment by dangershony** [comment]
Account is not equivalent to wallet (a wallet has many accounts) so this is correct and by design.
You stake on the whole HD seed.
