### ISSUE TITLE
spending staking balance doesn't reduce the staking weight even though staking stops for that stake

### ISSUE THREAD

**Issue by majikandy** [stratisproject/StratisBitcoinFullNode#1294]
spending balance during staking doesn't reduce the staking weight.  

It does change the staking to false, even though enabled is true.

Eg a wallet with 3ish strat, started staking and then spent 3 strat.

http://localhost:37221/api/Miner/getstakinginfo
Response Body
{
  "enabled": true,
  "staking": false,
  "errors": null,
  "currentBlockSize": 1051,
  "currentBlockTx": 3,
  "pooledTx": 2,
  "difficulty": 2801938.94206241,
  "searchInterval": 16,
  "weight": 300000000,
  "netStakeWeight": 2416188529798498,
  "expectedTime": 484818631
}

**Comment by Aprogiena** [comment]
The mechanics of this is that enabled indicates if the staking was enabled in this instance, but does not necessarily means you can stake. Staking means whether you stake at the very moment. And weight and expectedTime are only valid if staking is true.

But it is no problem to make those 2 valid even if staking is false. The easiest way to do it is probably to create the setter for staking property inside GetStakingInfoModel. And if the new value is supposed to be false, then just set the weight and expected time to default values.

**Comment by dangershony** [comment]
I dont see how we can return valid arguments for weight and time when no outputs are available.
We could definitely return valid argument for netweight and difficulty when staking=false

**Comment by Aprogiena** [comment]
When you are mining, those values are filled. When you then stop mining, those values are not reset. The question is whether they should be reset are not, because even their default values, zeros, will be as invalid as any other values. Simply because when you are not staking, those values have no meaning. So having 3000 is as meaningful as having 0 there. But optically, it looks better if you have 0 there regardless of that it is not meaningful.

**Comment by dangershony** [comment]
Ah yeah ok lets reset them optics is important when user input is involved.

**Comment by kogot** [comment]
Hey guys, I discovered, that if while staking we send transaction. Its stops staking by set `this.rpcGetStakingInfoModel.Staking = false`. That param stops node staking, and even if you try to start staking again, it won't start cause "currentStatus" hasn't been changed, so node still thinks that it's staking.
And as a result, GetStakingInfo returns incorrect weight.

BTW if you stop staking it will reset GetStakingInfoModel to 0.
