### ISSUE TITLE
merge unit tests into a single project with folders per assembly tested

### ISSUE THREAD

**Issue by majikandy** [stratisproject/StratisBitcoinFullNode#1298]
Unless the projects are likely to be used independently of each other and/or composed into other solution files.  The only benefit of having separate unit tests per assembly is having a logical separation.  

The separation can be achieved very simply in a single unit test project by having a folder per tested assembly.

I have used this approach at several companies and it works really well.   One of its main advantages is it reduces a bit of load on Visual Studio. VS doesn't like lots of projects, so you have 30 projects,  you have 30 + 1 projects rather than 30 + 30 projects  (or perhaps 32/33 if you have integration tests and acceptance/e2e tests) - but at least not 62.

discussed the idea with @noescape00  - open for more discussion here.

**Comment by dangershony** [comment]
Why would you do that?
Features are isolated entities each feature should have its own tests project.
What we can do is move some features out of VS or create different solutions 

For example WatchOnly feature can love in another repo.

**Comment by majikandy** [comment]
If they truly can be composed into other solutions and actually will be then yes, separate is fine.

If it is just for logical separation, folders is easier because VS performs better with less projects

**Comment by noescape00** [comment]
>Why would you do that?

The issue was raised after a PR was created by @majikandy where some of the utils from the tests projects were copy pasted in order to remove dependencies between different test projects. 

I suggested that if we really dont want test projects to depend on each other we can move shared code to a Test.Utils project or move all tests to a single project- any of those 2 solutions would be better comparing to copy-pasting the code. 

But the questions is: do we actually need to avoid those dependencies? I'm fine with having them. 

I don't see why those dependencies are a problem.

**Comment by majikandy** [comment]
The dependencies between the test projects are sort of ok but they were causing (for @fassadlr ) tests to be run multiple times - especially on the build server where the dlls get copied to the output directory and then.

But then if you are gonna have dependencies between the projects, this rules out composing other solutions with only some of the projects, as you now have to have the other projects too. Therefore if you are going to have dependencies between projects, you might as well have a single unit test project and get the advantages of simplifying the vs solution and automatically have access to the shared code.

>Why would you do that?
>Features are isolated entities each feature should have its own tests project.
Therefore having dependencies between the test projects then breaks that isolation.
Now that the dependency is broken, it is quite ok to have separate test projects per feature project if felt necessary for isolation.

**Comment by majikandy** [comment]
>any of those 2 solutions would be better comparing to copy-pasting the code.
The copy paste was a subset of the 500 line "helper" class shared. Just 1-3 methods used by the other few projects... having their own copy of those methods is not automatically a bad solution just because it is a copy paste. If something changes with the behaviour of that, you have to update in a few places, but this is test code, so the tests would highlight that, and at that point if it became an issue you could consolidate the code and have a shared library. Moving immediately to a shared library is not always the best solution.  I personally was swaying more towards their own copy rather than shared tests wallet common with the test helper as that class is already a dumping ground, having it shared possibly just encourages that even more, so we'll need to watch out for that.

**Comment by bokobza** [comment]
At the moment we have a project common to all tests and a projects common to all the tests for wallet-related projects. I think it's ok like that for now 👍 
If everyone is happy, @majikandy feel free to close this issue.
