### ISSUE TITLE
Unit tests intermittent failure when running as a group (removing directories not empty)

### ISSUE THREAD

**Issue by majikandy** [stratisproject/StratisBitcoinFullNode#1299]
Many unit tests are using a TestBase with creates and removes Data directories etc.

This sometimes fails when running all tests due to folders not being empty or files being locked.  Rerunning these tests individually again gives a pass.

This is not good behaviour to have. They should be 100% reliable whether run as a group or individually.

The main problem as I see it here is that unit tests shouldn't be creating files and folders like this, if they are for the logger then the logging should be mocked out / turned off and only used for real when actually testing the logged logs to disk.  The same with any chain stuff / the persistence can be mocked out.

Then the actual persisitence stuff of loggers or dbreeze stuff can be tested using integration tests where having a Data Directory and using the file system is perfectly fine.

Unit tests should be as fast as possible and not touch slower resources like the file system unnecessarily.

**Comment by majikandy** [comment]
That looks useful,  I do wonder if this is sticking a "band aid" on the issue instead of actually resolving it. In a way, the current behaviour has highlighted too much file system stuff perhaps?

**Comment by majikandy** [comment]
File system stuff is OK for integration tests, and the TestBase is used by that too, probably that should have its own IntegrationTestBase

**Comment by Neurosploit** [comment]
@majikandy The logging used to be a static logger without any interface to mock. Since then we've gotten an interface and we can remove the logfactory and replace it with a mock. 

With regards to the filesystem we need an abstraction layer for this so we can mock away the filesystem persistence.

**Comment by bokobza** [comment]
This issue has been fixed in this PR: https://github.com/stratisproject/StratisBitcoinFullNode/pull/1330

**Comment by majikandy** [comment]
>With regards to the filesystem we need an abstraction layer for this so we can mock away the filesystem persistence.
@Neurosploit Yep - and then we can split the TestBase and not use the same one for unit and integration tests as they have different concerns.

**Comment by bokobza** [comment]
Done
