### ISSUE TITLE
Checkpoints are always disabled

### ISSUE THREAD

**Issue by noescape00** [stratisproject/StratisBitcoinFullNode#1315]
If `settings.UseCheckpoints` is `false` we won't load the checkpoints:

Checkpoints.cs: 157

```
if (!settings.UseCheckpoints) this.checkpoints = new Dictionary<int, CheckpointInfo>();
```

The problem is that we call the checkpoints constructor and check that `settings.UseCheckpoints` before we load the value in ConsensusSettings: 41

```
this.UseCheckpoints = config.GetOrDefault<bool>("checkpoints", true);
```

So basically checkpoints are always disabled no matter what.

ps
I also suggest adding test for the use-checkpoints switch after the issue is fixed.

**Comment by noescape00** [comment]
@dangershony

**Comment by Aprogiena** [comment]
How is that possible? It worked before well, have we changed something?

**Comment by dangershony** [comment]
@Neurosploit all yours

**Comment by dangershony** [comment]
This was fixed closing
