### ISSUE TITLE
NLog file to be picked from datafolder

### ISSUE THREAD

**Issue by dangershony** [stratisproject/StratisBitcoinFullNode#1336]
More info here
https://github.com/stratisproject/StratisBitcoinFullNode/issues/1307

**Comment by Aprogiena** [comment]
> It is from a user experience most users know where the data folder is and its easy to just drop a file there (our other config files are there already) ok I will create an issue.

Yes, but this is exactly what we don't need because logs configuration is not use a feature, it is for developers only

**Comment by Aprogiena** [comment]
But okay if we want to do that regardless of motivation, we need to make sure that we loaded is the 1st thing in the node, so that the whole initialisation of the node can be logged

**Comment by dangershony** [comment]
Ok I guess its not high priority but the settings are anyway loaded before any DI is injected (in the settings Load method).
