### ISSUE TITLE
Stratis.StratisD initializes wrong network from .conf file

### ISSUE THREAD

**Issue by mikedennis** [stratisproject/StratisBitcoinFullNode#1355]
If you specify the network in the conf file instead of with command line it will always initialize with Stratis mainnet. Also we should support stratis regtest network as well.

This is an issue with integrating with NBitcoin AltCoin test framework.

**Comment by dangershony** [comment]
Support regtest from console or config? yeah why not.

I guess the problem is we look at args in stead of ConfigReader

**Comment by mikedennis** [comment]
Yes might be a bit tricky. NodeSettings would need to know which daemon it's running under to select the right network. Could we use ProtocolVersion == ProtocolVersion.ALT_PROTOCOL_VERSION to determine if should look at Stratis networks instead of Bitcoin ones?

**Comment by quantumagi** [comment]
The problem is that we are passing the network to the NodeSettings constructor. Once a network is passed in this way it takes precedence over the command line and configuration file.

Simply not passing the network to the constructor should leave us with the desired outcome.

**Comment by mikedennis** [comment]
Yes that works for me thanks!
