### ISSUE TITLE
Missing Stratis RPC methods for integrating with NBitcoin AltCoin test framework

### ISSUE THREAD

**Issue by mikedennis** [stratisproject/StratisBitcoinFullNode#1356]
The NBitcoin AltCoin test framework uses RPC on a regtest daemon. The following RPC functions are used:

- GetBlock
- Generate
- GetBestBlockHash
- getnewaddress
- validateaddress (DONE)
- sendtoaddress (DONE)
- getrawtransaction (DONE)
- sendrawtransaction

**Comment by quantumagi** [comment]
- getblock
- generate (MiningRPCController)
- getbestblockhash (ConsensusController)
- getnewaddress
- validateaddress (DONE) (FullNodeController)
- sendtoaddress (DONE) (WalletRPCController)
- getrawtransaction (DONE) (FullNodeController)
- sendrawtransaction

**Comment by quantumagi** [comment]
The current approach allows new features to be added together with any RPC methods that they contribute - i.e. it does not require updating any code that is shared between features.

**Comment by dangershony** [comment]
Yes agreed, though we have the api feature for that.
RPC I would hope will slowly become less used and we only support it for legacy reasons.

**Comment by mikedennis** [comment]
The current architecture leads to dependencies on the RPC feature like below:

```
public static IFullNodeBuilder AddPowPosMining(this IFullNodeBuilder fullNodeBuilder)
        {
            LoggingConfiguration.RegisterFeatureNamespace<MiningFeature>("mining");

            fullNodeBuilder.ConfigureFeature(features =>
            {
                features
                    .AddFeature<MiningFeature>()
                    .DependOn<MempoolFeature>()
                    .DependOn<RPCFeature>()
                    .DependOn<WalletFeature>()
                    .FeatureServices(services =>
                    {
                        services.AddSingleton<IPowMining, PowMining>();
                        services.AddSingleton<IPosMinting, PosMinting>();
                        services.AddSingleton<IBlockProvider, BlockProvider>();
                        services.AddSingleton<BlockDefinition, PowBlockDefinition>();
                        services.AddSingleton<BlockDefinition, PosBlockDefinition>();
                        services.AddSingleton<BlockDefinition, PosPowBlockDefinition>();
                        services.AddSingleton<StakingRpcController>();
                        services.AddSingleton<StakingController>();
                        services.AddSingleton<MiningRpcController>();
                        services.AddSingleton<MiningController>();
                        services.AddSingleton<MinerSettings>();
                    });
            });

            return fullNodeBuilder;
        }
```
If we truly want RPC to be pluggable then it should be the other way around. RPC should depend on the features it needs and have the controller in the RPC feature.

If we want to treat RPC as kind of core component (not pluggable) then it makes sense to have RPC controllers in the individual features.

I'm in the midst of adding some more methods according to @quantumagi suggestions above. Is this what we want to do?

@dangershony

**Comment by mikedennis** [comment]
After looking into this I think I agree with dangershony, I'm not sure coupling the RPC feature to all the features like above is a good idea.  If we want to make RPC pluggable we should create a separate feature like "Stratis.Bitcoin.Features.Miner.RPC" that has RPC controller for the miner feature.

But for now the easiest approach without re-architecting some of this is to add:
getblock -> FullNodeController (it already has reference to blockstore)
getnewaddress, sendrawtransaction -> WalletRPCController (it already has references to wallet stuff)

**Comment by mikedennis** [comment]
Also need to add:
sendtoaddress -> WalletRPCController

Currently only a stub there, it doesn't actually work.

**Comment by mikedennis** [comment]
Also need to add:
  gettransaction
  getbalance
