### ISSUE TITLE
[POS Mining] incorrect logic due to missing return

### ISSUE THREAD

**Issue by Aprogiena** [stratisproject/StratisBitcoinFullNode#1357]
there should be return after this line https://github.com/stratisproject/StratisBitcoinFullNode/blob/master/src/Stratis.Bitcoin.Features.Miner/PosMinting.cs#L383

**Comment by dangershony** [comment]
OMG how did I miss this that fixes the other bug I raised, good spot.

**Comment by dangershony** [comment]
This bug is related
https://github.com/stratisproject/StratisBitcoinFullNode/issues/1338

**Comment by Aprogiena** [comment]
Actually I believe that one is not related. 1338 is kind of trivial because we are not waiting for the end of the loop which is using something that we set to null. Just check the cancellation token there, stop staking its setting it to null.
