### ISSUE TITLE
Advantages of the NetworkBuilder?

### ISSUE THREAD

**Issue by bokobza** [stratisproject/StratisBitcoinFullNode#1362]
I'm trying to understand why we have a NetworkBuilder for creating a Network object, rather than use vanilla property assignment.

I find it easier to understand
1.
```
Network network = new Network();
network.DefaultPort = 18333;
network.RPCPort = 18332;
```
than
2.
```
var builder = new NetworkBuilder()
.SetPort(26178)
.SetRPCPort(26174);
Network network = builder.BuildAndRegister();
```

When you want to add an extra property in 1., all the user has to do is 
1. add a property to Network
2. assign it when we create a Network

When you want to add a property in 2., the user needs to:
1. add a property to Network
2. add a property in the builder
3. add a method in the builder
4. use the method when we construct the Network
5. add the property from the builder to the Network in the `Network Register(NetworkBuilder builder)` method

There is a lot more room for error in 2., for example if the developer forgets to do 5. above.

Can anyone think of a good reason why we should keep the NetworkBuilder?
In the interest of simplicity and code maintainability, I think we should can it.

**Comment by monsieurleberre** [comment]
I agree that if the flow methods are only setting a field value (like it often seems to be the case here) that seems like an overkill. If each method sets a complex object, and that those different objects can be composed independently (like for building and attaching features to the node), then I think it is a very clean syntax. Here, I agree that I am not sure where this adds value.

**Comment by rowandh** [comment]
The Network object itself is immutable, which is a good thing. Using the builder pattern here enables immutability.

Though we are not yet using it like this, one other advantage of using a builder would be to prevent a Network object ever being created in an invalid state. Eg. if a Network object always needs a Genesis, or a Port, the builder can enforce this.

If we treat Network as a property bag, we lose immutability and the ability to prevent it from being in invalid states. I would argue that there is more room for error with this approach, vs. the one-off effort of adding another property to both `Network` and `NetworkBuilder`.

**Comment by Neurosploit** [comment]
I agree with rowan here. I find the immutability of the network class important enough to require the need for a builder. I would rather move away from the direct property assignment that we still have in the networks class in favor of the builder.

**Comment by bokobza** [comment]
Presently, whether we construct the Network with a builder or by using properties, it all comes down to the Network object, modifiable exactly in the same way.
The Network properties are all privately settable so I think the "inadvertently messing the Network object" argument doesn't hold.

**Comment by rowandh** [comment]
Ah ok, I thought you were proposing to make the setters public. Keeping them private means new Networks have to be defined inside of `Network`, as they currently appear to be. This might be fine for a single network + testnet, but with the addition of eg. a SmartContract network + testnet, it begins to feel like we're abusing partial classes.

**Comment by bokobza** [comment]
Yeah at the moment we have 6 networks, and the Network class is split between Networks.cs and Network.cs.
One of my next tasks will be to unify these and make it easy for anyone to create a Network.

**Comment by rowandh** [comment]
I see I've been assigned this but what is the task? NetworkBuilder seems to have been removed already.

**Comment by dangershony** [comment]
The acceptance criteria of this task would be:
Making Network Immutable
Making Network Flexible

For example Consensus has a mixture of POW/POS parameters where POW just ignores some of them, how can we make a better separation

**Comment by rowandh** [comment]
Progress: #1715, #1716, #1717, #1742
