### ISSUE TITLE
WalletTransactionHandler TransactionBuilder does not use network MinRelayTxFee

### ISSUE THREAD

**Issue by rowandh** [stratisproject/StratisBitcoinFullNode#1363]
StandardTransactionPolicy has a hardcoded MinRelayTxFee of 5000 Satoshis. Mainnet has a MinRelayTxFee of 1000 Satoshis.

This affects these usages:
* TransactionBuilder.Verify (uses StandardTransactionPolicy.Check)
* TransactionBuilder.GetDust
* TransactionBuilder.Send (uses TransactionBuilder.GetDust)
* WalletTransactionHandler (uses TransactionBuilder.Verify and TransactionBuilder.Send)

Result: 
* Dust threshold is higher for transactions created using WalletTransactionHandler
* Transactions can fail verification in WalletTransactionHandler even though they might be using a fee rate higher than the network's fee rate

**Comment by noescape00** [comment]
Default min fee is 10k sat/kb so it's not possible that a tx will be created that won't pass StandardTransactionPolicy or MinRelayTxFee threshold. 
Well, unless you are manually creating it- but in that case you should be aware of this limitations. 


The reason why StandardTransactionPolicy fee is greater than MinRelayTxFee is that we want to relay Non-Standard txes just in case there is a miner that might mine it (one that accepts and mines Non-Standard txes). At the same time we would like to avoid having mempool flood attacks (or make them harder) so we have a small relay threshold just so we don't spam the network with txes that spend 1 sat.

**Comment by noescape00** [comment]
@bokobza can you please take a look at this one since you are quite familiar with wallet/fees stuff?

**Comment by rowandh** [comment]
Nice find of the NBitcoin mistake, seems like we need to fix the default value.

There is still a scenario where our code is used by a third party who wanted set a different/no MinRelayTxFee in their Network configuration. Their code might behave unexpectedly if they are unaware of the default value in the StandardTransactionPolicy.

**Comment by dangershony** [comment]
New StandardTransactionPolicy has the Network class passed in the constructor so what we should do is use the values from Network and change them there if they are wrong.

So this is a task we need to push in to the sprint, unless SC team wants to take it
@fassadlr can you check with @bokobza?
