### ISSUE TITLE
Mempool behaviour SendMempoolPayloadAsync doesn't send anything

### ISSUE THREAD

**Issue by mikedennis** [stratisproject/StratisBitcoinFullNode#1375]
Please correct me if I'm wrong but to me it looks like this code doesn't work:

https://github.com/stratisproject/StratisBitcoinFullNode/blob/master/src/Stratis.Bitcoin.Features.MemoryPool/MempoolBehavior.cs#L301-L314

```
            List<TxMempoolInfo> sends = await this.manager.MempoolLock.WriteAsync(() =>
            {
                List<TxMempoolInfo> ret = new List<TxMempoolInfo>();
                foreach (TxMempoolInfo txinfo in vtxinfo)
                {
                    uint256 hash = txinfo.Trx.GetHash();
                    this.inventoryTxToSend.Remove(hash);
                    if (filterrate != Money.Zero)
                        if (txinfo.FeeRate.FeePerK < filterrate)
                            continue;
                    this.filterInventoryKnown.TryAdd(hash, hash);
                }
                return ret;
            });
```

To me it seems like it's missing a step of adding it to sends after it removes it from ```this.inventoryTxToSend``` 

Unless I'm misunderstanding how this is suppose to work?

**Comment by dangershony** [comment]
Yes this code is incomplete, so it needs to be done and also we need to compare with StratisX and bitcoin core behaviour for vulnerabilities.

**Comment by mikedennis** [comment]
Ok I will look at this as part of the work I'm doing on mempool behaviour as it is some of the code I will be touching anyways.  Thanks!

**Comment by dangershony** [comment]
yes please.
