### ISSUE TITLE
Don't allow block signature validation rule skip

### ISSUE THREAD

**Issue by noescape00** [stratisproject/StratisBitcoinFullNode#1391]
Block signature rule shouldn't be skippable (because a bogus signature might be supplied and then when some peer asks us for this block we will provide a block with a wrong signature and we will be banned by such a peer).

Created by @Aprogiena

**Comment by dangershony** [comment]
Ah yeah thats because the block signature is not part of the header hash we have to check it every time.

**Comment by fenix2222** [comment]
@bokobza @dangershony Can this be closed now as https://github.com/stratisproject/StratisBitcoinFullNode/pull/1663 was merged?
