### ISSUE TITLE
Create additional Integration Tests

### ISSUE THREAD

**Issue by bokobza** [stratisproject/StratisBitcoinFullNode#1395]
4 tests here:
* User tries to double-send and fails
* Create 2 tests that tests a transaction size limit:
  -  a test that has a big transaction but valid
  -  a test that has a big transaction but invalid (small size increment from the previous test)
* Create a transaction that uses sequence locks

**Comment by noescape00** [comment]
@bokobza @fassadlr 
Which of those tests were implemented in 1424? Can you please update the issue?

**Comment by fassadlr** [comment]
@noescape00 it was @thefazzer you needed to tag ;)

**Comment by noescape00** [comment]
Ah, yes. Sorry 🙂

**Comment by bokobza** [comment]
sending_transaction_over_policy_byte_limit
sending_transaction_near_policy_byte_limit
sending_transaction_with_double_spend_mined_trx
sending_transaction_with_double_spend_in_mempool

✔️ User tries to double-send and fails
Create 2 tests that tests a transaction size limit:
✔️ a test that has a big transaction but valid
✔️a test that has a big transaction but invalid (small size increment from the previous test)
❔  Create a transaction that uses sequence locks

**Comment by herbepau** [comment]
_**MinerCreateBlockRelativeTimeLockedAsync**_ in **_MinerTests.cs_** already covers sequence locks (nSequence - relative time locks vs absolute time locks - nLockTime).  Accompanying this test are three other tests that also use and test against sequence locks: MinerCreateBlockNonFinalTxsInMempoolAsync, MinerCreateBlockAbsoluteHeightLockedAsync and MinerCreateBlockAbsoluteTimeLockedAsync.
