### ISSUE TITLE
Stabilize Integration Tests

### ISSUE THREAD

**Issue by bokobza** [stratisproject/StratisBitcoinFullNode#1396]

**Comment by dangershony** [comment]
This will also include find what tests can move out from the Integration tests talk to @majikandy @bokobza  or myself to discuss more.

**Comment by monsieurleberre** [comment]
OK I'll give it a try

**Comment by dangershony** [comment]
@maciejzaleski team will take over this task after TB release.

**Comment by ArcSin2000X** [comment]
Running the suite of **intergration tests(158)** is providing better results when executed on bigger box(16CPU) when compared to lower spec. After running numerous test sessions I was able to isolate list of tests that consequently fail on big box test. Notably if you run most of the tests on the list as standalone test you are unlikely to find problems. The next step is to work through the list and fix tests  1 by 1
![image](https://user-images.githubusercontent.com/37782512/44218699-28f09800-a172-11e8-9a76-1e2aef2f0a02.png)

**Comment by ArcSin2000X** [comment]
Zip with stack traces
[HTML_version_of_top_offenders.zip](https://github.com/stratisproject/StratisBitcoinFullNode/files/2294238/HTML_version_of_top_offenders.zip)

**Comment by dangershony** [comment]
Closing this as it will be traced by
https://github.com/stratisproject/StratisBitcoinFullNode/issues/2195

**Comment by bokobza** [comment]
Closing this as we now have many issues opened to fix this.
