### ISSUE TITLE
PoSMinting race condition

### ISSUE THREAD

**Issue by noescape00** [stratisproject/StratisBitcoinFullNode#1397]
There is a race condition in case you call `StopStake` and `Stake` at the same time: 

First Stake will create a new `stakeCancellationTokenSource ` and StopStake will dispose it so by the end of the Stake call staking won't start. Also this race condition covers the whole staking loop itself.

**Comment by dangershony** [comment]
Is that an issue? Staking can then just be called again and will work properly.
Is stop staking was called it was intentional

**Comment by noescape00** [comment]
I guess it is an issue in case in UI we will have a button Start staking/Stop staking. Calling stop and after that start might produce such a race condition so node stats will say that staking is on when it's off.

**Comment by dangershony** [comment]
I am not sure you are right, the cancellation will be cancelled the loop will stop, and this code will still be called `this.rpcGetStakingInfoModel.Enabled = false;`   
So the UI will see staking is not on and user will try again.

Yeah it might crash the node if the cancellation is not initialized already.

But I agree we should put a regular lock around the code in the methods just to be safe.

**Comment by Aprogiena** [comment]
This is a race condition, I appeal to argument by authority and conclude that I am right. LOL

Anyway, seriously, it can crash the node, I can show you on Skype.

**Comment by dangershony** [comment]
Fair point a race condition as small as it is will bite back eventually I learned that the hard way.
