### ISSUE TITLE
StratisDnsD Seeding Banned Peers

### ISSUE THREAD

**Issue by StratisIain** [stratisproject/StratisBitcoinFullNode#1423]
Banned peers are written to the Masterfile.JSON resulting in banned peers continuing to be distributed to new nodes on the network.

**Comment by dangershony** [comment]
This task should also fix  the issue of banning of white-listed nodes (a node that is about to be banned if its white-listed it should not be banned)

**Comment by ferdeen** [comment]
Did a quick review of the code around this.  

It looks like the `DnsFeature `(which deals with seednodes and the whitelist), needs access to peer banning functionality, which is carried out in `Stratis.Bitcoin.Connection`.
