### ISSUE TITLE
Smart Contracts: TestSmartContractState.cs Storage Emulator Bugs

### ISSUE THREAD

**Issue by mwherman2000** [stratisproject/StratisBitcoinFullNode#1428]
There's a series of bugs in `TestSmartContractState.cs` that cause the objects that are being "persisted" to be passed around as Heap objects.  

For example, `TestPersistentState.SetObject`, `TestMapping.Put`, and `TestList.SetValue` store *references* to Heap objects in their respective collection structures ...so after you have "persisted" an object and you change the values of one of the objects fields (assuming the object is an instance of a class with members), you are also changing the values of the "persisted" state as well.  While this may seem desirable, I don't believe this was the intended design and is, in fact, a serious bug.

Here's an example of a test case that demonstrates the problem:
<https://github.com/mwherman2000/STRAT.StorageEmulatorBug1/blob/master/STRAT.StorageEmulatorBug1/STRAT.StorageEmulatorBug1.Tests/AuctionTests.cs#L68>

Here are some suggested fixes for `TestSmartContractState.cs` (basically use JSON to serialize and deserialize each object to simulate it being read and written from Persistent Storage):

https://github.com/mwherman2000/STRAT.StorageEmulatorBug1/blob/master/STRAT.StorageEmulatorBug1/STRAT.StorageEmulatorBug1.Tests/TestSmartContractState.cs#L141

https://github.com/mwherman2000/STRAT.StorageEmulatorBug1/blob/master/STRAT.StorageEmulatorBug1/STRAT.StorageEmulatorBug1.Tests/TestSmartContractState.cs#L157

https://github.com/mwherman2000/STRAT.StorageEmulatorBug1/blob/master/STRAT.StorageEmulatorBug1/STRAT.StorageEmulatorBug1.Tests/TestSmartContractState.cs#L190

https://github.com/mwherman2000/STRAT.StorageEmulatorBug1/blob/master/STRAT.StorageEmulatorBug1/STRAT.StorageEmulatorBug1.Tests/TestSmartContractState.cs#L203

https://github.com/mwherman2000/STRAT.StorageEmulatorBug1/blob/master/STRAT.StorageEmulatorBug1/STRAT.StorageEmulatorBug1.Tests/TestSmartContractState.cs#L239

https://github.com/mwherman2000/STRAT.StorageEmulatorBug1/blob/master/STRAT.StorageEmulatorBug1/STRAT.StorageEmulatorBug1.Tests/TestSmartContractState.cs#L248

p.s. It's interesting to note that the on-chain persistent storage functions also uses JSON serialization (reference: `PersistentStateSerializer` class)

**Comment by mwherman2000** [comment]
A PR/fix for the `TestSmartContractState.cs` VSIX template can be found here:
<https://github.com/stratisproject/StratisBitcoinFullNode/pull/1427>

**Comment by mwherman2000** [comment]
Please check/confirm if this is an issue with the on-chain Persistent Storage design/implementation.

**Comment by codingupastorm** [comment]
Good find. On-chain implementation doesn't have this issue.

Means testing environment and live environment differ. 

I think the only way to have contracts behave in exact same way as on-chain here is to use the exact same serializer.

Will check out your PR, thanks @mwherman2000

**Comment by rowandh** [comment]
Hey @mwherman2000, thanks for the report! We don't support storage of arbitrary reference types yet, so hopefully nobody is writing tests that try to persist them. If they do then they will encounter your bug, which is definitely a problem.

Rather than fix the immediate issue, I think a better approach is to constrain the types that can be stored in PersistentState so that people don't encounter problems such as the one you did. This will be done in an upcoming release.

**Comment by mwherman2000** [comment]
Is this going to be the long-term solution? ... short-term? ...just for off-chain testing? ...or will this restriction also apply on-chain smart contract execution as well?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by mwherman2000** [comment]
Fix re-issued as PR https://github.com/stratisproject/StratisBitcoinFullNode/pull/1455

**Comment by rowandh** [comment]
Closing as this functionality has been removed from the template.
