### ISSUE TITLE
Simplify the conditional statement in Pos/Pow CoinView Rules

### ISSUE THREAD

**Issue by majikandy** [stratisproject/StratisBitcoinFullNode#1433]
Currently the conditional is slightly confusing and has a todo over it

```
                    // TODO: Simplify this condition.
                    if (!tx.IsCoinBase && (!context.IsPoS || (context.IsPoS && !tx.IsCoinStake)))
```

Also in the PosCoinViewRule  another different call is used for checking these things

`BlockStake.IsProofOfStake(block)`
`coins.IsCoinStake`

Perhaps these are correct, but some level of standardisation would be nice.

**Comment by dangershony** [comment]
This was done
