### ISSUE TITLE
Move verify scripts into its own rule

### ISSUE THREAD

**Issue by majikandy** [stratisproject/StratisBitcoinFullNode#1434]
Script verification should go in its own rule rather than within CoinViewRule as this was avoided at the time of coinview rule pull out as changing too much in one go in consensus would be confusing to review - especially as this is a slight change in behaviour.

Script verification could live in its own loop through transactions outside of the coinviewrule transaction loop.

@dangershony sp1 please

**Comment by bokobza** [comment]
this is not required for sp1 as it requires more thoughts and it's an improvement rather than a must-have.

**Comment by bokobza** [comment]
Also do this as part of this change: https://github.com/stratisproject/StratisBitcoinFullNode/issues/1446
