### ISSUE TITLE
Test rules registration order for validation and execution rules

### ISSUE THREAD

**Issue by majikandy** [stratisproject/StratisBitcoinFullNode#1435]
The rules unit test is currently a bit weak as it only tests that the rule registration class returns a list in the correct order.

This will prevent an accidental mistake if it is changed however it doesn't really test the fundamentals of how these rules are called in the main code.

It could be better to test these rules are correctly wired up to the components in a more accurate scenario to the live code and test when validation and execution rules are requested. This would also ensure they are attributed up with the correct Validation/Execution attribute.

Either way, there is definitely room for improvement here.

@dangershony sp1 this please

**Comment by bokobza** [comment]
Closed by https://github.com/stratisproject/StratisBitcoinFullNode/pull/2009
