### ISSUE TITLE
Cancelation token for CheckInputs in PowCoinViewRule

### ISSUE THREAD

**Issue by majikandy** [stratisproject/StratisBitcoinFullNode#1446]
aprogiena wrote: 
>we want to quit checking as soon as possible to prevent denial of service attacks. This will be fully mitigated only when we later implement that cancellation token.

The current for loop for checking the results could be changed to use a cancellation token.

```
                foreach (Task<bool> checkInput in checkInputs)
                {
                    if (await checkInput.ConfigureAwait(false))
                        continue;

                    this.Logger.LogTrace("(-)[BAD_TX_SCRIPT]");
                    ConsensusErrors.BadTransactionScriptError.Throw();
                }
```

**Comment by Aprogiena** [comment]
General idea here is to have a common cancellation token for all the tasks which would be cancelled in case an invalid script is detected and which would prevent starting the costly validation work on the tasks that have not really been started yet.

**Comment by noescape00** [comment]
@majikandy what is the status of this issue?

**Comment by dangershony** [comment]
This is actually more complicated then expected so it can be a low priority refactor
