### ISSUE TITLE
Stratis (pos) BlockHeader get hash method uses the bitcoin consensus factory

### ISSUE THREAD

**Issue by dangershony** [stratisproject/StratisBitcoinFullNode#1467]
This is because ConsensusFactory is defaulted to Bitcoin main network.

Possible fixes are 
- Pass CF in the GetHash method - least preferred idea.
- Inject the CF in the constructor of BlockHeader (possible as the block header is created in CF) could also be done only in the POSHeader
- Move the method GetHash to another place (CF maybe)

**Comment by bokobza** [comment]
This is done.
