### ISSUE TITLE
Split NodeSettings class

### ISSUE THREAD

**Issue by quantumagi** [stratisproject/StratisBitcoinFullNode#1471]
The NodeSettings class is currently both a configuration source for all settings classes AND the settings class for the base feature. This improvement splits the class into two separate classes: `NodeConfiguration` and `BaseSettings`.

**Comment by quantumagi** [comment]
This first PR is ensuring that we have a `public xxxSettings(NodeSettings nodeSettings, Action callback)` method for all settings classes and also does some logging improvements.

**Comment by quantumagi** [comment]
PR 1470 was closed and replaced by https://github.com/stratisproject/StratisBitcoinFullNode/pull/1478.

**Comment by dangershony** [comment]
Not sure this is relevant anymore closing
