### ISSUE TITLE
Blocks are not accessible at some rare points in time

### ISSUE THREAD

**Issue by noescape00** [stratisproject/StratisBitcoinFullNode#1479]
This behavior was present in our node for a long time and it might have been a source of several problems. 

When consensus advances or reorgs it signals components about a new block. This block will get to the block store pending storage and until batch with this block is saved it won't be accessible to anyone and if some component asks for a block it might receive a null because it's not in the repository. 

Solution for this would be avoiding calling BlockRepository directly (allow only block store queue access it) and whenever we want a block we should ask BlockStoreQueue which will first check if the block is present in the pending storage and if not- ask block repository. 

Ps
Right now we have some safeguards against this- we use block store cache in most of the places and usually block is there while we are saving the batch. However it's still possible to have a problem because cache keeps 300 blocks and batch is saved based on the batch size.

**Comment by noescape00** [comment]
>But for such cases that are not solicited perhaps as you suggested we put all blocks in some cache before they make it to store.

I'm suggesting asking pending storage as well. 

If we put blocks into the cache (which we already do) and in the background we have a wallet syncing it will override those 300 items that are in the cache.

**Comment by Aprogiena** [comment]
The idea is to get rid of the cache because a better cache is implemented in CHT. Then we need the queue itself to be checked for the blocks that are yet to be written to the database.

**Comment by dangershony** [comment]
This is done in activation right?

**Comment by noescape00** [comment]
@dangershony yes

**Comment by noescape00** [comment]
Fixed with activation merge.
