### ISSUE TITLE
Stratis Full Node

### ISSUE THREAD

**Issue by FaysalM** [stratisproject/StratisBitcoinFullNode#151]
Hi guys 

I have some azure credits and wanted to run a full Stratis node now that its playing with the big boys. What do I need to do? Just compile the master and run? 

Thanks,

**Comment by dangershony** [comment]
That's great what network do you want to run on stratis or bitcoin?

Yeah just compile the master and either run stratisd or bitcoind

**Comment by FaysalM** [comment]
Stratis of course ... bitcoin has more than enough nodes!! So startisd should do it then?

**Comment by dangershony** [comment]
Hi you need any support here or can I close this?

**Comment by FaysalM** [comment]
Sorry I left this open. Closing this now. All good!
