### ISSUE TITLE
wallet private chain and main chain building

### ISSUE THREAD

**Issue by xianaofei** [stratisproject/StratisBitcoinFullNode#1525]
How to build a private chain, for example, to build a BTC Wallet
WGet https://bitcoin.org/bin/bitcoin-core-0.15.1/bitcoin-0.15.1-x86_64-linux-gnu.tar.gz
Echo "export PATH=${PATH}: /usr/local/bitcoin/bin/"
Bitcoin.conf
Seek help
How to build the private chain and main chain of Stratis Purse
WGet xxx (What is the address of the wallet？)
Does Stratis have a wallet under Lunix?
Thank you

**Comment by dangershony** [comment]
Yes stratis is dotnet core which is cross platform.

To create a new wallet is fairly easy please refer to our discord for guidance.

**Comment by xianaofei** [comment]
Sorry

I want more details. As a beginner, I need more help.

Thank you

**Comment by osef123** [comment]
Go on discord to ask questions please: https://discord.gg/9tDyfZs
