### ISSUE TITLE
SmartContracts: Add support for `public partial structs`

### ISSUE THREAD

**Issue by mwherman2000** [stratisproject/StratisBitcoinFullNode#1545]
Add support for `public partial structs` to enable structs to be implemented across more than one C# source file:
- C# compiler supports this already
- Creates a single, plain old C# MSIL assembly/DLL
- SCT would need to be updated to support the passing in of multiple source files.

```csharp
namespace SerentityData.mwherman2000.ImageManager.Prototype
{
    public partial struct ImageLedgerEntry : IGenericLedgerEntry030Basic<ImageLedgerEntry> /* Level 0 Basic */
    {
        private Int32  _imageVersion;
        private string _imageName;
        private byte[] _imageContent;
    }
}
```
CC: @codingupastorm

**Comment by codingupastorm** [comment]
Can do. We'll have support for multiple files in the future. Will try and sneak that in soon.

**Comment by codingupastorm** [comment]
@mwherman2000 we're starting to address this: 

https://github.com/stratisproject/StratisBitcoinFullNode/pull/1700

I believe it will be available by beta / mainnet

**Comment by rowandh** [comment]
This functionality is present now.
