### ISSUE TITLE
Resolve todo issues in mempool behavior 

### ISSUE THREAD

**Issue by mikedennis** [stratisproject/StratisBitcoinFullNode#1555]
Work based upon bitcoin core implementation

**Comment by mikedennis** [comment]
@noescape00 @dangershony I notice that there is logic in btc core related to setting min tx fee on peers. Do you guys know do we have that feature in our peer implementation?

**Comment by dangershony** [comment]
Its min relay tx fee no? (meaning how much fee required to relay a trx)
I think we have it and its configurable.

**Comment by noescape00** [comment]
Yeah, we have it. And it's lower than min fee to include it to the block.

**Comment by mikedennis** [comment]
```ProcessInvAsync()``` logic around blocksOnly mode is incorrect. It currently is just outputting a warning and still sending the the tx, but what btc core is doing is it should just add it to known inventory but not relay it to peer.

**Comment by mikedennis** [comment]
A few other todo's that need to be discussed for "INV" (``` ProcessInvAsync() ```)message:
* Misbehaving logic (basically peer banscore). I don't think we have banscore implemented at all in our p2p? Is this something we want to implement?
* Btc process blocks in inventory in addition to tx (we currently only process tx's). It looks like when btc receives a block in inventory that it doesn't already have it asks the peer for it's headers. Is this something we should be doing as well? 
```
if (inv.type == MSG_BLOCK) {
                UpdateBlockAvailability(pfrom->GetId(), inv.hash);
                if (!fAlreadyHave && !fImporting && !fReindex && !mapBlocksInFlight.count(inv.hash)) {
                    // We used to request the full block here, but since headers-announcements are now the
                    // primary method of announcement on the network, and since, in the case that a node
                    // fell back to inv we probably have a reorg which we should get the headers for first,
                    // we now only provide a getheaders response here. When we receive the headers, we will
                    // then ask for the blocks we need.
                    connman->PushMessage(pfrom, msgMaker.Make(NetMsgType::GETHEADERS, chainActive.GetLocator(pindexBestHeader), inv.hash));
                    LogPrint(BCLog::NET, "getheaders (%d) %s to peer=%d\n", pindexBestHeader->nHeight, inv.hash.ToString(), pfrom->GetId());
                }
}
```
* There is some logic around combining fetch flags from the peer to the inventory type 
``` 
uint32_t nFetchFlags = GetFetchFlags(pfrom, chainActive.Tip(), chainparams.GetConsensus()); 
inv.type |= nFetchFlags;
``` 
I'm not sure whether this is something we should be doing as well. Do we have these fetch flags?

**Comment by mikedennis** [comment]
@dangershony @noescape00  Looking for your opinion on the above when you get a chance.

Also in regards to tx relay fee. What I'm looking at is actually the "feefilter" p2p message. It doesn't look like we implement it. It was implemented in BTC 0.13 here is the bip https://github.com/bitcoin/bips/blob/master/bip-0133.mediawiki

**Comment by mikedennis** [comment]
Also in GetData for btc core there is some logic to not relay transactions from mempool if they weren't inv'd from a mempool request. It doesn't look like we've implemented this logic in our version. Let me know if this feature is a priority.

```
            } else if (pfrom->timeLastMempoolReq) {
                auto txinfo = mempool.info(inv.hash);
                // To protect privacy, do not answer getdata using the mempool when
                // that TX couldn't have been INVed in reply to a MEMPOOL request.
                if (txinfo.tx && txinfo.nTime <= pfrom->timeLastMempoolReq) {
                    connman->PushMessage(pfrom, msgMaker.Make(nSendFlags, NetMsgType::TX, *txinfo.tx));
                    push = true;
                }
            }
```

**Comment by bokobza** [comment]
Closed with https://github.com/stratisproject/StratisBitcoinFullNode/pull/1649
