### ISSUE TITLE
Node drops all connections if there are no DNS nodes

### ISSUE THREAD

**Issue by noescape00** [stratisproject/StratisBitcoinFullNode#1561]
AddrPayload is created with no addresses If there are no DNS nodes specified. This makes all connections to drop (connections are establishes using -connect and -addNode commands).

Reported by sondreb from the community discord, didn't check myself yet.

**Comment by sondreb** [comment]
The setup is with two local nodes, with only the two LAN IPs as seed nodes (no DNS seeds). Connection stops after the resulting "addr" response, if it returns an empty array.

Manually setting some values in the return value of AddrPayload class, makes two nodes successfully connect and keep connection open.

**Comment by sondreb** [comment]
I think this problem means that in an instance where multiple nodes have issues connecting to the DNS seed nodes, and doesn't already have a peers list cached locally, nodes won't be able to connect and start sharing data. Starting up 4 nodes locally (different ports), they will all attempt to connect and then fail.

If I modify the Addresses property of the AddrPayload, with the following, then all 4 nodes will connect:

```
public NetworkAddress[] Addresses { get {
        return new NetworkAddress[] { new NetworkAddress(System.Net.IPAddress.Parse("10.0.0.192"), 24333),
            new NetworkAddress(System.Net.IPAddress.Parse("10.0.0.192"), 25333),
            new NetworkAddress(System.Net.IPAddress.Parse("10.0.0.192"), 26333),
            new NetworkAddress(System.Net.IPAddress.Parse("10.0.0.192"), 27333) };
    } }
```

**Comment by dangershony** [comment]
@sondreb why do the nodes disconnect any idea, Is there an exception thrown?

**Comment by sondreb** [comment]
To have VS 2017 react to the exception on the client node connecting to another node, you have to turn on break on all .NET exceptions. If you do that, you will see:

ExtendedSocketException: No connection could be made because the target machine actively refused it

And in the log of the client node, you will see:

Peer '[::ffff:IPv4]:PORT' offline, reason: 'Receiving cancelled.'.

**Comment by dangershony** [comment]
>I think this problem means that in an instance where multiple nodes have issues connecting to the DNS seed nodes, and doesn't already have a peers list cached locally, nodes won't be able to connect and start sharing data

I don't really understand the problem here, if DNSs are down and the node has no address db then where will it find peer to connect to?
