### ISSUE TITLE
Incorrect proof of work

### ISSUE THREAD

**Issue by sondreb** [stratisproject/StratisBitcoinFullNode#1614]
Setting up a local network of two nodes, I had two nodes both mining, the first node was online first and mined 2 blocks, then I turned on the second node and it mined 1 block before it synced up with the other node. Then after a short while, the second node started complaining about "incorrect proof of work" (the node finds a new block).

```
Consensus error exception occurred in miner loop: Stratis.Bitcoin.Consensus.ConsensusErrorException: incorrect proof of work

at Stratis.Bitcoin.Consensus.ConsensusError.Throw() in C:\...\src\Stratis.Bitcoin\Consensus\ConsensusErrorException.cs:line 44

at Stratis.Bitcoin.Features.Consensus.Rules.CommonRules.BlockHeaderPowContextualRule.RunAsync(RuleContext context) in C:\...\src\Stratis.Bitcoin.Features.Consensus\Rules\CommonRules\BlockHeaderPowContextualRule.cs:line 33
```

The code at the line:

```
// Check proof of work.
if (header.Bits != context.NextWorkRequired)
```

Here is a zip of the data folder. This is built using the "main" Stratis network, but I have modified the node to not use checkpoints, no DNS seed and only my LAN nodes. The only modification to stratis.conf, is mine=1 and the address.

[StratisMain.zip](https://github.com/stratisproject/StratisBitcoinFullNode/files/2164378/StratisMain.zip)

I have attempted a few times to use this data folder when running StratisD from Visual Studio (Debugging), but then the problem does not occur. Only when I run from cmd, with "dotnet stratis.stratisd.dll".

I did a run with debug level on trace, and here is the log output from a quick startup and close. Search for "Validating new block" to find the interesting parts.

[node.zip](https://github.com/stratisproject/StratisBitcoinFullNode/files/2164421/node.zip)

**Comment by dangershony** [comment]
I am aware what the problem is and will work with @fassadlr to fix it.
Basically we need another BlockDefinition for a POS network that is mining POW blocks.

**Comment by fassadlr** [comment]
Hi @sondreb this issue has now been fixed. A PR will be sumbitted today. Thanks!
