### ISSUE TITLE
Unable to mint PoS coins throguh staking

### ISSUE THREAD

**Issue by einewton** [stratisproject/StratisBitcoinFullNode#1625]
Referring to the test case Staking_wallet_can_mint_new_coins this method does 6 things. The test runs successful, however it is invalid.

When reading through the 6 things this test case runs, first it will create a genesis block via PoW, with a PoS node will stake the pre-mined coins, during the stake process new coins **should** show up in your wallet, but this is not the case.

The newly generated coins are done through the PoW process, not the PoS process. The easiest way to see this is setting the StratisRegTest network reward to zero like this:
this.Consensus.ProofOfWorkReward = Money.Zero;

Setting this to Zero, the PoW node will not create any new coins, only the PoS staking process will.

Then fix the test on "pos_node_wallet_has_earned_coins_through_staking" like so:

Referring to ProofOfStakeSteps.cs on line 80: https://github.com/stratisproject/StratisBitcoinFullNode/blob/c82b0200b4bfd59b2efd6748c5d0810ad94f1b48/src/Stratis.Bitcoin.IntegrationTests/ProofOfStakeSteps.cs#L80

`return staked >= Money.COIN * 98000000;`

needs to be

`return staked > Money.COIN * 98000000;`

Then you can see there are no new coins minted through staking.

Could this be related to issue #1113 ?

**Comment by fassadlr** [comment]
Hi @einewton, yes the test's assert was incorrect. However, there was other work that needed to be done on block creation to ensure that the test passes correctly. A PR for this will be submitted today. Thanks for pointing this out 👍 

(This relates to #1614 as well)

**Comment by bokobza** [comment]
@fassadlr please close this if possible.

**Comment by fassadlr** [comment]
Fixed with #1634
