### ISSUE TITLE
Implications of receiving a bogus block locator

### ISSUE THREAD

**Issue by noescape00** [stratisproject/StratisBitcoinFullNode#1657]
When we receive GetHeadersPayload we try to find fork using block locators. Explore the implications of sending 32mb of rubbish as a block locator.

**Comment by zeptin** [comment]
Is this not resolved by #2094? @dangershony 

And then #2124 also adds some additional protection I think - they mention the message size earlier on in the thread, referring to altcoins that are (were) still on 32mb.
