### ISSUE TITLE
DNS entries not picking the DNS server

### ISSUE THREAD

**Issue by dangershony** [stratisproject/StratisBitcoinFullNode#166]
When a test net node starts first time (no address.dat file) the node doesnt connect to the dns seed node
This might be related to the AddressBehaviour/AddressManager in NStratis

**Comment by dangershony** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[Connection] DNS Seed Discovery Bug](https://trello.com/c/z4Oszo0z/10-connection-dns-seed-discovery-bug)

**Comment by Aprogiena** [comment]
unable to reproduce, seems to me like the node does resolve the DNS seed address and attempts to connect to it and that operation succeeds, so not sure what the problem is about

**Comment by dangershony** [comment]
Great thanks.
