### ISSUE TITLE
Add support for separate passphrase and encryption password for account creation (and decryption)

### ISSUE THREAD

**Issue by sondreb** [stratisproject/StratisBitcoinFullNode#1677]
**Issue**
the api/wallet/create API method that takes WalletCreationRequest type, does currently not support separate passphrase and password for disk encryption.

The API Create method calls WalletManager.CreateWallet, which does support separation of passphrase and password. When passphrase is not supplied (which is it not in the API), the wallet manager will use the password for both mnemonic seed and disk encryption.

It would be nice to be able to have an advanced option to supply two different secrets to the wallet creation and decrypt methods.

**Why support this?**
Separating the two values, would allow API consumers to have wallets without mnemonic seeds (e.g. "" according to the standard). It is currently required to supply this value.

If the two values are separate, it would be possible to have a HD seed that consists of only the 12-word mnemonic, but still have a password to unlock the wallet. This would make disk storage secure with the password, but the HD seed wouldn't require a password.

This could be useful for scenarios with paper wallets, without having password.

Additionally it would be possible to have a much less secure wallet decrypt password, and a much better mnemonic seed extension. If someone keeps their computer safe, they could have a much simpler password for every day usage, but if they want to restore their accounts on a different device, they could then supply a more secure password.

It could even be possible to store the wallet password in secure storage on the device (with an auto-generated password, instead of user-provided), for example DPAPI on Windows and allow users to have a "remember me" capability.

**Comment by bokobza** [comment]
I agree 100% and this is something we've talked about a lot.
The first step would be to separate the passphrase from the password.

To do that you can: 
1. add a passphrase field where required, from wallet creation request objects (WalletCreationRequest and WalletRecoveryRequest) to the WalletController to the WalletManager 
2. if there's no passphrase, use only the mnemonic to create the private key and use the password to encrypt it
3. if there's a passphrase, use it with the mnemonic to create the private key and use the password to encrypt it

@sondreb Do you know someone that think maybe they could do it? 👀

**Comment by bokobza** [comment]
Closed with https://github.com/stratisproject/StratisBitcoinFullNode/pull/1914
