### ISSUE TITLE
Add Api support to BitcoinD

### ISSUE THREAD

**Issue by bokobza** [stratisproject/StratisBitcoinFullNode#1685]
At the moment, for some unknown reason, bitcoinD isn't using the Api feature.

**Comment by ferdeen** [comment]
Confirm Api support :

![image](https://user-images.githubusercontent.com/16000683/42954754-2f5c0a20-8b75-11e8-8df3-163d26c44c94.png)

And in Swagger :

![image](https://user-images.githubusercontent.com/16000683/42955116-614f9bd2-8b75-11e8-99e7-97812d8c99e3.png)

**Comment by ferdeen** [comment]
https://github.com/stratisproject/StratisBitcoinFullNode/pull/1691
