### ISSUE TITLE
TransactionBuildContext should only be used internally by the WalletTransactionHandler.

### ISSUE THREAD

**Issue by codingupastorm** [stratisproject/StratisBitcoinFullNode#1689]
Currently `WalletTransactionHandler` uses `TransactionBuildContext` internally, but this same object is passed in to `BuildTransaction` as a kind of option. What ends up happening is you can set values on the context and pass it into `BuildTransaction` but they will be completely overwritten by the internal functionality of the `WalletTransactionHandler`.

There should really be a separate options object to pass into `BuildTransaction` that has fields like `ChangeAddress` which you can set. 

Would be beneficial for SC and the FN! 

@majikandy @dangershony can you guys add this to the board and give appropriate labels? <3

**Comment by rowandh** [comment]
@codingupastorm while you're looking at this, can you take a look at the TransactionBuilder property and see if it makes sense to remove the property and instead add a method `Build(TransactionBuilder builder)` on TransactionBuildContext?

If it does we can add another issue, feel free to assign to me.

**Comment by codingupastorm** [comment]
Hey @bokobza the PR is still open. If you're happy with the changes want to merge it? I made a last little refactor and dropped a comment on the PR too, it should help you out a bit!

Thanks
