### ISSUE TITLE
Implement API call to run smart contract methods locally in SmartContractsController

### ISSUE THREAD

**Issue by codingupastorm** [stratisproject/StratisBitcoinFullNode#1695]
Developers may want to return the result of a particular method locally without running the code on-chain. The primary use case will be in the retrieval of some static information. E.g. maybe there is a `GetAverageHoldings` method in an ICO contract that returns `totalSupply / investors.Count`.

They should be able to do this via the API.

We need a public API call, built into SmartContractsController that takes in all the required parameters  (contract address, method name, method parameters), executes a method, and returns a result. Ideally it will also return the amount of gas used. 

This functionality already exists roughly in the Executor.cs file, so it should be a matter of using that and returning the result.

Current Bounty: 20 STRAT

**Comment by mwherman2000** [comment]
A nice extension (no bounty from me) would be to enable a symmetric programming model where an SC could also be deployed off-chain to support the wrapping of an identical implementation of a set of business rules around off-chain data. The existing Visual Studio SSC template test harness provides most of the source code you need to implement this capability.

**Comment by codingupastorm** [comment]
When resolving a method, if given no params this should check all properties first.
