### ISSUE TITLE
SmartContractGasInjector fails with recursive methods.

### ISSUE THREAD

**Issue by codingupastorm** [stratisproject/StratisBitcoinFullNode#1697]
The SmartContractGasInjector throws `System.InvalidOperationException: 'Operation is not valid due to the current state of the object.'` when injecting gas into a recursive method.

Simple, albeit contrived example:

```
    public void ThrowException()
    {
        ThrowException();
    }
```

We should have a test for a recursive example, like above, in GasInjectorTests.cs, and have a fix so this is resolved.

Current Bounty: 10 STRAT

**Comment by nathanielcook** [comment]
Yes, on both. I will DM you on Twitter if that's ok.

**Comment by codingupastorm** [comment]
Sounds good!
