### ISSUE TITLE
documentation little "problem"

### ISSUE THREAD

**Issue by clintm90** [stratisproject/StratisBitcoinFullNode#1729]
hello boys

just a very little problem at https://github.com/stratisproject/StratisBitcoinFullNode/blob/master/Documentation/getting-started.md

when we git clone the program it's not writed than we must change dir for src/

dirty english ><

**Comment by dangershony** [comment]
https://github.com/stratisproject/StratisBitcoinFullNode/pull/2044

**Comment by maciejzaleski** [comment]
Can this be closed now?
