### ISSUE TITLE
Make the default data directory ("StratisNode") configureable

### ISSUE THREAD

**Issue by sondreb** [stratisproject/StratisBitcoinFullNode#1738]
**Problem**

When no DataDir is specified in the arguments, a default of "StratisNode" is assumed. It is fairly hard to supply a proper "-datadir" as argument, as this will simply create a folder relative to the launching binaries, and not stored in AppData (Windows).

The "magic" happens in "CreateDefaultDataDirectories", which is private. And it handles various OS platforms and finds the proper paths to create folders.

NodeSettings constructor could take an additional parameter to set this folder, which is different from the args and perhaps it should be disallowed to supply it from arguments, and only in code as a new argument?

**Why is this needed?**

If anyone want to run a full node that is not "Stratis.StratisD", that supports multiple networks, it will actually use the same folder as Stratis. This will give conflicts if both are running at the same time (shouldn't happen anyway), but it also means that the third party daemon might corrupt/overwrite the StratisNode files.

**What would it look like**

Instead of "Stratis.StratisD" and "MyCustomDaemon" both writing and reading files from:

C:\Users\user1\AppData\Roaming\StratisNode\bitcoin
C:\Users\user1\AppData\Roaming\StratisNode\stratis

The "MyCustomDaemon" will have it's own exclusive database:

C:\Users\user1\AppData\Roaming\MyDaemon\bitcoin
C:\Users\user1\AppData\Roaming\MyDaemon\stratis

As additional information, I am working on a SimpleWalletFeature, which will host a Web Socket endpoint used for mobile wallets. It won't have API or RPC enabled, so there won't be any port conflicts, but I need to rely on the same block storage and don't to conflict with Stratis.StratisD.

**Comment by bokobza** [comment]
@sondreb if you set a full path then there is no problem:
`dotnet run -datadir=mydatadir` will save the data in "_binariespath_\mydatadir\stratis\StratisTest"

`dotnet run -datadir=C:\mydatadir` will save the data in "C:\mydatadir\stratis\StratisTest"

Only when -datadir is not supplied do we have "AppData\StratisNode\stratis\etc".

Your idea is that setting `-datadir=mydatadir` should set "AppData\mydatadir\stratis\etc". I think that'd be a good thing but I'm not sure about having an extra parameter. We can just check if it's a full path or not and create folders accordingly.
