### ISSUE TITLE
BlockMaxSize and BlockMaxWeight are stored as long, uint and int. Casts. Everywhere.

### ISSUE THREAD

**Issue by codingupastorm** [stratisproject/StratisBitcoinFullNode#1740]
We should decide on data type and use it everywhere. 

I believe long makes the most sense for these values, as we won't have issues with large numbers in the future (sure, who wants 2GB blocks now, buttttt who knows?), and there are a lot of places that calculations happen with these numbers, so long will be easier to use than ulong.

I have noticed that the 'configuration' seems to only deseralize ints? So this may need to be fixed too.

**Comment by fassadlr** [comment]
Closing and re-raising in VSTS.
