### ISSUE TITLE
Make MinimumStakingCoinValue configurable

### ISSUE THREAD

**Issue by monsieurleberre** [stratisproject/StratisBitcoinFullNode#1743]
In order to solve https://github.com/stratisproject/StratisBitcoinFullNode/issues/1180, a constant
`public const long MinimumStakingCoinValue = 10 * Money.CENT;` has been introduced.
It would be nicer to have this configurable rather than a constant

This line can currently be seen in PosMinting.cs

Acceptance; this is solved when 
- nodesetting or commandLine can be used to change the default (and currently hardcoded) value of  10 * Money.CENT

**Comment by bokobza** [comment]
Closed with https://github.com/stratisproject/StratisBitcoinFullNode/issues/1743
