### ISSUE TITLE
Use registered cointype 1 for Stratis testnet  (BIP44)

### ISSUE THREAD

**Issue by majikandy** [stratisproject/StratisBitcoinFullNode#1745]
Currently we use registered cointype 105 for Stratis Testnet but the BIP44 specification says we should be using 1.

https://github.com/satoshilabs/slips/blob/master/slip-0044.md#registered-coin-types

See CoinType.cs as this does contain that definition, but it is not used in the code.

Special attention should be taken with regard to recovering wallets when this is changed to use 1 as any funds at addresses derived with 105 won't be visible in the wallet.  Perhaps recover (as an interim thing) could generate addresses for 1 and 105.  

Another alternative is resetting testnet.

@dangershony @bokobza for discussion on how to solve.

**Comment by majikandy** [comment]
On a side note - TSTRAT is now on iancoleman's converter site under the cointype 105.  So that will need a PR too if we change to 1.

**Comment by bokobza** [comment]
I'm of the view that we shouldn't even bother and just leave it as 105.
@dangershony thoughts?

**Comment by fassadlr** [comment]
Closing as we are going to leave Stratis TestNet cointype as 105.
