### ISSUE TITLE
Add ActionFilters to web api calls to show or hide calls by network.

### ISSUE THREAD

**Issue by ferdeen** [stratisproject/StratisBitcoinFullNode#1747]
In relation to  #1691. 

We were trying to stop the Staking type web api calls to be executed when running on the Bitcoin network.

Look into whether it's possible to do this via Actions filters.

So far, trying out the `ActionFilterAttribute`.  

Problem we are facing is trying to pass `this.fullNode.Network...` as a parameter to the attribute.   We know that primitive types can only be used with attributes, however we need a way to pass the current network into the attribute.

![image](https://user-images.githubusercontent.com/16000683/43204074-e92ad00c-9017-11e8-9409-40539a438181.png)

While working on #1691 we realised that all API controllers are discoverable in Swagger.   

So starting StratisD or BitcoinD you will always see all the API controllers (Staking and Mining) if at least one API controller is included within a feature setup.  We will need to tackle this at a later date and focus on sprint tasks.

@TjadenFroyda 

> MvcBuilderExtensions.cs from Features.Api is used to automatically find all of the api endpoints.
> 
> Could the network specific mining/staking endpoints be filtered there?

**Comment by TjadenFroyda** [comment]
Replying on this issue vs the closed PR. Happy to give it a try.

Thinking out loud - this might work and will submit PR if successful:
I think I'll be able to get the network inside AddControllers with:

var network = services.GetService<Network>();

And then add filtering logic from there on line 23 with network.Consensus.IsProofOfStake (as opposed to hardcoding network names) to remove the respective controllers.

**Comment by TjadenFroyda** [comment]
The above didn't work, but found something that did (see below). Wrote some integration tests to prove that calling staking methods from a pow node (and vice versa) fails appropriately. Will submit PR when done, waiting for ITs to finish running. 

Proof of Stake Consensus: Mining methods removed. (staking still present)
![image](https://user-images.githubusercontent.com/38709281/43561136-2ead4cc2-95db-11e8-8c9c-29aed9e0bfee.png)


Proof of Work Consensus: Staking methods removed (mining still present)
![image](https://user-images.githubusercontent.com/38709281/43561079-fc09888a-95da-11e8-88df-416a3692c099.png)

**Comment by bokobza** [comment]
Solution implemented in https://github.com/stratisproject/StratisBitcoinFullNode/pull/1842
