### ISSUE TITLE
[SC] Reuse smart contract assemblies or unload to avoid memory leak.

### ISSUE THREAD

**Issue by codingupastorm** [stratisproject/StratisBitcoinFullNode#1755]
Currently we load assemblies into the node application every time we are executing a smart contract. However, these assemblies aren't tracked, and we discard the reference to them after getting the type that we need. 

Instead, assemblies should be stored in some kind of in-memory dictionary that we can access, and decide whether we can access this stored assembly or need to create an assembly from scratch. 

This is particularly interesting given the gas injection - we will have to make a decision about how best to handle this. Currently the gas injection code is only added to any methods which we know could be called. However if we're loading the assembly into memory semi-permanently then we may need to inject gas into every method in the assembly.

**Comment by codingupastorm** [comment]
@rowandh lets make this post-launch too?

**Comment by codingupastorm** [comment]
This issue will be used to track the potential memory leak that occurs when loading many assemblies with Assembly.Load.

Solution should be to wait for .NET Core 3.0.

**Comment by fassadlr** [comment]
@codingupastorm is this still applicable? If not, close, otherwise re-open in VSTS.

**Comment by codingupastorm** [comment]
Replaced with https://stratisplatformuk.visualstudio.com/StratisBitcoinFullNode/_workitems/edit/4195
