### ISSUE TITLE
Missing RPC methods

### ISSUE THREAD

**Issue by noescape00** [stratisproject/StratisBitcoinFullNode#1761]
Currently we implement 16 RPC methods

BTC core supports 58: https://en.bitcoin.it/wiki/Original_Bitcoin_client/API_calls_list

I think we should implement the rest of them (except for those that deal with non-HD wallet or with features we don't have).

**Comment by dangershony** [comment]
We should implement RPC methods as and when we need them else it might be useless work.
If we dont need them for our core code we can delegate to the foundation

**Comment by noescape00** [comment]
>We should implement RPC methods as and when we need them else it might be useless work.

We don't really need them because we use API. 

However around 4 people contacted me in the last 2 months who were tying to integrate FN to their project and they had problems with missing RPC methods. 2 of them chose QT wallet over FN just because of that reason. 

So I'd say RPC methods are really needed in case your goal is to make it easy for non-stratis developers to use FN.

**Comment by dangershony** [comment]
Yes so please create a list of the RPC methods they require and we can ask the foundation to create bounties.

**Comment by noescape00** [comment]
Basically all the commands that are dealing with wallets- 
get total amount of money that was received by address
get current address money amount (with argument of how many confirmations required). 

Those are 2 that pop up in my head right away.

**Comment by sondreb** [comment]
These 6 methods are used by at least one exchange, not sure what others are relying on. The two first, is supported today, the 4 others are not (at least not returned in the listmethods results:

- **validateaddress**
- **getblockcount**
- getnewaddress
- sendtoaddress
- getwalletinfo
- gettransaction

**Comment by sondreb** [comment]
I see that getnewaddress is supposed to have been implemented, but not returned as part of the listmethods. So this is a separate issue really, that perhaps listmethods doesn't return everything.

**Comment by sondreb** [comment]
It is either a bug, or intentional change. I think it is a bug, with with the latest modifications to the Stratis daemon, it uses the cold staking wallet, and not the normal wallet. When it does this, the RPC controller in the wallet is not loaded and initialized in the RPC host. So all the RPC methods in the wallet is missing, unless the daemon instead launches with regular wallet, and not staking wallet.

**Comment by zeptin** [comment]
Ah, nicely spotted sondreb, that makes perfect sense. We will need to resolve that.

**Comment by maciejzaleski** [comment]
This issue relates to #2758

**Comment by dangershony** [comment]
Closing as duplicate
