### ISSUE TITLE
[SC] Smart contracts should use the same versions of .NET as the Full Node.

### ISSUE THREAD

**Issue by codingupastorm** [stratisproject/StratisBitcoinFullNode#1766]
Currently all non-smartcontracts features are .NET Standard 2.0 whilst smart contracts ones are .NET Core 2.1. We should move all the features to .NET Standard 2.0 and ensure that the daemons are congruent with what the full node is doing too.

We will likely want to go live for SC with .NET Standard 2.0 on all libraries and .NET Core 2.1 as the node / daemon as it is an LTS release.

**Comment by rowandh** [comment]
See #1885 for why this is difficult at the moment.

**Comment by fassadlr** [comment]
@codingupastorm is this still applicable? If not, close, otherwise re-open in VSTS.

**Comment by codingupastorm** [comment]
Closing, kind of covered by https://stratisplatformuk.visualstudio.com/StratisBitcoinFullNode/_workitems/edit/4195
