### ISSUE TITLE
[CoinView] steps needed for core way of syncing activation

### ISSUE THREAD

**Issue by noescape00** [stratisproject/StratisBitcoinFullNode#1768]
Following changes are required for the activation: 

1) Ensure rewind data is not aggregated (1 block per rewind data) while still saving those in batches. 
2) Remove some fields from rewind data that we can get from the block being disconnected.  
3) Change signaling from Block to ChainedHeaderBlock.
4) Update CM tests to test the new logic.

**Comment by dangershony** [comment]
This means no backwards compatibility to existing store right?
