### ISSUE TITLE
Create Proven Header Payloads

### ISSUE THREAD

**Issue by noescape00** [stratisproject/StratisBitcoinFullNode#1787]
Create ProvenHeader class which will inherit from BlockHeader.
Add following payloads:

_provhdr_ - ProvenHeadersPayload which contains list of up to 2000 proven headers.

_sendprovhdr_ - SendProvenHeadersPayload which informs the peer that we are only willing to sync using the proven headers and not the old type of headers.

_getprovhdr_ - GetProvenHeadersPayload which requests proven headers using a similar mechanism as the getheaders protocol message.

For more info see: https://github.com/stratisproject/Research/blob/master/CoreSyncingAndProvenHeaders/ProvenHeaders.md

**Comment by Aprogiena** [comment]
Please don't forget to include full comments on every field and every class

**Comment by noescape00** [comment]
Depends on https://github.com/stratisproject/StratisBitcoinFullNode/issues/2141

**Comment by noescape00** [comment]
Fixed
