### ISSUE TITLE
Implement handling of new  protocol version. 

### ISSUE THREAD

**Issue by noescape00** [stratisproject/StratisBitcoinFullNode#1788]
At this point processed them as normal headers + add tests.

**Comment by dangershony** [comment]
Create a PreferHeaders flag in block store

Implement SendProvenHeaders (plus height)

Consider adding a flag to enable/disable PH (possibly in the Network class)

Create a new `ProtocolVersion` number for PH (consider creating different types of ProtocolVersion enum or take a number that does not collide with BTC).

**Comment by noescape00** [comment]
Depend on: https://github.com/stratisproject/StratisBitcoinFullNode/issues/2144

**Comment by noescape00** [comment]
No longer relevant. We wen't with keeping old protocol version.
