### ISSUE TITLE
Create validator class for proven headers and make Consensus Manager use it. + Tests.

### ISSUE THREAD

**Issue by noescape00** [stratisproject/StratisBitcoinFullNode#1792]
1. Add new logic to the chain tree: proven headers should be validated for up to coinstakeAge headers from the fork point. 
2. If we advance consensus on the same chain we should check if there are any headers withing the coinstakeAge from the consensus tip and if there are- validate them.

**Comment by dangershony** [comment]
We should try to avoid making changes that are specific to PH in the low level consensus code.

**Comment by dangershony** [comment]
Possibly create a PosChainedHeader that will store the PH class.
This can then be sent in to CM (and CHT)

**Comment by noescape00** [comment]
Depends on https://github.com/stratisproject/StratisBitcoinFullNode/issues/1790

**Comment by dangershony** [comment]
A comment I have on this is that we may not need to create new Validator for CM but add new rules that manage the validation of PH

**Comment by noescape00** [comment]
Don't create validator, just update set of rules in the rules engine for the headers validation on PoS networks
