### ISSUE TITLE
Delete concurrent chain.

### ISSUE THREAD

**Issue by noescape00** [stratisproject/StratisBitcoinFullNode#1797]

**Comment by maciejzaleski** [comment]
Comment from @MithrilMan 

> A todo list of what has to be done to remove ConcurrentChain from our lives
> 
> Partial list:
> 
> Methods to move to CM or CHT
> 
> from ChainBase:
> 
> * `public virtual ChainedHeader Genesis { get { return GetBlock(0); } }`
>   needs a port to expose similar feature (tests uses this, so must be updated)
> * `ToEnumerable(bool fromTip)` used by test, can be removed/moved to test helper
>   uses:
>   
>   * `protected abstract IEnumerable<ChainedHeader> EnumerateFromStart();`
>     used only by this method, so can be removed too
>     (this method uses the dictionary of blocks by height, and start from height 0 till the tip)
> * `public abstract ChainedHeader SetTip(ChainedHeader chainedHeader);`
>   use CM one instead of this, fix tests that uses this
> * `public ChainedHeader SetTip(ChainBase otherChain)`
>   used by test, can be removed/moved to test helper
> * `public bool SameTip(ChainBase chain)`
>   used by test, can be removed/moved to test helper
> * `public virtual ChainedHeader Genesis { get { return GetBlock(0); } }`
>   used by some internal classes and lot of tests. Need a refactory to access genesys from CM/CHT or another place if already available
> * `public IEnumerable<ChainedHeader> EnumerateToTip(ChainedHeader block)`
>   uses calls:
>   
>   * `public IEnumerable<ChainedHeader> EnumerateToTip(uint256 blockHash)`
>     uses:
>     
>     * `public abstract ChainedHeader GetBlock(uint256 id);`
>       implemented in CC and uses internal dictionaries (I think we need to implement those dictionary too, maybe in an helper class BlockIndexer used by CM
>       similar to the override that uses `int height`
>     * `public IEnumerable<ChainedHeader> EnumerateAfter(uint256 blockHash)`
>       uses:
>       
>       * `GetBlock(hash)` (see above)
>       * `public virtual IEnumerable<ChainedHeader> EnumerateAfter(ChainedHeader block)`
>         uses:
>         
>         * `GetBlock(height)` (see above)
> * `public Target GetWorkRequired(Network network, int height)`
>   used by test, can be removed/moved to test helper

**Comment by fassadlr** [comment]
This has been implemented,
