### ISSUE TITLE
Ensure rewind data is not aggregated

### ISSUE THREAD

**Issue by dangershony** [stratisproject/StratisBitcoinFullNode#1810]
Ensure rewind data is not aggregated (1 block per rewind data) while still saving those in batches

Discussion here
https://github.com/stratisproject/StratisBitcoinFullNode/issues/1768

**Comment by dangershony** [comment]
The issue I have here is that in order to reorg we will need to have blocks available.
Can we guarantee that? what if we dont have blocks available we need to delete the entire store (or alternatively download form a peer).

**Comment by noescape00** [comment]
More info on the issue: 

How it currently works: 
When new block is connected changes that his block has introduced are commited to the CachedCoinView. After some time those changes are flushed- a new rewind data instance is created. This instance might combine changes for many blocks. In IBD one rewind data might have 2000 blocks worth of changes.
When we try to rewind cosnensus we can't go 1 block back, only 1 rewind data back so it's possible that we will rewind 2000 blocks which is not intended and creates several problems for consensus manager. 


We need to implement a mechanism similar to pending storage in BSQ- 
create rewind data per block and put it to the pending storage (in the memory),
after pending storage reaches threshold we flush it to the database. We also should flush every ~30 seconds no matter the pending storage batch size and we should when we've reached the tip (synced with the best chain we are aware of).

Changes will mostly touch CachedCoinView. 
Also it's important to make sure we can rewind using the rewind data from the pending storage and not only from DBreeze coinview.

**Comment by noescape00** [comment]
fixed
