### ISSUE TITLE
Remove some fields from rewind data

### ISSUE THREAD

**Issue by dangershony** [stratisproject/StratisBitcoinFullNode#1812]
Remove some fields from rewind data that we can get from the block being disconnected
Rewind method in coinview should accept blocks being disconnected. 

Change rewinding process so it takes the block and gets info that will be removed from RewindData from the block being disconnect. 

Implications:
What if coinview is ahead of block store and we can't rewind properly because we don't have data about UTXOs to disconnect

**Comment by noescape00** [comment]
Removed from activation per discussion with @dangershony and @Aprogiena

**Comment by dangershony** [comment]
Coinview refactor is in the plan so I would say we can close this issue
