### ISSUE TITLE
Mempool initialization speed

### ISSUE THREAD

**Issue by noescape00** [stratisproject/StratisBitcoinFullNode#1818]
Node takes forever to initialize with non-empty mempool (max size is 300mb. With just 2 mb it takes 10-15 minutes to launch)

**Comment by mikedennis** [comment]
@noescape00 were you on stratis or bitcoin network? Just tried with bitcoin testnet and it seemed reasonably fast (a few seconds) with this size of mempool:  

MempoolSize: 1216 DynamicSize: 1187 kb OrphanSize: 100

**Comment by noescape00** [comment]
I got those problems running on stratis testnet. I had bunch of big txes (1 input, 500 outputs), some of them were ancestor txes. 

Txs type might affect the speed of AcceptTxToMempool execution big time. 

Basically what we are looking for is the setup where we have the heaviest type of tx that is withing the standard tx policy. Fill 5-10% of mempool (15-30mb) and check loading speed. 
I think target reasonable value for loading should be up to 5 minutes.

**Comment by mikedennis** [comment]
Ok sounds good. I'll see if I can write a quick test to reproduce then see if I can find where the bottleneck is.

**Comment by mikedennis** [comment]
### Initial test - Running on Stratis Regtest POW
2000tx with 500 outputs each
=======Mempool=======
MempoolSize: 2000 DynamicSize: 68637 kb OrphanSize: 0
- Took about ~3 minutes to load and get added to mempool
- These are simple tx's, no ancestors outputs to all new wallets

So next will try some more complex tx's as it looks like it's not IO but more likely something to do with the tx makeup.

**Comment by noescape00** [comment]
Looks like they are loading quite fast for you. 
I wonder if something changed in the mempool that allowed them to be processed faster or it's just different tx type. 

If you won't encounter issues with the ancestor txes then it's probably not an issue anymore and was optimized at some point.

**Comment by mikedennis** [comment]
Tried ancestor transactions as well and still only was a couple of minutes to load with a large tx set. I have an SSD drive so maybe that's masking it a bit, or maybe I just haven't come up with the tx set that is a problem. 

I think what I will do next is add some trace logging around mempool as there is hardly any present right now so makes it tough to troubleshoot problems like these if someone runs into something.

**Comment by noescape00** [comment]
Thanks for detailed feedback and good investigation. 

Looks like it's not an issue anymore and was fixed at some point since the issue was first discovered 4-6 months ago. 

Feel free to close the issue.

**Comment by bokobza** [comment]
Closed with https://github.com/stratisproject/StratisBitcoinFullNode/pull/1915
