### ISSUE TITLE
Wallet is slow with large amount of UTXOs

### ISSUE THREAD

**Issue by noescape00** [stratisproject/StratisBitcoinFullNode#1819]
Wallet can't create and sign more than 3-5 txes per minute given that it has >2000 UTXOs (1-2 week)

**Comment by bokobza** [comment]
Operations that take time:
- deriving private keys to sign the unspent items (in WalletTransactionHandler.AddSecrets)
- sign all the inputs (in TransactionBuilder.Sign)
- verify the transaction (in StandardTransactionPolicy.Check => Transaction.VerifyScript)

Each of the above item takes around 3-4ms, multiplied by the number of outputs we're using.

When we have a trx with 600 items, it takes around 600 * (3 + 3 + 4) = 6s to process, which is very acceptable for large transactions.

One way to speed things up is to remove the verification of the transaction as it should be in a good state after being just built.

**Comment by bokobza** [comment]
So I tried to remove the verification after the transaction build, and I'm of the view that it's a good thing to have as it catches bad trxes that buildTransaction wouldn't, like max trx size.
It's also not very heavy performance-wise, as only very big transactions will see an additional 2-3 seconds to their build time.
If this is a problem in the future, we can reopen.
Closing as Won't fix.
