### ISSUE TITLE
Question: Writing Tests

### ISSUE THREAD

**Issue by detroitpro** [stratisproject/StratisBitcoinFullNode#182]
I am not sure if this is better here or in slack. Please feel free to move if required.

I am looking to write some tests as a way to learn more about the codebase.
![coverage](https://user-images.githubusercontent.com/49996/27451812-683a7bc0-575e-11e7-9aba-b4730deb9339.PNG)

I think starting with tests around "configuration" would be simple enough to let me focus on tests while still learning a little...

So, before I write a line of code....here is the question and I don't want to start a war. :) There seems to be a mix of var and explicit type.
![var_vs_type](https://user-images.githubusercontent.com/49996/27451869-8fa99ee8-575e-11e7-9842-d766dedd0e01.PNG)

I see that using var is a warning in the editorconfig....but it seems to be used pretty liberally....any change we could remove the var warning from editorconfig? or maybe even swap it for require var?

![bitmoji](https://render.bitstrips.com/v2/cpanel/8263858-138244880_4-s4-v1.png?transparent=1&palette=1&width=246)

#ThisIsNotJava :pray:

**Comment by Neurosploit** [comment]
IMO we should put some effort towards having a 0 warning policy. We could suppress this warning in the csproj files or just solve them all. Same goes for using this.Prop instead Prop.
![image](https://user-images.githubusercontent.com/11396035/27477883-dd2b540e-580d-11e7-8561-25c29eb84a03.png)

The way I look at it is the following:
When the LoC does not show directly which type var would be then specifiy it explicitly.
ex. var lines = a.ToList(); -> IEnumerable<string> lines = a.ToList();
When the can be found in the LoC use var:
var lines = new List<string>();

**Comment by bokobza** [comment]
agreed. in our coding style doc, these 2 items are relevant:
4. We always use this. to easily distinguish instance and methods arguments.
10. We only use var when it's obvious what the variable type is (i.e. var stream = new FileStream(...) not var stream = OpenStandardInput()).

Here is the link to the guide:(https://github.com/stratisproject/StratisBitcoinFullNode/blob/master/Documentation/coding-style.md)

**Comment by detroitpro** [comment]
In my experience, teams that adopt a policy to not use abbreviations and acronyms often create a more maintainable code base.

It's things like "obvious" that creates a problem. Variables are for humans not computers and to that end, why would anyone name a variable something not obvious?

👍 for zero warnings.

Out of curiosity, are you users of ReSharper? Things like the possible NRE bug that I sent a PR for yesterday are big-and-visible with R#.

**Comment by Neurosploit** [comment]
Personally I don't have a resharper license. I know a lot of people like it a lot but I haven't found a reason yet myself to get a license and spend that amount on it. Most of these cases it finds could already have been found if the code was tested in the first place.

**Comment by dangershony** [comment]
I don't like to be too restrictive with styling so I wouldn't make a big deal of using var or not but I am a string believer in writing really readable code (you can use var and still make the code very readable) the compiler will anyway optimize the code.  

I use resharper it really makes life easier.

I think we should to keep the "this." but remove the warning on var.

**Comment by detroitpro** [comment]
If I understand the value proposition of the straits token, it's mostly focused on it's technical value.  Being a C#, Open Source project might I suggest that you review and emulate the most popular open source C# projects. Here are some suggestions after a short review of those projects that I use often. Obviously this is far from a list complete list of best practices and there are gray areas too.

1. Findings extracted from the following projects: 

- https://github.com/AutoMapper/AutoMapper
- https://github.com/IdentityServer/IdentityServer4
- https://github.com/cake-build/cake
- https://github.com/StackExchange/StackExchange.Redis
- https://github.com/ayende/ravendb/tree/v4.0
- https://github.com/Reactive-Extensions/Rx.NET
- https://github.com/autofac/Autofac
- https://github.com/serilog/serilog
- https://github.com/JeremySkinner/FluentValidation

2. Please try using R#, the only projects that don't use R# are those that come from MS.  IMHO, R# is to source code as seatbelts are to cars. Sure you can drive without wearing it but do you really want to?

3. If you don't want to use R#, please provide a DotSettings file with the settings that you would like. Even if the project adopts R#, it should provide a DotSettings file.

4. This and Me are universally not used.

5. There is about a 50/50 split with prefixing private properties with an underscore _privateProp 

6. David Fowl (.NET Core developer at MS) provided a sample github project template, many projects use something close to this format: https://gist.github.com/davidfowl/ed7564297c61fe9ab814

7. Consider Cake or Fake for a build system.

8. Once you have a build system, you can make it auto publish to nuget.....

9. 💯 for zero warnings

10. I am not sure if there is a C# version of https://coveralls.io but if there is the project should adopt it. If not, maybe setup a SonarQube server.

**Comment by dangershony** [comment]
This is an excellent list thanks, many of the projects in the list are well above 1k commits so there is a lot of experience and best practices we can can adopt.  
I definitely think we should aim to follow other OSS standards (and add our flavor) we initially started with the net core styling standards.

I will try to get most of the stuff on the list sorted after the release.

**Comment by dangershony** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[General] Add to contribute read-me](https://trello.com/c/5bVXDX6u/102-general-add-to-contribute-read-me)
