### ISSUE TITLE
local js attack on API

### ISSUE THREAD

**Issue by noescape00** [stratisproject/StratisBitcoinFullNode#1820]

**Comment by monsieurleberre** [comment]
this should be resolved when https://github.com/stratisproject/StratisBitcoinFullNode/issues/1263 is resolved

**Comment by monsieurleberre** [comment]
more details from a discussion with @noescape00 
```
Basically the idea is that you go to a website and there is js code that calls API methods. 
It doesn't get the response because of cross domain origin calls policy, but the method is called anyway.

Fix would be doing smth that's prevents such calls to go through. It can be done using some token for example

**Comment by ferdeen** [comment]
[Enabling CORS](https://docs.microsoft.com/en-us/aspnet/core/security/cors?view=aspnetcore-2.1)

![image](https://user-images.githubusercontent.com/16000683/44086762-7d8141d0-9fb5-11e8-9e6f-856f0c20148c.png)

**Comment by monsieurleberre** [comment]
Thanks for the input guys! I will have a look now, this is not my forte but I am very interested to learn :)

**Comment by Aprogiena** [comment]
the scenario is that you visit a malicious website which contains a JavaScript, which will connect to the API of your wallet and execute the command

**Comment by Aprogiena** [comment]
If I remember correctly, the browser will allow the JavaScript to invoke a call to arbitrary URL, but it will prevent the JavaScript to read the response from the target server. Therefore, if we make sure that all GET methods are strictly used for querying only (which means that you are unable to change any state by calling them), which I believe we already do have it like that, it should just probably be reviewed once again, then the only methods that can be problematic should be POST methods. However, if I remember correctly again, the browser will not send a POST request unless it is allowed by the policy or it has empty body. Therefore, if we change all the POST requests that can be currently called without any body, to have a body with some value that we check in the controller, for example `a=1`, then it should be impossible for the JavaScript to invoke such a request and therefore would fix the issue.

**Comment by Aprogiena** [comment]
Alternative solution would be to do CSRF tokens as mentioned above.

**Comment by Aprogiena** [comment]
But please verify what I wrote, I could have been mistaken

**Comment by monsieurleberre** [comment]
That seems to indicate that if we are not creating sessions or other mechanisms by which we keep track of the client's state, then CSRF is not needed :)
https://security.stackexchange.com/questions/166724/should-i-use-csrf-protection-on-rest-api-endpoints

**Comment by monsieurleberre** [comment]
I have had a look through our controllers and have put some questions I will come back to.
I leave them here for the moment.

### AppsController
- can get all available apps, maybe some are sensitive ?

### BlockStoreController
- ok

### ConnectionManagerController
```
[Route("api/[controller]/addnode")]
[HttpGet]
public IActionResult AddNodeAPI([FromQuery] string endpoint, string command)
```
Should be a POST ?

### ConsensusController
- ok

### DashboardController:
- ok (if nothing sensitive is coming out of the logs)

### MempoolController:
- ok, only getrawmempool

### MiningController

### NodeController
```
[HttpPost]
[Route("shutdown")]
[Route("stop")]
public IActionResult Shutdown()
```
Empty bodied post, someone could stop the node for you ?

### NotificationController:
 ```
 [HttpGet]
 [Route("sync")]
 public IActionResult SyncFrom([FromQuery] string from)
 ```
 This one triggers a sync from block. Maybe if you call it too much you can create DOS. Also think it should at least be a POST ?

### RPCController
```
[Route("callbyname")]
[HttpGet]
public IActionResult CallByName([FromQuery]string methodName)
```
this needs to be a POST at least ?

### SmartContractWalletController
```
[Route("history")]
[HttpGet]
public IActionResult GetHistory([FromQuery] WalletHistoryRequest request)
```
This one looks like it could be resource intensive

### SmartContractsController
- OK

### StakingController:
- getstakinginfo: anything sensitive ?
- stopstaking: one could stop staking discreetly on behalf of the user [POST] with empty body

### WalletController
```
[Route("remove-transactions")]
[HttpDelete]
public IActionResult RemoveTransactions([FromQuery]RemoveTransactionsModel request)
```
Check Delete with fromQuery

unusedaddress and unusedaddresses migh want to become POST, they can create an address if needed

### WatchOnlyWalletController:
```
[HttpGet]
public IActionResult GetWatchOnlyWallet()
```
Can be used for DOS ?
```
[Route("watch")]
[HttpPost]
public IActionResult Watch([FromQuery]string address)
```
Can be used for DOS ? Needs to be FromBody ?
