### ISSUE TITLE
[SC] Serialization of method parameters should be simpler.

### ISSUE THREAD

**Issue by codingupastorm** [stratisproject/StratisBitcoinFullNode#1830]
When sending parameters in to a method inside of a transaction, we should just send them in string form, rather than the current form that prefixes the items with a number etc.

When working out which method to call, use the parameters on the class via reflection to work out which types to deserialize to.

If ambiguous, should just select the first one. This is a risk we will warn developers of at the compiler level.

**Comment by rowandh** [comment]
Investigate use of `ContractPrimitiveSerializer` to perform param serialization as bytes rather than a string.
