### ISSUE TITLE
[SC] Implement Fallback functions 

### ISSUE THREAD

**Issue by codingupastorm** [stratisproject/StratisBitcoinFullNode#1831]
If a smart contract is called without a method being specified, its fallback should be invoked.

The fallback should be declared via an attribute on a method. 

I believe we have more info available on our internal design rationale.

**Comment by rowandh** [comment]
As per discussion, the fallback function will be defined on `Stratis.SmartContracts.SmartContract` and have this signature: `void Fallback() `. This prevents multiple fallbacks being defined, and prevents the fallback accepting args - both problems with an attribute-based approach.

Calls made to a fallback that has not been implemented will not cause the empty fallback method to be invoked.
