### ISSUE TITLE
[SC] Insert stub contract selfdestruct method

### ISSUE THREAD

**Issue by codingupastorm** [stratisproject/StratisBitcoinFullNode#1832]
In version 1 we have decided we won't be able to kill contracts. This is a difficult decision but we are able to justify it via our internal design rationale. 

However, should we decide to change this functionality in the future, we will want a stub 'Kill()' method, so that we can easily update the rules on the nodes behind the scenes without needing to update the API of our Stratis.SmartContracts dll/nuget.

**Comment by rowandh** [comment]
Closing this for now. We have decided not to expose unusable functionality in the Stratis.SmartContracts public API.
