### ISSUE TITLE
Addnode/connect should override a peer ban?

### ISSUE THREAD

**Issue by majikandy** [stratisproject/StratisBitcoinFullNode#1848]
Perhaps in PeerBehavior.cs  (which incidentally could do with a rename to PeerBehaviour)....

we could check if not whitelisted as well... `&& !whitelisted`

```
        protected override void AttachCore()
        {
            this.logger.LogTrace("()");

            INetworkPeer peer = this.AttachedPeer;
            if (peer.State == NetworkPeerState.Connected)
            {
                bool whitelisted = peer.Behavior<IConnectionManagerBehavior>().Whitelisted;

                if (this.peerBanning.IsBanned(peer.RemoteSocketEndpoint) && !whitelisted)
                {
                    this.logger.LogDebug("Peer '{0}' was previously banned.", peer.RemoteSocketEndpoint);
                    peer.Disconnect("A banned node tried to connect.");
                    this.logger.LogTrace("(-)[PEER_BANNED]");
                    return;
                }
            }
```

**Comment by bokobza** [comment]
I can see that in PeerBanning.BanAndDisconnectPeer(), we're already not banning whitelisted items.
https://github.com/stratisproject/StratisBitcoinFullNode/blob/17b5e3d33799ed5079c019ff382d2191f58bc795/src/Stratis.Bitcoin/Connection/PeerBanning.cs#L72-L81

but in PeerBanningBehavior (not PeerBehavior as the issue states), we're not checking for whitelisting:

https://github.com/stratisproject/StratisBitcoinFullNode/blob/17b5e3d33799ed5079c019ff382d2191f58bc795/src/Stratis.Bitcoin/Connection/PeerBanningBehavior.cs#L58-L68
