### ISSUE TITLE
[SC] Foreach loops fail determinism due to enumerator and try finally under the hood.

### ISSUE THREAD

**Issue by codingupastorm** [stratisproject/StratisBitcoinFullNode#1849]
Hey @rowandh @fassadlr remember this conversation?

I'm wondering if we can explicitly allow foreachs through or if that could be too dangerous? In the case of a foreach the only thing inside of the finally will be the .Dispose() of the enumerator, so it would be okay, unless there was any way to get around this. Do we need to investigate?

If we decide to disallow them entirely that's fine as well, but the error given to the user needs to be clearer as well.

Also if we disallow them, we need to ensure that our primitives / arrays etc. can easily be iterated over within the constraints, in a for loop.

**Comment by rowandh** [comment]
This problem arose when attempting to use foreach on an early implementation of `ISmartContractList` which implemented `IEnumerable`. The compiler-generated iterator state machine classes failed validation. We no longer use this approach.
