### ISSUE TITLE
Discussion: How to move NStraits code to the fullnode 

### ISSUE THREAD

**Issue by dangershony** [stratisproject/StratisBitcoinFullNode#189]
Ideally we would want to remove the dependency on NStratis.  
- Either we go for a [big-bang](https://github.com/netsfx/StratisBitcoinFullNode) and refactor
- Cheery pick classes and move over only what we need.

At the moment we decided to go big-bang after the coming release

**Comment by netsfx** [comment]
I've simulated the big-ban approach here:
https://github.com/netsfx/StratisBitcoinFullNode
I just merged the latest commits from stratisproject/StratisBitcoinFullNode.
To do this
- I created 2 new empty netstandard1.6 class library projects, HashLib and Stratis.NBitcoin
- copy/pasted all the code files from NStratis to HashLib and Stratis.NBitcoin.
- set NETCORE on the new HashLib
- set NETCORE;NOSTRNORMALIZE;NOCUSTOMSSLVALIDATION; on the new Stratis.NBitcoin
- added nuget packages to Stratis.NBitcoin:
  Newtonsoft.Json, System.Diagnostics.TraceSource, System.Net.NameResolution, System.Net.Promitives, System.Net.Requests
- made some code changes, all marked with // TODO
-- replaced use of Thread with Task and async/await
-- commented out Trace.CorrelationManager
- removed the NStratis nuget package 
- referenced the new Stratis.NBitcoin
- compile/run

**Comment by dangershony** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[NStratis] make NStratis netstandard](https://trello.com/c/w4A4LnBb/45-nstratis-make-nstratis-netstandard)

**Comment by dangershony** [comment]
I will be merging NBitcoin for the last time then we make the netstandard change and finish with NStratis

**Comment by dangershony** [comment]
I now merge the latest NBitcoin which is now using project file to target all platforms.
This means I would need to change the hashlib projects to be the same.

As we are only interested in netstandard1.6 perhaps it worth stopping here and just going on with  the nststanrad1.6 migration.

Any new changes to NBitcoin will have to be manually merged form now on.
