### ISSUE TITLE
Mark integration tests that are expected to fail with Skip attribute

### ISSUE THREAD

**Issue by rowandh** [stratisproject/StratisBitcoinFullNode#1893]
There are currently some integration tests in master that are known to fail.

We should mark these with the Skip attribute to make it easier to determine whether or not all relevant integration tests have passed. Also prevents us wasting time running failing tests.

Tests that seem to be known failures that are consistently ignored:
* AddNewAccount_for_xpub_only_wallet_informs_user_to_create_new_wallet_
* CreateExtPubKeyOnlyWallet_creates_wallet_with_extra_flag
* A_cut_off_miner_advanced_ahead_of_network_causes_reorg_on_reconnect

Ideally we should fix these tests but until that is done I don't see harm in skipping them if we are allowing PRs to be merged without them passing anyway.

**Comment by zeptin** [comment]
Note that `AddNewAccount_for_xpub_only_wallet_informs_user_to_create_new_wallet_` and `CreateExtPubKeyOnlyWallet_creates_wallet_with_extra_flag` are failing because of a trivial bug in ApiSteps.cs.

**Comment by rowandh** [comment]
@zeptin OK, did not know that. What is the bug?

**Comment by zeptin** [comment]
A missing value when instantiating a `WalletExtPubRecoveryRequest`:
https://github.com/stratisproject/StratisBitcoinFullNode/pull/1760/files/d2fe96fbf5350f64cbcfc553bfeeca633ec6986c#diff-7486e7b637d07113c405e5dbc9a66418R264

**Comment by rowandh** [comment]
Nice work, we probably don't need to worry about skipping those for much longer then.

**Comment by fassadlr** [comment]
Closing as we now have `Retry`'s and all integration tests should be passing locally.
