### ISSUE TITLE
API: Extend the blockstore/block to retrieve full transaction details

### ISSUE THREAD

**Issue by sondreb** [stratisproject/StratisBitcoinFullNode#1912]
The current blockstore/block API method only returns transaction hash, even though the complex type is already populated with all the transaction details from the block store.

To reduce the amount of queries needed to show blocks and the transactions for local API clients, I propose that the block method includes a boolean property (query) named "Verbose" that can be set to include transaction details.

A related question, that might be relevant to this feature. This feature should maybe be turned off, if txindex=0 in the configuration (which it is by default). The node/getrawtransaction API method returns null if txindex is turned off in the configuration. Even with txindex turned off, at least some, if not all, transaction details are included in the block index (from my local debug testing). I don't know if txindex=0 results in some pruning eventually and might not always have block data available, hence I'm asking the question if this feature suggestion should throw error if txindex is not enabled.

Current API result:

![image](https://user-images.githubusercontent.com/309938/44042523-c39d7606-9f20-11e8-956e-fc72291b6c73.png)

API result with verbose turned on:

![image](https://user-images.githubusercontent.com/309938/44042570-e6a2ea28-9f20-11e8-8cdc-0a2e7a58fd96.png)

**Comment by bokobza** [comment]
Done in https://github.com/stratisproject/StratisBitcoinFullNode/pull/1913
