### ISSUE TITLE
[SC] Contracts shouldn't be able to be instantiated in code via their constructors.

### ISSUE THREAD

**Issue by codingupastorm** [stratisproject/StratisBitcoinFullNode#1921]
Contracts being instantiated in code via their constructors is nonsensical - contracts should only be created via the `.Create<>` method on the `SmartContract` class, which will create them in persistent storage permanently. 

We should likely prevent this in the Format Validator.

**Comment by rowandh** [comment]
Investigate whether we can blacklist all `newobj` instructions that aren't creating an instance of a struct (ie. a type that inherits from ValueType).
