### ISSUE TITLE
[Activation] fix failing tests

### ISSUE THREAD

**Issue by noescape00** [stratisproject/StratisBitcoinFullNode#1936]
fix unit tests on activation branch. 
this issue can be assigned to multiple developers

**Comment by noescape00** [comment]
@fassadlr is working on integration tests

**Comment by noescape00** [comment]
Upd: currently only around 60 unit tests are failing. 
So we are almost there.

**Comment by bokobza** [comment]
@fenix2222: PowMiningTest
@zeptin : PeerBanningTest
@bokobza: Stratis.Bitcoin.Features.Notifications.Tests ---- in PR
@majikandy : MempoolValidatorTest
@herbepau : BlockPullerTest
@thefazzer : CoinbaseHeightRuleTest
@ferdeen : TransactionLocktimeActivationRuleTest

![image 2](https://user-images.githubusercontent.com/1867877/44585693-147d5280-a7a5-11e8-8db2-1433a96f0fe4.png)

**Comment by noescape00** [comment]
Will fix following ones: 

Stalling_DoesntAffectPeersThatFailedToDeliverNotImportantBlocksAsync
Stalling_PeerStallsButQualityScoreIsTheBestBecausePeerIsTheOnlyOneAsync
ProcessHeadersAsync_PeerThatSentInvalidHeaderIsBannedAsync

**Comment by noescape00** [comment]
Fixed
