### ISSUE TITLE
X509Certificate2 without password cannot be opened on MacOs

### ISSUE THREAD

**Issue by monsieurleberre** [stratisproject/StratisBitcoinFullNode#1984]
There is an opened issue in .Net Core
https://github.com/dotnet/corefx/issues/31328

Basically creating a PFX certificate that is not secured by a password creates an issue on MacOs which cannot open then, and instead throws an error with the message "MAC verification failed during PKCS12 import (wrong password?)"

- If we don't want to support password protected certificates, we need to wait for this issue to be solved, or let mac users know that can only use p12 certificates without password, that they won't be able to import the certificate to the store and trust them, and therefore will have to tolerate the *unsafe* warnings from browsers like Chrome.
- If we are OK to use certificates with password, the solution exists and was working in the PR 1897 at this point:
https://github.com/stratisproject/StratisBitcoinFullNode/pull/1897/commits/b57028904062429c090f7cb72140e3545f0cfd50
- If we are OK to use Stores as supported by .Net Core cross platforms, the solution exists and can be found in PR 1897 at this point:
https://github.com/stratisproject/StratisBitcoinFullNode/pull/1897/commits/88183374df0bcac586ed9338c8476ba37d4735a7

-------------------

This issue will be solved when a user can talk to the API through HTTPS on a Mac using a Trusted certificate that does not give warnings in web browsers.

**Comment by bokobza** [comment]
Linked to https://github.com/stratisproject/StratisBitcoinFullNode/issues/1263 and https://github.com/stratisproject/StratisBitcoinFullNode/pull/1897.

**Comment by maciejzaleski** [comment]
Migrated to: https://dev.azure.com/Stratisplatformuk/StratisBitcoinFullNode/_workitems/edit/3049
