### ISSUE TITLE
Light wallet

### ISSUE THREAD

**Issue by noescape00** [stratisproject/StratisBitcoinFullNode#1990]
This is for discussion. 

Most of the stuff in light wallet feature should be removed. Also BlockNotification.cs and maybe more. 

The reason for that is that we won't have a light wallet as it is now. It will be a pruned node with smaller set of consensus rules. Therefore almost everything we have for the light wallet is redundant after the activation.

**Comment by noescape00** [comment]
@Aprogiena @dangershony @bokobza

**Comment by rowandh** [comment]
Breeze uses the light wallet feature - not sure if this has been considered.

**Comment by bokobza** [comment]
> Most of the stuff in light wallet feature should be removed. 

Why?

**Comment by zeptin** [comment]
A pruned node would be much easier to work with as far as Breeze is concerned. But there would be work needed to change to using it, obviously.

**Comment by noescape00** [comment]
The light wallet as it is now is vulnerable to the same attacks the FN used to be before the proven headers and core way of syncing. 

Therefore it's not safe to use the light wallet as it is now.
