### ISSUE TITLE
Need a license file

### ISSUE THREAD

**Issue by sgryphon** [stratisproject/StratisBitcoinFullNode#20]
What license is StratisBitcoinFullNode under? 

NBitcoin uses the MIT License, but that is very permissive, so Stratis could use anything.

See as it is publicly available on GitHub, there are already a bunch of forks, but it would be good to clarify what license is intended. 

Personally, these days I prefer copyleft licenses, which force derivatives to remain open. With a Microsoft background, I tend to use Ms-RL, although something like the GPL or LGPL also work.

**Comment by dangershony** [comment]
This is a very good idea, I was planning to use the same Bitcoin licence however a copyleft licence will keep our work as open source.

Can you suggest an example of Ms-RL?
