### ISSUE TITLE
[SC] Internal Creates in smart contracts don't add to internaltransferlist.

### ISSUE THREAD

**Issue by codingupastorm** [stratisproject/StratisBitcoinFullNode#2000]
The UTXOset will never be updated correctly. See `Create` method in InternalTransactionExecutor

Acceptance:
- New integration test with a create and a value sent should also check UTXOset for address balance.
- Internal creates can be made with an amount sent and a generated transaction will be created dishing out funds correctly.

**Comment by rowandh** [comment]
Add:
* Internal creates that fail should not update the internal transfer list
