### ISSUE TITLE
Peer endpoint is never set in the validation context

### ISSUE THREAD

**Issue by noescape00** [stratisproject/StratisBitcoinFullNode#2008]
Peer endpoint is never set in the validation context of the consensus rules engine but it's used for banning in case validation failed. 

We need to set it for every validation in case header/block was provided by a peer and not mined

**Comment by noescape00** [comment]
@dangershony would you like to fix it or I can do it?

**Comment by bokobza** [comment]
Closed with https://github.com/stratisproject/StratisBitcoinFullNode/pull/2052
