### ISSUE TITLE
Zeroed wallet files when saved around unplanned restarts

### ISSUE THREAD

**Issue by sondreb** [stratisproject/StratisBitcoinFullNode#2012]
I have a Windows Server that is notoriously unstable, it restarts normally at least once a day, but not always. It is likely some driver / hardware fault.

It runs Windows Server 2012 R2 and is used for Storage Spaces.

The C:\ is a normal disk (not a Storage Space), and the default AppData folder is used to store the chain database and wallet files.

It has happened twice in a few weeks time that the wallet files has become corrupt, and ended up being only zeroes.

The last time it happened, the peers.json was written 1-2 minutes before reboot, and then all 3 wallet files was modified around the time an unexpected reboot happened.

![image](https://user-images.githubusercontent.com/309938/44537359-e34a4700-a6fe-11e8-9b4c-c14b5b2a4d51.png)

Here is the Windows event log:

![image](https://user-images.githubusercontent.com/309938/44537382-f5c48080-a6fe-11e8-8c06-1dc3519844fa.png)

Here is the file opened in Visual Studio Code:

![image](https://user-images.githubusercontent.com/309938/44537474-36bc9500-a6ff-11e8-900b-0bfd4be3246c.png)

As you can see, the wallets are fairly large and this is running on a testnet, so there is a lot of transactions in the wallets. The strange thing is that all 3 wallet files ends up being zeroed like this, not just a single one. And it has happened at least two times, with all 3 files becoming corrupt.

Couple of possible suggestions for additional features to help mitigate issues like this:

- Create a backup of the wallet file upon creation, that is stored in a "backup" folder in the same AppData folder. If at any time the fullnode is unable to open a wallet, it could allow user to restore from the backup file.

- When saving the wallet files, which happens often when there is a lot of transactions going to the addresses, the node could actually attempt to JSON-parse the file before overwriting/delete the previous file.

Additional details:

Node is built from source.
Not the latest commits, a couple of weeks old or tree.
Intel Core 2 Duo, E8400 CPU
8GB RAM
64-bit, 2012 R2

And not to worry, I have backup of seed and this is testing. But it might be something going on in the code that could potentially create issues for users upon power failures, restarts, etc.. It might also be cause by my server, but I have used it for storage for many years and works fine, except for the random reboots.

**Comment by bokobza** [comment]
Thanks for raising the issue @sondreb. 
We've seen that before and I thought we took care of it by more or less doing what you suggested.
Check inside this method, that's the one we use to save files:
https://github.com/stratisproject/StratisBitcoinFullNode/blob/93491b76bc8f314d79c419ae8b5a6c68d2e1a245/src/Stratis.Bitcoin/Utilities/FileStorage.cs#L50-L74

**Comment by sondreb** [comment]
I can confirm it has happened again, got a new motherboard I'm planning on installing which should help, but still would be nice to have some sort of verification of the written file. And at a minimum a backup folder with the initially created wallet, would be nice.

**Comment by maciejzaleski** [comment]
I have not observed this behaviour in the recent code versions. I will keep the issue opened for next few weeks and will close it if there is no more updates.

**Comment by bokobza** [comment]
@sondreb is this something you have noticed recently?
