### ISSUE TITLE
[Activation] Fix BlockNotification class and BlockNotificationTest

### ISSUE THREAD

**Issue by bokobza** [stratisproject/StratisBitcoinFullNode#2020]
This was broken during the Activation work.
It needs to be fixed.

**Comment by noescape00** [comment]
issue resolved

**Comment by bokobza** [comment]
The light wallet is currently broken because these classes have been commented out during the activation work.
This issue can be resolved when either these classes are adapted to the new way of doing things or the light node will take the shape of a pruned node instead.

**Comment by maciejzaleski** [comment]
Migrated to: https://dev.azure.com/Stratisplatformuk/StratisBitcoinFullNode/_workitems/edit/3055
