### ISSUE TITLE
Node will disconnect peers that don't support required services

### ISSUE THREAD

**Issue by noescape00** [stratisproject/StratisBitcoinFullNode#2048]
Node will disconnect peers that don't provide network services which is a problem in case SPV client syncs from us. Such a client can't provide network services and we will disconnect it. 

Check all code that invokes NetworkPeerRequirement.Check

**Comment by dangershony** [comment]
After checking the code we confirm its probably fine we need to fix two places.
A bug in the method 'AddDiscoveredNodesRequirement' delete param `discoveredNodeRequiredService`
And use param `services` instead of `NetworkPeerServices.NODE_WITNESS`

**Comment by dangershony** [comment]
We need to set `NetworkPeerServices` in to the Network and only enrich it in Store.

**Comment by maciejzaleski** [comment]
Migrated to: https://dev.azure.com/Stratisplatformuk/StratisBitcoinFullNode/_workitems/edit/3054

**Comment by maciejzaleski** [comment]
Resolved by PR #3241
