### ISSUE TITLE
speedup uint256.GetHashCode

### ISSUE THREAD

**Issue by noescape00** [stratisproject/StratisBitcoinFullNode#2092]

**Comment by zeptin** [comment]
Did you have in mind some kind of caching here to prevent recomputing it? I doubt we can outdo the compiler in optimising the actual implementation of `GetHashCode`.

**Comment by noescape00** [comment]
Yeah. I'd have a bool `hashCodeRecalculationRequired` which will be set to true each time we modify uint256. On gethashcode I'd check against the bool and if it's true- calculate it and save to a variable. if it's false- return hashed value. 

Btw @Aprogiena suggested to create this issue so I'd also check with him.

**Comment by noescape00** [comment]
Or because when we compare uint256 instances we are not using hashcodes we can also generate a random number in constructor and it will be our permanent hash code

**Comment by noescape00** [comment]
Had a chat with Apro and the follwoing solution should be implemented: 

`this.pn7` should be returned as a hashcode instead of advanced hashcode calculation because: 

1) btc core does that
2) we use uint256.GetHashCode only for balancing buckets in the dictionary and not for comparing 2 instances of uint256

**Comment by noescape00** [comment]
@Aprogiena pn7 doesn't work for btc because first few bits are 0- because of PoW
I think it will be reasonable to use pn1
