### ISSUE TITLE
Put protocol version and client version in coinbase transaction using OP_RETURN

### ISSUE THREAD

**Issue by noescape00** [stratisproject/StratisBitcoinFullNode#2098]
PoS miner should by default add an output to coinbase tx which will contain information about node's protocol version and node's version. 

This will allow us to track percentage of miners who use C# nodes and in the future it will allow us to gather more information about the network and have better estimations on how long it takes for the majority of the network to upgrade. 

@dangershony @bokobza @Aprogiena

**Comment by Aprogiena** [comment]
Strong Nack
