### ISSUE TITLE
QbitNinja cant connect to bitcoind

### ISSUE THREAD

**Issue by alfhv** [stratisproject/StratisBitcoinFullNode#2103]
I'm trying to connect qbitninja (indexer) to stratis.bitcoind server but I can't get connection work, I receive error: "The node is not in a connected state" when calling node.VersionHandshake.
already tried with same config file with bitcoind (Bitcoin core client node) and it is ok. (Ip whitelist, rpc open, etc)
any tip where to check ??
thanks

**Comment by dangershony** [comment]
Do you still have issues?

**Comment by alfhv** [comment]
yes, still..

**Comment by dangershony** [comment]
Can you perhaps provide some logs here, or try to debug the code inside the C# node to find out why the connection issue?
It sounds a bit like a TCP problem.

**Comment by alfhv** [comment]
ok, i have prepared a solution with QBitNija, NBitcoin and NBitcoin.Listener projects.

bitcon.conf content:
whitebind=127.0.0.1:18333

running on testnet.

running with bitcoind (core) all good.

running with stratis.Bitcoind error as follow:

![screenshot 8](https://user-images.githubusercontent.com/5492961/45258485-aea1e500-b3b8-11e8-8107-599daf95c90d.jpg)

then debugging:
in class QBitNija.InitialIndexer, line 129, method:
public int Run(ChainBase chain = null) {}

here the node is in connected state, as you can see in log above, I have added the line of log "Node status: True", just before Handshaking...
Then I go inside node.VersionHandshake(); line 129 in InitialIndexer().
Now in class Node, method: public void VersionHandshake, line 1061, I go inside call SendMessageAsync(MyVersion);
(MyVersion = 70012 by the way)
and here node is disconnected, disconnected reason as follow:

![screenshot 7](https://user-images.githubusercontent.com/5492961/45258535-b1e9a080-b3b9-11e8-9f0a-65698f10e1df.jpg)

means in some moment, node get disconnected. I can run some other tests if you ask me for.

thanks.
