### ISSUE TITLE
[SC] Move thrown state transition exceptions to ITE

### ISSUE THREAD

**Issue by rowandh** [stratisproject/StratisBitcoinFullNode#2121]
AC:
* Return all expected errors as part of the StateTransitionResult
* In the ITE, observe the error and throw the appropriate exception

@codingupastorm

**Comment by codingupastorm** [comment]
AC ACK!

**Comment by rowandh** [comment]
Re. AC - there are no appropriate exceptions to be thrown/rethrown in the ITE, we just need to handle the state transition result and return transfer/create success/fail results.
