### ISSUE TITLE
Remove reorged headers from chain in case new chain is shorter

### ISSUE THREAD

**Issue by noescape00** [stratisproject/StratisBitcoinFullNode#2140]
In chain repository when we save the chain we might save chain which is different from what was there. In case new chain is shorter the suffix of the old chain should be manually removed.

**Comment by fassadlr** [comment]
@noescape00 is this still valid?

**Comment by noescape00** [comment]
Yes

**Comment by maciejzaleski** [comment]
Migrated to: https://dev.azure.com/Stratisplatformuk/StratisBitcoinFullNode/_workitems/edit/3053
