### ISSUE TITLE
Create Proven Headers Store + Tests

### ISSUE THREAD

**Issue by dangershony** [stratisproject/StratisBitcoinFullNode#2142]

**Comment by dangershony** [comment]
It was decided this will be its own store (not dependent on chain store)

**Comment by Aprogiena** [comment]
includes initialization and rewinding

**Comment by noescape00** [comment]
Depends on https://github.com/stratisproject/StratisBitcoinFullNode/issues/2141

**Comment by ferdeen** [comment]
In the 11am standup on Tue 18th Sep, @dangershony mentioned the rewind logic should go in the cached layer.  Added this note so we can discuss a way forward for rewind.
