### ISSUE TITLE
[Activation] Node does not advance after failed Coinstake signature verification

### ISSUE THREAD

**Issue by fassadlr** [stratisproject/StratisBitcoinFullNode#2153]
My node has stopped syncing after block 448135.

After a bit of debugging I found out that block 448136 (the next block) contains an UTXO which which fails signature verification here:

```
private bool VerifySignature(UnspentOutputs coin, Transaction txTo, int txToInN, ScriptVerify flagScriptVerify)
{
    this.logger.LogTrace("({0}:'{1}/{2}',{3}:{4},{5}:{6})", nameof(coin), coin.TransactionId, coin.Height, nameof(txToInN), txToInN, nameof(flagScriptVerify), flagScriptVerify);

    TxIn input = txTo.Inputs[txToInN];

    if (input.PrevOut.N >= coin.Outputs.Length)
        return false;
```

This then causes the peers that contains the blocks, to be banned and as such my node does not advance (rightly so).

I suspect that this issue relates to the incorrect shutdown problem and/or the stake store load error?

For whatever reason my node cannot process my block data at height 448136.

@dangershony @noescape00 @Aprogiena

**Comment by fassadlr** [comment]
Could this just be because my data is corrupt due to previously mentioned bugs?

**Comment by zeptin** [comment]
@fassadlr Can you add the specific txid failing verification to this thread? And what are the values that the trace log is logging on entry to the method?

**Comment by fassadlr** [comment]
Update:

From my logs it appears that when I connected to IP 13.64.76.48, which is an older Stratis X node (2.0.0.3), block validation failed and the peer got banned. However, even though I was connected to other peers with higher versions and/or block heights it failed to advance.

I'm investigating why.
