### ISSUE TITLE
[SC] Provide support for multidimensional arrays inside smart contracts

### ISSUE THREAD

**Issue by codingupastorm** [stratisproject/StratisBitcoinFullNode#2157]
Once #2156 goes in, 2d+ arrays will not be allowed inside smart contracts.

To allow them, we need to be able to check the memory constraints for them, otherwise contracts can force an OOM just by allocating a large multi-dimensional array.

Multi-dimensional arrays are a newobj call, and take in the dimension number of parameters off the stack. To check them with the observer we would need to bring them all into an array, pass that to the observer, and then somehow return all of the items onto the stack. Not easy but possible!

**Comment by fassadlr** [comment]
@codingupastorm is this still applicable? If not, close, otherwise re-open in VSTS.

**Comment by codingupastorm** [comment]
Closing until we have an active request for multidimensional arrays.
