### ISSUE TITLE
Fix race condition between block announcement & block saving to disk

### ISSUE THREAD

**Issue by zeptin** [stratisproject/StratisBitcoinFullNode#2162]
In `BlockStoreSignaled.OnNextCore`:

```
            this.blockStoreQueue.AddToPending(blockPair);

            if (this.initialBlockDownloadState.IsInitialBlockDownload())
            {
                this.logger.LogTrace("(-)[IBD]");
                return;
            }

            // Add to cache if not in IBD.
            this.blockStoreCache.AddToCache(block);

            this.logger.LogTrace("Block header '{0}' added to the announce queue.", chainedHeader);
            this.blocksToAnnounce.Enqueue(chainedHeader);
```

It is possible for the `blocksToAnnounce` queue to get processed quickly enough that a peer node requests the announced block while the block is still in the `blockStoreQueue`. In the background `BlockStoreQueue.DequeueBlocksContinuouslyAsync` is grabbing blocks off the aforesaid queue and putting them into the batch to be saved.

However, the GetBlockAsync method expects the block to either be in the batch or in the repository, nowhere else:

```
        public async Task<Block> GetBlockAsync(uint256 blockHash)
        {
            this.logger.LogTrace("({0}:'{1}')", nameof(blockHash), blockHash);

            Block block = null;

            lock (this.getBlockLock)
            {
                block = this.batch.FirstOrDefault(x => x.ChainedHeader.HashBlock == blockHash)?.Block;
            }

            if (block == null)
                block = await this.blockRepository.GetBlockAsync(blockHash).ConfigureAwait(false);
            else
                this.logger.LogTrace("Block was found in the batch.");

            this.logger.LogTrace("(-)");
            return block;
        }
```

So the block doesn't get found and the peer waits its timeout interval to request the block again. This is bad if our node mined the block that is getting announced, as it introduces substantial block propagation latency.

**Comment by noescape00** [comment]
Assigned to @zeptin per discussion on skype (he wanted to take it).
