### ISSUE TITLE
Feature: Add the assumevalid flag

### ISSUE THREAD

**Issue by dangershony** [stratisproject/StratisBitcoinFullNode#22]
https://github.com/bitcoin/bitcoin/commit/e440ac7ef3b6f3ad1cd8fc7027cece40413202d9

**Comment by Aprogiena** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[Consensus] Assume Valid blocks](https://trello.com/c/IwuQQ2C6/26-consensus-assume-valid-blocks)

**Comment by Aprogiena** [comment]
in order to reasonably test this, we would first need to solve #476 
so i would say, do that first, then do this
it would be more convenient, esp. for reviewers

**Comment by dangershony** [comment]
I think this is not related to a check point switch why would that matter?

**Comment by Aprogiena** [comment]
it is related in a way that it is easier to implement this (test it) when you have a way to disable checkpoints

it is because the functionality is very similar to what checkpoints do, so if you have checkpoints enabled then in order to test this, you would need to be synced almost fully

so just for easier deving, it is better to wait for `-checkpoints`

**Comment by mikedennis** [comment]
How do we want to handle the default values for this for the various networks? For bitcoin core seems like the defaults are in code.  Do we want to do the same? This is something that you'll want to update each release. This is bitcoin core's release process around this:

> Update `src/chainparams.cpp` defaultAssumeValid  with information from the getblockhash rpc.
>   - The selected value must not be orphaned so it may be useful to set the value two blocks back from the tip.
>   - Testnet should be set some tens of thousands back from the tip due to reorgs there.
>   - This update should be reviewed with a reindex-chainstate with assumevalid=0 to catch any defect
>      that causes rejection of blocks in the past history.

**Comment by Aprogiena** [comment]
afaik assume valid allows you to manually mark blocks that you want to assume valid. checkpoints are stronger and hence when we have checkpoints enabled by default, we can have the default list of assume valid blocks empty. so imho this makes sense only if the user is actively disabling checkpoints and adding its own list of assume valid blocks.

**Comment by dangershony** [comment]
AssumeValid is only one hash right?
Basically AssumeValid overrides checkpoints and also allows to fast download beyond the checkpoint height.

**Comment by Aprogiena** [comment]
i don't see why not to allow to be a collection of hashes

i also don't think assumevalid overrides checkpoints, it is rather the other way around - checkpoints override assumevalid (checkpoints are stronger)

**Comment by Aprogiena** [comment]
i can see bitcoin core has it as just one hash, so it is probably sufficient

**Comment by dangershony** [comment]
Yeah there is no reason to provide more then one hash, presumably they are on the same chain so all the hashes will be on the same chain then only the last is enough.

**Comment by mikedennis** [comment]
Bitcoin core logic is to skip validation for any ancestors of the block hash specified with assumevalid. Looks like they hard code the default to two blocks back from the tip prior to release. What do you guys think about doing the checkpoint check first and then the assumevalid check as I believe the check for whether a block is an assumevalid ancestor will be more expensive than the checkpoint check?

**Comment by Aprogiena** [comment]
it is not expensive. as @dangershony suggested, we need to add a flag to the block validation context that will tell us "do full validation of this block or not", now when you are creating the context, you need to specify this flag and you set it like that:

```
flag := (checkpoints are enabled AND (block.height <= last checkpoint)) OR (best chain contains assume valid block hash && (block.height <= assume valid block height)) 
```
and that's all

**Comment by mikedennis** [comment]
@Aprogiena Should assumevalid apply to these code blocks as well? Or is this only relevant to checkpoints.

https://github.com/stratisproject/StratisBitcoinFullNode/blob/master/src/Stratis.Bitcoin.Features.Consensus/ConsensusManager.cs#L47-L48

https://github.com/stratisproject/StratisBitcoinFullNode/blob/master/src/Stratis.Bitcoin.Features.Consensus/PosConsensusValidator.cs#L440-L454

**Comment by Aprogiena** [comment]
very good question, the code block in PosConsensusValidator is checkpoints only, it has to stay as it is

the code in ConsensusManager is just a helper sign to recognize IBD, theoretically it could apply to assume valid because you are in IBD if assume valid height is higher it is almost guaranteed we are in IBD, but feel free to leave it as it is because this is outside block validation context
