### ISSUE TITLE
DBreezeSerializer could validate binary data before parsing HashHeightPair

### ISSUE THREAD

**Issue by sondreb** [stratisproject/StratisBitcoinFullNode#2205]
I'm not entirely sure if this is possible, but I do think that "Deserializer" method on DBreezeSerializer type could perform a validation on the length of the bytes before actually attempting to load.

If the bytes.length == 32, it will crash with "No more byte to read" exception.
If the bytes.length == 36, it works just fine.

![image](https://user-images.githubusercontent.com/309938/45584513-108cae00-b8d5-11e8-887a-2b0ecbae1af2.png)

I experienced with the latest updates to the code, that the code was loading transactions of 32-bytes which then failed in the HashHeightPair.Load.

The only validation inside the load method, is to check if there are no bytes at all:

```
Guard.NotNull(bytes, nameof(bytes));
```

**Comment by noescape00** [comment]
Not an issue since the db schema changed and in case you have it you need to remove data folder and resync
