### ISSUE TITLE
High memory usage when syncing bitcoin testnet

### ISSUE THREAD

**Issue by mikedennis** [stratisproject/StratisBitcoinFullNode#2206]
I think we may have some big memory leaks. I've been observing my node syncing on the bitcoin testnet and my memory usage sits mostly at 92-97% (I have 6GB RAM). I also see my node slow down syncing and disk usage spike which seems to me it might be trying to page out memory.

I suspect block syncing may have some memory leaks.

I'm running the latest code (as per this date) on with stratis.bitcoind on testnet.

**Comment by mikedennis** [comment]
Did a couple of memory snapshots - here are two different heaps a few minutes apart:

![image](https://user-images.githubusercontent.com/24234359/45591233-020cb980-b90a-11e8-9437-d9021aa72f6a.png)

![image](https://user-images.githubusercontent.com/24234359/45591237-194ba700-b90a-11e8-95a2-3d9f41959523.png)

**Comment by D3m0nKingx** [comment]
### Status Update:
Runtime: 5+ hours
Blocks synced: 175411 (12%)
Peers connected: 8
RAM: 2.8 GB of 8 GB
CPU: 0 - 1.3%
Disk: 70 - 100 K/s (Occassional bursts of up to 2 MB/s, during this CPU spikes to 200%)
Bandwidth usage: 0.00 - 0.7 KB/s  (My ISP provides 60mbps)
Number of Thread Processes: 20

For the moment I can't confirm there's a memory leak. but synchronization is agonizingly slow

**Comment by MithrilMan** [comment]
Take a look at my issue, probably i found the reason
https://github.com/stratisproject/StratisBitcoinFullNode/issues/2294

**Comment by mikedennis** [comment]
Believe addressed by 2294 so closing.
