### ISSUE TITLE
[BlockStoreQueue] Block store should persist when the local node is in range of ConsensusIsConsideredToBeSyncedMargin

### ISSUE THREAD

**Issue by fassadlr** [stratisproject/StratisBitcoinFullNode#2214]
This relates to changes made in #2173.

If the node's consensus height is at 1 and no more blocks get mined, the node should be considered to be synced and we should push to store without waiting for the timer task to run out in BSQ,

**Comment by fassadlr** [comment]
This relates to changes made in #2173.

If the node's consensus height is at 1 and no more blocks get mined, the node should be considered to be synced and we should push to store without waiting for the timer task to run out in BSQ,

**Comment by dangershony** [comment]
Why can't we wait for the timer?
Now that IBlockStore will look in the pending blocks batch we don't have an urgency to persist.

**Comment by fassadlr** [comment]
@dangershony as long as we dont have to wait for 37secs for the timer to run out before we persist then we are ok ;)

**Comment by noescape00** [comment]
@fassadlr is this still an issue for integration tests?

**Comment by fassadlr** [comment]
@noescape00 Im closing this as the node sync speed's with running the node and integration tests has now been improved via other mechanisms.
