### ISSUE TITLE
[SC] Prevent nullable types on structs.

### ISSUE THREAD

**Issue by codingupastorm** [stratisproject/StratisBitcoinFullNode#2222]
This isn't a massive deal because if they actually try to set it then determinism validation will fail it anyhow, but we probably shouldn't let people think they can use them if they're on a struct.

**Comment by fassadlr** [comment]
@codingupastorm is this still applicable? If not, close, otherwise re-open in VSTS.

**Comment by codingupastorm** [comment]
Not very important anymore.
