### ISSUE TITLE
Check duplicate input Bitcoin core bug

### ISSUE THREAD

**Issue by dangershony** [stratisproject/StratisBitcoinFullNode#2226]
We need to check this does not effect our fullnode.

https://github.com/TheBlueMatt/bitcoin/blob/9b4a36effcf642f3844c6696b757266686ece11a/src/consensus/tx_verify.cpp#L184

>Upgrade to Bitcoin Core 0.16.3 to fix denial-of-service vulnerability: a bug introduced in Bitcoin Core 0.14.0 and affecting all subsequent versions through to 0.16.2 will cause Bitcoin Core to crash when attempting to validate a block containing a transaction that attempts to spend the same input twice. Such blocks would be invalid and so can only be created by miners willing to lose the allowed income from having created a block (at least 12.5 XBT or $80,000 USD)

**Comment by ferdeen** [comment]
Checked the code base and I can see the logic in `CheckPowTransactionRule`.

https://github.com/stratisproject/StratisBitcoinFullNode/blob/6ffac6c2cb0a7b1462f7bab666b7693a02a65fb7/src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/CheckPowTransactionRule.cs#L85-L95

Therefore closing this issue.
