### ISSUE TITLE
Replace list of disposable resources with explicit disposal

### ISSUE THREAD

**Issue by noescape00** [stratisproject/StratisBitcoinFullNode#2237]
Sometimes we have something like `List<IDisposable> Resources` and add stuff to it and on Dispose we dispose items in the list. 

This is a bad idea and we were removing it from the codebase but there are still some instances of this pattern. 

Reason why it should be removed: this pattern removes control over disposing sequence.

**Comment by MithrilMan** [comment]
I think that a list of disposable resources may be useful to check that all disposable resources are effectively disposed.
We have many places with naive implementation of Dispose() where we don't catch exception and we may end up with disposable object not disposed (and this may be the cause of some weird behavior node has sometime)

reference to an issue I just opened: #3035
