### ISSUE TITLE
Add trace entry\exit logs during compilation

### ISSUE THREAD

**Issue by noescape00** [stratisproject/StratisBitcoinFullNode#2249]
Currently we write all the entry and exit logs explicitly. That leads to following problems:

1. PRs being blocked because people don't follow logging guidelines.
2. Code is longer and because of that harder to read.
3. People don't care and create and merge PRs without any logging or insufficient logging.

Since we have very detailed logging stile it's possible to generate entry and exit logs automatically.
So I suggest generating entry and exit logs during compilation.

### Pros:
- no requirement for developers to write entry\exit logs
- code is shorter and easier to read because there will be no entry\exit logs 
- 100% logging coverage

### Cons:
- solution compilation takes 2 seconds longer (on slow PCs might be more)

Read also:
Fody: https://github.com/Fody/Fody
Tracer wiki: https://github.com/csnemes/tracer/wiki

### List of steps to take to achieve this:

1. Configure projects mentioned above.
2. Remove all trace logs from solution.
3. Analyze logs and mark methods that we don't wan't to see in the logs with [NoTrace] tag because those are called too often. (this one might be ongoing)
4. Update logging policy

ps
Those changes won't affect how we use logging and what targets are enabled. Logging usage experience is exactly the same as before.

**Comment by dangershony** [comment]
I like the idea very much, this also means we can choose if to include logs or not by flipping a switch.

**Comment by MithrilMan** [comment]
nice I was going to propose something similar few days ago, didn't saw there was already this PR
I found PostSharp but it has license needs, so i was googling about alternatives but didn't had time to investigate further, happy you already did it!

It could be useful even to Inject performance counters...

**Comment by noescape00** [comment]
We can also inject a lot of interesting stuff like Guards and checks that objects are always disposed.

**Comment by MithrilMan** [comment]
As long as we don't use it too much it could come pretty handy, shifting some of the development toward AoP https://en.wikipedia.org/wiki/Aspect-oriented_programming

I this article explain more or less your log implementation
https://www.codeproject.com/Articles/1223461/AOP-Method-and-property-interception-in-Csharp

**Comment by noescape00** [comment]
fixed
