### ISSUE TITLE
Implement sendtoaddress RPC method

### ISSUE THREAD

**Issue by mikedennis** [stratisproject/StratisBitcoinFullNode#2266]
Bitcoin Core Documentation:
https://bitcoin.org/en/developer-reference#sendtoaddress

**Comment by dangershony** [comment]
In our case this method will look a bit different as we have the wallet protected with a password that will need to be provided.

**Comment by mikedennis** [comment]
@zeptin @dangershony @bokobza 

So according to the attached docs this is also related to wallet encryption and passphrases. Also it looks as though with bitcoin core the default wallet is either unencrypted or is automatically decrypted on regtest because I see tests using **sendtoaddress** on regtest without calling **walletpassphrase** first. 

I will do some more research on bitcoin core and gets some clearer answers on what it does but if you guys have any suggestions on how best we should proceed with this on Stratis please feel free to add comments.

**Comment by mikedennis** [comment]
So this is my understanding, please correct if any of below are incorrect.

Bitcoin core currently creates wallets unencrypted by default. If the wallet is unencrypted the private keys are stored in unencrypted. You can encrypt a wallet by using rpc method [encryptwallet](https://bitcoin.org/en/developer-reference#encryptwallet). This is executed only one time and then the wallet is unlocked by user supplied passphrase using [walletpassphrase](https://bitcoin.org/en/developer-reference#walletpassphrase). The wallet can then be relocked by using [walletlock](https://bitcoin.org/en/developer-reference#walletlock). For a user to spend coins on an encrypted wallet using [sendtoaddress](https://bitcoin.org/en/developer-reference#sendtoaddress) they first need to call [walletpassphrase](https://bitcoin.org/en/developer-reference#walletpassphrase) to unlock. If the wallet is not encrypted they can call [sendtoaddress](https://bitcoin.org/en/developer-reference#sendtoaddress) without specifying any passphrase.

In Stratis wallet it looks like private keys are always encrypted with the wallet password (I guess the parallel of the bitcoin walletpassphrase). I don't think we currently have a way of creating an unencrypted wallet and require the caller to specify the password on API's that require access to private keys.

I am unsure what to do here. A couple of different options:
1. We could implement **walletpassphrase** and **walletlock** similar to bitcoin which basically stored a time limited "master key" into memory that is then used to decrypt the keys in subsequent **sendtoaddresss** calls.
2. We could pass in the wallet passphrase(password) into the **sendtoaddress** call but that would be a non compatible implementation of **sendtoaddress** with bitcoin core.

Also I don't think we have a way of creating an unencrypted wallet. This may also be an issue in terms of compatibility with bitcoin testing frameworks. That being said I believe eth also creates their wallets encrypted by default, so I'm not sure this is such a bad idea to always create encrypted wallets. Just makes testing a little more difficult.

Thoughts?

**Comment by zeptin** [comment]
Note that for #1 above, we already do something similar for the staking functionality, as that requires the ability to sign transactions using private keys encrypted in the wallet. So the password gets kept in memory while staking is switched on.

I think using a similar approach (i.e. implementing `walletpassphrase` and `walletlock` and keeping the proffered password in memory for usage by `sendtoaddress`) would lead to the greatest compatibility with existing RPC-aware software. There is a security risk keeping the password available like this, but it is opt-in.

`encryptwallet` could just be a null operation. I am not sure we need unencrypted wallet capability at all.

**Comment by mikedennis** [comment]
Sounds good, I agree. Will go with that unless someone comes up with something better. Bitcoin core also encrypted the password while it is held in memory, so I will do something similar.

**Comment by bokobza** [comment]
@mikedennis @zeptin @dangershony 	here my take on it:
We want maximum compatibility with the bitcoin protocol, but as far as APIs are concerned (RPC, Web apis), we're kind of doing our own stuff.
I'm personally not too keen on creating unencrypted wallets, or even creating temporary master keys.
I think passing a password to the **sendtoaddress** call is perfectly fine.

**Comment by dangershony** [comment]
>I think passing a password to the sendtoaddress call is perfectly fine.
But this is incompatible with core RPC, the whole idea of this practice is that we can test the node with NBitcoin tests and by that we can make sure the NBitcoin support for stratis works 

What I suggested is to create an interface IPasswordCache for keeping the password in memory for a limited period,
then we can create the same functionality as walletlock/walletunlock by passing the password in to memory,then send to address can perhaps have an option to pass an empty password and the method will look in the PasswordCache if its there it can continue.

This, we could provide this only in RPC and not api for example.

**Comment by bokobza** [comment]
Apologies, I didn't realize this was for compatibility with NBitcoin.

**Comment by mikedennis** [comment]
I was actually able to use the existing key cache in WalletTransactionHandler so we shouldn't need to add a whole new password cacheing mechanism but should be able to reuse what is already there. I'm just writing some tests now to verify this will all work then will create a PR so you guys can take a look.

For the unencrypted wallet, I agree. I will try to work around this on the NBitcoin side.
