### ISSUE TITLE
FullNode BTC network memory leak [bug] [sp]

### ISSUE THREAD

**Issue by MithrilMan** [stratisproject/StratisBitcoinFullNode#2294]
@dangershony reported an issue with Bitcoin network synching using fullnode that smells of memory leak

here the screenshot

![image](https://user-images.githubusercontent.com/5107375/46154108-bf859e00-c274-11e8-8156-f9cda659b9fb.png)

Dan guess it's a background task not disposing, I'll investigate the issue reporting here the findings

**Comment by mikedennis** [comment]
See also #2206

**Comment by MithrilMan** [comment]
As said on Slack, i think the problem is generated by the `ConsensusManager` method `ProcessDownloadQueueLocked` that requires too many blocks without considering their size
this check fails

https://github.com/stratisproject/StratisBitcoinFullNode/blob/b42026e2800725d4cdb8f2952de380e2dd638c99/src/Stratis.Bitcoin/Consensus/ConsensusManager.cs#L1094-L1101

because when this is called the first times, `expectedBlockDataBytes` keep storing `0` because avgSize start from 0 and there are no blocks downloaded yet so the average can't change

https://github.com/stratisproject/StratisBitcoinFullNode/blob/b42026e2800725d4cdb8f2952de380e2dd638c99/src/Stratis.Bitcoin/Consensus/ConsensusManager.cs#L1103

https://github.com/stratisproject/StratisBitcoinFullNode/blob/b42026e2800725d4cdb8f2952de380e2dd638c99/src/Stratis.Bitcoin/Consensus/ConsensusManager.cs#L1137

as a result, it enqueue lot of `RequestBlocksDownload` that result in a download of, actually, 10000 blocks that may take up to 10GB if the blocks are full (1 MB per block)

A proposed fix is to set feed with a list of the latest XX blocks taken from the blockstore, to the `averageBlockSizeBytes` member of 'BlockPuller' in order to have a meaningful set of samples that returns a valid average (or just, in case of empty set, return the max block size, could be easier and safer in case a future new chain start having already big blocks)

**Comment by noescape00** [comment]
By quickly checking memory snapshot from profiler it seems to me @MithrilMan is right and the problem is about block size estimation- it's incorrect.

**Comment by dangershony** [comment]
Ah excellent MM good spot, I will try to reproduce myself as well.
Proposed solution is not clear yet.
