### ISSUE TITLE
Bad peers can DDoS fullnode

### ISSUE THREAD

**Issue by MithrilMan** [stratisproject/StratisBitcoinFullNode#2297]
`PeerBanningBehavior` doesn't take into account bad peers that can send invalid `HeadersPayload` containing bad headers (expecially the first).

What happens in this scenario, is that a bad peer return a list of invalid headers that get passed to 
`PresentHeadersLockedAsync` method in `ConsensusManagerBehaviour` that has this try/catch block

https://github.com/stratisproject/StratisBitcoinFullNode/blob/4b9dc8f9b9b4dd8d582b91e96639719c039383d0/src/Stratis.Bitcoin/Consensus/ConsensusManagerBehavior.cs#L383-L394

`this.consensusManager.HeadersPresented` calls this line 
https://github.com/stratisproject/StratisBitcoinFullNode/blob/4b9dc8f9b9b4dd8d582b91e96639719c039383d0/src/Stratis.Bitcoin/Consensus/ConsensusManager.cs#L207

that throws the exception because of

https://github.com/stratisproject/StratisBitcoinFullNode/blob/4b9dc8f9b9b4dd8d582b91e96639719c039383d0/src/Stratis.Bitcoin/Consensus/ChainedHeaderTree.cs#L674-L678  

**When `this.consensusManager.HeadersPresented` rises ConnectHeaderException, our node try calls 
`await this.ResyncAsync().ConfigureAwait(false);` that basically starts an infinite loop of** 

>give me your headers
>damn I haven't the first one you returned to me, let's sync again maybe i messed up something

**The truth is that the rogue peer gave us at least a wrong first header. The first one `headers[0]` has a special meaning (it must be presented in our chain) that causes that exception.
We are now hostage of that peer.**

In case the wrong hash is 2nd or further, a fork will be created but I don't think this would cause trouble because would be a legit fork with a proper proof of work linked to our previous valid block.

What I propose is to internally count these kind of behaviours and ban the peer if it generates too much consensus problem in a timeframe. If there is already this kind of process in place, then it must include this code in his "counter".

**Comment by Aprogiena** [comment]
we are aware that we do not  implement any rate limits ,it has been suggested  before - https://github.com/stratisproject/StratisBitcoinFullNode/issues/722

**Comment by Aprogiena** [comment]
closing as duplicate
