### ISSUE TITLE
Activate Proven Headers using deployments

### ISSUE THREAD

**Issue by dangershony** [stratisproject/StratisBitcoinFullNode#2329]
Currently we activate PH using a param in the network class (this will be ok for testnet) we sould consider using BIP9 deployment mechanisem to activate it on mainnet

**Comment by zeptin** [comment]
+1 for using the BIP9 mechanism. We may have to introduce a network-specific enum so that we don't have overlapping bit definitions, or bits that are applicable to BTC and not STRAT, or vice versa.

**Comment by MithrilMan** [comment]
https://github.com/stratisproject/StratisBitcoinFullNode/issues/2464

**Comment by dangershony** [comment]
Tracking this https://github.com/stratisproject/StratisBitcoinFullNode/pull/2680

**Comment by noescape00** [comment]
Fixed by having it activated by default instead of having activation height
