### ISSUE TITLE
MiningAndPropagatingPOW [Mining and Staking tests implementation]

### ISSUE THREAD

**Issue by thefazzer** [stratisproject/StratisBitcoinFullNode#2345]
**MiningAndPropagatingPOW [Mining and Staking tests implementation]**
- MineBlockCheckNodeConsensusTipIsCorrect : _Mine a block check consensus   tip (success)_
- MineBlockCheckPeerHasNewBlock : _Mine a block and propagate to peers (success)_
- NodeConsensusTipHasLessWorkThanNetworkTipResets : _Node consensus tip has less work than network tip and   consensus resets (success)_

**Comment by fassadlr** [comment]
This has been completed.
