### ISSUE TITLE
[SC] Enable MultiSig Scripts through the AllowedScriptTypesRule.

### ISSUE THREAD

**Issue by codingupastorm** [stratisproject/StratisBitcoinFullNode#2355]
The implementation of AllowedScriptTypesRule is complete, but we need to test for MultiSig addresses, and ensure that it is flexible enough to be used for the sidechains implementation.

**Comment by codingupastorm** [comment]
Get some empirical idea about how much time will be consumed, what we need the block time to be, and thus where to go next

**Comment by dangershony** [comment]
Basically there is a Multisig Standard Template, I believe this should be enough to support for federation Multisig (up to 15 signers)

**Comment by zeptin** [comment]
@dangershony Note my comments previously on #2356 as we currently use P2SH for the federation cross chain transfers. My understanding of the PoA feature is that it is transfer-agnostic and leaves the transfers up to other code (in this case the federation gateway feature).
