### ISSUE TITLE
Unit tests stability on CI

### ISSUE THREAD

**Issue by noescape00** [stratisproject/StratisBitcoinFullNode#2378]
From time to time 1-5 tests would fail to pass on Travis or AppVeyor. 
Those tests should be examined and updated in a way that they are always passing. 

One who works on this should trigger CI like 20-30 times till all of problematic tests are found and fixed. 
We want CI to be 100% stable.

**Comment by fassadlr** [comment]
Closing as all 100% unit tests pass on CI build.
