### ISSUE TITLE
Care about Stopwatch ElapsedTicks property

### ISSUE THREAD

**Issue by MithrilMan** [stratisproject/StratisBitcoinFullNode#2391]
Worning on an Issue about DNS feature, I spotted a point where Stopwatch was used old fashioned way to measure dns performance instead using our StopwatchDisposable class, so I refactored the code.
In the process of refactoring, I saw that we were getting the elapsed Ticks in two different ways:
- using stopwatch.ElapsedTicks property (a long value=
- using stopwatch.Elapsed property (a Timespan value) accessing then it's Ticks property

While at first I thought it was the same, I googled to confirm that.

What I discovered was this: https://stackoverflow.com/a/1438984/1716620

now looking at dotnet source, one isn't just a wrapper of another

https://github.com/dotnet/corefx/blob/f267aed8b4a8f8314b2f6773cd1d825a82b0075f/src/System.Runtime.Extensions/src/System/Diagnostics/Stopwatch.cs#L115-L128

that lead to this:
https://github.com/dotnet/corefx/blob/f267aed8b4a8f8314b2f6773cd1d825a82b0075f/src/System.Runtime.Extensions/src/System/Diagnostics/Stopwatch.cs#L144-L175
```
// Get the elapsed ticks.        
private long GetRawElapsedTicks()
{
    long timeElapsed = _elapsed;


    if (_isRunning)
    {
        // If the Stopwatch is running, add elapsed time since
        // the Stopwatch is started last time. 
        long currentTimeStamp = GetTimestamp();
        long elapsedUntilNow = currentTimeStamp - _startTimeStamp;
        timeElapsed += elapsedUntilNow;
    }
    return timeElapsed;
}


// Get the elapsed ticks.        
private long GetElapsedDateTimeTicks()
{
    long rawTicks = GetRawElapsedTicks();
    if (IsHighResolution)
    {
        // convert high resolution perf counter to DateTime ticks
        double dticks = rawTicks;
        dticks *= s_tickFrequency;
        return unchecked((long)dticks);
    }
    else
    {
        return rawTicks;
    }
}
```

IsHighResolution doc: https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.stopwatch.ishighresolution?redirectedfrom=MSDN&view=netframework-4.7.2

so the conlusion of that stackoverlow post seems legit

> I just found out that ElapsedTicks in the StopWatch class doesn't mean real "ticks" if StopWatch.isHighResolution is True
> 
> Note([if isHighResolution is True][1]):
> 
> >  Stopwatch ticks are different from
> > DateTime..::.Ticks. Each tick in the 
> > DateTime..::.Ticks value represents
> > one 100-nanosecond interval. Each tick
> > in the ElapsedTicks value represents
> > the time interval equal to 1 second 
> > divided by the Frequency.
> 
> You can do the math above or it seem you can use **StopWatch.Elapsed.Ticks** instead of **StopWatch.ElapsedTicks**
> 
> 
>   [1]: https://msdn.microsoft.com/en-us/library/system.diagnostics.stopwatch.ishighresolution(v=vs.110).aspx

StopwatchDisposable class was already using `Elapsed.Ticks` so refactoring DNS code to use that class would be beneficial (I haven't seen other usage of stopwatch.ElapsedTicks in our codebase) even I found an interesting comment that could be caused by this issue:
https://github.com/stratisproject/StratisBitcoinFullNode/blob/36388d365f473c48f521ce4535d3343007134316/src/Stratis.Bitcoin.Tests/Utilities/StopwatchTest.cs#L12-L19

I can even already close this issue, I thought was worthy to point this out.

**Comment by dangershony** [comment]
@MithrilMan is this still an issue?
