### ISSUE TITLE
Fee estimation returns 0 in StratisRegTest network

### ISSUE THREAD

**Issue by maciejzaleski** [stratisproject/StratisBitcoinFullNode#2415]
**Request:**
curl -X GET "http://192.168.98.100:37221/api/Wallet/estimate-txfee?WalletName=Wallet-AAA&AccountName=account%200&DestinationAddress=TWhr5DhynqZXiGt88BcUJmoYh4UpDDCpQN&Amount=100000&FeeType=Medium&AllowUnconfirmed=true&ShuffleOutputs=true" -H "accept: application/json"

**Response:**
0

**Comment by bokobza** [comment]
Maybe I shouldn't closed that automatically.
@maciejzaleski @ArcSin2000X please retest this.
I have the suspicion that https://github.com/stratisproject/StratisBitcoinFullNode/issues/2416 will also get fixed with this. Can you please retest that as well?

**Comment by maciejzaleski** [comment]
I can confirm that this functionality now works for StratisRegTest network
