### ISSUE TITLE
Can't get maximum transaction amount

### ISSUE THREAD

**Issue by maciejzaleski** [stratisproject/StratisBitcoinFullNode#2416]
**Request:**
curl -X GET "http://192.168.98.100:37221/api/Wallet/maxbalance?WalletName=Wallet-AAA&AccountName=account%200&FeeType=Medium&AllowUnconfirmed=true" -H "accept: application/json"

**Response:**
{
  "errors": [
    {
      "status": 400,
      "message": "This should be unreachable; please find and fix the bug that caused this to be reached.",
      "description": "Stratis.Bitcoin.Features.Wallet.WalletException: This should be unreachable; please find and fix the bug that caused this to be reached.\n   at Stratis.Bitcoin.Features.Wallet.WalletTransactionHandler.GetMaximumSpendableAmount(WalletAccountReference accountReference, FeeType feeType, Boolean allowUnconfirmed) in C:\\Code\\InternalTestnet\\tmp\\StratisBitcoinFullNode\\src\\Stratis.Bitcoin.Features.Wallet\\WalletTransactionHandler.cs:line 169\n   at Stratis.Bitcoin.Features.Wallet.Controllers.WalletController.GetMaximumSpendableBalance(WalletMaximumBalanceRequest request) in C:\\Code\\InternalTestnet\\tmp\\StratisBitcoinFullNode\\src\\Stratis.Bitcoin.Features.Wallet\\Controllers\\WalletController.cs:line 620"
    }
  ]
}

**Comment by bokobza** [comment]
@maciejzaleski  Can you copy your wallet in here please?

**Comment by maciejzaleski** [comment]
This API is now working as expected.

**Comment by bokobza** [comment]
👍
