### ISSUE TITLE
Add support for the listen option

### ISSUE THREAD

**Issue by maciejzaleski** [stratisproject/StratisBitcoinFullNode#2421]
There should be a `-listen` configuration option which will allow configuration of the PeerServer as it is the case for other blockchain clients.

**Example**
`-listen`: Accept connections from outside (default: 1 if no -proxy or -connect/-noconnect)

**Comment by maciejzaleski** [comment]
#2418

**Comment by MithrilMan** [comment]
Agree, this is an important option to have

**Comment by maciejzaleski** [comment]
Closed

**Comment by bokobza** [comment]
@maciejzaleski do we have this in the code?

**Comment by maciejzaleski** [comment]
Issue has been moved to: https://dev.azure.com/Stratisplatformuk/StratisBitcoinFullNode/_workitems/edit/3041
