### ISSUE TITLE
LookaheadBlockPuller NextBlockCore race condition

### ISSUE THREAD

**Issue by Aprogiena** [stratisproject/StratisBitcoinFullNode#244]
Race condition (R1) and potential race condition (R2) exist in LookaheadBlockPuller: 
https://github.com/stratisproject/StratisBitcoinFullNode/blob/fd06b73f8251421c7084cddc44324f9166fedece/Stratis.Bitcoin/BlockPulling/LookaheadBlockPuller.cs#L406

R1: As soon as IsDownloading returns false here, another thread can change the state (consider BlockPullerBehavior.Node_MessageReceived, just before the newly downloaded block is pushed, the above check for DownloadedBlocks will fail - block not pushed yet - but then IsDownloading here returns false), which will cause this thread to call AskBlocks for a block that was already downloaded. 

R2: Another potential race condition here is unclear: Is there also a possibility that this happens when the block is being downloaded? I.e. is this the only thread that can exist in the node and lead to execution of DistributeDownload? If there can be another thread executing DistributeDownload, the map can be updated after IsDownloading returns false, which would lead to a single block being downloaded twice. 

R2 is not clear because NextBlockCore is called from NextBlock, which is called from BlockNotification.Notify, which is run in its own async loop, but the NextBlock is also called from ConsensusLoop.ExecuteNextBlock, called from ConsensusLoop.Execute, called from ConsensusFeature.RunLoop, which runs in its own thread. So it seems like there are two different threads that can end with calling NextBlock, but it is unclear whether there is not some mechanism to prevent the concurrency.

The problem in both cases is the same - IsDownloading allows you to get state of shared resource, but once IsDownloading returns, the state is no longer guaranteed and you are working with potentially outdated information. It would be possible to use such an information, if later the code guaranteed that the unwanted behavior (downloading block that has been downloaded already, or is being downloaded) could not occur. This is not the case, however.

**Comment by dangershony** [comment]
BlockNotification and ConsensusLoop are not running together in one node. (Notification is for a light wallet consensus for a fullnode)

**Comment by Aprogiena** [comment]
OK, so R2 seems to be non-issue.

**Comment by Aprogiena** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[BlockPuller]  LookaheadBlockPuller NextBlockCore race condition](https://trello.com/c/HPihbfW9/140-blockpuller-lookaheadblockpuller-nextblockcore-race-condition)

**Comment by dangershony** [comment]
Indeed there may be a race condition if a block was downloaded just after this check   
```    if (header != null && TryRemoveDownloadedBlock(header.HashBlock, out block))```

A block that is already been queued to download will either be in downloading or downloaded state so to fix we need to check all 3 dictionaries, this is the only place where IsDownloading is called so I would change IsDownloading() to
```
        public bool IsAsked(uint256 hash)
        {
            bool res = false;
            lock (this.lockObject)
            {
                res = this.assignedBlockTasks.ContainsKey(hash) || 
                      this.pendingInventoryVectors.Contains(hash) || 
                      this.downloadedBlocks.ContainsKey(hash);
            }
            return res;
        }

```

**Comment by Aprogiena** [comment]
I don't like that solution conceptually, but it would probably work (maybe not! see the end of this post) because there is this invariant that NextBlockCore is called strictly from one thread. I don't like it because this invariant is not documented anywhere and as you could see from my analysis, it is not obvious to a newcomer that it holds. Thus anyone coming newly to this code later again, could spend time wondering if this is safe or not, which is what we should avoid. 

The whole code looks so confusing because the way it is written implies that some other thread on the background can exist and change things.

One of the sources of confusion (for me) here is this line

`ChainedBlock header = this.Chain.GetBlock(this.location.Height + 1);`

and the fact that it is INSIDE the loop. As it is inside the loop, it suggests that there could be another thread that would change the header over two iterations of the loop. 

Another source of confusion is that if branch that deals with reorg - as if there could be reorg by another thread.

So if I read it right, the download of the chain of block headers is completely separated from this code, so in fact the reorg can happen on background, while still NextBlockCore is called by just one thread. 

If that is the case, however, the analysis is even more complex here and it seems like there are race conditions everywhere - consider AskBlocks in LBP, everytime you call this.Chain.Something, on the very next line it may not longer be the case. 

**THIS**
For me the main question now is - can reorgs happen on the background as this code in NextBlockCore suggest? If no - then why the code is written like that. If yes, then **consider the following in NextBlockCore**:

`ChainedBlock header = this.Chain.GetBlock(this.location.Height + 1);`

say your location is now 100, on this line you basically ask for block height 101. But you ask for block 101 regardless of which chain that is. It would make sense to ask for "block 101 on the chain i'm working with now". But that is not what we do here, we ask for any block with height 101 on any chain. So if the chains can be switched on the background then what? It seems like we deliver it to the upper layer. But code like ConsensusLoop.ExecuteNextBlock looks like it relies on the puller to tell it whether reorg happened or not. But as we are asking for block number X and not block hash Y, we might miss the reorg and the upper layer won't know it. Now I don't know what happens next, but I would assume that if we deliver the block from different chain, it won't fit (be invalid), and this will lead to ban of such peer (which actually delivers the correct block from the longest chain), and i'm not sure if the node can recover from this somehow (would be surprising if it could).

I think all this is not problem only because there are no reorgs on Bitcoin blockchain. So you don't really run into these problems during IBD. I'm not sure if this code is used for not IBD stage (i.e. if natural small reorgs apply to this or not). But say something like Bitcoin Cash happens, then nodes doing IBD at that stage could see such reorgs.

If the puller is used even after IBD then this can be a big problem. Is it?

**NOTE**
Note that I still don't have enough knowledge about other parts of the code so the above is written with many assumptions, some of them may be wrong - maybe i'm analyzing something that can't happen, but i just don't know it yet. I also made many shortcuts to avoid spending too much time before you could give me more info about the subject.

**Comment by dangershony** [comment]
When testing on POS and running simulations we had many reorgs and they where clean further more we have tests that simulates reorgs and they all pass fine.

Some of your assumptions are right a reorg will happen in the background and when that happens the puller will send null back to the caller (upper layer) but this is fine as the caller needs to decide how to recover from a reorg.

The node can recover from reorgs yes in fact each feature needs to deal with reorg independently, see block store reorg step, so we wont deliver a bad block to a peer (if we do we need to fix it) and the wallet also deals with reorg on its own its all dr2oven by Chain.

**Comment by Aprogiena** [comment]
OK, so at least this adds another dimension to the code that I should be aware of - that the ConcurrentChain (or this.Chain) can reorg at any time. At this point I can't tell if that is a good thing (good is not the right word, "necessary" is better) to have or not. 

As for the tests - yes, I understand that, but at the same time there is no logic in this code that would allow you to test this particular scenario - i.e. reorg happens at this and this line of code. As such, you can't really say "it is covered by tests", you can only say "it have never broke so far".

I wonder if it could be handy to have the ConcurrentChain (or rather a new object wrapping it) to give you exception on some read operations (such as GetBlock) in case of reorg happened from the last time you used it. So you could configure this new object to this behavior and thus be informed about any reorg happening, which would provide you much much easier thinking about the design when working with the chain.

This is a little offtopic though, sorry about that, but still maybe useful.

**Comment by Aprogiena** [comment]
As for the original problem of this issue, I was thinking whether this IsAsked (I'd maybe rather called it IsDownloadingOrReady) should not be called first in the loop. Now, you first try to consume the block to see if it is ready and only then you call IsDownloading. But if you reverse that, you can have much greater information to start your decision with.

**Comment by Aprogiena** [comment]
Once again back to the chain reorgs (but maybe we should open a new issue for that, not sure yet). How about this:

LookaheadBlockPuller.PushBlock is called when the block is being delivered in BPB.Node_MessageReceived. Now consider the strat of the method:
```
            uint256 hash = block.Header.GetHash();
            ChainedBlock header = this.Chain.GetBlock(hash);
            while (this.currentSize + length >= this.MaxBufferedSize && header.Height != this.location.Height + 1)
```

If we reorged to different chain before the block came, can't we get null header here? So do we rely here on the exception to be consumed by OnMessageReceived try/catch block around `handler.DynamicInvoke(this, m);`? This is probably OK, although not sure if intentional. But what if reorg happened later, but before this new block is consumed. It seems like it will be added to downloadedBlocks and never consumed. Looks like memory leak and if blocks are full, this means 1MB of memory gone forever, and eventually, if the node is run for a long time, it could sum up.

**Comment by dangershony** [comment]
Yes indeed this is a side effect of reorg that the block will be forever in the Downloaded list, we need to fix it, on reorg clear all 3 dictionaries.

**Comment by Aprogiena** [comment]
OK, I'll create a new issue for that. I'm a bit afraid that things like that will be hidden in the other code as well and I'll have to think about the code even more carefully having this new knowledge.

**Comment by dangershony** [comment]
Regarding reorg tests I was just answering some assertions you made regarding reorg not working like you questions 
> I think all this is not problem only because there are no reorgs on Bitcoin blockchain

Yes reorg works generally, ofcourse its very hard to test specific race conditions.

Perhaps you don't have yet the full view of the code base and it's architecture but this will come the more you linger around the code, for example we cannot isolate reorgs on ConcurrentChain too many parts will be involved in that so each feature will manage its own reorgs.

**Comment by Aprogiena** [comment]
Alright, back to your suggestion:

```
        public bool IsAsked(uint256 hash)
        {
            bool res = false;
            lock (this.lockObject)
            {
                res = this.assignedBlockTasks.ContainsKey(hash) || 
                      this.pendingInventoryVectors.Contains(hash) || 
                      this.downloadedBlocks.ContainsKey(hash);
            }
            return res;
        }

```

I don't think it would work as there is the gap we've discussed on slack. So because of the PushBlock delay, we can't make DownloadTaskFinished and PushBlock one atomic operation, which means the block can be NOT present in all 3 data structures at the same time, so this new IsAsked implementation would not work.

**Comment by dangershony** [comment]
As discussed PushBlock will be refactored and some of the logic may move in to DownloadTaskFinished
