### ISSUE TITLE
api/SmartContracts/build-and-send-call  return Error 500

### ISSUE THREAD

**Issue by Nayyar525** [stratisproject/StratisBitcoinFullNode#2442]
Hi team ,

when i cam trying to call the api "api/SmartContracts/build-and-send-call" 
Error : 
Curl:
curl -X POST "http://localhost:38220/api/SmartContracts/build-and-send-call" -H "accept: application/json" -H "Content-Type: application/json-patch+json" -d "{ \"walletName\": \"Gaurav\", \"accountName\": \"account 0\", \"contractAddress\": \"SUjKHU1EtA2afhoVoPCwTdyaoknndTKstc\", \"methodName\": \"Test\", \"amount\": \"10\", \"feeAmount\": \"0.002\", \"password\": \"password\", \"gasPrice\": \"11\", \"gasLimit\": \"1500\", \"sender\": \"SaoZYiQQzExoh9dJKFFyxRMfa89joerZs8\", \"parameters\": [ \"5\" ]}"

Requested URL:
http://localhost:38220/api/SmartContracts/build-and-send-call

Code | Details
-- | --
500 | Error: Internal Server ErrorResponse headers content-length: 0  date: Wed, 10 Oct 2018 11:03:15 GMT  server: Kestrel

```
Smart Contract 👍 

using Stratis.SmartContracts;
public class Test :SmartContract
{
    public int data
    {
        get
        {
            return PersistentState.GetInt32("data");
        }
        private set
        {
            PersistentState.SetInt32("data", value);
        }
    }

    public Test(ISmartContractState smartContractState)
       : base(smartContractState)
    {
       
    }

    public int Method01(int x )
    {

        data = x;
        return data;

    }


`}`
```

Josn 👍 
{
  "walletName": "Gaurav",
  "accountName": "account 0",
  "contractAddress": "SUjKHU1EtA2afhoVoPCwTdyaoknndTKstc",
  "methodName": "Method01",
  "amount": "10",
  "feeAmount": "0.002",
  "password": "password",
  "gasPrice": "11",
  "gasLimit": "1500",
  "sender": "SaoZYiQQzExoh9dJKFFyxRMfa89joerZs8",
  "parameters": [
    "5"
  ]
}

i am able to deploy contract successfully and got result. Please let me know who to reslove the issue

**Comment by rowandh** [comment]
You have two different sample json requests. In the first one you're calling a method 'Test' that does not exist on the contract. In both the first and the second you're formatting the params incorrectly.

Can you do the following:
* Change the signature of `Method01` to be `Method01(uint x)`. An int was an unsupported param type in this release.
* Format the params in the request [as per the docs](https://stratis-smart-contracts.readthedocs.io/en/latest/deploying-your-first-smart-contract.html#specifying-smart-contract-constructor-parameters). For a uint with value 5, this would like like `12#5`

**Comment by Nayyar525** [comment]
@rowandh thanks its work fro me.

can you please let me knw how i can retrieve the transaction. The parameter  i  send to the method how i can get back from that..
{
  "fee": 216500,
  "hex": "010000000120bf5b017865a1c73639776139ba5266e13bed5b20593bdc2601ff7848fe28f64e012bbf000000006a47304402204fae3d8556f25033bacb734fc76c6db3054099838bdd295d0afbb0b7da1eea9502206291c0f7f6e351b7d9e11663dff5ae0f9830712b3eec76b849a466943ba29c82012102aafc7f1ab7ad876f74dda8a1376a567e8345ce8f7f362f2f02f8530e578b3f5effffffff024cda67ee000000001976a9149430d71c66e0fa29c032441fe47dffd6d9c8680788ac00ca9a3b0000000055c10400000001000000080000000b0000000000000008000000dc05000000000000140000005192840218b0cb1e5d063d25da1bd0fd96f29cd7110000004d6574686f6430312875696e74202078290300000038233500000000",
  "message": "Contract was successfully called with method Method01(uint  x).",
  "success": true,
  "transactionId": "a8ac30e4a9050d533315081101fa6cea9f345b86ac9fa7bb3bd338e14687bafb"
}
what i tried --
/api/SmartContracts/receipt

give the txHash in the get api.
a8ac30e4a9050d533315081101fa6cea9f345b86ac9fa7bb3bd338e14687bafb
result--

{
  "errors": [
    {
      "status": 400,
      "message": "Receipt not found.",
      "description": "Could not find a stored transaction for this hash."
    }
  ]
}

**Comment by rowandh** [comment]
You have passed `Method01(uint x)` as the method name, but the method name is `Method01`.

**Comment by Nayyar525** [comment]
i used with Method01 but result are same. Did i am missing any thing  ? 

why its showing false ..?
