### ISSUE TITLE
How to make public and private transaction in Stratis 

### ISSUE THREAD

**Issue by Nayyar525** [stratisproject/StratisBitcoinFullNode#2457]
Hi Team, 

I am exploring  stratis from few days its working super. Just want to know if there is any   private transaction in stratis. i tried finding on google and stratisplatform.com but no luck.

Please share if any document or link is available on the same.

Thanks in advance :)

**Comment by noescape00** [comment]
What do you mean by private tx? 

If you mean smth like what monero or zcash do- no. 
But we have tumbling- it's called tumblebit

ps
Don't open issues for questions, we have a community discord for that. Feel free to ask anything in dev_general or support channel.

**Comment by Nayyar525** [comment]
Smth like hyperleger ,quorum, corda support ?

**Comment by noescape00** [comment]
Yeah, we will soon have stratis DLT (by the end of Q4) which is an enterprise-oriented solution. But it's mostly for private chains that companies host on their own network. So privacy of txes on those chains come from privacy of the whole blockchain which is just not exposed to general public.

**Comment by Nayyar525** [comment]
but in some of the use case you don't want to share the tx with every node but share among some node then how this is handle by startis ? -- any link or document

**Comment by noescape00** [comment]
In v1 of stratis DLT solution we don't have permissions matrix so some of the nodes can see some txes and some don't. But we might add this in v2. 

>any link or document

It's private before the release (which is end of Q4). But you can contact the company officially and they might give it to you.

**Comment by Nayyar525** [comment]
ok cool thanks
