### ISSUE TITLE
Separate ConsensusFeature into PoSConsensusFeature and PoWConsensusFeature 

### ISSUE THREAD

**Issue by noescape00** [stratisproject/StratisBitcoinFullNode#2459]
Right now both builder extensions (UsePowConsensus and UsePosConsensus) share ConsensusFeature. 
But recently we figured out that based on consensus type we need to add different things to template behaviors so we need to have pos and pow consensus features (they might inherit from consensus feature). And each will add things that are specific to pos or pow. 
For example for pos we want to have ProvenHeaderConsensusManagerBehavior in template behaviors and for pow we wnat ConsensusManagerBehavior.

**Comment by dangershony** [comment]
While this is not a bad idea, If it's only about solving the behaviour injection this can be done using DI

**Comment by bokobza** [comment]
Done with https://github.com/stratisproject/StratisBitcoinFullNode/pull/2519
