### ISSUE TITLE
Potential race condition in BlockPuller AskBlocks->GetNodeBehaviors->DistributeDownload

### ISSUE THREAD

**Issue by Aprogiena** [stratisproject/StratisBitcoinFullNode#246]
I'm not sure about this one, but will add it anyway. So if you can argue why this can not happen, please do.

BlockPuller.AskBlocks calls BlockPuller.GetNodeBehaviors, which selects candidate nodes to assign work to. It seems to me that it can happen that another thread will call Node.Cleanup when the peer node disconnects. In that case the Nodes collection that BlockPuller.GetNodeBehaviors works with might be unupdated until BlockPullerBehavior.DetachCore is called, so BlockPuller.AskBlocks can get a list of nodes including the one that just disconnected.

Then let's say BlockPuller.AskBlocks calls BlockPuller.DistributeDownload and just before it modifies BlockPuller.map, the BlockPullerBehavior.DetachCore can be called in the other thread, which would release all the work assigned to this freshly disconnected node. Then BlockPuller.DistributeDownload would continue and modify the map. 

This would end with a work assigned to a no longer existing node, which would lead to puller stalling once the assigned block would be requested.

**Comment by Aprogiena** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[BlockPuller] AskBlocks->GetNodeBehaviors->DistributeDownload Race condition](https://trello.com/c/YFYbRoi0/137-blockpuller-askblocks-getnodebehaviors-distributedownload-race-condition)

**Comment by dangershony** [comment]
Yes I see a race condition.

The lock is held in BlockPuller.AssignDownloadTaskToPeer but if DetachCore is called between BlockPuller.GetNodeBehaviors and BlockPuller.AssignDownloadTaskToPeer there will be a race condition.

I think its not directly related to DetachCore so much but to the fact the Node and the BlockPullerBehavior are still part of the connection,  we need a way to invalidate the BlockPullerBehavior inside the lock.

We can add a flag to to BlockPullerBehavior, it will be set inside the lock in the method BlockPuller.ReleaseAllPeerDownloadTaskAssignments and BlockPuller.AssignDownloadTaskToPeer will return false if the flag is set.

Will this work?

**Comment by Aprogiena** [comment]
This seems one of the tougher ones to me to be honest. We have two quite unrelated components, one sharing its list of nodes and the other making decisions based on that. 

The lock of BlockPuller is of no use here. The problem is in the way Nodes is provided and accessed. Once GetNodeBehaviors gets its own copy of the collection (or its subset) the game is somewhat lost. The problem is that even if we fixed it for GetNodeBehaviors, the copy of the list is carried to AssignPendingVectors where the problem is present again and even if we fixed that then again in DistributeDownload.

But looking at the code, no one is actually using the list of nodes except for DistributeDownload, so there is probably no why to call GetNodeBehaviors before DistributeDownload is called. I'm talking about narrowing the window for the race, which often gives a good clue to a solution, but is not the solution by itself (in other words, i'm just thinking out loud). So probably first thing to do here is to move GetNodeBehaviors closer to AssignDownloadTaskToPeer. Won't solve anything, but will make thinking about the design easier.

You are right about invalidating the peer from DetachCore-ReleaseAll, the question is how to do it. And yes, the flag inside BPB should work. It seems ugly though because suddenly you have a property inside BPB that you can only access with lock from the puller. So it is in fact the puller's property, just inside another class. But it would work.

It would work, but then DistributeDownload would be slightly broken. Currently AssignDownloadTaskToPeer can not really fail and returns false only if the work is assigned to someone else (so either you will assign it or it is assigned already, in any case it is assigned as you finish the call), but with the flag, you would like to introduce a third option, in which case you would like the work to be tried to assigned to someone else. But this is solvable, so yes, it would work :)
