### ISSUE TITLE
MiningMempoolTransactions [Mining and Staking tests]

### ISSUE THREAD

**Issue by thefazzer** [stratisproject/StratisBitcoinFullNode#2466]
MiningMempoolTransactions [Mining and Staking tests]

- MineZeroBlocksNoTxsInMempoolNoPeersConnected 
 _No blocks mined when no peers connected and no txs in mempool_
 
- MineBlocksBlockOrphanedAfterReorgTxsReturnedToMempool
 _Mine block after block is orphaned after reorg and txs returned to mempool_

**Comment by fassadlr** [comment]
Closed with #2502
