### ISSUE TITLE
Network fork created when transactions with small fees are propagated

### ISSUE THREAD

**Issue by maciejzaleski** [stratisproject/StratisBitcoinFullNode#2468]
The transactions have been created on SBFN using the estimated fee returned by the `/api/Wallet/estimate-txfee` API call.
The fee algorithm could be flawed on SBFN for StratisRegtest which is a problem but not a main concern.

**Steps to recreate network fork**
 - Create transaction on SBFN with small fees
 - Transaction is not accepted to Stratis-Qt mempool
   `ERROR: AcceptToMemoryPool : not enough fees 6203feab1f6ba6bb6f535fa0c22f995f219e44c7810892307489dc6e5ef5b1d6, 1960 < 10000`
 - Send another transaction from SBFN with small fee
`ERROR: FetchInputs() : 0c0a531d26e40476fc78ef22e81a8cad37736f4c41ce5fb76e818eeb7403d1ff mempool Tx prev not found 6203feab1f6ba6bb6f535fa0c22f995f219e44c7810892307489dc6e5ef5b1d6`
 - Both transactions are propagated to SBFN all nodes but not to any Stratis-Qt nodes
 - Mine block on Stratios-Qt; the transactions will not be included in the block as they are not in Stratis-Qt memory pool
 - Mine block on SBFN; new block is mined and propagated to all SBFN nodes but not to any Stratis-Qt nodes
 - Stratis-Qt will reject the new block
`ERROR: ConnectBlock() : coinbase reward exceeded (actual=400009640 vs calculated=400000000)
InvalidChainFound: invalid block=1fe9f0f248cb5bb96e89b8853bddfe5e60bc6e1230899c927239c2b2f4a61ffe  height=16  trust=34  blocktrust=2  date=10/11/18 16:15:26
InvalidChainFound:  current best=9a1a95c22bc69b5a3d0247b61cc811be4531e347641a82ba9c450b05ee97b7b1  height=15  trust=32  blocktrust=2  date=10/11/18 15:59:52
ERROR: SetBestChain() : SetBestChainInner failed
ERROR: AcceptBlock() : AddToBlockIndex failed
ERROR: ProcessBlock() : AcceptBlock FAILED
Misbehaving: 192.168.98.103:16178 (0 -> 50)`

**Comment by noescape00** [comment]
That's really weird. I don't think it's about txes and different fees in standard tx policy. 
So your coinbase reward is 400009640, 40000000 is the subsidy and 9640 are the fees from txes included in that block. 
Could you please send the raw block here? Does the QT have those txes in the block being validated?

**Comment by noescape00** [comment]
So far I have a feeling that maybe C# node somehow included a tx without it's ancestors. But not sure- need more info.

**Comment by dangershony** [comment]
This is a `coinbase reward exceeded` bug we need to verify our calculations of reward are similar between X and C#.

Very good job @maciejzaleski keep them coming.

**Comment by zeptin** [comment]
It is actually quite easy to reproduce this.

The problem seems to be in the PoW phase of the network. See the following code snippet in `main.cpp`:

```
    if (IsProofOfWork())
    {
        int64_t nReward = GetProofOfWorkReward(nFees);
        // Check coinbase reward
        if (vtx[0].GetValueOut() > nReward)
            return DoS(50, error("ConnectBlock() : coinbase reward exceeded (actual=%d vs calculated=%d)",
                   vtx[0].GetValueOut(),
                   nReward));
    }
```

Even though `nFees` is passed to the `GetProofOfWorkReward` function, it is not considered in any calculations (it is for PoS, the calculations are different there). Therefore it is actually invalid for a Stratis PoW block to pay fees to the miner via the coinbase. This is probably a bug in stratisX itself, but ostensibly we will need to work around this in SBFN going forwards.

**Comment by zeptin** [comment]
Here are the two reward calculations, for reference. Note difference in usage of `nFees`:

```
// miner's coin base reward
int64_t GetProofOfWorkReward(int64_t nFees)
{
	int64_t PreMine = 98000000 * COIN;
    if(pindexBest->nHeight == 1){return PreMine;} else {return 4*COIN;}
}

// miner's coin stake reward
int64_t GetProofOfStakeReward(const CBlockIndex* pindexPrev, int64_t nCoinAge, int64_t nFees)
{
    return (1 * COIN) + nFees;
}
```

**Comment by dangershony** [comment]
Very good job @zeptin and @maciejzaleski for finding this, there is no risk of splitting stratis because POW era is over but its defo a consensus mismatch between C# and C++

**Comment by fassadlr** [comment]
@zeptin @dangershony on first glance and from the comments given on here, is my assumption correct in saying that in FN we currently DON'T included a fee when getting the POW reward but in Stratis-X we do?

So I need to change FN so that we DONT include a fee when the block is mined? Wont this affect our tests etc quite massively?

Cause in PowBlockDefinition we do this:

```
    var coinviewRule = this.ConsensusManager.ConsensusRules.GetRule<CoinViewRule>();
    this.coinbase.Outputs[0].Value = this.fees + coinviewRule.GetProofOfWorkReward(this.height);
```

Note this.fees + POW reward.

**Comment by dangershony** [comment]
Its only fees so I don't expect tests to be effected

The fix will be tricky if that's how we do it, so perhaps we need to pass the fee in to the method `GetProofOfWorkReward`

**Comment by MithrilMan** [comment]
basically we have burnt all the tx fees of PoW blocks on STRAT, this is something we should state somewhere, it affect market cap too (execpt if it's computed by sum of utxo)

**Comment by MithrilMan** [comment]
It seems we don't need to care about X as we are going to retire it.

**Comment by bokobza** [comment]
Looking at the changes that were made on StratisX, I can see that the fees were dropped on the port from Blackcoin to Stratis.
In here: https://github.com/stratisproject/stratisX/commit/970d66d01632e7d905769b1569f439f30bfb09d0
you can see
![image](https://user-images.githubusercontent.com/1867877/48141376-ad9b1000-e2a2-11e8-9d1c-36645788e5bd.png)

New chains using this code will have fees during their PoW phase, no big deal.

**Comment by bokobza** [comment]
A fix has been made in StratisX so this can be retested.

**Comment by maciejzaleski** [comment]
Resolved

**Comment by bokobza** [comment]
nice
