### ISSUE TITLE
LookaheadBlockPuller - QualityScore function is too penalizing

### ISSUE THREAD

**Issue by Aprogiena** [stratisproject/StratisBitcoinFullNode#247]
Added a bunch of logs in my local source code, it revealed that the block puller wanted to get a block, the work was assigned to a peer that had 75 quality score. The node provided the block in about 2 seconds, but during this time it lost 40 % of its quality score because of "stalling". Then by finishing the task, it gained +1, so it went 75 -> 45 -> 46. The peer ended with much worse score than it started, while it did a pretty good job. 

Basically what happens with the current score function is that any peer that is assigned work that is not currently needed can gain score, while to be assigned with the task to download currently needed block (say it was assigned to a peer that disconnected and then reassigned to other peer) always ends with dramatic lowering of the score. In case the peer is assigned the current and couple of following blocks, it will almost surely be thrown away (stalling -> score down -> score zero -> all tasks released from the node).

It seems like this downloading strategy does not really reflect how good nodes are.

**Comment by Aprogiena** [comment]
i am deeper in the log file and this


`
2017-07-24T13:33:59.0318266+01:00  [VRB] DistributeDownload(): Task candidate peer 3af70fa, height 204000, quality 37
2017-07-24T13:33:59.0318266+01:00  [VRB] DistributeDownload(): Task candidate peer 2d2e8c1, height 68000, quality 1
2017-07-24T13:33:59.0338264+01:00  [VRB] DistributeDownload(): Task candidate peer 3174ecc, height 14000, quality 1
`

then

`
2017-07-24T13:34:00.4669051+01:00  [VRB] DistributeDownload(): Task candidate peer 3af70fa, height 218000, quality 15
2017-07-24T13:34:00.4669051+01:00  [VRB] DistributeDownload(): Task candidate peer 2d2e8c1, height 72000, quality 2
2017-07-24T13:34:00.4669051+01:00  [VRB] DistributeDownload(): Task candidate peer 3174ecc, height 16000, quality 1
`


tells you the whole story - i've got 3 peers and two of them are out of score and now draining the third one

then it is basically about reaching quality 2, then back to 1, release all work and again and again, so constantly we are releasing all the work from everyone
which wastes a lot of resources

**Comment by dangershony** [comment]
Good point, it seems the quality score penalty depends on the wait time of the NextBlockCore loop and it feels this is not the correct way to penalize 

Perhaps we should add another time dimension to the point in time the block is sent and calculate penalty based on how long since the send happens rather then the wait loop iteration.

**Comment by Aprogiena** [comment]
Actually, I'm not sure the wait is the thing that is broken there. The pushed event signals whenever any other block is obtained from any other peer. So let's assume you have 5 peers, each downloads a block, that's 4 signals and 4 penalties, so you never wait a full second there. Then you wait 10 ms and get another penalty... 

I have a plan for this, to be described later.

**Comment by Aprogiena** [comment]
i mean thinking about it - assume you have 5 peers you donwnload from and now assume two different scenarios:

1) all 5 peers provide blocks with +- same frequency
2) 4 peers provide blocks with +- same frequency and the other 1 is significantly faster

i don't think the current alg works in either of those cases

**Comment by dangershony** [comment]
The only place the score is reduced is in the OnStalling method thats why I mentioned it.
And the score is only reduced for the peer that is downloading the pending next block hash.

In your example the faster peer will not have its score reduced as it downloaded fast so OnStalling was not called on it, right?

**Comment by Aprogiena** [comment]
I'll write little more about the two scenarios.

Scenario 1 - 5 peers, same freq. - And let's assume they are being assigned the next block evenly. Let's assume download time for a block is 0.5 seconds. Then peer A, currently responsible for next block, downloads the block. Our wait times are

`waitTime = new[] { 1, 10, 20, 40, 100, 1000 };`

What happens here is that A fails first 5 waits on timeout + 2 out of the remaining 4 peers are expected to deliver block faster than A, so that is 2 additional fails for A. Result is -7 on penalties for A and +1 bonus on block finished. Total -6. Also +1 for B and C who delivered faster. And if this rate continues as such, each round someone will get -6 and some other two will get +1. The total score per round is thus roughly -4. There seem to be that 1000ms wait to save the situation, but that is never going to timeout because meanwhile other peers will deliver their blocks and also since variable i is not static, it will always reset to 0 (-> 1ms wait) with every block consumption. So the outcome is not exactly -4 each round, it is much more complex, but still, it seems like it can not work with this setup. We would need to change avg. block download time to maybe 0.1 seconds to see something interesting. 

Scenario 2 - 5 peers with one king - so let's say A downloads in 0.1 secs, others 0.5 secs. What happens here is that if A is not the one to deliver next block (B), the score of that peer B goes down dramatically because A delivers 4x before this one + B fails first 5 waits on itself + 1.5 of other peers deliver faster than B, so this is >10 penalties for B already, while just +1 bonus for block finished. A's scores would go up in longterm, all others would go to minimum very quickly.

Observation - the system behaves differently with first 100k-200k blocks because their validation is very fast (faster than downloading), then it changes to the opposite. In such situations penalties would mostly come other peers delivering blocks rather than wait timeouts.

Introducing the download time for a block is problematic because you don't know how fast the Internet connection one have, so fixed times won't work and you'd need to make some statistics and set the times dynamically somehow.

The plan is to
- migrate to NLog and introduce detailed logs to puller -> this will allow easy analysis of all new strategies and is thus prerequisite for further improvement of this thing
- then to try to figure out new strategies - one possibility is, as you mentioned, to introduce the new time dimension, possibly based on statistics and such, but this sounds quite complex to me, so it would need a very detailed specification first

I can see another problem there and that is that even if the new tasks are assigned based on the score, it is still very possible (there are so many blocks that it will happen for sure) that very bad peers are assigned with very next blocks. This is very costly assignment, because it always ends with the tasks being reassigned and wasted because when a peer has a minimum or close to minimum score and gets the next block assignment, it is very unlikely for it to finish the job before it is reassigned to someone else. This is huge problem from my point of view and need to be addressed in the new strategy. 

So I'd like to develop a new strategy that will also not have this problem, because this one is probably the most costly.

**Comment by dangershony** [comment]
I agree the score currently is not perfect because the loop the one making the scores.
This needs to be broken away from the loops responsibility.

A think my suggestion of an additional time dimension that will track each node and the average time it takes to download a block as the score system will be much more accurate.

Peer A score = 100 (avg of 100ms)
-> Block1 = 100ms
-> Block2 = 90ms
-> Block3 = 110ms

Peer B score = 80 (avg of 80ms)
-> Block1 = 30ms
-> Block2 = 90ms
-> Block3 = 210ms

In such a strategy the lower score is preferred.

**Comment by Aprogiena** [comment]
I'd add to this issue the fact that there is a race condition on QualityScore property itself. This is minor thing as there is no real harm in case of the race, just +- 1 to score. But since we will rework this, it is better to have the code without races.

**Comment by Aprogiena** [comment]
So, I have thought about this one and checked what we have in the code. 

**Measuring Peer's Block Time**

So yes, there is stats for nodes calculating bandwidth of the channel with it. However, in BPB we do not have this information accessible and we could make it accessible, but the cost of that would be creating more binds between the components. Also the benefit of that is unclear. 

So maybe, instead of using this stat (and leave it just for stats purposes), I'd suggest to change `peersPendingDownloads`, which is now basically a mapping between the peer and the download tasks it is responsible for / assigned with. This has the form of `Dictionary<BlockPullerBehavior, HashSet<uint256>>` and I would go for something like `Dictionary<BlockPullerBehavior, Dictionary<uint256, DownloadTask>>`. `DownloadTask` would describe the task - currently it would contain hash and `Stopwatch`. So once it finishes via calling `DownloadTaskFinished` you could stop the `Stopwatch` and see how long it took for this block to be provided.

So that is how we can measure time for each block from specific peer.

**New Alg Features**
Then we need to think about how do we want to use this information. It turns out that having just one peer is somehow special thing - consider that you have one peer and it is very slow. But you don't have anything better. Current algorithm allows this peer to be penalized to minimum, which will result in its tasks being released from it and reassigned to it (because you have no one else). So it seems like a new alg should consider **special case of having just one peer**.

Another problem has been mentioned earlier already - current alg allows poor peers to be assigned most important jobs (very next blocks). This should be mitigated, not only using probability (as the current alg does) but **using hardcoded limits in alg disallowing poor peers to get important jobs**. This requires being able to sort peers by their quality, which we can do already now.

**Old Alg Discussion**

The current alg implements two kinds of penalties:

1. **Time Penalty** - using `waitTime`, which is defined as `private static int[] waitTime = new[] { 1, 10, 20, 40, 100, 1000 };` What you do is that you wait `waitTime[i++]` milliseconds and if you don't get your next block, the peer assigned with that task is penalized by 1.

2. **Competitor Penalty** - while waiting for `waitTime`, if another (not the very next) block is delivered even by the same peer, the peer responsible for the very next block is penalized by 1.

I can't figure out what is behind this `waitTime` distribution, so **I'd simply suggest a fixed period of time being used every time to impose the time penalty**. Something like 100ms might be good. The actual number does not really matter unless it is too high (i.e. low granularity). Also too low means too much CPU being used just for quality score calculations...

**New Alg Features / Description**

* min score = 0 => release tasks from pear upon reaching (as it is now)
* max score = 100
* default score = 50
* avgBlockTime = calculate avg time for block of last 100 blocks (circular array, O(1) updates)
* special next block penalty on wait timeout => if next block not delivered, score -= 1 (regardless of avgBlockTime)
* prevent score going down if sum(score) of all peers is lower than numPeers * 2 (also prevents single peer to go to 0 if it is alone)
* block received - reward peer if its blockTime is not worse than 2x average, penalize if it is worse
  * `if (blockTime < 2 * avgBlockTime) score += avgBlockTime / blockTime;` 
  * `else score -= blockTime / (2 * avgBlockTime);` 
* next block assignment - peer can be assigned blocks within tip + 10 range task only if 
  * if its score is better or equal to median of available peer scores (i.e. do not assign any work we might need quickly to lower half of peers measured by quality)
* all block assignments 
  * better score = better chance to get work (as it is now)
  * peer with a lot of work has smaller chance of getting more work (prevent putting too much pressure on a single peer) - inverse quadratic relation

@dangershony comments pls?

**Comment by Aprogiena** [comment]
What I think is missing in that new alg is situation when a good peer stops working properly (i.e. it is very good, very fast and suddenly stops to be). That case should be handled somehow and there is currently nothing for it.

**Comment by Aprogiena** [comment]
Rethinking my last comment - if the very good peer stops to be good, it will either be disconnected (total failure) or will deliver its current assignments late (just slowdown), in which case it will be penalized. It is true that meanwhile it will receive more tasks, but possibly this is OK imperfection of the alg.

**Comment by Aprogiena** [comment]
And I will try to improve the alg by considering size of the block - i.e. not just raw time but time/size.

**Comment by dangershony** [comment]
Ah good point calculating the download time plus the size of the block is important.

```Dictionary<BlockPullerBehavior, Dictionary<uint256, DownloadTask>>``` sounds good

What about not using a virtual score, but the score can be a calculation of kb/sec of last 100 blocks.
And when assigning work sort based on averages as weight and best peers get more and closest blocks bad peers get less and further away blocks:

#### 3 peers:
- A - 100 kb/s
- B - 400 kb/s
- C - 1500 kb/s

Weight of B is 75% =>  B/(A+B+C)*100=75

#### Distribute has 10 blocks (100-110)
- C (75%) => first 7 best blocks (100-106)
- B (20%) => next 2 blocks (107-109)
- A (5%) => last block (110)

Interesting idea on the special next block penalty, that will reduce score.

**Comment by Aprogiena** [comment]
Yes, I've already implemented everything from my proposal with just couple of changes:
- minimal score is 1 again for technical reasons
- i'm probably looking for setting maximal score to 150 again, but leaving default score to 50
- **i have implemented kb/ms scoring** - so it is not about time of block anymore in all the calculations, but average "time per kb" vs the current peer's block's "timer per kb"
- but it is still kind of virtual score in a sense that there are those penalties (-1 for missed 100ms timeout on the very next block) and the reward/penalty system is as mentioned when the block arrives

the non-random distribution that you suggest suffer from the problem when node C goes down / starts to be not that good - in that case you will miss all the "next work" instead of just "the very next work", so i'm not sure about that part - i think what i have now works little better in this edge case, when within those next 7 blocks, we will have something done even if C dies (and has the very next block assigned)

the only thing I don't have yet is "next block assignment" part from my alg above because i was unable to get the information about consensus height

**Comment by Aprogiena** [comment]
@dangershony I've thought about it again and I like your proposal except for the problem I've mentioned, so that lead me to a new idea, which is brilliant in that it kind of combines your idea with my idea, does not suffer from the problem AND does not need ChainState! 

The idea is that within the work to be assigned, I'll use the "median or better" quality limit for assignment of bottom half of the requested blocks. So whatever the chain height is, if the method is about to distribute work for blocks 100-110, blocks 100-105 will not be assigned to a node with worse than median quality.

**Comment by dangershony** [comment]
Sounds good to me, one more thing about the issue, if node C goes down all the pending vectors will be redistributed so that's not an issue, the issue is if node C goes down in quality while in flight, if it suddenly goes form 100kb/ms to 50kb/ms  then the download will stall but maybe only for that round as it will be reflected in the avg (I think)

**Comment by Aprogiena** [comment]
yes exactly, but it would still work better than the previous version, so maybe "good enough"
