### ISSUE TITLE
[Mining] stakeValidator.CheckKernel should use return codes, not exceptions (stops API from responding)

### ISSUE THREAD

**Issue by sondreb** [stratisproject/StratisBitcoinFullNode#2473]
The current implementation of CheckKernel relies on exceptions for normal processing, and not return codes. It is throwing a huge amount of exceptions when processing. It does this so much, that the API ends up becoming unresponsive for the wallet. The API starts throwing errors short time after enabling staking.

Changing the implementation of CheckKernel to return status codes (int), fixes the issues. I have tested for a few minutes, and the API responds with no issues in less than 100 ms for most requests.

With exceptions being thrown in this method, then requests starts taking 3+ seconds and fails.

Here is network log, showing what happens during the kernel execution:

![image](https://user-images.githubusercontent.com/309938/46841236-07eda180-cdc7-11e8-99e2-75a88f9ca988.png)

And sometimes it is total stop:

![image](https://user-images.githubusercontent.com/309938/46841340-8cd8bb00-cdc7-11e8-8452-526e1e46c11f.png)

Individual loop for each of the 30 threads that is spawned for POS "mining", is reduced from 6692346-185683984 ticks to only 20-5000 ticks. Huge performance increase by not relying on exceptions for normal processing (it checks for a specific exception and then continues to process the loop).

My suggestion is to do something similar to:

var result = this.stakeValidator.CheckKernel(contextInformation, chainTip, block.Header.Bits, txTime, prevoutStake);

And have CheckKernel return status code (integer) for the various steps in the validation.

Discovered this when I was attempting to debug why staking (not on Stratis network) wouldn't work properly, and I kept getting errors from the API whenever staking was enabled.

The CheckKernel is processed to the very end, this is where it "fails":

```
// Now check if proof-of-stake hash meets target protocol.
var hashProofOfStakeTarget = new BigInteger(1, context.HashProofOfStake.ToBytes(false));
if (hashProofOfStakeTarget.CompareTo(weightedTarget) > 0)
{
    this.logger.LogTrace("(-)[TARGET_MISSED]");
    ConsensusErrors.StakeHashInvalidTarget.Throw();
```
The wallet has more than 700 transactions which is part of the staking.

**Comment by sondreb** [comment]
Could also be a simple boolean return value, as it is only a single exception type that performs continue, the others are exceptions and should probably just be?

**Comment by sondreb** [comment]
Performed some performance logging, the following snippet is what I timed a difference between boolean return value, and exception:

```C#
var workersResult = new CoinstakeWorkerResult();
for (int workerIndex = 0; workerIndex < workerCount; workerIndex++)
{
    var cwc = new CoinstakeWorkerContext
    {
        Index = workerIndex,
        Logger = this.loggerFactory.CreateLogger(this.GetType().FullName, $"[Worker #{workerIndex}] "),
        utxoStakeDescriptions = new List<UtxoStakeDescription>(),
        CoinstakeContext = coinstakeContext,
        Result = workersResult
    };

    int stakingUtxoCount = Math.Min(stakingUtxoDescriptions.Count - coinIndex, UtxoStakeDescriptionsPerCoinstakeWorker);
    cwc.utxoStakeDescriptions.AddRange(stakingUtxoDescriptions.GetRange(coinIndex, stakingUtxoCount));
    coinIndex += stakingUtxoCount;
    workerContexts[workerIndex] = cwc;

    workers[workerIndex] = Task.Run(() => this.CoinstakeWorker(cwc, chainTip, block, minimalAllowedTime, searchInterval));
}

await Task.WhenAll(workers).ConfigureAwait(false);
```

Handling exception:
14,694 ms
45,503 ms
36,132 ms
28,956 ms

Handling return value:
8,782 ms
429 ms
170 ms
3,032 ms
154 ms
145 ms

This is on my Core i-7 8700K, 16GB RAM, M.2 SSD PC, so numbers should be a lot higher on smaller devices, if for example someone wants to stake on Raspberry Pi or lowlevel/cheap cloud VM.

**Comment by dangershony** [comment]
Interesting idea, normally on the consensus path stake is valid so no perf issue but in stake path perhaps

**Comment by sondreb** [comment]
I don't know for sure, but from debugging I don't think that the minting process actually does any more attempts even if it runs faster. Nonce is not used, instead it's a combination of transaction inputs and time values that are random inputs for block generation, or what?

When the difficulty is high then (due to POW making it high), it might not be able to easily find POS blocks by minting, and searchInterval is calculated perhaps too low to perform enough attempts?

Without changing the return value of CheckKernel, to use boolean return value, the CPU will spike for a short time each time it attempts to find a new block.

![image](https://user-images.githubusercontent.com/309938/47272274-898dbe00-d583-11e8-93d7-bca3e73c9a35.png)

**Comment by dangershony** [comment]
Ok that's a good reason to do it already.
Can you share your PR lets give it a look.
