### ISSUE TITLE
Using Fody to inject Null guards into constructor

### ISSUE THREAD

**Issue by MithrilMan** [stratisproject/StratisBitcoinFullNode#2477]
Since we are already using Fody, could be nice to add automatically Guards on our classes that uses DI (using an attribute), so we can rid of all those Guard.NotNull and to have implemented Guards on classes we didn't used Guard at all.

See #2249 for the Fody issue about logging

**Comment by maciejzaleski** [comment]
Migrated to: https://dev.azure.com/Stratisplatformuk/StratisBitcoinFullNode/_workitems/edit/3058
