### ISSUE TITLE
[MemPool] Orphaned transaction stays in mempool

### ISSUE THREAD

**Issue by ArcSin2000X** [stratisproject/StratisBitcoinFullNode#2481]
Context: Have 2 nodes connected: NodeA running C# and NodeB running StratisX. Mining is switched off

1) I send 1 transaction from NodeA to NodeB that is rejected by mempool on NodeB:

ERROR: ConnectInputs() : tried to spend coinbase at depth 9
ERROR: AcceptToMemoryPool : ConnectInputs failed 

2) I send 1 transaction from NodeA to NodeB that is rejected by mempool on NodeB:

ERROR: FetchInputs() : 679b1dda04ee19dbe1433bdd26b7ab42c3d5028873d4e2f602c3915dcee4e43c mempool Tx prev not found bb60c6f14bd0910b9d98a81181aaacd1dbe6d6c8f5cf5a66d1f32601a60b1d19

3) Both transactions are present on NodeA. If I try and generate 1 block on NodeA invoking API call to generate I get: 
{
  "errors": [
    {
      "status": 400,
      "message": "Object reference not set to an instance of an object.",
      "description": "System.NullReferenceException: Object reference not set to an instance of an object.\n   at Stratis.Bitcoin.Features.Miner.PowMining.ConsensusIsAtTip(MineBlockContext context) in C:\\Dev\\InternalTestnet\\tmp\\StratisBitcoinFullNode\\src\\Stratis.Bitcoin.Features.Miner\\PowMining.cs:line 191\n   at Stratis.Bitcoin.Features.Miner.PowMining.GenerateBlocks(ReserveScript reserveScript, UInt64 amountOfBlocksToMine, UInt64 maxTries) in C:\\Dev\\InternalTestnet\\tmp\\StratisBitcoinFullNode\\src\\Stratis.Bitcoin.Features.Miner\\PowMining.cs:line 165\n   at Stratis.Bitcoin.Features.Miner.Controllers.MiningController.Generate(MiningRequest request) in C:\\Dev\\InternalTestnet\\tmp\\StratisBitcoinFullNode\\src\\Stratis.Bitcoin.Features.Miner\\Controllers\\MiningController.cs:line 85"
    }
  ]
}

**Comment by bokobza** [comment]
1. `ERROR: ConnectInputs() : tried to spend coinbase at depth 9` indicates to me that the C# node has sent some immature coins to the QT node. 
As it happens, we have a PR waiting to fix this: https://github.com/stratisproject/StratisBitcoinFullNode/pull/2487

2. `mempool Tx prev not found ` means that the QT received a transaction that is spending inputs it doesn't know. Which is ok,maybe he hasn't received them in a previous block?

3. Can you reproduce this? @ArcSin2000X

**Comment by bokobza** [comment]
This is ready to be retested. I believe the fix is in https://github.com/stratisproject/StratisBitcoinFullNode/pull/2487

**Comment by ArcSin2000X** [comment]
doesnt seem to be a problem anymore
