### ISSUE TITLE
DBreezeCoinView performance improvement

### ISSUE THREAD

**Issue by MithrilMan** [stratisproject/StratisBitcoinFullNode#2483]
Ok, let's start linking the DBreeze documentation: https://github.com/hhblaze/DBreeze/blob/master/Documentation/_DBreeze.Documentation.actual.pdf

and the DBreezeCoinView class
https://github.com/stratisproject/StratisBitcoinFullNode/blob/master/src/Stratis.Bitcoin.Features.Consensus/CoinViews/DBreezeCoinView.cs

Subject of the issue is how SaveChangeAsync is implemented.
I was trying to sync bitcoin chain, I've a super connection so I can download blocks very fast and so download speed isn't an issue.
What i was noticing was that my Consensus.Height was progressing veeeery slow, 1 block every few minutes

Digging into it, I saw that the bottleneck was the SaveChangeAsync that was taking too much (note that I'm not using an SSD for this sync)

I started to tweak from this line
https://github.com/stratisproject/StratisBitcoinFullNode/blob/22abd08c3dfc624f0c60c06cba887da78b43ce05/src/Stratis.Bitcoin.Features.Consensus/CoinViews/DBreezeCoinView.cs#L203

where the comment reason was "nobody knows what this do".
Well, actually looking at the documentation you can guess something

> 20130529 - Speeding up batch modifications (updates, random inserts) with
> Technical_SetTable_OverwriteIsNotAllowed instruction

> We CAN SEE SPEED DEGRADE, when ​we update batch of values or data-blocks or if we
> insert a batch of keys in random order and, especially, if these keys have high entropy.
> For such cases we have integrated new methods for transactions and for nested tables:
> tran.Technical_SetTable_OverwriteIsNotAllowed(”t1”);
> or
> var tblABC = tran.InsertTable<byte[]>(“masterTable”, new byte[] { 1 }, 0);
> tblABC .Technical_SetTable_OverwriteIsNotAllowed();
> - This technique is interesting for the transactions with specific batch modifications,
> where speed really matters. Only developer can answer this question and find a
> balance.
> - This technique is not interesting for the memory based data stores.
> - These methods work only inside of one transaction and must be called for every
> table or nested table separately, before table modification command.
> - When new transaction starts, overwrite automatically will be allowed again for all
> tables and nested tables.
> - Overwriting concerns all: search trie nodes, values and data blocks.
> - Remember always to sort batch ascending by key, before insert - it will economize
> HDD space.
> Of course this technique makes data file bigger, but it returns the desired speed. All data
> which could be overwritten will be written to the end of the file.
> Note
> When Technical_SetTable_OverwriteIsNotAllowed​ is used, InsertPart ​still tries to update
> values, that can bring to speed loss. If we need the speed while update, we can use such
> workaround​:
> ● don't use InsertPart, only Insert
> ● read the whole value into memory as byte[]
> ● then change its middle part (with DBreeze.Utils.BytesProcessing CopyInside or
> CopyInsideArrayCanGrow)
> ● insert the complete value.
> ● All the time Technical_SetTable_OverwriteIsNotAllowed​ can be on.

So I re-enabled that line.

Second aspect is about how DBreeze is optimized for inserting records with ordered keys (ascending)
There was already an attempt on that, in the starting part of this loop
https://github.com/stratisproject/StratisBitcoinFullNode/blob/22abd08c3dfc624f0c60c06cba887da78b43ce05/src/Stratis.Bitcoin.Features.Consensus/CoinViews/DBreezeCoinView.cs#L216-L225

The problem I see is that it's mixing Insert with Remove and I think this could cause speedup issues.
On top of that I noticed that LogTrace were using conditional operator `?` querying for IsPrune twice everytime and actually executing those instruction even when logs were disabled.

My solution has been to split that list in prunable and not, and sorting them like this
```
var toRemove = all.Where(utxo => utxo.IsPrunable == true).ToList();
toRemove.Sort(UnspentOutputsComparer.Instance);

var toInsert = all.Where(utxo => utxo.IsPrunable == false).ToList();
toInsert.Sort(UnspentOutputsComparer.Instance);
```
and simplifying logs

**Comment by MithrilMan** [comment]
something worthy to try out is referenced by this "new" feature we are not using

> [20170319]
> RandomKeySorter
> Starting from ver. 1.84, instance of the transaction contains instantiated class
> RandomKeySorter. It can be very handy in case of batch insert of random keys ​or batch
> update of random keys​ with the flag “Technical_SetTable_OverwriteIsNotAllowed​()”.
> Huge speed increase and space economy can be achieved in such scenarios. We have
> earlier many times discussed that DBreeze is sharpened for the insert of sorted keys within
> huge batch operations, so here there is a useful wrapper.

that should take care of reordering issue itself.


Another aspect that we have to investigate and need an implementation is about table shrinking, because DBreeze remove is only logical, so the db size will increase over time.

**Comment by MithrilMan** [comment]
Performance results on my system are these:
Prior to the changes I had logs like this

> ======DBreezeCoinView Bench======
> Insert speed:       3,8825 ms/utxo
> Insert time:        00:03:49.4729856
> Inserted UTXO:      59104

> ======DBreezeCoinView Bench======
> Insert speed:       3,9030 ms/utxo
> Insert time:        00:04:24.8159010
> Inserted UTXO:      67849

After the changes I have
> ======DBreezeCoinView Bench======
> Insert speed:       0,1323 ms/utxo
> Insert time:        00:00:07.1988311
> Inserted UTXO:      54415

> ======DBreezeCoinView Bench======
> Insert speed:       0,1057 ms/utxo
> Insert time:        00:00:05.4095262
> Inserted UTXO:      51188

The improvement is huge, I'd like to confirm this with other sync experience by others.

**Comment by D3m0nKingx** [comment]
@MithrilMan what's your branch I'd like to test it

**Comment by MithrilMan** [comment]
oh just wrote it on discord :D
here it is : https://github.com/mithrilman/StratisBitcoinFullNode/tree/imp/dbreezeCoinView

**Comment by D3m0nKingx** [comment]
## Test on BitcoinD Mainnet:
Hardware: 4-core amd 2.0ghz, HDD, 8GB Ram, Ubuntu 16 64-bit

### Without improvement:
![coinviewinsertspeednoimprov](https://user-images.githubusercontent.com/18432686/46882899-39de2280-ce1e-11e8-867d-34b274b4f34a.png)
![coinviewinsertspeed2noimprov](https://user-images.githubusercontent.com/18432686/46882901-39de2280-ce1e-11e8-93cc-ecb0c4d70e1c.png)

### With improvement:
![coinviewspeedwithimprov2](https://user-images.githubusercontent.com/18432686/46883140-08198b80-ce1f-11e8-9f69-637e83179e60.png)
![coinviewspeedwithimprov](https://user-images.githubusercontent.com/18432686/46883141-08198b80-ce1f-11e8-893c-442fee15eba3.png)

I'd say that's a huge difference! :dancer:  @MithrilMan

**Comment by D3m0nKingx** [comment]
@MithrilMan what blocks were you syncing at when you did the snapshot of those perfs ? Mine were in the beginning around 5k blocks. so it's probably gonna be a different result later in the sync where there's more  transactions.

**Comment by D3m0nKingx** [comment]
One last snapshot:
![image](https://user-images.githubusercontent.com/18432686/46883524-4e231f00-ce20-11e8-9289-0dbafc6a5a87.png)

**Comment by MithrilMan** [comment]
nice it shows an improvement indeed
actually this is my position
> ======Node stats====== 10/12/2018 17:29:01
      Headers.Height:      545485   Headers.Hash:     00000000000000000003c728846371e2a7584a8be4e41709cc590725fc52974e
      Consensus.Height:    339071   Consensus.Hash:   0000000000000000105d15403ad27d5b4c79cd756bb29e8a95a37e6fa151d92b
      BlockStore.Height:   339065   BlockStore.Hash:  0000000000000000042af39e8cee0d07dda8d28e04ed7d14c24ab5a04226fc3d

**Comment by D3m0nKingx** [comment]
@MithrilMan My second set of screenshots above your comment was around 50k blocks. Either way I think we can say this confirms a definite improvement :)

**Comment by fassadlr** [comment]
@MithrilMan I'm closing this as I believe a performance improvement has been since then. You can reopen another issue is VSTS should you wish to further investigate this.
