### ISSUE TITLE
It shouldn't be possible to set up swagger to listen on all public interfaces

### ISSUE THREAD

**Issue by maciejzaleski** [stratisproject/StratisBitcoinFullNode#2506]
The current code allows use of a API bind address which could be accessible over LAN or the Internet.
apiuri=http://0.0.0.0

This should be disallowed as it is dangerous setup for the user.

**Comment by bokobza** [comment]
Maybe we need to have a list of IPs for which we allow access to the api.
Not for this release though.

**Comment by maciejzaleski** [comment]
Miggrated to: https://dev.azure.com/Stratisplatformuk/StratisBitcoinFullNode/_workitems/edit/3057
