### ISSUE TITLE
Adds a bool Sign to the TransactionBuildContext

### ISSUE THREAD

**Issue by bokobza** [stratisproject/StratisBitcoinFullNode#2514]
At the moment, signing of a transaction is done if a password is passed to the TransactionBuildContext.
This should be explicitly stated as sometimes, the password is not passed as it is cached, resulting in the transaction not getting signed.

Related to https://github.com/stratisproject/StratisBitcoinFullNode/pull/2382

**Comment by zeptin** [comment]
Fixed in #2525
