### ISSUE TITLE
Wallet transactions should always be indexed

### ISSUE THREAD

**Issue by maciejzaleski** [stratisproject/StratisBitcoinFullNode#2520]
**Scenario**
- Ensure that the txindex is disabled (default setting `txindex=0`)
- Restore wallet with some existing transactions
- Get a transaction id from the wallet json file which contains transaction with one of the local wallet's address
- Execute `getrawtransaction` API call
- Swagger should return raw transaction data as all wallet transactions should be indexed regardless of the txindex setting

**Comment by zeptin** [comment]
If the `savetrxhex` command line option is not enabled, `getrawtransaction` may not have enough information available to return a meaningful response if `txindex` is similarly disabled.

**Comment by bokobza** [comment]
Why is this a requirement?

**Comment by bokobza** [comment]
@maciejzaleski There is no requirement for the wallet to be able to serve or contain full transaction data.

**Comment by fassadlr** [comment]
@zeptin , @noescape00 mentioned that we should always index transactions that are in our wallet? @noescape00 can you comment?

**Comment by zeptin** [comment]
I think I possibly phrased my comment badly. The block store's transaction index is completely separate to the wallet, and it is from the store that `getrawtranasction` derives info. As Jeremy points out, the wallet does not store full transaction data, and only optionally does so for use cases that require it e.g. Breeze.

**Comment by bokobza** [comment]
yeah, I'm happy to close this.

**Comment by bokobza** [comment]
Just need @maciejzaleski to tell me where the requirement comes from.

**Comment by maciejzaleski** [comment]
Not an issue
