### ISSUE TITLE
Staking flag never set to true 

### ISSUE THREAD

**Issue by bokobza** [stratisproject/StratisBitcoinFullNode#2574]
In the `GetStakingInfoModel` class, the property `bool Staking` is not set to true when the node starts staking.
It's only set to true when staking is resumed.

Repro steps: 
- have a wallet with funds
- start staking 
- check that staking works
- call the api/staking/getstakinginfo endpoint
- see that `enabled` is set to `true` but `staking` is set to `false`.

**Comment by maciejzaleski** [comment]
Resolved
