### ISSUE TITLE
Check that POS is not mining at IBD

### ISSUE THREAD

**Issue by dangershony** [stratisproject/StratisBitcoinFullNode#2581]
Can PoS minting generate a block while in IBD?

we have this pro protect against this kind of things:
```// Prevent mining if not fully synced.
if (this.initialBlockDownloadState.IsInitialBlockDownload() ||
    this.consensusManager.Tip != this.chain.Tip)
{
    this.logger.LogTrace("Waiting for synchronization before mining can be started.");

    await Task.Delay(TimeSpan.FromMilliseconds(this.minerSleep), cancellationToken).ConfigureAwait(false);
    continue;
}
```

but now it's useless since this.consensusManager.Tip will always be the same as this.chain.Tip.

So if we are not in IBD and mined >500 blocks behind header's tip we would announce this block and violate max reorg rule for other nodes. And they will ban us.

**Comment by fassadlr** [comment]
Reopen so that it can be retested.

**Comment by bokobza** [comment]
@thefazzer I was looking at https://github.com/stratisproject/StratisBitcoinFullNode/issues/2666 and I think this now works as expected.
Check my comment here https://github.com/stratisproject/StratisBitcoinFullNode/issues/2666#issuecomment-435946415

@maciejzaleski
