### ISSUE TITLE
PH BlockStoreSignaled

### ISSUE THREAD

**Issue by noescape00** [stratisproject/StratisBitcoinFullNode#2589]
Create PH version of block store signaled class. 
Difference in logic comparing to base class: 
when block is signaled we should check if it's at height after PH activation ad if it is- check if PH is available in PH store. It it's not we should construct PH and put it in store. This logic should be executed before we announce those headers to our peers. 

PH BlockStoreSignaled should be enabled only for PoS networks. 

ps
this logic is needed for cases when we synced blocks using headers acquired from whitelisted QT nodes- for those we don't have proven headers and need to construct them to allow C# nodes sync from us.

**Comment by MithrilMan** [comment]
I'm doing this as per specifics, but what happens if a reorg happens?

**Comment by MithrilMan** [comment]
needed re-design, addressed in https://github.com/stratisproject/StratisBitcoinFullNode/issues/2662.
