### ISSUE TITLE
Command line argument -listen in Stratis node behaves like -bind in Bitcoin Core

### ISSUE THREAD

**Issue by Aprogiena** [stratisproject/StratisBitcoinFullNode#259]
Stratis node uses -listen for what Bitcoin Core uses -bind. Bitcoin Core also defines -listen, but uses it for different thing. 

This is probably not an intention and the parameters should be compatible.

**Comment by bokobza** [comment]
Indeed.
See https://en.bitcoin.it/wiki/Running_Bitcoin
https://trello.com/c/dDJwppji/193-nodesettings-command-line-argument-listen-in-stratis-node-behaves-like-bind-in-bitcoin-core

**Comment by Aprogiena** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[NodeSettings] Command line argument -listen in Stratis node behaves like -bind in Bitcoin Core](https://trello.com/c/dDJwppji/193-nodesettings-command-line-argument-listen-in-stratis-node-behaves-like-bind-in-bitcoin-core)

**Comment by quantumagi** [comment]
The most obvious solution seems to be to change "listen" to "bind" as follows (line 222 of NodeSettings.cs):
```

            try
            {
                nodeSettings.ConnectionManager.Listen.AddRange(config.GetAll("bind")
                        .Select(c => new NodeServerEndpoint(ConvertToEndpoint(c, port), false)));
            }
            catch (FormatException)
            {
                throw new ConfigurationException("Invalid bind parameter");
            }

```
