### ISSUE TITLE
Node is failing to synchronise after a reorg

### ISSUE THREAD

**Issue by maciejzaleski** [stratisproject/StratisBitcoinFullNode#2595]
**Setup**
 - Two nodes are staking NodeDA and NodeDB
 - NodeAD is failing to sync consensus and blockstore.
 - Wallet hash is set to 0000000000000000000000000000000000000000000000000000000000000000

**Full Logs**
https://stratisplatform-my.sharepoint.com/:u:/p/maciej_zaleski/EQzF5PI43ZZArNrpWZZ7_JwBKixJYkSnoEEUFrwvY_KtYg?e=CasADm

```[2018-10-24 10:40:15.4594 36] INFO: Stratis.Bitcoin.FullNode.<StartPeriodicLog>b__76_0 ======Node stats====== 10/24/2018 10:40:15
Headers.Height:      2075     Headers.Hash:     f613bb91a34527471c7f8a696083c6c8c29282efc8b9d5915d584cf71d880c38
Consensus.Height:    2075     Consensus.Hash:   f613bb91a34527471c7f8a696083c6c8c29282efc8b9d5915d584cf71d880c38
BlockStore.Height:   2075     BlockStore.Hash:  f613bb91a34527471c7f8a696083c6c8c29282efc8b9d5915d584cf71d880c38
Wallet.Height:       2075     Wallet.Hash:      f613bb91a34527471c7f8a696083c6c8c29282efc8b9d5915d584cf71d880c38

======Connection====== agent StratisBitcoin:1.2.2
Peer:[::ffff:192.168.98.121]:36249,      connected:inbound,         height:2075,          agent:StratisBitcoin:1.2.2
Peer:[::ffff:192.168.98.190]:45329,      connected:inbound,         height:2066,          agent:StratisBitcoin:1.2.2
Peer:[::ffff:192.168.98.150]:44557,      connected:inbound,         height:2075,          agent:StratisBitcoin:1.2.2
Peer:[::ffff:192.168.98.193]:16178,      connected:outbound,        height:2075,          agent:/Stratis:2.0.0.5/
Peer:[::ffff:192.168.98.102]:42029,      connected:inbound,         height:2070,          agent:StratisBitcoin:1.2.2

======Consensus Manager======
Unconsumed blocks: -178 -- (-114 386 / 209 715 200 bytes). Cache is filled by: -0.05%

======Block Puller======
Blocks being downloaded: 0
Queueued downloads: 0
Average block size: 0.7 KB
Total download speed: 39.75 KB/sec
Average time to download a block: 17.73 ms
Amount of blocks node can download in 1 second: 56.39

======BlockStore======
Batch Size: 0 kb / 5000 kb  (0 blocks)

=======Mempool=======
MempoolSize: 0    DynamicSize: 0 kb   OrphanSize: 0   

======Wallets======
Wallet: Wallet-ADA,          Confirmed balance: 16.80000000          Unconfirmed balance: 0.00000000

[2018-10-24 10:40:20.5321 36] INFO: Stratis.Bitcoin.FullNode.<StartPeriodicLog>b__76_0 ======Node stats====== 10/24/2018 10:40:20
Headers.Height:      2076     Headers.Hash:     5649a86da993f97f62aee0fe69a67079390a35023b3a2e1d2c6a47ec3775660b
Consensus.Height:    1996     Consensus.Hash:   ddf896f89cf3b770ddfec8bc6dbd7c53560b4c9379f8bdfdeb8f08ba414a1d8c
BlockStore.Height:   2075     BlockStore.Hash:  f613bb91a34527471c7f8a696083c6c8c29282efc8b9d5915d584cf71d880c38
Wallet.Height:       2075     Wallet.Hash:      0000000000000000000000000000000000000000000000000000000000000000
```

**Comment by noescape00** [comment]
Ps
I can see CM logging this on critical level, but it's not shown in node.txt
Looks like smth wrong with logging configuration

**Comment by noescape00** [comment]
I've asked @maciejzaleski to disable block data removal and after that bug stopped being reproducible. 
Now I'm convinced that the root of the problem is a bug in CM or CHT that leads to removing block data of the blocks that we still need. 
Also it's connected to having large reorgs. 
Maybe at some point we expect block data to be in a header when in fact we should get it from block store.

**Comment by noescape00** [comment]
I'm convinced that this bug is critical and should be fixed before production release.

**Comment by maciejzaleski** [comment]
Running the InternalTestnet network with the patch yields similar results. I have observed that the network have forked and two nodes got stuck at different heights for header and consensus.

**Comment by dangershony** [comment]
Yes @noescape00 fix was missing to set the chained header validation status to headers only, so this will trigger a redownload of the whole missing branch and in that include the blocks that are passed 100 in height. its not the ideal solution but fasted to implement.
Ideally we would have a store of blocks that are not part of the main chain we can put temporary store blocks above the 500 max reorg

**Comment by maciejzaleski** [comment]
I have retested this making sure that I merge the master with PR #2612 and #2627 and there is still a reorg issue.

**Comment by maciejzaleski** [comment]
This has been partial fixed, new issues will be opened for other cases when this problem occur.
