### ISSUE TITLE
Node stopped advancing 

### ISSUE THREAD

**Issue by dangershony** [stratisproject/StratisBitcoinFullNode#2625]
@StratisIain got some failures on his nod this issue will track it

**Comment by StratisIain** [comment]
https://stratisplatform-my.sharepoint.com/:f:/p/iain_mccain/EqybdlQkPaZAuqVU2WJuZbEBJIRm9_U7aRzB7reTWr0WgA?e=fhJ1C5

**Comment by sondreb** [comment]
This might be the same I'm seeing, I was testing the latest changes and it appears that the node does not sync, even with new blocks found on the network. If I shut down and start back up, it syncs, and a few times it has updated, but I can confirm that it is stopping a lot and simply not getting latest blocks. Might be related to recent changes in the broadcast manager? My local node is the only one on latest code base, all other nodes run a week or two older code.

**Comment by fassadlr** [comment]
@StratisIain has reported that this issue is no longer happening.

This was fixed in #2645
