### ISSUE TITLE
UTXO low coin age is off by 1

### ISSUE THREAD

**Issue by sondreb** [stratisproject/StratisBitcoinFullNode#2653]
The method **GetUtxoStakeDescriptionsSuitableForStakingAsync** will return UTXO at 49, if PosConsensusOptions is set to 50.

Code that accepts the UTXO:

```C#
if (depth < requiredDepth)
{
    this.logger.LogTrace("UTXO '{0}' depth {1} is lower than required minimum depth {2}.", utxoStakeDescription.OutPoint, depth, requiredDepth);
    continue;
}
```

This is passed, but later in the CheckKernel, the following validation fails:

```C#
UnspentOutputs prevUtxo = coins.UnspentOutputs[0];
if (this.IsConfirmedInNPrevBlocks(prevUtxo, prevChainedHeader, ((PosConsensusOptions)this.network.Consensus.Options).GetStakeMinConfirmations(prevChainedHeader.Height + 1, this.network) - 1))
{
     this.logger.LogTrace("(-)[LOW_COIN_AGE]");
     ConsensusErrors.InvalidStakeDepth.Throw();
}
```

The problem here is the IsConfirmedInNPrevBlocks method, which calculates the actualDepth to be 48, not 49, which was the input of the 3rd parameter to this method:

```C#
public bool IsConfirmedInNPrevBlocks(UnspentOutputs coins, ChainedHeader referenceChainedHeader, long targetDepth)
{
    int actualDepth = referenceChainedHeader.Height - (int)coins.Height;
    bool res = actualDepth < targetDepth;

    return res;
}
```

As soon as 1 more block is found, then IsConfirmedInNPrevBlocks will return false and the supplied UTXO for staking is approved.

Not a major issue,  but should be correct I think to avoid exceptions that doesn't need to happen.

**Comment by dangershony** [comment]
Yeah seems like a bug

**Comment by dangershony** [comment]
This should also probably come with a set of tests (if not already exist)

**Comment by maciejzaleski** [comment]
Reviewed by @noescape00 

> Checked it. Looks like there is no bug. "the following validation fails" - code referenced after this line doesn't exist anymore and therefore exception that was the reason for raising this issue can't occur anymore.
