### ISSUE TITLE
Use Checkpoints instead of ProvenHeadersActivationHeight

### ISSUE THREAD

**Issue by MithrilMan** [stratisproject/StratisBitcoinFullNode#2662]
After lot of discussions and design changes we agreed on activating Proven Header since genesis.
This mean we'll store PH for every block and we are able to serve PH at any height.

To speedup IBD, we are going to use CheckPoints when available, and we are synching in the legacy way with normal headers and bypassing some validation rules.

In case a peer supports Checkpoints, Last Checkpoint act as previous ProvenHeadersActivationHeight in the sense that since that height it accepts only Proven Headers.

The required changes are to remove all occurrance of ProvenHeadersActivationHeight using Checkpoints  instead.

**Comment by MithrilMan** [comment]
Memorandum:
- remove all occurrance of ProvenHeadersActivationHeight using Checkpoints instead
- improve `ProvenBlockHeaderRepository` to handle reorgs
- convert the header of any legacy blocks received pre-checkpoint into ph header and store it

**Comment by dangershony** [comment]
This is now tracked here https://github.com/stratisproject/StratisBitcoinFullNode/issues/2464
