### ISSUE TITLE
Blocks are staked when the node is not synchronised

### ISSUE THREAD

**Issue by maciejzaleski** [stratisproject/StratisBitcoinFullNode#2666]
The node is staking while it is not fully synchronised. Header height is higher than consensus height.

Node data and logs: https://stratisplatform-my.sharepoint.com/:u:/p/maciej_zaleski/EaPeS6Ewj8tEtUCTFyeBJrEBH_YnbEJZ_PWYaa4PlisV6A?e=vS79va

```[2018-11-03 02:45:42.5200 107] INFO: Stratis.Bitcoin.Features.Miner.Staking.PosMinting+<CheckStakeAsync>d__41.MoveNext ==================================================================
[2018-11-03 02:45:42.5713 107] INFO: Stratis.Bitcoin.Features.Miner.Staking.PosMinting+<CheckStakeAsync>d__41.MoveNext Found new POS block hash 'bc3a59ca21e3e7fd830d33b1abcbd086fd4d20d134cfc472ef1997dd96e08f0f' at height 2813.
[2018-11-03 02:45:42.6539 107] INFO: Stratis.Bitcoin.Features.Miner.Staking.PosMinting+<CheckStakeAsync>d__41.MoveNext ==================================================================
[2018-11-03 02:45:43.4200 13] INFO: Stratis.Bitcoin.FullNode.<StartPeriodicLog>b__76_0 ======Node stats====== 11/03/2018 02:45:43
Headers.Height:      2900     Headers.Hash:     eaa8e89b816b1749e09d052cf294d41be4ebd6980456beef050438874aaad055
Consensus.Height:    2813     Consensus.Hash:   bc3a59ca21e3e7fd830d33b1abcbd086fd4d20d134cfc472ef1997dd96e08f0f
BlockStore.Height:   2811     BlockStore.Hash:  8fd2d4ce02f8d9b7cbe26dd4a47f4379eba8be6786b6d59960190e2e17188f41
Wallet.Height:       2813     Wallet.Hash:      bc3a59ca21e3e7fd830d33b1abcbd086fd4d20d134cfc472ef1997dd96e08f0f```

**Comment by bokobza** [comment]
I don't think this is a problem.
The worst case scenario is that a miner mines a block, that gets reorged.
For this to even happen, the miner needs to have such staking power that he mines a block between the time the node decides it's not in IBD and the last block. With IBD being determined at 2 hours, the miner needs to find a block in less time it would take it to download ~120 blocks.

**Comment by maciejzaleski** [comment]
Agreed with @bokobza and following discussion with @dangershony. It wouldn't be good to implement rule to stop staking every time Consensus < Headers because that would create a vulnerability.
