### ISSUE TITLE
Wallet is not reorging correctly

### ISSUE THREAD

**Issue by ArcSin2000X** [stratisproject/StratisBitcoinFullNode#2676]
**Description:** 
When running internal testnet we have NodeFD not being able to advance Consensus, Blockstore and Wallet to the tip of the Header, node will never go above height 1845.
Node wallet hash becomes `0000000000000000000000000000000000000000000000000000000000000000`

`[2018-11-03 17:01:28.3594 21] INFO: Stratis.Bitcoin.Consensus.ConsensusManager+<RewindToForkPointAsync>d__50.MoveNext Reorg from block '1845-29265ba908294d9b6f88857147e910fe159db44fffd16dfd3dbfe5bb4967f7f2-FullyValidated' to '1839-0100b52070436df710ce133a86f73c6fdba67c955fd7fdbe73506220f0a9360c-FullyValidated'
[2018-11-03 17:01:28.3891 22] INFO: Stratis.Bitcoin.Features.Miner.Staking.PosMinting+<CreateCoinstakeAsync>d__43.MoveNext Node staking with 3293794.15820313 (120.27 % of the network weight 2738675.44907665), est. time to find new block is 00:00:53.
[2018-11-03 17:01:28.9692 27] INFO: Stratis.Bitcoin.FullNode.<StartPeriodicLog>b__76_0 ======Node stats====== 11/03/2018 17:01:28
Headers.Height:      1846     Headers.Hash:     1fa1c6e450d648461e2682b3318c7d9513f5003c25e8dd6ae1c96f6c3eacc912
Consensus.Height:    1839     Consensus.Hash:   0100b52070436df710ce133a86f73c6fdba67c955fd7fdbe73506220f0a9360c
BlockStore.Height:   1845     BlockStore.Hash:  29265ba908294d9b6f88857147e910fe159db44fffd16dfd3dbfe5bb4967f7f2
Wallet.Height:       1845     Wallet.Hash:      0000000000000000000000000000000000000000000000000000000000000000`

if I try and find all where search string == `Wallet.Height:` i get
`Wallet.Height:       1841     Wallet.Hash:      f320de68748d6fad97fda602f889780366620c639454df79ad3635149f16f483
Wallet.Height:       1841     Wallet.Hash:      f320de68748d6fad97fda602f889780366620c639454df79ad3635149f16f483
Wallet.Height:       1841     Wallet.Hash:      f320de68748d6fad97fda602f889780366620c639454df79ad3635149f16f483
Wallet.Height:       1842     Wallet.Hash:      7fec0a355d6b57f69c2109a96831737262696a0fcf40ff2e705f92f05859ef92
Wallet.Height:       1842     Wallet.Hash:      7fec0a355d6b57f69c2109a96831737262696a0fcf40ff2e705f92f05859ef92
Wallet.Height:       1842     Wallet.Hash:      7fec0a355d6b57f69c2109a96831737262696a0fcf40ff2e705f92f05859ef92
Wallet.Height:       1842     Wallet.Hash:      0000000000000000000000000000000000000000000000000000000000000000
Wallet.Height:       1843     Wallet.Hash:      c51f3cb5f91234eee061224836f84b6e558f3c2990086a3cbf2d8cc49c8681ac
Wallet.Height:       1843     Wallet.Hash:      c51f3cb5f91234eee061224836f84b6e558f3c2990086a3cbf2d8cc49c8681ac
Wallet.Height:       1843     Wallet.Hash:      c51f3cb5f91234eee061224836f84b6e558f3c2990086a3cbf2d8cc49c8681ac
Wallet.Height:       1844     Wallet.Hash:      f2f38a3420551b55627ac522eb593ccf84e70d050f1557214bdca0408f65ce0b
Wallet.Height:       1844     Wallet.Hash:      f2f38a3420551b55627ac522eb593ccf84e70d050f1557214bdca0408f65ce0b
Wallet.Height:       1844     Wallet.Hash:      f2f38a3420551b55627ac522eb593ccf84e70d050f1557214bdca0408f65ce0b
Wallet.Height:       1845     Wallet.Hash:      29265ba908294d9b6f88857147e910fe159db44fffd16dfd3dbfe5bb4967f7f2
Wallet.Height:       1845     Wallet.Hash:      0000000000000000000000000000000000000000000000000000000000000000
Wallet.Height:       1845     Wallet.Hash:      0000000000000000000000000000000000000000000000000000000000000000
Wallet.Height:       1845     Wallet.Hash:      0000000000000000000000000000000000000000000000000000000000000000
Wallet.Height:       1845     Wallet.Hash:      0000000000000000000000000000000000000000000000000000000000000000
Wallet.Height:       1845     Wallet.Hash:      0000000000000000000000000000000000000000000000000000000000000000
Wallet.Height:       1845     Wallet.Hash:      0000000000000000000000000000000000000000000000000000000000000000
Wallet.Height:       1845     Wallet.Hash:      0000000000000000000000000000000000000000000000000000000000000000
Wallet.Height:       1845     Wallet.Hash:      0000000000000000000000000000000000000000000000000000000000000000`

**Comment by maciejzaleski** [comment]
This problem has not reoccurred and can be closed due to it not not being reproducible.
