### ISSUE TITLE
Migrate logging to NLog 

### ISSUE THREAD

**Issue by Aprogiena** [stratisproject/StratisBitcoinFullNode#271]
There is a lot of complex code in the project and sometimes it is hard to analyze problems. This can be very much solved with detailed logging system. I have many years of experience with NLog and it offers some great features that fit the bill that we are unsure how to do in Serilog that we currently use. 

Thus I'd like to suggest migration to NLog for logging, which will allow me to install detailed logs in very sensitive and complex code - like puller, coin views, memory pool, block store, etc. 

One of the objections for block puller is that there are no tests to cover the complex code of this part of the code. However, it is very difficult to creates tests after the code is written and deployed for a significant amount of time. Even if we create a large number of tests for block puller, we will certainly not cover all possibilities and code paths that can occur. This is where logging is so powerful. 

All we need is to install detailed logs in these complex parts and when there is something weird, we just need to analyze the log. This assumes that developers will be testing their code mostly with detailed logging enabled even for the parts that are currently not working with. We can achieve this by using configuration file for NLog that will not make it into the production release and the logging of the release would be normally directed by command line options and node config file.

**Comment by bokobza** [comment]
Sounds good.
Could we also decide to have only logs enabled for the part of the code we're working on?
Say I'm working on the mining bit and I don't want to see the block puller's logs or any other's, is it possible?
Also can we set log levels? So for example when we debug we enable all logs from 'debug' upwards by default and then in released apps we use 'info' upwards.

**Comment by Aprogiena** [comment]
There is a huge benefit of having detailed logging enabled for everything because if a bug occurs randomly in one of 100 instances and you are just lucky to get it while you are working on something else, you have the most precious log file of the week and you can share it.

Having said that, it is completely understandable that you want logs to reflect the part of the code that you are working on. And that is absolutely no problem to have - you will simply have 2 log files. One will contain all the stuff and you might not be interested in reading that, and the other will contain just those parts that you want. Here again we would have a great use of the NLog's configuration file - when you want to work on something and have a log limited to that, you make a local modification to your NLog.config so that you have a special file created for what you are working on. This can include multiple classes on different logging levels.

Together with this, it might be interesting to consider splitting Console output and logging completely. Although this does sometime create code like 

```
  Console.WriteLine(something);
  this.logger.Info(something);
```

it prevents mixing things that should not be mixed. And often you don't really want **exactly** the same thing to go to the output for the user as it goes to the log file. We can also create a wrapper around Console, not to access it directly.

**Comment by bokobza** [comment]
Having a log file with everything and others that are more focused would be the absolute 💣 . That'd be awesome.
Console.WriteLine(something);
  this.logger.Info(something);
Don't really like that. Maybe we could have different levels. Console would show "Information" up, while logging would do something else.

**Comment by Aprogiena** [comment]
As for splitting - I just find it better after many years of doing just that - using Info level for console output. It is occasionally problematic. The main problem with that and probably the primary reason for the separation for me, is that the log levels are usually (they are in case of NLog) constructed like this:

Fatal > Error > Warn > Info > Debug > Trace

And many times I wanted Warnings not to shown to the users and some times even Errors should not go to user. So what you usually do is "Info or higher goes to console", which is where you have this problem. So then you can say "only Info goes to console, not Warn or Error", but then for many Errors and Warnings you want them to go to the console. So then you end with logging Errors on Info level or I don't know :)

For example, as I described elsewhere, I don't think user should see exceptions (esp. with stack trace). And so on which level do you log bad exceptions? 

So for that reason I'd like the split. But it is still possible to not having a split, it just leads to users seeing stuff that I don't think they should see. If we are OK with that then OK. I tend to prefer user output to be carefully constructed, while logs to contain as much info as possible.

**Comment by bokobza** [comment]
Good point. Logs are tricky to get just right, but in our case I think we're ok, here's why:
Normal users won't see any console at all when they run the wallet, or even when we have a UI for the Full Node. The console is shown only when running our daemons directly, in which case you're probably doing dev work. So these console logs will be useful during dev because you can see (and read) things that are happening within the app. 
Full logging will go to a file no problem.

> Fatal > Error > Warn > Info > Debug > Trace

I think that's the general convention

**Comment by Aprogiena** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[Logging] Migrate to NLog](https://trello.com/c/SeSlhXac/146-logging-migrate-to-nlog)

**Comment by dangershony** [comment]
How will the migration to NLog work? is it similar to serilog where you just ad an extension to the ILogerFactory?

**Comment by Aprogiena** [comment]
I've worked on that over the weekend and it will be very smooth. You will **almost** not see any difference.

**Comment by Aprogiena** [comment]
Here is the renewed mapping:
```
            var keyToCategory = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
            {
                //{ "addrman", "" },
                //{ "alert", "" },
                { "bench", "Stratis.Bitcoin.Features.Consensus.ConsensusStats" },
                //{ "coindb", "" },
                { "db", "Stratis.Bitcoin.Features.BlockStore.*" }, 
                //{ "lock", "" }, 
                //{ "rand", "" }, 
                { "rpc", "Stratis.Bitcoin.Features.RPC.*" }, 
                //{ "selectcoins", "" }, 
                { "mempool", "Stratis.Bitcoin.Features.MemoryPool.*" }, 
                //{ "mempoolrej", "" }, 
                { "net", "Stratis.Bitcoin.Connection.*" }, 
                //{ "proxy", "" }, 
                //{ "prune", "" }, 
                //{ "http", "" }, 
                //{ "libevent", "" }, 
                //{ "tor", "" }, 
                //{ "zmq", "" }, 
                //{ "qt", "" },
                
                // Short Names
                { "estimatefee", "Stratis.Bitcoin.Features.MemoryPool.Fee.*" },
                { "configuration", "Stratis.Bitcoin.Configuration" },
                { "fullnode", "Stratis.Bitcoin.FullNode" },
                { "consensus", "Stratis.Bitcoin.FullNode" },
                { "mining", "Stratis.Bitcoin.FullNode" },
                { "wallet", "Stratis.Bitcoin.Wallet" },
            };
```

I haven't checked that the keys are all that Core has, I would assume so. 

My question here is - of those empty (commented) key-values, do we have any that we can add? I thought about addrman for example, but I can see that is part of NBitcoin, so that won't work I guess :/  Anything else?

**Comment by Aprogiena** [comment]
Also should "mining" really map to "Stratis.Bitcoin.FullNode"?

**Comment by dangershony** [comment]
Yeah this are clearly wrong
                { "consensus", "Stratis.Bitcoin.FullNode" },
                { "mining", "Stratis.Bitcoin.FullNode" },
I think eventually we will refactor/pull the addrman from NBitcoin and then it will get its own log key

**Comment by Aprogiena** [comment]
Yes and there seems to be couple of classes that accept ILogger instead of ILoggerFactory, which basically disables you to log just those end classes. I'm fixing this just for the classes that I am mapping to - like ConsensusStats, but it should be general rule to always pass factory and not just logger. 

If you pass just ILogger, it probably means your idea was that this logger "covers" the whole bunch of classes, but that is NLog's job to do, not yours. (I'm saying you/yours, but I don't mean you specifically :))

**Comment by Aprogiena** [comment]
This has been done, we probably want to implement prefix logger, but that is for another issue.
