### ISSUE TITLE
[P2P] sendprovhdr gets sent unconditionally during handshake

### ISSUE THREAD

**Issue by zeptin** [stratisproject/StratisBitcoinFullNode#2727]
The default `ConnectionManagerBehavior` gets overridden with `ProvenHeadersConnectionManagerBehavior` when PoS is being used. This behaviour overrides the default functionality of the method `OnHandshakedAsync`, which would normally instruct the peer to preferentially send headers. The PH version instead tells the peer to send proven headers, which is not valid as the functionality is not active on the network yet.

**Comment by MithrilMan** [comment]
I see it's related to this PR #2609 

I think they forgot to call `base.OnHandshakedAsync` to let the implementation being backward compatible (or just check if the peer supports proven header and send `SendHeadersPayload` if it isn't
