### ISSUE TITLE
Miner Refactor - On BlockAssembler

### ISSUE THREAD

**Issue by dangershony** [stratisproject/StratisBitcoinFullNode#273]
Instead of an assembler that uses inheritance we could create a BlockBuilder
Then to construct a block and find a valid POW/POS block we could have extensions 
Perhaps similar to this:
```
var block = new BlockBuilder()
       .UseNetwork(this.network)
       .CreateBlock()
       .AddTransactions(IMempool)
       .Mine()
       .Validate()
       .Build()

var block = new BlockBuilder()
       .UseNetwork(this.network)
       .CreateBlock()
       .AddTransactions(IMempool)
       .Stake()
       .Validate()
       .Build()
```

**Comment by dangershony** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[Miner] Create a BlockBuilder for mining](https://trello.com/c/jM8bnuFP/34-miner-create-a-blockbuilder-for-mining)

**Comment by bokobza** [comment]
Is this still relevant? @dangershony

**Comment by bokobza** [comment]
Not relevant anymore.
