### ISSUE TITLE
Network fork created when 400 transactions propagated on the network

### ISSUE THREAD

**Issue by ArcSin2000X** [stratisproject/StratisBitcoinFullNode#2734]
I have propagated transactions using attached scripts which led to following network fork
![image](https://user-images.githubusercontent.com/37782512/48314197-ed713880-e5bd-11e8-9de6-ba73b6cfd932.png)
Notably nodes that are not on the chain that includes propagated transactions has mempool count = 45

[PropagationScripts.zip](https://github.com/stratisproject/StratisBitcoinFullNode/files/2569462/PropagationScripts.zip)

**Comment by ArcSin2000X** [comment]
Sequence of events: i first send burst of 100 with staking off on all nodes. Burst was from single node, subsequently I observed all nodes mempool reaching 99 transactions. I switched staking on and all the nodes mempool went to zero. Next thing to do was to push 100 x 3 nodes while staking was switched on which led to fork and transactions staying in mempool

**Comment by maciejzaleski** [comment]
Resolved
