### ISSUE TITLE
Reorgs causing memory leaks in block puller

### ISSUE THREAD

**Issue by Aprogiena** [stratisproject/StratisBitcoinFullNode#274]
LookaheadBlockPuller.PushBlock is called when the block is being delivered in BPB.Node_MessageReceived. Now consider the start of the method:
```
            uint256 hash = block.Header.GetHash();
            ChainedBlock header = this.Chain.GetBlock(hash);
            while (this.currentSize + length >= this.MaxBufferedSize && header.Height != this.location.Height + 1)
```
If we reorged to different chain before the block came, can't we get null header here? So do we rely here on the exception to be consumed by OnMessageReceived try/catch block around handler.DynamicInvoke(this, m);? This is probably OK, although not sure if intentional. But what if reorg happened later, but before this new block is consumed. It seems like it will be added to downloadedBlocks and never consumed. Looks like memory leak and if blocks are full, this means 1MB of memory gone forever, and eventually, if the node is run for a long time, it could sum up.

**Comment by Aprogiena** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[BlockPuller] Reorgs causing memory leaks in block puller](https://trello.com/c/muleLBqt/147-blockpuller-reorgs-causing-memory-leaks-in-block-puller)

**Comment by dangershony** [comment]
I think we only need to clear all 3 dictionaries on reorg that will sort everything, if a block arrives that was asked from a different chain it will be ignored as it will be treated like it was not solicited.

**Comment by Aprogiena** [comment]
+- yes, but it has to be done very carefully, otherwise we can introduce more problems by fixing this.

**Comment by fassadlr** [comment]
Hi @Aprogiena , according to Jeremy you have done a lot of work on Reorg? Do you now if this still an issue?

**Comment by Aprogiena** [comment]
AFAIK, this code has not been touched. The leak should still be present here.

**Comment by dangershony** [comment]
@fassadlr this applies to both the puller (consensus) and store as well.

**Comment by Aprogiena** [comment]
looking at this issue again, i think this can't be solved in `BlockPuller` class because that one has no idea about these reorgs

so he new logic of cleaning has to be implemented at higher level, there are two consumers of `BlockPuller` - `LookaheadBlockPuller` and `StoreBlockPuller`

`LookaheadBlockPuller` will probably be OK on its own to implement such a logic

but `StoreBlockPuller` not, so we have to go level up here again. so it is probably `BlockStoreLoop` and the BS steps classes that have to implement that logic

sounds quite complicated

**Comment by Aprogiena** [comment]
alternatively, but not very elegantly, we could insert a timer into each downloaded block - `DownloadedBlock` class. something like - if no one consumes the block within 5 minutes, the block will remove itself 

that would be very simple to implement, but it is very inelegant solution. would work though :/

**Comment by dangershony** [comment]
Well that would work but we could instead of a time use the reorg events, when a reorg is detected in the LookaheadPuller we can call a method that cleans all the collections, alternatively this can also be called from the ConsensusLoop where we handle the reorg.

Same as Store the step that handles the reorg can clean up the puller.

**Comment by Aprogiena** [comment]
i don't think we have anything like reorg event that would be reliable

**Comment by noescape00** [comment]
fixed by the new puller btw so we may close it already

**Comment by noescape00** [comment]
Fixed with activation merge.
