### ISSUE TITLE
No "address" field in the reply of decoderawtransaction RPC

### ISSUE THREAD

**Issue by xiewenlong1202** [stratisproject/StratisBitcoinFullNode#2748]
Hello there
recently I tried the decoderawtransaction RPC call of the StratisFullNode and in the Vout's "scriptPubKey" field, there is only there parameter value: asm, hex, type
the same call in swagger ui also return similar result
I can't find the "address" filed in the response. But, in the reply of Bitcoind for the same rpc call, the Vout indeed have the "address".

can anybody tell me how to get this field? with additional arguments or calculate it from the returned values?

**Comment by zeptin** [comment]
Whether you get an address field or not depends on the type of transaction you are decoding.

The coinstake transactions in a block (e.g. `10ebe9c14f0a2bacfd361642597b6ab359db7224c61ecb61e239539a583725ab` on testnet) are of the P2PK (pay to pubkey) type. These do not actually have an address.

Investigating further I have found that the block explorer & C++ client (stratisX) create an address by hashing the pubkey. This effectively treats the output as if it was P2PKH (pay to pubkey hash).

See another explanation of the same thing:
https://github.com/bitcoinjs/bitcoinjs-lib/issues/822#issuecomment-316792471

**Comment by xiewenlong1202** [comment]
Thanks, I will check it.
