### ISSUE TITLE
Efficiency of coinview caching

### ISSUE THREAD

**Issue by zeptin** [stratisproject/StratisBitcoinFullNode#2761]
Currently if the cached coinview receives an array of multiple copies of the same txid it appears it will do a lookup for all of them against the cache. It also appears that the DBreeze coinview will perform one lookup for each occurrence, rather than one lookup per unique txid.

This could either be handled in all the callers of `FetchCoinAsync`, or the txid array could be collapsed within `FetchCoinsAsync` prior to fetching.

**Comment by dangershony** [comment]
I agree we can try to add a .Distinct() in the caller to the method `FetchCoinAsync()` or better in the method `GetIdsToFetch`
