### ISSUE TITLE
BlockPullerBehavior.Node_MessageReceived is calling blocking PushBlock

### ISSUE THREAD

**Issue by Aprogiena** [stratisproject/StratisBitcoinFullNode#277]
This is probably not intentional as it seems that we could still ask for more blocks to arrive and they will but we will block in PushBlock until the consumer consumes them because there are limits on how many bytes we want to use by the puller. However, we will still use more and more RAM as new blocks arrive, they will just not go to the puller. So the limits in the puller won't achieve their original goal - limit RAM consumption.

If we really want to limit amount of RAM consumed, we would need to stop asking, rather than blocking processing (of already received) blocks.

So this issue should be resolved by not asking for more if we are full and probably completely removing the blocking logic in PushBlock.

**Comment by Aprogiena** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[BlockPuller] BlockPullerBehavior.Node_MessageReceived is calling blocking PushBlock](https://trello.com/c/Oy3uMiUG/156-blockpuller-blockpullerbehaviornodemessagereceived-is-calling-blocking-pushblock)

**Comment by Aprogiena** [comment]
PushBlock was newly renamed to BlockPushed, the problem remains unsolved, however

Moreover, there is race condition on this.currentSize, which is checked in loop and incremented without lock and possibly on other properties as well. These need to be solved as a part of this issues.

**Comment by Aprogiena** [comment]
So, how do we redesign this to fix this issue?

Maybe it would be sufficient to change `LBP.AskBlocks` not to call `BP.AskBlocks` directly, but instead it would just put these requests to a queue. Then we would need to implement a consumer of this queue, this would run in its own thread (so one new thread for every LBP). This consumer would then call `BP.AskBlocks` if there is a space in the buffer (similarly to current `BlockPushed` logic).

Finally, we would modify `LBP.BlockPushed`. We would remove the wait loop there, so that it would no longer block.

@dangershony What do you think?

**Comment by dangershony** [comment]
Yes this needs to be refactored, adding more to the reason this wont work is that the node has two threads a listener and publisher, currently the listener will block but requests will still be made to peers on the publisher thread , this blocks will arrive to our node non the less just not read from the stream.

As for the fix indeed we can limit on ask instead of receive, I am against adding a new thread if you need a background loop you can use the AsyncLoop code, but perhaps the solution is to use the already existing loop of NextBlockCore.

**Comment by Aprogiena** [comment]
I'll check what can we do with NextBlockCore loop.

BTW, new thread vs AsyncLoop - I think AsyncLoop is quite inefficient. When I have a producer - consumer relationship, I don't want to periodically poll, I want event based signalling. I think AsyncLoop is worse every time you don't want periodical polling.

**Comment by Aprogiena** [comment]
OK, I've checked NBC loop and it certainly can be used, so no new thread is needed. The only disadvantage is that NBC loop will be more complex as it will contain additional logic, but it saves the extra thread, so the complexity is possibly justified.

**Comment by dangershony** [comment]
The only benefit of AsyncLoop is to remove the need of taking a thread from the system, you decouple the the execution of Tasks periodically away from Threads

**Comment by Aprogiena** [comment]
No longer a concern here, solved it with NBC loop.

But for general discussion - taking a thread from the system is not a big deal for many use cases. It is just some little amount of RAM that is being consumed and from time to time a tiny extra work for the scheduler. 

I agree that if you want a loop (i.e. do something every X ms), then go with AsyncLoop, no problem. But if you do not want to do that then avoid AsyncLoop.
