### ISSUE TITLE
Inbound connections not stored in address db

### ISSUE THREAD

**Issue by dangershony** [stratisproject/StratisBitcoinFullNode#2776]
This will be fixe din the following PR
https://github.com/stratisproject/StratisBitcoinFullNode/pull/2723

However we need to verify this is correct behaviour 
Note how Bitcoin handles handshake can be found here
https://github.com/bitcoin/bitcoin/blob/master/src/net_processing.cpp#L1621

**Store to db**
When a peer connects inbound we don't know what is the peers listening port (if any) as the actual connected port may be different to the listening port, for that matter we can use the AddressFrom property that is send from the peer on version handshake, the AddressFrom will be the ip and port the peer claims to be listening on, I believe this is the port we should be using when we add the peer to the address db.

**Peer banning**
We ned to make sure this does not effect peer banning, when a node is banned the bann should be in the ip only (excluding port) this needs to be verified.

**Comment by dangershony** [comment]
A conversation on Discord that can help

![image](https://user-images.githubusercontent.com/7487930/48705398-e915d280-ebf0-11e8-9564-0ff066f8a503.png)

**Comment by dangershony** [comment]
Another issue regarding DNS is not knowing if an inbound peer is listening perhaps we can work this out from the AddressFrom property in the handshake.

**Comment by fassadlr** [comment]
Closed with #2723
