### ISSUE TITLE
SBFN PH: SBFN connects to not whitelisted StratisX node

### ISSUE THREAD

**Issue by maciejzaleski** [stratisproject/StratisBitcoinFullNode#2788]
When SBFN node has entry in `peers.json` for StratisX it will connect to StratisX even if StratisX node is not whitelisted.

**Setup**
- NodeJE whitelists NodeJFX only
- NodeJFX connects and syncs from NodeJE (connection is allowed because NodeJE whitelists NodeJFX)
- NodeJE connects to NodeJDX based on entry in `peers.json` (i.e. no forced connection using `-addnode` or `-connect`)
- NodeJDX syncs blocks from NodeJE

**Comment by MithrilMan** [comment]
why should this be an issue?
It's a correct behavior, if you want to limit to who connect, you should use -connect option

**Comment by maciejzaleski** [comment]
Closing as none issue
