### ISSUE TITLE
[P2P] ValidationContext.BanDurationSeconds doesn't work as expected

### ISSUE THREAD

**Issue by MithrilMan** [stratisproject/StratisBitcoinFullNode#2815]
https://github.com/stratisproject/StratisBitcoinFullNode/blob/b9ca70868ade00aaac83efbd8e4077fc81fb04bd/src/Stratis.Bitcoin/Consensus/ValidationContext.cs#L45 comment says that it will default to ConnectionManagerSettings.BanTimeSeconds if not specified

following briefly the code it doesn't seems true.

It gets used in
https://github.com/stratisproject/StratisBitcoinFullNode/blob/b9ca70868ade00aaac83efbd8e4077fc81fb04bd/src/Stratis.Bitcoin/Consensus/ConsensusManager.cs#L393-L394

and its value is used straight to set BanUntil
https://github.com/stratisproject/StratisBitcoinFullNode/blob/b9ca70868ade00aaac83efbd8e4077fc81fb04bd/src/Stratis.Bitcoin/Connection/PeerBanning.cs#L101

I don't see any code that check if the value is 0 and apply in that case the default value

**Comment by maciejzaleski** [comment]
Migrated to: https://dev.azure.com/Stratisplatformuk/StratisBitcoinFullNode/_workitems/edit/3059
