### ISSUE TITLE
Rework how Stratis.Bitcoin.Signals are used

### ISSUE THREAD

**Issue by Aprogiena** [stratisproject/StratisBitcoinFullNode#282]
Consider removing ISignals.Blocks and ISignals.Transactions from the interface and make them private in Signals. This will require Subscribe method to be implemented.

Reason: All code is currently using something like this:
`this.signals.Blocks.Broadcast(block.Block);`

instead of 

`this.signals.Signal(block.Block);`

and both `[Blocks|Transactions].Broadcast` implement guards and then `.Signal()` methods also implement guards. This is probably not used as intended.

**Comment by Aprogiena** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[Signals] Rework how Stratis.Bitcoin.Signals are used](https://trello.com/c/5sAOLUBo/159-signals-rework-how-stratisbitcoinsignals-are-used)

**Comment by dangershony** [comment]
This raises the questions whats more readable?
Maybe even
``` this.signals.SignalBlock(block.Block); ```

**Comment by Aprogiena** [comment]
sure, could be something like that

**Comment by kalani1234** [comment]
Join US in our new private Telegram channel which will show you how to make real money from the Crypto Markets!
We are not a Pump and Dump channel and we do not support them as most members in there lose money. We are limited to 5000 members and after this the invite link will expire.
All details will be shared inside the channel 
Join us here: https://t.me/joinchat/AAAAAEWfPN6QN9-wVIukIA
