### ISSUE TITLE
[P2P] Node connects to already connected node

### ISSUE THREAD

**Issue by maciejzaleski** [stratisproject/StratisBitcoinFullNode#2841]
When NodeAA connects to NodeAB, NodeAB will connect to NodeAA resulting in two TCP connections for every two nodes. This happens without using `-addnode` or `-connect` options.

**Steps to reproduce**
 - Add IP address of NodeAB to NodeAA peers.json
 - Start both nodes
 - Nodes will establish 2 connections between each other

```
[
  {
    "id": 0,
    "addr": "[::ffff:192.168.98.100]:45215",
    "addrlocal": "[::ffff:192.168.98.120]:16178",
    "services": "1",
    "relaytxes": false,
    "lastsend": 0,
    "lastrecv": 0,
    "bytessent": 0,
    "bytesrecv": 0,
    "conntime": 0,
    "timeoffset": 0,
    "pingtime": 0,
    "minping": 0,
    "pingwait": 0,
    "version": 70012,
    "subver": "StratisBitcoin:1.2.5",
    "inbound": true,
    "addnode": false,
    "startingheight": 0,
    "banscore": 0,
    "synced_headers": 0,
    "synced_blocks": 0,
    "whitelisted": true,
    "inflight": null,
    "bytessent_per_msg": null,
    "bytesrecv_per_msg": null
  },
  {
    "id": 1,
    "addr": "[::ffff:192.168.98.100]:16178",
    "addrlocal": "[::ffff:192.168.98.120]:32881",
    "services": "1",
    "relaytxes": false,
    "lastsend": 0,
    "lastrecv": 0,
    "bytessent": 0,
    "bytesrecv": 0,
    "conntime": 0,
    "timeoffset": 0,
    "pingtime": 0,
    "minping": 0,
    "pingwait": 0,
    "version": 70012,
    "subver": "StratisBitcoin:1.2.5",
    "inbound": false,
    "addnode": false,
    "startingheight": 0,
    "banscore": 0,
    "synced_headers": 0,
    "synced_blocks": 0,
    "whitelisted": false,
    "inflight": null,
    "bytessent_per_msg": null,
    "bytesrecv_per_msg": null
  }
]
```

Related to #2458

**Comment by dangershony** [comment]
We just need to investigate whether whitelist is causing this but otherwise this is low priority

**Comment by MithrilMan** [comment]
Isn't this a normal behavior? if peers.json contains very few items and reference each other, then they will connect to each other inbound/outbound

We could use nonce to disconnect one, the problem anyway is that we will have timing problems and both node may decide to close connection, ending up with both connection dropping.

Maybe would be easier to have a task that periodically checks if there are connection on the same ip with the same nonce, and drop the newer one

@dangershony @noescape00 WDYT?

**Comment by noescape00** [comment]
>Maybe would be easier to have a task that periodically checks if there are connection on the same ip with the same nonce, and drop the newer one

Nonces are created per version payload. So those 2 connections will have different nonces. 

Unless we modify handshake protocol to provide nonce that is created on node's startup and always stays the same.

**Comment by MithrilMan** [comment]
yes I forgot nonce is created during Version payload, as per bitcoin documentation
> 8 | nonce | uint64_t | Node random nonce, randomly generated every time a version packet is sent. This nonce is used to detect connections to self.

Do you know tho why it's created during the version payload and it doesn't have validity for the whole bitcoin node lifetime?
If it's because someone could infer all the public IP interface that node is exposing, we may have a nonce for every interface.
If it's not an issue, why can't we then just create a single nonce every time the node start, and use that? we could use that to find transaction to the same peer.
Of course being just a long there is an higher risk of collision respect having a GUID, but at the same time we could just match nonce with ip and we'd still have an improvement on these scenarios we are trying to address

**Comment by maciejzaleski** [comment]
Resolved
