### ISSUE TITLE
SBFN PH: StratisX nodes are not syncing from SBFN nodes

### ISSUE THREAD

**Issue by maciejzaleski** [stratisproject/StratisBitcoinFullNode#2842]
This test is based on the latest network topology: https://github.com/maciejzaleski/InternalTestnet/blob/master/Documentation/FullNode/InternalTestnet-NetworkDesign.draw.io.svg

**Setup**
 - Started network with NodeJFX fully synced
 - Waited for all nodes to sync; this completed successfully for all standard SBFN nodes and gateway nodes but failed for StratisX. StratisX will fully sync if it is connected to another StratisX node (NodeJGX). 
 - The problem seems to be present ONLY if StratisX is syncing blocks post IBD
 - The IBD block download (SBFN -> StratisX) seems to be running flawlessly

**Logs**:  https://stratisplatform-my.sharepoint.com/:u:/p/maciej_zaleski/EcMzTK1Y_dVCtwTpkxGH96EB0wn0YJJWj_bK-huvz8Khfg?e=de7g7L

**Network View**
![image](https://user-images.githubusercontent.com/6422181/49113233-e53b1d80-f28c-11e8-96f2-3100e9ee6808.png)

**Comment by noescape00** [comment]
Looks like I got lucky that time. Resynced QT 4 times from C# node with full logging enabled but the bug didn't appear. 

@maciejzaleski is it easily reproducible on InternalTestnet?

**Comment by noescape00** [comment]
I was able to reproduce a bug several times but it never lead to QT node being stuck for longer than 3-5 minutes. 

When QT syncs from C# node it can occasionally drop the connection `Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
 `

after which it would reconnect and it would take some time to start syncing again. 

I've also checked logs provided by @maciejzaleski and didn't find there a disconnection which was a precursor to the situation I found somewhat problematic.

However there might be a problem in the setup that might have caused the bug- bidirectional connections. 

HA:
```
Peer:[::ffff:192.168.98.101]:37021,      connected:inbound,         height:1241,          agent:StratisBitcoin:1.2.5
Peer:[::ffff:192.168.98.101]:16178,      connected:outbound,        height:1241,          agent:StratisBitcoin:1.2.5
Peer:[::ffff:192.168.98.171]:43076,      connected:inbound,         height:0,             agent:/Stratis:2.0.0.5/
```

HBX:

```
receive version message: version 70012, blocks=0, us=192.168.98.171:16178, them=127.0.0.1:16178, peer=192.168.98.174:40377
Added time data, samples 2, offset +0 (+0 minutes)
keypool reserve 1
keypool return 1
keypool reserve 1
keypool return 1
receive version message: version 70012, blocks=0, us=192.168.98.171:16178, them=127.0.0.1:16178, peer=192.168.98.174:39649
keypool reserve 1
keypool return 1
keypool reserve 1
keypool return 1
keypool reserve 1
keypool return 1
Adding fixed seed nodes as DNS doesn't seem to be available.
keypool reserve 1
keypool return 1
keypool reserve 1
keypool return 1
keypool reserve 1
keypool return 1
receive version message: version 70012, blocks=0, us=192.168.98.171:16178, them=127.0.0.1:16178, peer=192.168.98.174:38507
keypool reserve 1
keypool return 1
keypool reserve 1
keypool return 1
keypool reserve 1
keypool return 1
keypool reserve 1
keypool return 1
receive version message: version 70012, blocks=0, us=192.168.98.171:43076, them=127.0.0.1:16178, peer=192.168.98.170:16178
```

@maciejzaleski could you please run the network on latest master ensuring that there are no bidirectional connections and check if the bug still appears?

**Comment by maciejzaleski** [comment]
**Logs**
https://stratisplatform-my.sharepoint.com/:u:/p/maciej_zaleski/EbR7WtCPYppKnk-PS4QjxBIBuohZFrXR5fzHwlb2qHsbRA?e=tpoTca

**Network State**
![image](https://user-images.githubusercontent.com/6422181/49339770-84199e00-f62e-11e8-9bf8-905b953182b7.png)

**SBFN version**
```
58d3d1dd (01 Dec @ 13:54); Patches: Kevin 
   
*** Build date: 01/12/2018 19:56:38.64 

*** Recent commits 
*    58d3d1dd - (HEAD -> master, origin/master, origin/HEAD) Fix consecutive header bug (#2865) (Sat, 1 Dec 2018 13:54:20 +0000) <Francois de la Rouviere>
*    700c871a - Correctly store and load rewind data index,  (#2875) (Fri, 30 Nov 2018 23:46:54 +0000) <Dan Gershony>
*    c63e0c36 - Fix for "PHBS can serve reorged headers" (#2876) (Fri, 30 Nov 2018 18:13:46 +0300) <noescape0>
*    4d05de89 - Update SeedData (#2872) (Fri, 30 Nov 2018 10:04:03 +0000) <StratisIain>
*    08dc1140 - (origin/sc/v0.12.0-beta) nameof variables fix (#2868) (Thu, 29 Nov 2018 16:48:10 +0000) <Fazz>
*    0403c3cf - Inbound/outbound peer connection count (#2866) (Thu, 29 Nov 2018 15:49:19 +0000) <Fazz>
*    a981244c - (R/C) tip height, refactoring, IBD status (#2856) (Thu, 29 Nov 2018 13:45:13 +0000) <Fazz>
*    a1f70708 - Fix two tests (#2859) (Thu, 29 Nov 2018 10:32:25 +0000) <Francois de la Rouviere>
*    4c308677 - Add default connection params to SC networks (#2858) (Thu, 29 Nov 2018 17:45:09 +1100) <Rowan de Haas>
*    914e2549 - [ProvenHeaders] Set PHBS tip to ChainTip if its ahead (#2853) (Wed, 28 Nov 2018 18:56:18 +0000) <Francois de la Rouviere>  
****************** 
```

**Comment by noescape00** [comment]
Based on info received from @maciejzaleski I'm now trying another setup to reproduce the bug: 

NETWORK --> C# A (fully synced) --> C# B --> QT

C# B and QT node is syncing from scratch
C# B has IBD always disabled

Expected outcome: QT node gets stuck and can't sync fully.

**Comment by noescape00** [comment]
This one is fixed by #2893

@fassadlr why reopened?

**Comment by fassadlr** [comment]
@noescape00 we can't close it until the testers has retested it... It is currently in the Re-Test column :)

**Comment by noescape00** [comment]
Fair point 👍

**Comment by maciejzaleski** [comment]
Retest failed, logs: https://stratisplatform-my.sharepoint.com/:u:/p/maciej_zaleski/Ee6crzATL1BLm0ZMeZV6IywBVsRW-qLpnmh9FIRlnMiO2w?e=OUXp7V

![image](https://user-images.githubusercontent.com/6422181/49591313-01624d00-f966-11e8-8536-a83be20ca0ee.png)

**Comment by maciejzaleski** [comment]
The issue has been resolved
