### ISSUE TITLE
Error in ProvenBlocksHeadersStore.InitializeAsync

### ISSUE THREAD

**Issue by quantumagi** [stratisproject/StratisBitcoinFullNode#2845]
This method does not handle the case where `FindAncestorOrSelf` returns a null value:

```
        public async Task<ChainedHeader> InitializeAsync(ChainedHeader highestHeader)
        {
            await this.provenBlockHeaderRepository.InitializeAsync().ConfigureAwait(false);

            ChainedHeader tip = highestHeader;
            HashHeightPair repoTip = this.provenBlockHeaderRepository.TipHashHeight;

            if (repoTip.Hash != tip.HashBlock)
            {
                // Repository is behind chain of headers.
                tip = tip.FindAncestorOrSelf(repoTip.Hash, repoTip.Height);
            }

            this.TipHashHeight = new HashHeightPair(tip.HashBlock, tip.Height);
            this.logger.LogDebug("Proven block header store initialized at '{0}'.", this.TipHashHeight);

            return tip;
        }
```

which can lead to:

![image](https://user-images.githubusercontent.com/29645989/49134355-651dc200-f337-11e8-91a2-302fde9ba231.png)

**Comment by MithrilMan** [comment]
do you mean we should release this as it is now? I think we should address this anyway, and then maybe remove this fix when TipManager is merged

**Comment by noescape00** [comment]
>do you mean we should release this as it is now?

No, that probably would be a bad idea. 

As a temporary fix we can try getting headers by height till we get one which is present on concurrent chain. This will be the common fork and then we rewind everything till that fork or recreate missing data in store.

**Comment by fassadlr** [comment]
OK so the issue here is that  `chainTip` is behind the tip of proven header block store. So when you call `FindAncestorOrSelf` on line 137 in `ProvenHeaderBlockStore` it returns a null.
