### ISSUE TITLE
NodeBuilder: AddRPC() requires UseWallet()

### ISSUE THREAD

**Issue by mikedennis** [stratisproject/StratisBitcoinFullNode#285]
If you don't include UseWallet() then the Stratis node crashes on startup. Crash is due to a dependency on WalletManager (which isn't there if you don't include UseWallet())

**Comment by mikedennis** [comment]
Is this a dependency we require or should we load WalletRPCController conditionally depending upon whether UseWallet() was included?

**Comment by dangershony** [comment]
For now a quick fix is to allow wallet to be null however a better fix is to separate the controllers in to their features (like with api).

**Comment by mikedennis** [comment]
This is the actual exception being thrown:
```
System.InvalidOperationException occurred
  HResult=0x80131509
  Message=Unable to resolve service for type 'Stratis.Bitcoin.Features.Wallet.IWalletManager' while attempting to activate 'Stratis.Bitcoin.Features.Miner.PosMinting'.
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.Service.PopulateCallSites(ServiceProvider provider, ISet`1 callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
```
The exception is thrown when copying the node services to the RPC services in this line
https://github.com/stratisproject/StratisBitcoinFullNode/blob/9aec20b1a922fc73f2aff755c35c44881bdbd40a/Stratis.Bitcoin/Features/RPC/RPCFeature.cs#L48

**Comment by dangershony** [comment]
Unfortunately I cant see to reproduce this bug.
If I comment out .UseWallet() in NodeBuilder this tests fails only on the RPC call 'SendCommand' (not the node init)
```
        [Fact]
        public void CanMineBlocks()
        {
            using(NodeBuilder builder = NodeBuilder.Create())
            {
                var stratisNodeSync = builder.CreateStratisNode();
                builder.StartAll();
                var rpc = stratisNodeSync.CreateRPCClient();
                rpc.SendCommand(NBitcoin.RPC.RPCOperations.generate, 10);
                Assert.Equal(10, rpc.GetBlockCount());
            }
        }
```

**Comment by mikedennis** [comment]
If you startup the node like this you will encounter the error:

``` C#
 var node = new FullNodeBuilder()
                .UseNodeSettings(nodeSettings)
                .UseStratisConsensus()
                .UseBlockStore()
                .UseMempool()
                .AddPowPosMining()
                .AddRPC()
                .Build();
```

Maybe I should create a unit test for it?

**Comment by dangershony** [comment]
As discussed the solution is to probably check feature dependencies at Feature level.
Suggested is to add to the FeatureExecutor the following 
```
this.Execute(featureCollection, service => service.ValidateDependencies(featureCollection),  service.Start());
```
Then each feature can verify its dependencies (by feature)

**Comment by mikedennis** [comment]
As per discussion going to change so validate dependencies on per feature prior to feature startup.

**Comment by mikedennis** [comment]
@dangershony 

Execute() does both starting and stopping the service and the validation is only relevant to starting. Propose we do this instead:

1. Expose FullNode.Features property in IFullNodeBuilder

2. In FullNodeFeatureExecutor.cs

''' C#
       public void Start()
        {
            try
            {
                FeatureCollection featurecollection = this.FullNodeBuilder.Features;
                this.Execute(service => service.ValidateDependencies(featureCollection));
                this.Execute(service => service.Start());
            }
            catch (Exception ex)
            {
                this.logger.LogError("An error occurred starting the application", ex);
                throw;
            }
        }
'''
3. ValidateDependencies() would iterate through its service DI dependencies and compare each dependency with what is in featureCollection. If there is any dependencies that aren't in feature collection then it would log them and throw an InvalidOperationException.

Thoughts?

**Comment by mikedennis** [comment]
The above somewhat works but have one problem I haven't been able to figure out.  IFullNodeBuilder is not registered in DI unless RPC is added. So I can't get to IFullNodeBuilder from FullNodeFeatureExecutor. Any ideas?

**Comment by dangershony** [comment]
I don't think we need to iterate over services, just let each feature validate its dependencies.

```
features.FeatureRegistrations.Any(i => i.FeatureType == typeof(WalletFeature);
```

**Comment by mikedennis** [comment]
Yes I guess doing it via trying to resolve all the dependent services is probably a bit of overkill. Dependencies between features is likely more the exception than the rule.  I'm sure in general the features are designed to be as standalone as possible. 

I will look at implementing your solution.

**Comment by mikedennis** [comment]
@dangershony 

I had problems getting access to the FullNodeBuilder.Features from within the FullNodeExecutor so instead I invoke the validation logic at the end of FullNodeBuilder.Build(). This seems to work but I have a couple of unit tests that now break.

This test below breaks because not all the dependent services are available for the BlockStoreFeature (specifically NBitcoin.ConcurrentChain). Should this be refactored to take in mock feature instead of a real feature? Or is this purpose of the test testing that the default configuration can build a node with  BlockStoreFeature?
https://github.com/stratisproject/StratisBitcoinFullNode/blob/d136fb494472e5872cf3e9ea10fa067827e67788/Stratis.Bitcoin.Tests/Builder/FullNodeBuilderTest.cs#L137

**Comment by dangershony** [comment]
Doesn't this work?
```
	this.node.Services.Features.ToList()
```

**Comment by mikedennis** [comment]
Think I finally have a reasonable solution to this. I'll make a PR if you want to take a look. Thanks for all the help!

**Comment by mikedennis** [comment]
PR has been merged into master
