### ISSUE TITLE
PH missing UTXO not checked correctly 

### ISSUE THREAD

**Issue by dangershony** [stratisproject/StratisBitcoinFullNode#2855]
`ProvenHeaderCoinstakeRule.GetAndValidatePreviousUtxo()` makes this check.

```
                prevUtxo = coins.UnspentOutputs[0];
                if (txIn.PrevOut.N >= prevUtxo.Outputs.Length)
                {
                    // This should never happen, if it did, an incorrect number of UTXOs were created for a trx.
                    this.Logger.LogTrace("(-)[PREV_UTXO_COUNT_MISMATCH]");
                    ConsensusErrors.ReadTxPrevFailed.Throw();
                }
```

This should not happen at all because if a prev trx is found it must have the same number of inputs (even if they are spend it will just have null there, so this needs to be investigated.

**Comment by dangershony** [comment]
Zip file
https://stratisplatform-my.sharepoint.com/:u:/p/iain_mccain/EZNJpAcUUztIlqIrpc5HaJABiYAJA4hHnbJZTakaAvYK2w?e=di23gb

**Comment by maciejzaleski** [comment]
Issue has been resolved
