### ISSUE TITLE
SBFN PH: Nodes fail to recover from 400 block reorg

### ISSUE THREAD

**Issue by maciejzaleski** [stratisproject/StratisBitcoinFullNode#2860]
**Setup**
 - Network started with all nodes at height 1670 but not the same chain; majority of the nodes are on chain **Fork1**
 - Four nodes (i.e. NodeDB, NodeGE and NodeHA, NodeJGB) on the network had a different chain **Fork2** from block starting from block 1241 (439 blocks long fork)
 - Staked blocks on NodeJFX which is on chain **Fork1**
 - Node NodeJGB managed to reorg onto the longest chain (from **Fork2** to **Fork1**)
 - Nodes NodeDB, NodeGE and NodeHA didn't reorg and are still on **Fork2**
 - Waited for 10min since the NodeJGB finished reorg and stopped the test

There are more detailed screenshots of the NetworkViewer in the Logs archive below.

Logs for all nodes in the network: https://stratisplatform-my.sharepoint.com/:u:/p/maciej_zaleski/EY8zeOpmdY1JvC5BxOWPhKwBfpWoSxN40Lh9JylkMF0uRA?e=Hai73o

**Network status at the end of the test**
![05_networkafterperiodoftime](https://user-images.githubusercontent.com/6422181/49227975-46283a00-f3e2-11e8-8e0c-aeb29a83531d.png)

**Comment by noescape00** [comment]
This issue depends on https://github.com/stratisproject/StratisBitcoinFullNode/issues/2855

After https://github.com/stratisproject/StratisBitcoinFullNode/issues/2855 is resolved we need to retest this, most likely it will be resolved.

**Comment by maciejzaleski** [comment]
Issue has been resolved
