### ISSUE TITLE
[P2P] -connect option doesn't disable NetworkPeerServer

### ISSUE THREAD

**Issue by noescape00** [stratisproject/StratisBitcoinFullNode#2863]
BitcoinCore client disables inbound connections if `connect` option is specified. It can be enabled then by `-listen=1`. 

We don't disable NetworkPeerServer in case we are using `-connect`.

Related to https://github.com/stratisproject/StratisBitcoinFullNode/issues/2421

**Comment by MithrilMan** [comment]
I'd change this behavior only after we implement -listen

**Comment by MithrilMan** [comment]
and when you use -connect, -listen should be defaulted to 0

**Comment by maciejzaleski** [comment]
Closed

**Comment by bokobza** [comment]
@maciejzaleski closed because it is resolved?

**Comment by maciejzaleski** [comment]
Issue moved to: https://dev.azure.com/Stratisplatformuk/StratisBitcoinFullNode/_workitems/edit/3040
