### ISSUE TITLE
Race condition that allows multiple connections to peers from the same subnet

### ISSUE THREAD

**Issue by noescape00** [stratisproject/StratisBitcoinFullNode#2864]
How to reproduce: 
create 2 nodes, A and B. 
A.peers.json should contain B, B.peers.json should contain A. 
Run them at the same time from the same machine or same subnet (first 2 digits of IP address should be the same). 
Nodes will establish bidirectional connection. 

We have code to prevent connections to the nodes from the same subnet (`PeerConnector` checks `PeerIsPartOfExistingGroup`) but in case both connections are established within a certain timeframe this check fails to prevent such connections. 

So let's say we are node A and connecting to node B. We select IP and it passes the `PeerIsPartOfExistingGroup` check, we establish a connection and start handshake. When handshake is finished peer is added to connectionmanager.connectedPeers and after that `PeerIsPartOfExistingGroup` will taker this peer in count. 

If some other node from the same subnet connects to us after we selected the IP for connection but before it was added to peers collection we will end up with connections to peers from the same subnet. 

ps
I believe this is the reason why bidirectional connections are happening on the internal testnet. See https://github.com/stratisproject/StratisBitcoinFullNode/issues/2842

**Comment by MithrilMan** [comment]
can't we just drop the last that handshake?

**Comment by dangershony** [comment]
Perhaps we need to do this check also in the behaviour then?

**Comment by maciejzaleski** [comment]
This has been proved to work as expected now

**Comment by sondreb** [comment]
This means that there needs to be X amount of public nodes available for every person that is behind a NAT with the same IP address, right?

Have a scenario where I might have hundreds of users running on the same public Wi-Fi, sharing the same external IP or range. Turning off IP Range filtering would be one option to get around that.
