### ISSUE TITLE
Network fork created during reorg test with multiple nodes staking

### ISSUE THREAD

**Issue by ArcSin2000X** [stratisproject/StratisBitcoinFullNode#2870]
`NodeDA` and `NodeDB` fork to seperate chain when on block 1884, both nodes have staking enabled:
![image](https://user-images.githubusercontent.com/37782512/49243829-3d495f80-f406-11e8-92b0-279afc5941d3.png)
Subsiquently they continue
growing forked chain on the network
![image](https://user-images.githubusercontent.com/37782512/49243896-64079600-f406-11e8-9180-8f96e0c51403.png)

Link to logs: https://stratisplatform-my.sharepoint.com/:f:/p/lukasz_krol/EjkcEubcs-NJgJ2VF2vapNoBwUUherlhCQa3Qpr5cr8O5g?e=ccHnhA

Network topology:
![image](https://user-images.githubusercontent.com/37782512/49244103-e6905580-f406-11e8-8367-08567b5ba729.png)

Version of SBFN tested:

```properties
Revision: c89d8e267dc45801d51b319599ac1e2dba74a11e
Author: Francois de la Rouviere <fassadlr@gmail.com>
Date: 27/11/2018 17:31:18
Message:
[BlockStore] Dequeue all items from the async queue on dispose (#2837)

* Add items from async queue to batch before saving



* Fixes as per review



* Changes as per review
----
Modified: src/Stratis.Bitcoin.Features.BlockStore/BlockStoreQueue.cs
Modified: src/Stratis.Bitcoin/Utilities/AsyncQueue.cs


```

**Comment by fassadlr** [comment]
@ArcSin2000X can we close this issue now? I believe this is no longer happening?

**Comment by maciejzaleski** [comment]
Resolved
