### ISSUE TITLE
FeeRate constructor in Overflow when paying a huge amount of fee

### ISSUE THREAD

**Issue by MithrilMan** [stratisproject/StratisBitcoinFullNode#2879]
Struggling with the creation of a valid transaction for tests, I found myself in a weird scenario that anyway caused a bug in the code.

In my scenario I was spending 98 milion of coins as input, and as output I set a very low value (3 in my case). In this scenario we are going to pay to miners 98 milions - 3 satoshis

when the (valid) transaction were inserted into the MemoryPool it was failing in  'AddUnchecker` method.
Digging more, I found the cause: it was in the `FeeRate` constructor

https://github.com/stratisproject/StratisBitcoinFullNode/blob/7215dcb189a6b483f3dc9d7c88c65adedaafbc70/src/NBitcoin/FeeRate.cs#L44

this can be solved applying ( ) parenthesis to give precedences.

~`this._FeePerK = feePaid * (1000 / size);`~
`this._FeePerK = feePaid / size * 1000;`

Probably should be worth investigate more for similar cases, even if to trigger this I had to pay milions of coins as fee... not something that probably should happen but anyway it's a bug

**Comment by bokobza** [comment]
One thing you can do as well is to check if this has been fixed in NBitcoin.

**Comment by MithrilMan** [comment]
at a first sight, NBitcoin has the same bug
https://github.com/MetacoSA/NBitcoin/blob/46b57d0e334d275f471a97ec3c648b4eb31013d2/NBitcoin/FeeRate.cs#L59

**Comment by MithrilMan** [comment]
@NicolasDorier FYI

**Comment by MithrilMan** [comment]
after a check, I've to change the proposed solution because it rounds badly.
the right one is
`this._FeePerK = feePaid / size * 1000;`

**Comment by NicolasDorier** [comment]
nice finding thanks a lot!

**Comment by MithrilMan** [comment]
wait I see this still causes rounding problems, this is what you'd want:

`this._FeePerK = (long)(feePaid.Satoshi / (decimal)size * 1000);`

or use a Money constructor that accepts decimal, without specifying the Unit (no need to convert, these are already satoshi)
