### ISSUE TITLE
[Refactor] Split DownloadBlockStep

### ISSUE THREAD

**Issue by fassadlr** [stratisproject/StratisBitcoinFullNode#288]
The logic contained in DownloadBlockStep in the BlockStore needs to be split into two logical areas for better unit testing.

Create a FindBlocks and DownloadBlocks "sub" step and unit test each separately.

**Comment by dangershony** [comment]
I would suggests the steps to be internal classes to this parent step.

**Comment by dangershony** [comment]
Yeah i like the idea then the other step will continue til it ends.

**Comment by fassadlr** [comment]
OK, Ive done the refactoring work and have added a multitude of tests for FindBlocks() as well as DownloadBlocks().

I would possibly also like to in another PR further investigate whether cant mock out the BlockRepository so that we don't have to write to disk to store blocks with unit tests.

**Comment by dangershony** [comment]
Yeah mocking BlockRepository will be a very good idea.

**Comment by fassadlr** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[BlockStore] Refactor DownloadBlocks into 2 logical areas](https://trello.com/c/NxyII0oV/150-blockstore-refactor-downloadblocks-into-2-logical-areas)
