### ISSUE TITLE
Minor bug: Should validate that MaxOutboundConnections is more than 0

### ISSUE THREAD

**Issue by sondreb** [stratisproject/StratisBitcoinFullNode#2895]
When MaxOutboundConnections is set to 0, the call to ForEachAsync fails with maxDegreeOfParallelism set to 0. This makes for a bit funky exception:

```
System.ArgumentException: 'The tasks argument contains no tasks.'
```

Perhaps the ForEachAsync extension method should validate that maxDegreeOfParallelism must be higher than 0, and also validation on MaxOutboundConnections.

**Comment by fassadlr** [comment]
@sondreb feel free to implement this one 😉

**Comment by dangershony** [comment]
https://github.com/stratisproject/StratisBitcoinFullNode/pull/3232
