### ISSUE TITLE
unused payloads

### ISSUE THREAD

**Issue by MithrilMan** [stratisproject/StratisBitcoinFullNode#2903]
In our codebase we have unused payloads.
I think we should remove them before releasing the fullnode.

some unused payloads I've found are:

> UTxOutputPayload
> FilterAddPayload
> FilterLoadPayload

**Comment by noescape00** [comment]
Agreed. Please create a PR

**Comment by MithrilMan** [comment]
I'm working on a PR and I've find other unused payloads:
BlockTxnPayload
CmpctBlockPayload
GetBlockTxnPayload
MerkleBlockPayload

SendCmpctPayload is not used but it's wired to this code
https://github.com/stratisproject/StratisBitcoinFullNode/blob/a6a8d2b743f903d3aafd0f65614ac63b780c10ca/src/Stratis.Bitcoin.Features.BlockStore/BlockStoreBehavior.cs#L288-L292

I left it there but probably could be removed also (or implemented, but then we should implement all cmpct payloads)
