### ISSUE TITLE
Sync stops progressing after last checkpoint

### ISSUE THREAD

**Issue by einewton** [stratisproject/StratisBitcoinFullNode#2910]
Headers.Height, Consensus.Height, BlockStore.Hight never progress past 1000000 (The last checkpoint?)

The block explorer shows well past this (1100377).

Reproduce: 
1. Download latest code
2. Delete the StratisMain folder (%AppData%\StratisNode\stratis\StratisMain)
3. Start full node with default settings (Do not create a wallet)

![image](https://user-images.githubusercontent.com/5290398/49553261-24ccbf80-f8b4-11e8-9c28-697d9b85caf3.png)

**Comment by codingupastorm** [comment]
hey @einewton what's actually happening here is from 1m onwards you will need to be connected to a C# node to continue progressing and the seeds for this are still being set up.

The recommendation is to wait, as peer discovery should get you there... Or you may be able to bypass it by adding a C# node manually - try starting your node with the extra param `-addnode=51.140.231.125`

**Comment by einewton** [comment]
@codingupastorm thanks, I am connected to @dangershony node... I will wait to see.

![image](https://user-images.githubusercontent.com/5290398/49553451-fb606380-f8b4-11e8-816c-fc4b9594bcc9.png)

**Comment by codingupastorm** [comment]
Good to hear :) Let us know how you progress

**Comment by noescape00** [comment]
There was a problem even when connected to PH enabled nodes. 
Should have been fixed in https://github.com/stratisproject/StratisBitcoinFullNode/pull/2893
So if you are running earlier version- please update
