### ISSUE TITLE
[Logging] Implement prefix logger

### ISSUE THREAD

**Issue by Aprogiena** [stratisproject/StratisBitcoinFullNode#292]
We have migrated to NLog, but there is more we can do about making logging even more useful. I call this feature "prefix logger". All it does is that it allows you to do something like this:

`this.logger = loggerFactory.CreateLogger(this.GetType().FullName, PREFIX);`

and the effect is that all logs you create with it are prefixed with PREFIX. So let's say we have BlockPullerBehavior and for logging purposes, we identify each behavior with behavior.GetHashCode(). 

Currently I need to write something like this:

`this.logger.LogTrace($"[{this.GetHashCode():x}] ()");`

and what I would like instead is this:

```
this.logger = loggerFactory.CreateLogger(this.GetType().FullName, "[{this.GetHashCode():x}] ");
...
this.logger.LogTrace("()");
```

This is useful for logging events of instances of objects where you have multiple instances and you wnat to know which instance invoked the event. It saves you from repeating the identifier in every log call.

**Comment by Aprogiena** [comment]
As a part of this issue, if it is implemented, BlockPullerBehavior should be modified to use it (to get rid of ID in each log call)

**Comment by dangershony** [comment]
Sounds good to me

**Comment by Aprogiena** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[Logging] Implement prefix logger](https://trello.com/c/re2CkaZI/163-logging-implement-prefix-logger)
