### ISSUE TITLE
Shutdown logging not appearing in log

### ISSUE THREAD

**Issue by sondreb** [stratisproject/StratisBitcoinFullNode#2935]
A while back there was a bug that causes shutdown not to be performed gracefully, and this caused the log file not to include the complete shutdown log messages.

On the latest code base, I have verified on two machines that shutdown messages are no longer logged.

When debugging from Visual Studio, it normally writes the shutdown log info.

The two test machines are one with Windows 10 and another with Windows Server 2019. They both launched the daemon using a UI.

Since I have no errors or anything, I don't have much to go on other than it fails to write shutdown log entries. Is this simply because it does not flush at the end, or is there an shutdown issue?

**Comment by mixitka** [comment]
Logging in these situations is tricky in many logging libraries. Adding `LogManager.Flush()` calls in the codebase may help you lose less logs. There is also a comment by [snakefoot](/snakefoot): https://github.com/NLog/NLog/issues/2778#issuecomment-398093729

Could you describe in more detail the steps you take to reproduce the issue?

**Comment by maciejzaleski** [comment]
@sondreb I was unable to reproduce this issue. Is that still a problem? Which log messages are missing, could you please share few so that I have an idea where to look.

**Comment by dangershony** [comment]
This is an old and likely fixed issue
