### ISSUE TITLE
Multiple BlockPullerBehaviors are created in connectionManager.Parameters.TemplateBehaviors

### ISSUE THREAD

**Issue by Aprogiena** [stratisproject/StratisBitcoinFullNode#294]
connectionParameters.TemplateBehaviors.Add(new BlockPullerBehavior is called on 3 different places:
- BlockNotificationFeature.Start()
- ConsensusFeature.Start()
- BlockStoreFeature.Start()

Somehow BlockNotificationFeature is not active because no one calls UseBlockNotification.
So only 2 instances (not 3) of BPB exist for each connection.

I'm not sure if this is intentional, I'd guess it is not. In all cases, I think BPB should be presented only once. As a consequence of this, every peer connection calls BPB.AttachCore twice, which causes BPB.Node_MessageReceived to be called twice for every message the peer sends. This causes DownloadTaskFinished to be called twice, once for the behavior that was assigned the job, one for the other behavior. Even if there was intention of having multiple BPB, the fact Node_MessageReceived is called twice is a bug.

**Comment by dangershony** [comment]
This is intentional, there are many instances of BPB infact two for every node, however there is only one logical instance of BP per caller (one for consensus and one for store).

MessageReceived is called twice on each node for each behavoir. This is absolutely fine as the BP filters out behaviours that dont belong to it.

There are two puller instances in code, it that an issue that DownloadTaskFinished is callwd twice?

**Comment by Aprogiena** [comment]
From my perspective and with my understanding of the design, it is quite a serious bug to call notification method for something unrelated to you. 

What I would expect is BPB.Node_MessageReceived to be called only for messages that originated from that BPB. But if there is some reason why this does not work like that I would expect the very basic filtering at the start of Node_MessageReceived to filter out that notification that is not relevant to this BPB. 

This is not there and so DownloadTaskFinished is called twice. Of course all the checks in DownloadTaskFinished prevent something bad happening, but the code flow is flawed here - and so are the logs. From code flow perspective, currently it is being claimed that:
- Node.BPB1 asks peer for a block
- Node.BPB2 does nothing
- Node.BPB1 finished downloading the block
- Node.BPB2 ALSO finished downloading the block <- this is simply not true

That last thing should be filtered IMHO.

**Comment by dangershony** [comment]
This is not definitelly not a bug its the design of the behaviours, you can't  filter on events (you have to filter before you raise it), every message that comes from the node goes to all behaviours.

If you question the desgin of Node i would agree that can be improved. There maybe even a way to create listeners on a Node I am not sure.

Yeah this can be improved by putting an internal list to each behaviour (wasent it like that before?).

**Comment by Aprogiena** [comment]
I need to get little more information about the bigger picture here - as you said, this is intentional and to me it was really surprising, so I need to learn little more about this.

**Comment by Aprogiena** [comment]
In any case I will add extra check at the top of Node_MessageReceived to avoid calling DownloadTaskFinished for blocks that do not belong to the puller. 

This may seem redundant as DownloadTaskFinished does this check as well, but the cost of this redundancy is almost zero while it make the execution flow more logical.

**Comment by Aprogiena** [comment]
OK, seems like no issue then! Closing.
