### ISSUE TITLE
Headers are not syncing on the PoA network

### ISSUE THREAD

**Issue by maciejzaleski** [stratisproject/StratisBitcoinFullNode#2959]
**Steps to reproduce**
Start the sidechains network with 7 gateways and create 2000 blocks

**Network state**
![image](https://user-images.githubusercontent.com/6422181/50004686-dbf5c480-ff9f-11e8-89eb-ece6ef5ca1d4.png)

**Comment by bokobza** [comment]
Are they not syncing at all?
From what I saw, it's working OK, both on a local and on the live network.

**Comment by noescape00** [comment]
Testing it. So far advanced to block 2100. Wasn't able to reproduce it yet. 
Will wait till block 3k and start analyzing logs. 
Unable to do other PRs today before finishing this since running 8 nodes consumes all CPU.

**Comment by maciejzaleski** [comment]
This has been retested with 7000 blocks on the PoA network. The network advances without any issues and no forks.
