### ISSUE TITLE
Default configuration file for RPC feature has invalid, says default is 0.0.0.0 when it is 127.0.0.1

### ISSUE THREAD

**Issue by sondreb** [stratisproject/StratisBitcoinFullNode#2961]
The code and default config says that default is 0.0.0.0 and :: (IP v6), but this is not true.

![image](https://user-images.githubusercontent.com/309938/50035246-4d199400-0001-11e9-9773-e6da0f194063.png)

When no rpcallowip is specified, then it runs the code shown below:

![image](https://user-images.githubusercontent.com/309938/50035282-789c7e80-0001-11e9-9f73-50b12c6ac739.png)

If the -rpcallowip is specified, then it triggers the binding to 0.0.0.0:

![image](https://user-images.githubusercontent.com/309938/50035319-bdc0b080-0001-11e9-8559-cdbc7c5b451e.png)

If the -rpcbind is specified, without the -rpcallowip, then whatever is filled out, is **cleared (removed) and replaced with 127.0.0.1**.

Is all of this suppose to work this way?

**Comment by maciejzaleski** [comment]
This is correct behaviour.
**- When no rpcallowip is specified**: We didn't allow any external connections so the RPC should bind to only to localhost interface.
**- If the -rpcallowip is specified, then it triggers the binding to 0.0.0.0**: In this case we bind to all interfaces and restrict the connections by source IP address
**- If the -rpcbind is specified, without the -rpcallowip, then whatever is filled out:** This is a security precaution. If the user is attempting to open their RPC interface to the whole Internet but they didn't specify from what source addresses the connection could be established we override the setting with a safe value - localhost address.
