### ISSUE TITLE
improve log when peer disconnected because of IP RANGE

### ISSUE THREAD

**Issue by MithrilMan** [stratisproject/StratisBitcoinFullNode#2969]
simple improvement that helps debugging:

https://github.com/stratisproject/StratisBitcoinFullNode/blob/4c1685abfb7e0b4f486b486fa4189f76034cedaf/src/Stratis.Bitcoin/Connection/ConnectionManager.cs#L286-L287

we should write the address of the disconnected peer

**Comment by maciejzaleski** [comment]
Resolved
