### ISSUE TITLE
Null reference exception on shutdown (RemoveReorgedBlocksFromStoreAsync)

### ISSUE THREAD

**Issue by sondreb** [stratisproject/StratisBitcoinFullNode#2996]
I have seen this twice now the last couple of days, while working with docker and my local machine. The docker VHD was hosted on an old-style disk so was really slow, moved to the SSD now. Not sure if this was related, but when this exception occurred, the shutdown was taking a lot of time and was slow. This did not happen always, but it was slow the two times it failed.

![image](https://user-images.githubusercontent.com/309938/50348103-1929fb80-0538-11e9-908d-04196638c521.png)

**Comment by maciejzaleski** [comment]
Issue has been resolved
