### ISSUE TITLE
Feature request: Several validation modes

### ISSUE THREAD

**Issue by NicolasDorier** [stratisproject/StratisBitcoinFullNode#3]
Several mode for validation:

* Managed Validation (current one, consensus reimplemented in C#)
* LibConsensus Validation (partially managed, script executed by libconsensus library of Bitcoin Core)
* No Validation (No check on blocks are done, safe only if connected to a whitelisted node)

The last would allows to be behind a bitcoin core proxy, while still being able to take advantage of a full UTXO and easier to develop features of Stratis full node.

**Comment by dangershony** [comment]
The white-listed node is the bitcoin core proxy?
This could allow faster block download as currently the validation is the bottle neck right?

**Comment by NicolasDorier** [comment]
yes. With No Validation the utxo would be built rather rapidly

**Comment by dangershony** [comment]
I think this will become obsolete with the AssumeValidBlocks feature.

**Comment by NicolasDorier** [comment]
mmh I think not, as stratis node consensus is different from libconsensus, but way less a priority.

**Comment by dangershony** [comment]
yeah good point, indeed it will never be possible to have a 100% compatibility between implementations. 
The consensus feature of the Bitcoin chain should probably use libconsensus when running the node on the bitcoin chain, with the new approach we'll be able to swap the consensus validation with one for stratis.

**Comment by NicolasDorier** [comment]
Maybe since assumevalid is implemented, we can simplify by having a settings `uselibconsensus=true|false|auto` where auto would be the default, trying to use LibConsensus and fallback on managed consensus if not found

**Comment by dangershony** [comment]
ok yes I will add that to the AssumeValid task
FYI I started to add tasks in the project tab https://github.com/stratisproject/StratisBitcoinFullNode/projects

**Comment by bokobza** [comment]
Closed with https://github.com/stratisproject/StratisBitcoinFullNode/pull/733.
