### ISSUE TITLE
FlushChain threw an unhandled exception

### ISSUE THREAD

**Issue by fassadlr** [stratisproject/StratisBitcoinFullNode#3030]
This happened during a stress test:

```FlushChain threw an unhandled exception: Stratis.Bitcoin.Features.Consensus.ProvenBlockHeaders.ProvenBlockHeaderException: Invalid new tip hash, tip hash has not changed.```

**Comment by dangershony** [comment]
I think its a duplicate of this one
https://github.com/stratisproject/StratisBitcoinFullNode/issues/3012

**Comment by fassadlr** [comment]
Closing as duplicate
