### ISSUE TITLE
Failing Unit Tests

### ISSUE THREAD

**Issue by quantumagi** [stratisproject/StratisBitcoinFullNode#3041]
Various unit tests are failing:

![image](https://user-images.githubusercontent.com/29645989/50762952-8c669800-12c2-11e9-833e-552b2abcd4c2.png)
Resolved
![image](https://user-images.githubusercontent.com/29645989/50762971-98eaf080-12c2-11e9-9c53-51ca57000f5a.png)

![image](https://user-images.githubusercontent.com/29645989/50762986-a6a07600-12c2-11e9-8803-1631bfd9ba08.png)

![image](https://user-images.githubusercontent.com/29645989/50763006-b750ec00-12c2-11e9-8df7-b86cdab5d73e.png)

![image](https://user-images.githubusercontent.com/29645989/50763028-c59f0800-12c2-11e9-8e51-5eef0cc84575.png)
See PR #3100 

![image](https://user-images.githubusercontent.com/29645989/50763039-cfc10680-12c2-11e9-9419-ef92e3899e74.png)
Resolved
![image](https://user-images.githubusercontent.com/29645989/50763057-dcddf580-12c2-11e9-83b6-1fde63194fff.png)
Resolved

**Comment by quantumagi** [comment]
More failing tests:

![image](https://user-images.githubusercontent.com/29645989/50947546-f82f4780-14f2-11e9-9cf1-843cc7ee4409.png)

**Comment by quantumagi** [comment]
PR #3062 resolved `sending_from_xxx` test cases.

**Comment by fassadlr** [comment]
@quantumagi which ones are left?

**Comment by quantumagi** [comment]
@fassadlr, note that I am adding "Resolved" as each test case is resolved.
