### ISSUE TITLE
Wallet history does not pick up on all staking transactions

### ISSUE THREAD

**Issue by dev0tion** [stratisproject/StratisBitcoinFullNode#3043]
I have reports from three different people saying that their wallet balance is showing correctly, but not all staking transactions are included in their history.
I've confirmed this with screenshots and comparing the address with the block explorer. It is indeed an issue.

Unfortunately no full logs available for the issue and I was not able to reproduce it myself as of yet.
Will update if I'm able to reproduce/get full logs.

**Comment by einewton** [comment]
I have seen this as well. You need a lot of coin to see this issue. Even if you restore from seed words, you can watch your wallet history disapear as it syncs.

Perhaps a test case is in order?
