### ISSUE TITLE
CheckHeaderSignatureWithCoinstakeKernel does not cater for OP_RETURN

### ISSUE THREAD

**Issue by quantumagi** [stratisproject/StratisBitcoinFullNode#3047]
The `CheckHeaderSignatureWithCoinstakeKernel(ProvenBlockHeader header)` in `ProvenHeaderCoinstakeRule.cs` assumes that the second output will always be a `PayToPubkeyTemplate`. However for cold staking this may be an `OP_RETURN`. Perhaps this code should leverage the existing `CheckBlockSignature(PosBlock block)` on `PosBlockSignatureRule.cs` instead?

**Comment by zeptin** [comment]
Here is the X version of the code for comparison:

https://github.com/stratisproject/stratisX/blob/master/src/main.cpp#L2352
