### ISSUE TITLE
Add a custom attribute for tests that are unreliable

### ISSUE THREAD

**Issue by mikedennis** [stratisproject/StratisBitcoinFullNode#310]
Was thinking we could do something like this https://lostechies.com/jimmybogard/2013/06/20/run-tests-explicitly-in-xunit-net/  so that we can flag tests that aren't reliable to be forced to run explicitly so they don't break the automated builds.

NUnit has an explicit attribute but it appears that XUnit doesn't have one but the above solution might be a nice compromise.

Tests that seem to fail often for me are:

BlockStoreCanReorg
WalletCanReorg 

They are useful tests but maybe we just run them manually until we can figure out a way of making them more reliable?

**Comment by Aprogiena** [comment]
nACK, there should not be any unreliable tests, marking them as such further postpones fixing them

**Comment by dangershony** [comment]
yeah we need to find out why they break (I have an idea), and this are integration tests so they don't effect the commit build and tests.

I will spend a bit of time looking at them.
