### ISSUE TITLE
Wallet showing incorrect spendable balance after POS stake

### ISSUE THREAD

**Issue by TjadenFroyda** [stratisproject/StratisBitcoinFullNode#3107]
Scenario:
1. Staked coin using POS on mainnet. 
2. Lets say I had 500 tokens and all were used for that stake. Confirmed balance would show 1001 coins (500+501). Stakeable balance is correctly decremented.
3. Correct balance shows when wallet is resynced. 

I sent details to @dev0tion on discord. 
*On latest master

**Comment by bokobza** [comment]
Thanks for the report @TjadenFroyda 🙏 
What version of the wallet are you using?

**Comment by TjadenFroyda** [comment]
SFN version 3.0.0, updated to latest master as of last night. (I see a bunch of commits this morning).

**Comment by bokobza** [comment]
Ah you're not running StratisCore? Just the console app?

**Comment by TjadenFroyda** [comment]
Correct. Headless :). 
Added a option with my recent PR so that one can connect StratisCore UI on demand without launching the daemon each time.

**Comment by bokobza** [comment]
> Correct. Headless :).
Like a boss 😎 

So the problem is that you have 500 coins but then it jumped to 1001 when you stake a coin?

**Comment by dev0tion** [comment]
Was able to reproduce this on testnet with full logs running. Jeremy is on the case @TjadenFroyda.
