### ISSUE TITLE
[Refactor] ConcurrentChain.cs contains second implementation of ReaderWriterLock

### ISSUE THREAD

**Issue by Aprogiena** [stratisproject/StratisBitcoinFullNode#313]
We have one in Stratis.Bitcoin.Utilities.ReaderWriterLock.cs, we should remove this one from ConcurrentChain.cs.

**Comment by Aprogiena** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[General] ConcurrentChain.cs contains second implementation of ReaderWriterLock](https://trello.com/c/KuwOsBb9/164-general-concurrentchaincs-contains-second-implementation-of-readerwriterlock)

**Comment by Aprogiena** [comment]
the problem here is that CC is NBitcoin, so we have one implementation in full node and other in NBitcoin

**Comment by Aprogiena** [comment]
I'd suggest here that we move ReaderWriterLock from Stratis utilities to NBitcoin's utilities because NBitcoin uses that as well and NBitcoin's version should be deleted

**Comment by dangershony** [comment]
Yeah they are the same class right so we can just use the one in NBitcoin.

**Comment by Aprogiena** [comment]
Yes, but we have comments there, therefore ours is better ;)

**Comment by dangershony** [comment]
Ah indeed, I am happy you move ours to NBitcoin so that's two PRs

**Comment by Aprogiena** [comment]
OK, trello task exists, someone will eventually pick it up or be assigned to.

**Comment by dangershony** [comment]
Related #659
