### ISSUE TITLE
Blocksonly - verify this is enforced in the handshake

### ISSUE THREAD

**Issue by dangershony** [stratisproject/StratisBitcoinFullNode#3164]
```
info: Stratis.Bitcoin.Features.MemoryPool.MempoolBehavior[0]
      Transaction ID 'de0fbc8330e4d5c1fbc8eef7a2a27705f7ead083b97082654e1f1dd57f13165c' inventory sent in violation of protocol peer '[::ffff:xxx]:49706'.
```

The `-blocksonly` argument is not sent correctly in the handshake

**Comment by zeptin** [comment]
Ok, so my finding is that we do send it in the handshake, but it is only valid from protocol version `70001` onwards. I therefore do not think that X is capable of respecting this requirement, and we should only log that debug message when a peer supports `fRelay` from BIP37:

https://github.com/bitcoin/bips/blob/master/bip-0037.mediawiki#extensions-to-existing-messages

@dangershony

**Comment by dangershony** [comment]
So this fix is only about changing the log message, very low priority and maybe not even worth doing.

**Comment by maciejzaleski** [comment]
Log level has been changed, closing the issue
