### ISSUE TITLE
BlockStore stuck - need logs

### ISSUE THREAD

**Issue by Aprogiena** [stratisproject/StratisBitcoinFullNode#317]
There is very rare bug in BlockStore during IBD. I've seen it several times before. I've tried to run about 100 IBDs today to try to confirm it before the sprint planning and I've failed, it did not occur once. But now testing the outcome of a new pull request, it is there (again).

There is not much we can (reasonably) do about it without having full logs in BlockStore. Maybe alternative is to review the code and search for it like that, but you can easily miss it that way.

I suggest we just log it.

What does it do? It simply creates a big gap during IBD between Consensus and Store:

```
      ======Node stats====== 08/14/2017 15:50:46 agent StratisBitcoin:1.0.2
      Headers.Height:    480506   Headers.Hash:     000000000000000000807de0ce829b6eb4dc04545d9768fc84088c2eb3d9940d
      Consensus.Height:  114071   Consensus.Hash:   000000000000478f1413014c8a6d85652be5103b74d75eb1adce38974922c89a
      Store.Height:      55811    Store.Hash:       0000000013d53405392513d5e7d26630c0231ace81d404224f90dedba9c6e7dd
```

Once the Store is stuck, it will stay there. I thought previously restarting the node helped, but currently I can see it does not. Which is good - I've got instance of that and if it stays like this it should be easy to find.

**Comment by Aprogiena** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[BlockStore] Bug - BlockStore stuck](https://trello.com/c/A0C6oYWY/170-blockstore-bug-blockstore-stuck)

**Comment by dangershony** [comment]
Ah that is interesting, sometimes store is stuck can be various reasons (probably on the downloading code) but it should self recover, I would be interested to know why its stack.

**Comment by dangershony** [comment]
try to add a log trace at this place in the code then you will know if its stopped because of a stalling block on download.
BlockStoreInnerStepDownloadBlocks line 54
just after the 

```
                await Task.Delay(100, context.CancellationToken);
```

I think we can definitely refactor the way blocks are downloaded on the StorePuller, for example at the moment blocks might be stuck in the StorePuller when the download step aborts, so this needs to be cleaned, but further maybe also find out why the stalling happened in the first place.

**Comment by Aprogiena** [comment]
I can confirm that if `if (context.StallCount > 10000)` was changed to `if (context.StallCount > 1000)` then I could see after a minute a progress on Store.Height

so this is a quick workaround

it still remains to find out why

**Comment by Aprogiena** [comment]
further examination of `StoreBlockPuller` logs  show that SBP is asking for a block and it is eventually delivered and SBP consumes it via `TryGetBlock`, which is called from `BlockStoreInnerStepDownloadBlocks.ExecuteAsync`

**Comment by Aprogiena** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[BlockStore] Add Logs](https://trello.com/c/01SrMyGP/177-blockstore-add-logs)

**Comment by Aprogiena** [comment]
OK, so I've added the logs - https://github.com/stratisproject/StratisBitcoinFullNode/pull/353/

So now I can see what is happening there. And this is kind of good news. There seems to be no big bug causing this. Rather this seems to be caused by unfortunate selection of arbitrary constants and it should not be problem to fix them with different selection. 

So what is going on:

1) We already knew that `BlockStoreInnerStepDownloadBlocks.ExecuteAsync` contained this line 

```
if (context.StallCount > 10000)
```

and if this `10000` was decreased to e.g. `100` the problem magically disappeared. 

The first suggestion here is to reduce this constant. It should cause no harm unless "reduced too much". The question is what is "reduced too much" here. So every stalling event has 100ms delay attached to it, so this is currently something like 10,000 * 100ms = 1,000 seconds = ~16 minutes delay before this "emergency stop" is triggered. It seems like waiting 16 minutes in case of block puller having trouble to obtain the asked block is little too much. 

With SW, the longest block must be under 4 MB in total size, so if we reduced the emergency stop from 16 minutes to 1 minute, we would allow for (i.e. require minimum of) 66kb/s Internet speed. Note that this is download speed (from our side) and the main factor here is the probably the upload speed of the peer we are connected to. 66kb/s might seem as little to hard requirement (that is for absolute max SW blocks, which will not be seen for quite a long time though!), so 2-3 minutes would probably be justified here. 

2.5 minutes = 150 seconds here would translate to the constant of 1,500 instead of original 10,000. And it should probably be a constant, not a magic number in the code.


2) Logs are pretty clear about what is happening here. We do not have the initial moment when this problem occurred, but we have logs from what happens after that. So initially block store is somewhat late to catch up with Consensus. Once this happens, the gap is ever increasing and BlockStore seems stuck. Even if the node is restarted, this changes nothing - the node starts with big gap bewteen Consensus and BlockStore and BS is stuck.

However, BS actually does download more blocks, it just ignores them because of other arbitrary constant selection. Once again we are in `BlockStoreInnerStepDownloadBlocks.ExecuteAsync`:

```
            if (context.BlockStoreLoop.BlockPuller.TryGetBlock(nextBlock, out downloadedBlock))
            {
                this.logger.LogTrace("Puller provided block '{0}/{1}', length {2}.", nextBlock.HashBlock, nextBlock.Height, downloadedBlock.Length);
                ChainedBlock chainedBlockToDownload = context.DownloadStack.Dequeue();
                context.Store.Add(new BlockPair(downloadedBlock.Block, chainedBlockToDownload));
                context.InsertBlockSize += downloadedBlock.Length;
                context.StallCount = 0;

                this.logger.LogTrace("Insert block size is {0} bytes, download stack contains {1} more blocks to download.", context.InsertBlockSize, context.DownloadStack.Count);
                if (context.InsertBlockSize > context.BlockStoreLoop.InsertBlockSizeThreshold || !context.DownloadStack.Any())
                {
```

as we can see here, once the block is provided by the puller, which normally happens, we increase `InsertBlockSize` in the context by the length of the `downloadedBlock`. Then we check if the total downloaded length is over `InsertBlockSizeThreshold`, which currently is `1000000 * 5`, that's 5 MB. And either we have to be over that or `DownloadStack` has to be empty for BS to care. Otherwise it does not care about block being delivered. The idea here is probably to avoid storing blocks to disk one by one and rather we would like to proceed in batches.

The problem here is that in IBD, downloaded block lengths of many blocks is like 236 bytes, thus we see:

```
[2017-08-19 14:07:26.1112 7] TRACE: Stratis.Bitcoin.Features.BlockStore.LoopSteps.BlockStoreInnerStepDownloadBlocks.ExecuteAsync Puller provided block '000000000af27c1a7b618ac8635b96025a5650b24c63764eca7414af6e886051/55812', length 151517.
[2017-08-19 14:07:26.1112 7] TRACE: Stratis.Bitcoin.Features.BlockStore.LoopSteps.BlockStoreInnerStepDownloadBlocks.ExecuteAsync Insert block size is 151517 bytes, download stack contains 25 more blocks to download.
...
[2017-08-19 14:07:27.9206 9] TRACE: Stratis.Bitcoin.Features.BlockStore.LoopSteps.BlockStoreInnerStepDownloadBlocks.ExecuteAsync Puller provided block '000000000018411a131b4309069305c9400569b7ac7999f34d433b2ca3ed8c4d/55867', length 236.
[2017-08-19 14:07:27.9206 9] TRACE: Stratis.Bitcoin.Features.BlockStore.LoopSteps.BlockStoreInnerStepDownloadBlocks.ExecuteAsync Insert block size is 341320 bytes, download stack contains 39 more blocks to download.
...
[2017-08-19 14:08:30.6459 26] TRACE: Stratis.Bitcoin.Features.BlockStore.LoopSteps.BlockStoreInnerStepDownloadBlocks.ExecuteAsync Puller provided block '00000000058d89f1cbc792843560b0d296ca406d6f415dbf78311ff6bbc60051/58874', length 235.
[2017-08-19 14:08:30.6459 26] TRACE: Stratis.Bitcoin.Features.BlockStore.LoopSteps.BlockStoreInnerStepDownloadBlocks.ExecuteAsync Insert block size is 1408068 bytes, download stack contains 153 more blocks to download.
```

So one thing is that if BS is behind, it uses its own block puller and that is `StoreBlockPuller`. This puller only downloads one block at the time (unlike LBP). So downloading is relatively slow. And then since blocks are so small, it takes very long time to reach that 5 MB threshold. 

So if puller has problems, we currently wait up to 16 minutes to restart. And if everything goes OK, we wait until 5 MB of blocks are downloaded one by one. And we can see it took more than 1 minute on very fast connection to get to 1.4 MB and this for blocks around 58k height. If this happened earlier, those blocks would be much smaller and it would take even longer. So again, we are here stuck for several minutes until we can see a progress. 

Batching the writes is definitely a good idea, but waiting more than 20-30 seconds is not helping with performance in any way, rather we are risking losing the work that has been done if the node/OS/electricity supply crashes.

**Comment by Aprogiena** [comment]
I've now confirmed that once we reach that 5 MB limit, the store tip goes up as expected, so this is really the full story.

**Comment by Aprogiena** [comment]
So to fix this second thing, we can either lower the 5 MB limit or introduce an alternative time limit - i.e. the condition is now:

`if we have more than 5 MB or nothing more to download` 

and we could change it either to 

`if we have more than 0.5 MB or nothing more to download` 

or 

`if we have more than 5 MB or nothing more to download or time from last save > 20 seconds`

**Comment by dangershony** [comment]
Very good analysis yes you got the point of the store pushing in batches, and yeah the download is very slow because of the 1 block for every pull( there is an task to make this more efficient where we will ask the puller for more blocks every loop not just one)

We need to remember that most of the time the store will get blocks from the consensus validator the download is only last resort, and if i am not mistaken store ia much faster then consensus on reaching the tip so it catches up quickly.

However we want to fix this for sure.
Your suggestion to add the 20 sec condition sounds right.

**Comment by Aprogiena** [comment]
OK, I'll let's go with 20 secs alternative, tx.

**Comment by Aprogiena** [comment]
And are you happy to reduce 10,000 constant (~16.6 minutes) to those 150 seconds (i.e. value of 1,500)?

**Comment by dangershony** [comment]
Yes this number was just arbitrary i choose it when playing with the store stats.
You calculations of 4 mb blocks and upload speed of avg home comnections seems reasonable so i would go for 3 min emergency stop. Also if we put a time flag on batching we can easily increase the hard 5 mb limit, so we push less often with bigger blocks  (maybe duble to 10 mb or even 20 mb)

**Comment by Aprogiena** [comment]
yes, we can increase 5 MB, not sure if 20 MB is not too much (SW blocks are likely to be 2.5 MB for a long time), but OK, no problem there

so the current plan here is 
10,000 -> 1,800
5 MB -> 20 MB
+time condition 20 secs

**Comment by fassadlr** [comment]
@Aprogiena @dangershony Is it possible that we can perhaps have these values configurable somehow?

I.e. so that InsertBlockSize and InsertBlockSizeThreshold can read the values from startup, from a config file so that we don't have to rebuild all the time? Either that or pass them in as command line parameters.

Hard-coding values like that is a bad practice, unless they never change  ;)

**Comment by Aprogiena** [comment]
@fassadlr perhaps, but that is for another issue, for sure we want to have constants instead of hard coded values and then we can discuss in another issue if we want something configurable

**Comment by dangershony** [comment]
In theory once we get a stable download processes the args wont change anymore, so hard code is fine for now (or const).
