### ISSUE TITLE
getrawtransaction not returning addresses

### ISSUE THREAD

**Issue by ek1977** [stratisproject/StratisBitcoinFullNode#3172]
I belive that this is the same issue as presented in [https://github.com/stratisproject/StratisBitcoinFullNode/issues/2731](url)

I am using Node version 3.0 and executing the rpc call: 
'{"jsonrpc": "2.0", "method": "getrawtransaction", "params": ["4bfa3a2dce4ac5280623275c91620b31aa88eaff60953b7d90a7fcee99eb3e4e", 1], "id": 1}'

This returns a pubkey type transaction but there is no list of addresses.  If the addresses are not supposed to be returned, how can I determine the address?  The raw transaction output from [https://chainz.cryptoid.info/strat/tx.dws?4bfa3a2dce4ac5280623275c91620b31aa88eaff60953b7d90a7fcee99eb3e4e.htm](url) does show the address list.

RPC Output:

'vout': [   {   'n': 0,
                                  'scriptPubKey': {   'asm': '',
                                                      'hex': '',
                                                      'type': 'nonstandard'},
                                  'value': 0.0},
                              {   'n': 1,
                                  'scriptPubKey': {   'asm': '03273624c66dad77069f005cad3556b7e22c94bad304df1616982bf87901c3a87d '
                                                             'OP_CHECKSIG',
                                                      'hex': '2103273624c66dad77069f005cad3556b7e22c94bad304df1616982bf87901c3a87dac',
                                                      'type': 'pubkey'},
                                  'value': 118.18},
                              {   'n': 2,
                                  'scriptPubKey': {   'asm': '03273624c66dad77069f005cad3556b7e22c94bad304df1616982bf87901c3a87d '
                                                             'OP_CHECKSIG',
                                                      'hex': '2103273624c66dad77069f005cad3556b7e22c94bad304df1616982bf87901c3a87dac',
                                                      'type': 'pubkey'},
                                  'value': 118.1801}]}}

**Comment by zeptin** [comment]
Note that I investigated this previously in closed PR #2770
I am not sure whether it is correct to treat P2PK transactions as having addresses in the first place, as there is no address format defined for them. I believe that what the block explorer is doing is extracting the corresponding public key and 'faking' a P2PKH address from it, which is misleading. Presumably the recipient in such a case will generally still be able to spend any received funds, but this is dependent on handling it as a special case in their wallet software.

@bokobza What do you think?

**Comment by ek1977** [comment]
@zeptin Thanks.  I saw that this was investigated but it was unclear from that post what the resolution is.  If it is correct as is, then I can deal with that but in 2731 it looked like perhaps the behavior had changed at some point.  Thanks for the consideration.

**Comment by bokobza** [comment]
The problem was that we were simply skipping the assignment of addresses.
I'm going to push a Pr that fixes this.
Thanks for reporting it @ek1977 !
