### ISSUE TITLE
TxMempoolBlockDoubleSpend test

### ISSUE THREAD

**Issue by mixitka** [stratisproject/StratisBitcoinFullNode#3221]
Hi @noescape00,

I have spent some time debugging `TxMempoolBlockDoubleSpend` test (which was removed - https://github.com/stratisproject/StratisBitcoinFullNode/commit/914b60c6ed5322cad586fafc9ccc6e5d44b4e87b - literally minutes ago) and seems that it's enough to just change:

`Assert.Throws<ConsensusException>` 

->

`Assert.ThrowsAny<ConsensusException>` 

as the later command is OK with `HeaderInvalidException` that is being throw here https://github.com/stratisproject/StratisBitcoinFullNode/blob/master/src/Stratis.Bitcoin/Consensus/ChainedHeaderTree.cs#L1058.

I ran the test like 10 times in a row with the change applied and it is always green for me. So hopefully the change fixes the test completely.

Is that a sufficient reason to bring the test back for you?

Regards,
M.

**Comment by noescape00** [comment]
That PR was taken over by @fassadlr 
Unstable tests were skipped instead of being removed. Those that were removed are duplicates. 

@fassadlr wdyt

**Comment by fassadlr** [comment]
HI @noescape00 , @mixitka yes this test has been removed as we already test for double spends in `sending_transaction_with_double_spend_in_mempool`
