### ISSUE TITLE
[Mempool] Add logging in mempool behavior

### ISSUE THREAD

**Issue by mikedennis** [stratisproject/StratisBitcoinFullNode#323]
I think there is likely an opportunity to add some trace logging to the mempool behavior node message processing. This would allow for troubleshooting the messaging between the mempool and the node.

**Comment by dangershony** [comment]
Yeah sounds like a good idea.

**Comment by bokobza** [comment]
@Aprogiena @mikedennis any of you doing this?

**Comment by Aprogiena** [comment]
I'm working on POS, so not me.

**Comment by Aprogiena** [comment]
This sort of task would require no one else working on mempool, otherwise it would be a mess. I'm very much interested in putting more logs everywhere where they are not present yet. Currently, I'm a bit overwhelmed, however.

**Comment by Aprogiena** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[Mempool] 1 Logging for mempool behavior messages.](https://trello.com/c/CVX9RPDq/195-mempool-1-logging-for-mempool-behavior-messages)

**Comment by mikedennis** [comment]
Fixed and merged into master.
