### ISSUE TITLE
Can't get any $TSTRAT through the faucet

### ISSUE THREAD

**Issue by babgev** [stratisproject/StratisBitcoinFullNode#3230]
I tried multiple addresses, and waited more than 8 hours but I don't get any $TSTRAT through the [faucet](https://faucet.stratisplatform.com/)

**Comment by babgev** [comment]
And it also accepts accounts from the main network.

**Comment by fassadlr** [comment]
@babgev can you confirm whether this is still the case?

**Comment by fassadlr** [comment]
Closing as no reply from user.
