### ISSUE TITLE
GetTransactionFeeEstimate() no longer works.

### ISSUE THREAD

**Issue by DennisAMenace** [stratisproject/StratisBitcoinFullNode#3251]
When calling GetTransactionFeeEstimate, at the end of this call during the return line, it will use InitializeTransactionBuilder when calling walletTransactionHandler.EstimateFee(context) and when initializing it's expecting a password, and will throw an exception.

A couple possible solutions:
1. We modify the TransactionBuildContext with a estimate property and will bypass the initialization of methods requiring a password, as we are only estimating the fee.

2. We can modify the TxFeeEstimateRequest to include the password and require the user to input the password before estimating the fee.

**Comment by DennisAMenace** [comment]
Never mind, I see the resolution is already being worked on.

**Comment by bokobza** [comment]
indeed, thanks @DennisAMenace !
