### ISSUE TITLE
Peer.Disconnected incorrectly set to true

### ISSUE THREAD

**Issue by dangershony** [stratisproject/StratisBitcoinFullNode#327]
@Aprogiena 
The property is set to true in this method ReleaseAllPeerDownloadTaskAssignments()
However this method is not only called when the peers is disconnected but also when a peer IsStalling()
This causes a peer that may still be useful to not be used for downloading. this is especially problematic when the node is connected to only one peer.

I think this caused some of the tests to fail randmoly

**Comment by dangershony** [comment]
A fix may be to add a flag to ReleaseAllPeerDownloadTaskAssignments(this, disconnect=false)
Then when DetachCore calls ReleaseAll() the flag is set.

**Comment by Aprogiena** [comment]
Good find and yes the resolution seems to be like you suggest. Thank you.

As the fix is rather simple, I'll add it as a part of the work I'm doing now as a separate commit.

**Comment by Aprogiena** [comment]
The only thing I was not sure about is ReleaseAll called from `LBP.RequestOptions`, but I guess it should be with disconnect set to true there.

**Comment by Aprogiena** [comment]
So I was thinking about `LBP.RequestOptions` call of ReleaseAll` and to me it seems like both true and false for disconnect would be just fine. Using false here would be little cleaner design as we would strictly use true only when the peer is actually disconnected, but using true here is preventing such peer from being assign a work in a small window which exists there. So the effect of using true is slightly less clean design with the benefit of minor edge case optimization.

I'm happy to go with either, the current code fixing this has true there.

**Comment by dangershony** [comment]
hmm yes good point, I opt for using 'true'.
