### ISSUE TITLE
[BlockExplorer] Investigate existing blockexplorer to communicate with the fullnode.

### ISSUE THREAD

**Issue by quantumagi** [stratisproject/StratisBitcoinFullNode#329]
===================================== Insight ================================
Installed Insight UI
- Found the following service end-points in "/public/src/js/services"
```
   - Transaction ("transaction.js")
      - 'Transaction' : <service url>/tx/<txid>
      - 'TransactionByBlock' : <service url>/txs/<block>
      - 'TransactionByAddress': <service url>/txs/<address>
      -  'Transactions' : <service url>/txs
   - Currency ("currency.js")
     - 'Currency' : <service url>/currency
   - Blocks ("blocks.js")
     - 'Block' : <service url>/block/<blockhash>
     - 'Blocks' : <service url>/blocks
     - 'BlockByHeight' : <service url>/block-index/<blockheight>
   - Address ("address.js")
     - 'Address' : <service url>/addr/<addrStr>/?noTxList=1
   - Status ("status.js")
     - 'Status' : <service url>/status
     - 'Sync' : <service url>/sync
    - 'PeerSync' : <service url>/peer
```

There is also a sockets interface which is probably used for real-time
display of incoming transactions on the web page:
"/public/src/js/services/socket.js"
Controllers are found in: "/public/src/js/controllers"

=========================== chainz.cryptoid.info ====================================
List of most important features for emulating
a block explorer such as cryptoID:
(https://chainz.cryptoid.info)

Block Details Page:
- Get Raw block 

Search Feature:
- Get block by height
- Get block by partial hash
- Get block by address
- Get transaction by partial hash 
- Get current block height

Largest Wallets:
- Future?

Coin Info:
- Total coins / Outstanding coins
- Difficulty

Block Info:
- Get block summary with from/to date
   - Number of blocks
   - Average block interval (seconds)
   - Total number of transactions
   - Total value out
   - Difficulty average and variance

Orphans Chart:
- Future?

**Comment by quantumagi** [comment]
From the above we can create an initial list of required API end-points:
- Task<Block> GetBlockByHeight(int height); // TODO
- Task<Block> GetAsync(uint256 hash); // Exists
- Task<Transaction> GetTrxAsync(uint256 trxid); // Exists
- Task<List<uint160>> GetScriptTransactions(uint160 address); // TODO
- Task<uint256> GetTrxBlockIdAsync(uint256 trxid); // Exists
- Task<string> GetSearchResult(string search, int options) // TODO 
   - Return list of JSON objects (transaction/address/block hashes)
- Task<string> GetNetworkInfo(int options) // TODO 
  - Returns JSON
    - Current current block height
    - Total coins / outstanding coins
- Task<string> GetBlockSummary(DateTime from, DateTime to, int options); // TODO

**Comment by bokobza** [comment]
Does // Exists refer to things we already have in the Full Node?

**Comment by dangershony** [comment]
Excellent:
- GetNetworkInfo - we might have a version of 
- GetScriptTransactions - not sure what that is
- GetSearchResult - also not sure what its about

I think we have most of the functionality in place to build the missing RPC methods.
Yeah insight uses web sockets to push memppol trx to the browser (we could do that as well with signalR) something to consider.

**Comment by quantumagi** [comment]
- //Exists refers to things we already have in the IndexStore.
- GetSearchResult - Would take a string where the string can be this first few characters from a block hash, transaction hash or Stratis address. It basically "completes" a partial hash number or address and determines if it is a transaction hash or block hash, or even a bitcoin address. It would rely on the "Transaction", "Block" and "Script" indexes to do that.
- GetScriptTransactions - This would depend on an index that returns transactions outputs (hash# + uint) 
which reference the specified script (i.e. based on "Script" index): script -> transactions.

**Comment by dangershony** [comment]
So basically we can cover all search queries with the current IndexStore?

**Comment by quantumagi** [comment]
Yeah. I forgot to add searching by block height which we should also be able to do. It's all about searching for blocks, transactions and addresses. DBreeze allows searches by partial keys so we should be good.

**Comment by bokobza** [comment]
@quantumagi @dangershony this is finished now isn't it?

**Comment by dangershony** [comment]
Yeah I think it is finished, we probably need a new task to build a UI on top of a local block explorer.
