### ISSUE TITLE
[PosMinting] Better of the two same tokens :)

### ISSUE THREAD

**Issue by mixitka** [stratisproject/StratisBitcoinFullNode#3307]
Hi,

I believe this line https://github.com/stratisproject/StratisBitcoinFullNode/blob/master/src/Stratis.Bitcoin.Features.Miner/Staking/PosMinting.cs#L288 should be changed from 

```C#
await this.GenerateBlocksAsync(walletSecret, this.stakeCancellationTokenSource.Token)
```

to 

```C#
await this.GenerateBlocksAsync(walletSecret, token)
```

`token` variable is unused at the moment.

**Comment by dangershony** [comment]
They are actually the same cancellation token, one instance is just passed via the asynchronous loop

**Comment by mixitka** [comment]
Yes. `token` is still preferable for readers' convenience.

**Comment by dangershony** [comment]
Sure submit a PR if you want to make this change.
