### ISSUE TITLE
[General] Investigate moving features completely standalone

### ISSUE THREAD

**Issue by quantumagi** [stratisproject/StratisBitcoinFullNode#331]
Current namespace level dependencies:

```
- Stratis.Bitcoin
  - Stratis.Bitcoin.Base
  - Stratis.Bitcoin.Builder
  - Stratis.Bitcoin.Configuration
  - Stratis.Bitcoin.Configuration.Logging
  - Stratis.Bitcoin.Connection
  - Stratis.Bitcoin.Features.BlockStore          (!FullNode.cs)
  - Stratis.Bitcoin.Features.Consensus           ('')
  - Stratis.Bitcoin.Features.Consensus.CoinViews ('')
  - Stratis.Bitcoin.Features.MemoryPool          ('')
  - Stratis.Bitcoin.Features.Wallet              ('')
  - Stratis.Bitcoin.Utilities
- Stratis.Bitcoin.Base
  - Stratis.Bitcoin.Builder
  - Stratis.Bitcoin.Builder.Feature
  - Stratis.Bitcoin.Configuration
  - Stratis.Bitcoin.Connection
  - Stratis.Bitcoin.Features.Consensus.Deployments
  - Stratis.Bitcoin.Signals
  - Stratis.Bitcoin.Utilities
- Stratis.Bitcoin.BlockPulling
  - Stratis.Bitcoin.Base
  - Stratis.Bitcoin.Connection
  - Stratis.Bitcoin.Utilities
- Stratis.Bitcoin.Builder
  - Stratis.Bitcoin.Base
  - Stratis.Bitcoin.Builder.Feature
  - Stratis.Bitcoin.Configuration
  - Stratis.Bitcoin.Utilities
- Stratis.Bitcoin.Configuration
  - Stratis.Bitcoin.Features.MemoryPool    (!) 
  - Stratis.Bitcoin.Configuration.Logging
  - Stratis.Bitcoin.Configuration.Settings
  - Stratis.Bitcoin.Utilities
- Stratis.Bitcoin.Connection
  - Stratis.Bitcoin.Base
  - Stratis.Bitcoin.BlockPulling
  - Stratis.Bitcoin.Configuration
  - Stratis.Bitcoin.Configuration.Logging
  - Stratis.Bitcoin.Configuration.Settings
- Stratis.Bitcoin.Features.BlockStore
  - Stratis.Bitcoin.Base
  - Stratis.Bitcoin.BlockPulling
  - Stratis.Bitcoin.Builder
  - Stratis.Bitcoin.Builder.Feature
  - Stratic.Bitcoin.Configuration
  - Stratis.Bitcoin.Configuration.Logging
  - Stratis.Bitcoin.Connection
  - Stratis.Bitcoin.Features.BlockStore.LoopSteps
  - Stratis.Bitcoin.Signals
  - Stratis.Bitcoin.Utilities
- Stratis.Bitcoin.Features.Consensus
  - Stratis.Bitcoin.Base
  - Stratis.Bitcoin.BlockPulling
  - Stratis.Bitcoin.Builder
  - Stratis.Bitcoin.Builder.Feature
  - Stratis.Bitcoin.Configuration
  - Stratis.Bitcoin.Configuration.Logging
  - Stratis.Bitcoin.Connection
  - Stratis.Bitcoin.Features.Consensus.CoinViews
  - Stratis.Bitcoin.Features.Consensus.Deployments
  - Stratis.Bitcoin.Utilities
- Stratis.Bitcoin.Features.MemoryPool
  - Stratis.Bitcoin.Base
  - Stratis.Bitcoin.Builder
  - Stratis.Bitcoin.Builder.Feature
  - Stratis.Bitcoin.Configuration
  - Stratis.Bitcoin.Connection
  - Stratis.Bitcoin.Features.Consensus
  - Stratis.Bitcoin.Features.Consensus.CoinViews
  - Stratis.Bitcoin.Features.Consensus.Deployments
  - Stratis.Bitcoin.Features.MemoryPool.Fee
  - Stratis.Bitcoin.Signals
  - Stratis.Bitcoin.Utilities
- Stratis.Bitcoin.Features.Miner
  - Stratis.Bitcoin.Base 
  - Stratis.Bitcoin.Builder 
  - Stratis.Bitcoin.Builder.Feature 
  - Stratis.Bitcoin.Features.Wallet 
  - Stratis.Bitcoin.Features.BlockStore 
  - Stratis.Bitcoin.Configuration 
  - Stratis.Bitcoin.Connection 
  - Stratis.Bitcoin.Features.Consensus 
  - Stratis.Bitcoin.Features.Consensus.CoinViews 
  - Stratis.Bitcoin.Features.Consensus.Deployments 
  - Stratis.Bitcoin.Features.MemoryPool 
  - Stratis.Bitcoin.Utilities 
- Stratis.Bitcoin.Features.Notifications
  - Stratis.Bitcoin.Base
  - Stratis.Bitcoin.BlockPulling
  - Stratis.Bitcoin.Builder
  - Stratis.Bitcoin.Builder.Feature
  - Stratis.Bitcoin.Connection
  - Stratis.Bitcoin.Signals
  - Stratis.Bitcoin.Utilities
- Stratis.Bitcoin.Features.RPC
  - Stratis.Bitcoin.Base
  - Stratis.Bitcoin.Builder
  - Stratis.Bitcoin.Builder.Feature
  - Stratis.Bitcoin.Configuration
  - Stratis.Bitcoin.Features.BlockStore (!)
  - Stratis.Bitcoin.Features.Consensus  (!)
  - Stratis.Bitcoin.Features.MemoryPool (!)
  - Stratis.Bitcoin.Features.Miner      (!)
  - Stratis.Bitcoin.Features.RPC.Converters
  - Stratis.Bitcoin.Features.RPC.ModelBinders
  - Stratis.Bitcoin.Features.Wallet     (!)
  - Stratis.Bitcoin.Utilities
- Stratis.Bitcoin.Features.Wallet
  - Stratis.Bitcoin.Builder
  - Stratis.Bitcoin.Builder.Feature
  - Stratis.Bitcoin.Configuration
  - Stratis.Bitcoin.Connection
  - Stratis.Bitcoin.Features.BlockStore
  - Stratis.Bitcoin.Features.RPC.Controllers
  - Stratis.Bitcoin.Features.MemoryPool
  - Stratis.Bitcoin.Features.MemoryPool.Fee
  - Stratis.Bitcoin.Features.Wallet.Controllers
  - Stratis.Bitcoin.Features.Wallet.Helpers
  - Stratis.Bitcoin.Features.Wallet.Models
  - Stratis.Bitcoin.Features.Wallet.Notifications
  - Stratis.Bitcoin.Features.Wallet.Validations
  - Stratis.Bitcoin.Features.Wallet.JsonConverters
  - Stratis.Bitcoin.Signals
  - Stratis.Bitcoin.Utilities
  - Stratis.Bitcoin.Utilities.JsonErrors
- Stratis.Bitcoin.Features.WatchOnlyWallet
  - Stratis.Bitcoin.Builder
  - Stratis.Bitcoin.Builder.Feature
  - Stratis.Bitcoin.Configuration
  - Stratis.Bitcoin.Features.RPC.Models
  - Stratis.Bitcoin.Features.Wallet
  - Stratis.Bitcoin.Features.Wallet.JsonConverters
  - Stratis.Bitcoin.Features.WatchOnlyWallet.Controllers
  - Stratis.Bitcoin.Features.WatchOnlyWallet.Models
  - Stratis.Bitcoin.Features.WatchOnlyWallet.Notifications
  - Stratis.Bitcoin.Signals
- Stratis.Bitcoin.Signals
  - Stratis.Bitcoin.Utilities
- Stratis.Bitcoin.Utilities
  - Stratis.Bitcoin.Features.Consensus.CoinViews (!) (DBreezeSingleThreadSession.cs)
```

**Comment by quantumagi** [comment]
There is a circular dependency between Stratis.Bitcoin and the features seen in FullNode.cs

**Comment by bokobza** [comment]
Thanks for doing that :-)
I only have a few questions:

- I'm not sure what you mean by a "circular dependency between Stratis.Bitcoin and the features references", FullNode.cs being inside the Stratis.Bitcoin project.
- Can you please give a little more details about the RPC features thing?
- Which classes are referencing features in Utilities and Configuration, and how hard would it be to make the classes in these namespaces Feature-independent?

**Comment by dangershony** [comment]
Ah nice I already see that Stratis.Bitcoin.Features.Consensus.Deployments need to go to Base

RPC will eventually be like api where only some base stuff will be in the RPC features and controller specifics go to each feature.

**Comment by quantumagi** [comment]
@bokobza 
  - Currently the features are referencing classes inside of Stratis.Bitcon and conversely the features are referencing classes inside of Stratis.Bitcoin. Hopefully this will only go one way - i.e. a reference from the features to classes inside of Stratis.Bitcoin.
  - Many features are or would want to reference the RPC feature. We can't have then have the RPC feature then also referencing those features.
  - There is not much of an issue with Utilities. We just need to ensure that Utilities does not reference that one feature that it is referencing currently: Consensus. So maybe that code can be moved into Consensus.

@dangershony 
- Maybe we can also re-factor the MemoryPool code currently present in Stratis.Bitcoin.Configuration.

**Comment by quantumagi** [comment]
> Hi this was not exactly how I planned it, ideally the fullnode should not have any dependency on any feature (maybe base feature).
> 
> So we can solve it on two ways.
> Creating a interfaces for features that will live in the fullnode or removing the dependency.
> 
> I prefer the second option:
> The fullnode exposes a property called IFullNodeServiceProvider, it should be possible for any external component to use this provider to get the service it needs.
> 
> Maybe instead of a base class we just delete the dependencies and expose a method as such
> 
> Public T NodeService<T>()
> {
>     var service = this.Services.ServiceProvider.GetService<T>()
>     if(service == null)
>       throw ...
> }
- Dan

**Comment by quantumagi** [comment]
Taken "as is" the above suggestion (2nd option) will lead to many changes to the integration tests that are referencing those properties everywhere.

There are 2 options:

- Add an extension method to the integration test NodeBuilder.cs. This means we have to add () everywhere that the properties are used.
- Create a class derived from the FullNode class for use with the integration tests and somehow get that passed back from the builder that the tests are using.

**Comment by dangershony** [comment]
Ah how about making the fullnode partial, then you can add a new partial class to features (or add a partial in the test project of each features)  that expose some of its properties.

**Comment by quantumagi** [comment]
Yeah I did consider that but unfortunately all partial-type definitions meant to be parts of the same type must be defined in the same assembly and the same module (.exe or .dll file). Partial definitions cannot span multiple modules. The main benefit of partial classes is to separate user code and generated code but it seems it must eventually be compiled into the same package. So it may not be compatible with our idea of having separate projects and I assume packages.

**Comment by quantumagi** [comment]
Please have a look at https://github.com/stratisproject/StratisBitcoinFullNode/pull/349 for the proposes changes.

**Comment by Aprogiena** [comment]
This issue has no new comment since 18th Aug and it seems like a lot has been done here. Is this finished or is something to be done here?

**Comment by dangershony** [comment]
Yes I am closing this we finished pulling all features out.
