### ISSUE TITLE
Move rules to network

### ISSUE THREAD

**Issue by dangershony** [stratisproject/StratisBitcoinFullNode#3321]
Currently the rules are registered in a way that is not as modular as we would like and they are also concentrated in the consensus project.

Ideally rules would be registered in the network class and rules that are specific to a network would be located in the projects location.

Some rules have dependency on the rules engine this needs so be considered.

See this PR that is attempting to fix this 
https://github.com/stratisproject/StratisBitcoinFullNode/pull/3198

**Comment by fassadlr** [comment]
Fixed in #3497
