### ISSUE TITLE
Global exception handling

### ISSUE THREAD

**Issue by dangershony** [stratisproject/StratisBitcoinFullNode#3324]
When an unhandled exception is caught it needs to be stored somewhere and signal somehow node is under exception

This mainly relates to AsyncQueue when a background call throws and is not handled this should be caught by some global handler and depending on how critical the error is should stop the node from advancing or printing to the consul some message (and signalling such an error).
(Also relates to AsyncLoop)

**Comment by MithrilMan** [comment]
closing this issue because it has been solved by #3455 and #3481
