### ISSUE TITLE
Wallets can be loaded twice in WalletManager

### ISSUE THREAD

**Issue by rowandh** [stratisproject/StratisBitcoinFullNode#3327]
Calling `WalletManager.Load` before `WalletManager.Start` will result in the same wallet being loaded twice.  This causes issues, particularly with `WalletManager.GetWalletByName`, which throws an exception if more than one wallet with the same name is loaded.

**Comment by rowandh** [comment]
For some more context, this is causing issues like stratisproject/StratisCore#201.

**Comment by dangershony** [comment]
>Calling WalletManager.Load before WalletManager.Start will result in the same wallet being loaded twice. 

I don't think this is possible, to call load you need to know about a wallet and to know about a wallet start needs to be called.

**Comment by rowandh** [comment]
It is happening in StratisCore - see the issue I mentioned.

StratisCore obtains the available wallets from disk, then asks `WalletManager` to load one. This can take place before `WalletManager` is initialised.

**Comment by dangershony** [comment]
Ok yeah this was clarified I agree with the fix.

**Comment by bokobza** [comment]
yeah, we're having a chat with @dev0tion to check the sequence of events and I think you're correct.
I think the fix is useful, although normally, nothing should be called before the wallet is initialized properly.
the culprit here is the api being loaded earlier that it normally is, signaling to StratisCore that the node is ready.

**Comment by dev0tion** [comment]
Hey guys, the sequence is as follows for Core:
1) Get node status
2) Go to login page on success.
3) Request wallet files '/wallet/files'
4) User selects wallet
5) On decrypt click, call '/wallet/load/' for the selected wallet name

**Comment by rowandh** [comment]
@bokobza agree with that and I think a better fix is to make sure StratisCore only uses wallets that have been loaded by WalletManager. Unfortunately this would result in long startup times for StratisCore because WalletManager is only loaded after the chain has been loaded from disk.

**Comment by dev0tion** [comment]
@rowandh I think that's OK if we have an endpoint that gets a status message so we can tell the user what's happening in the background.

**Comment by rowandh** [comment]
@dev0tion it might also be the only viable solution, because logging in before WalletManager has started means problems if users try to start staking before it has loaded. I wrote a bit more when I was looking into it [here](https://stratisplatformuk.visualstudio.com/Stratis%20Core/_workitems/edit/3229).
