### ISSUE TITLE
Add support for the additional field in getblockchaininfo

### ISSUE THREAD

**Issue by dangershony** [stratisproject/StratisBitcoinFullNode#3364]
See this comment bellow, some field are missing for RPC `getblockchaininfo` and `getnetworkinfo`

https://github.com/stratisproject/StratisBitcoinFullNode/pull/3309#issuecomment-471372001

**Comment by rowandh** [comment]
`softforks` and `bip9_softforks` added in #3925.

**Comment by dangershony** [comment]
I think the PR covers all the missing fields
