### ISSUE TITLE
[Improvement] Refactor BlockStorePuller/BlockStoreLoop so that BlockStoreInnerStepFindBlocks can ask for multiple blocks

### ISSUE THREAD

**Issue by fassadlr** [stratisproject/StratisBitcoinFullNode#339]
Set a threshold of 10 blocks to be asked for.

**Comment by fassadlr** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[BlockStore] 2 Improve how the DownloadBlocks step asks for blocks](https://trello.com/c/sBfhAgTA/167-blockstore-2-improve-how-the-downloadblocks-step-asks-for-blocks)

**Comment by fassadlr** [comment]
@dangershony I'm just looking at this and I see that we check the BatchDownloadSize before we stop asking for new blocks in BlockStoreInnerStepFindBlocks:

```
context.BlockStoreLoop.BlockPuller.AskForSingleBlock(context.NextChainedBlock);
context.DownloadStack.Enqueue(context.NextChainedBlock);

if (context.DownloadStack.Count == context.BlockStoreLoop.BatchDownloadSize)
    context.StopFindingBlocks();
```

Can't we change that BatchDownloadSize to 10 (it is currently hard coded to 1000) and then at the same time call the new method which asks for multiple blocks? Like so:

```
context.DownloadStack.Enqueue(context.NextChainedBlock);

if (context.DownloadStack.Count == context.BlockStoreLoop.BatchDownloadSize)
{
    context.StopFindingBlocks();
    context.BlockStoreLoop.BlockPuller.AskForMultipleBlocks(context.DownloadStack.ToArray());
}
```

Then in BlockStoreInnerStepDownloadBlocks we'll need to be able to potentially have BlockPuller.TryGetBlock return mulitple blocks? Somethign like this:

```
BlockPuller.DownloadedBlock[] downloadedBlocks;

if (context.BlockStoreLoop.BlockPuller.TryGetBlocks(context.DownloadStack, out downloadedBlocks))
{
```

Thoughts?

**Comment by fassadlr** [comment]
I think I might misunderstood where we want to ask for multiple blocks... Should this be done here?
```

 internal sealed class DownloadBlockStep : BlockStoreLoopStep
{
    internal DownloadBlockStep(BlockStoreLoop blockStoreLoop)
            : base(blockStoreLoop)
    {
    }

    /// <inheritdoc/>
    internal override async Task<StepResult> ExecuteAsync(ChainedBlock nextChainedBlock, CancellationToken token, bool disposeMode)
    {
        if (disposeMode)
            return StepResult.Stop;

        var context = new BlockStoreInnerStepContext(token, this.BlockStoreLoop).Initialize(nextChainedBlock);

        this.BlockStoreLoop.BlockPuller.AskForSingleBlock(nextChainedBlock);
```

In other words, should we ask for multiple blocks when the DownloadBlockStep  is called?

**Comment by dangershony** [comment]
The loop should go in BlockStoreInnerStepFindBlocks yes.

so it would be similar to this maybe.
```
      List<> toAsk
      while(...)          
      {
         context.GetNextBlock();
         
            if (await ShouldStopFindingBlocks(context))
            {
                if (!context.DownloadStack.Any())
                    return BlockStoreLoopStepResult.Break();

                context.StopFindingBlocks();
            }
            else
            {
                  if([should stop internal list])
                     break;

                 toAsk.add(context.NextChainedBlock)
           
                if (context.DownloadStack.Count == context.BlockStoreLoop.BatchDownloadSize)
                    context.StopFindingBlocks();
            }
  }
    context.BlockStoreLoop.BlockPuller.AskBlock(toAsk.ToList());
    context.DownloadStack.Enqueue(toAsk.Tolist());
```

**Comment by fassadlr** [comment]
@dangershony So last night I ran the full node from IBD for a few hours, using code similar to what you proposed, to see if the download stack will increase to 10 before asking the puller for multiple blocks.

The download stack only ever got to having one item in it before the ShouldStopFindingBlocks() causes the execution to stop finding more blocks. This is constantly happening because the next chained block is always by then in the block store's pending storage queue. Therefore I wasn't able to run into a scenario where the download stack would actually ever increase?

Maybe this cant happen once the node is fully synced?

**Comment by dangershony** [comment]
Yeah this only going to happen when downloading gets triggered, so the store needs to fall behind.
In normal operation you would normally not even go in to the download steps as all blocks will be available in the pending storage queue, if you want to simulate the download delete your 'blocks' folder this will trigger downloading all the blocks til it hits whats in pending storage queue.

**Comment by fassadlr** [comment]
@dangershony Ive got a very nice workable version now of FindBlocks asking for 10 blocks at a time. I was thinking if we cant extend this to BlockPuller.TryGetBlock to get multiple blocks at a time?

1: Ask for 10 blocks from the puller
2: If all 10 blocks exists in downloadedBlocks then push to the repository only?

E.g. add to:

`context.Store.Add(new BlockPair(downloadedBlock.Block, chainedBlockToDownload));`

until the store's count is 10.

Thoughts?

**Comment by dangershony** [comment]
Yes I think you can put a loop on each step (the arbitrary number of 10 sounds fine).
Also rename BlockStoreInnerStepDownloadBlocks to BlockStoreInnerStepReadBlocks (they are downloaded in the previous step)
