### ISSUE TITLE
[BlockPuller] Remove AutoResetEvent

### ISSUE THREAD

**Issue by Aprogiena** [stratisproject/StratisBitcoinFullNode#350]
@dangershony mentioned that it might be possible to completely get rid of pushed/consumed events in BlockPuller

I've had this idea before as well, but I've passed on it at the time as it needed little more deeper look. We want to check if we need them or not.

**Comment by Aprogiena** [comment]
@dangershony there are two events `pushed` and `consumed`

I don't think `pushed` should be removed as the logic is - peer sends block, `BlockPushed` is called, triggers `pushed` -> NBC is waiting for that and consumes it

so this is perfectly valid use and it is beneficial

so how about `consumed`? `consumed` is set when a block we were waiting for is available and we are returning it from NBC to NC.  then during the next round, NBC starts with `consumed` set, which causes `ProcessQueue` to be called (the logic is that we consumed the block -> we can possibly ask for more)

however, `ProcessQueue` is also called from `AskBlocks` and that is called from NC 
1) during the startup twice - this is uninteresting case
2) after a block was delivered in case the lookahead needs to be recalculated

however, 2) is not always the case, so that `consumed` being set does actually ends with extra `ProcessQueue` being called that would otherwise not be called

therefore it seems that `consumed` should also stay as it plays its role (although the logic is somewhat complex)

**Comment by dangershony** [comment]
A I think I actually ignores this code in my review
```  int handleIndex = WaitHandle.WaitAny(handles, WaitNextBlockRoundTimeMs);```
>Waits for any of the elements in the specified array to receive a signal

So the WaitHandle.WaitAny will block until an 'AutoResetEvent' will receive a signal (if its already in a signaled state it does not matter the wait will still block)

In this case we actually need both, I will close the issue.

**Comment by Aprogiena** [comment]
if AutoResetEvent event is signalled, WaitAny will return immediately and unset that event, so it can be signalled "from before" and the next round we run into the wait it will immediately finish, causing us to call `ProcessQueue` and then loop into wait again
