### ISSUE TITLE
The static members of Network and Consensus should be eliminated.

### ISSUE THREAD

**Issue by netsfx** [stratisproject/StratisBitcoinFullNode#358]
Instead, network and consensus should be passed around like a service or set to a single location like Consensus.Current, Network.Current. INetwork or IConsensus could add some flexibilty.

**Comment by dangershony** [comment]
Ho yeah I agree but the node generally doesn't use the static versions (only at startup)

**Comment by netsfx** [comment]
ohh, it uses it in may places, believe me :-)

**Comment by dangershony** [comment]
In the fullnode? can you show me where?

**Comment by netsfx** [comment]
some typical workarounds:

static Network()
		{
			if (!NetworkConfig.UseSingleNetwork)
			{
				_Main = new Network();
				_Main.InitMain();
				_Main.Consensus.Freeze();

				_TestNet = new Network();
				_TestNet.InitTest();
				_TestNet.Consensus.Freeze();

				_RegTest = new Network();
				_RegTest.InitReg();
			}
			
		}
public static IEnumerable<Network> GetNetworks()
		{
			if (!NetworkConfig.UseSingleNetwork) // don't yield null results
			{
				yield return Main;
				yield return TestNet;
				yield return RegTest;
			}

**Comment by netsfx** [comment]
public bool CheckProofOfWork() // Block.cs
		{
			return CheckProofOfWork(null);
		}

public bool CheckProofOfWork(Consensus consensus)
		{
			consensus = consensus ?? Consensus.Main; // you always get Consensus.Main.

**Comment by netsfx** [comment]
There are perhaps 15 places or so where you get Network.Main or Consensus.Main (or Bitcoin RegTest) instead of e.g. StratisTest. Network is often not passed on, instead taken from the properties of the Network class, so it changes silently ;-)

**Comment by netsfx** [comment]
public static Network Main // has 99 references!
		{
			get
			{
				return _Main;
			}
		}

**Comment by netsfx** [comment]
Network.TestNet has 15 and Network.RegTest has 29 references. This all goes from if you want your 'other' Network and not one of the defaults :-)

**Comment by netsfx** [comment]
closed this, to make a more detailed proposal!
