### ISSUE TITLE
Node shout down issue

### ISSUE THREAD

**Issue by dangershony** [stratisproject/StratisBitcoinFullNode#371]
Seems the node shuts down correctly but the cursor is not displayed.
Pressing enter brings it back.

It may be that the console outputs is still writing after the shoutdown this needs to be investigated.

![image](https://user-images.githubusercontent.com/7487930/29710898-4897fed8-898a-11e7-8abe-452c428b9493.png)

**Comment by Aprogiena** [comment]
I don't think there is an issue other than the one reported in https://github.com/stratisproject/Breeze/issues/181

Try running `start dotnet run` in the shell.

**Comment by Aprogiena** [comment]
How's this issue going?

**Comment by dangershony** [comment]
Ah this is solved closing
