### ISSUE TITLE
[BlockStore] Crash during shutdown - access disposed object

### ISSUE THREAD

**Issue by Aprogiena** [stratisproject/StratisBitcoinFullNode#384]
```
 BlockStore.RelayWorker threw an unhandled exception
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'DBreezeSession'.
   at Stratis.Bitcoin.Utilities.DBreezeSingleThreadSession.AssertNotDisposed()
```

called from
DBreezeSingleThreadSession.cs:line 207
from
BlockStoreSignaled.cs:line 119

**Comment by Aprogiena** [comment]
This happened when I run StratisD on testnet and in the middle of the IBD I pressed ctrl+C

**Comment by Aprogiena** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[BlockStore] Crash during shutdown - access disposed object](https://trello.com/c/r2UQ2iMR/178-blockstore-crash-during-shutdown-access-disposed-object)

**Comment by fassadlr** [comment]
I'm going to look at this now @Aprogiena

**Comment by fassadlr** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[BlockStore] Crash during shutdown - access disposed object](https://trello.com/c/r2UQ2iMR/178-blockstore-crash-during-shutdown-access-disposed-object)

**Comment by Aprogiena** [comment]
To help reproduce this, try putting `await Task.Delay(1000)` or something like that inside BlockStoreSignaled.cs RelayWorker method, inside the foreach

**Comment by bokobza** [comment]
Closed with https://github.com/stratisproject/StratisBitcoinFullNode/pull/429
