### ISSUE TITLE
[BlockStore] ProcessPendingStorage should download and persist new blocks immediately

### ISSUE THREAD

**Issue by fassadlr** [stratisproject/StratisBitcoinFullNode#392]
When a new block arrives from consensus, it needs to be downloaded and pushed to the repository immediately so that other peers can have access to it.

Currently, we will wait for a 100 blocks to download OR 200secs before we push to the repository.

**Comment by dangershony** [comment]
Indeed we need to override that 100/200sec condition if not in IBD.
This is important as it will slow the propagation of a block
