### ISSUE TITLE
[POS] CreateCoinStake loop looking for staking solution could be improved

### ISSUE THREAD

**Issue by Aprogiena** [stratisproject/StratisBitcoinFullNode#393]
The loop searches backwards for solutions with older times and the timestamp mask check is wrongly placed.

**Comment by Aprogiena** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[POS] CreateCoinStake loop looking for staking solution could be improved](https://trello.com/c/ZDuvh8G3/187-pos-createcoinstake-loop-looking-for-staking-solution-could-be-improved)

**Comment by Aprogiena** [comment]
Also 
`if (context.Stake.HashProofOfStake != null)` could probably be removed.

**Comment by Aprogiena** [comment]
Also below the loop

`if ((nCredit == 0) || (nCredit > (nBalance - this.reserveBalance)))`

this is probably wrongly positioned, it should only disqualify only one output, not all of them.

**Comment by Aprogiena** [comment]
Similarly to the first comment, the checks of 
`scriptPubKeyKernel = coin.TxOut.ScriptPubKey`
are probably faster than calling CheckKernel.

**Comment by Aprogiena** [comment]
also the condition inside SignBlock, just before CreateCoinStake is called
```
if (searchTime > this.lastCoinStakeSearchTime)
```

could be moved one level up to GenerateBlocks, which would make the whole process even cleaner and save the node from doing more useless work

**Comment by dangershony** [comment]
All very good comments indeed. 
This is how the logic was pulled from X so for sure I am up for improving it.
