### ISSUE TITLE
Mempool Management

### ISSUE THREAD

**Issue by nopara73** [stratisproject/StratisBitcoinFullNode#3956]
In the [MempoolBehavior](https://github.com/stratisproject/StratisBitcoinFullNode/blob/master/src/Stratis.Bitcoin.Features.MemoryPool/MempoolBehavior.cs) class what is your strategy of sending out the `GetDataPayload` to the node?

https://github.com/stratisproject/StratisBitcoinFullNode/blob/fe218bb1df7a041562d3b53c7d8fde1668912272/src/Stratis.Bitcoin.Features.MemoryPool/MempoolBehavior.cs#L310-L331

As I see you guys reply with `GetDataPayload` to every `INV`, except if you're in blocksonly mode or you already have the tx in `orphans`, which I'm not sure what that is.  

Now, if you already proceed the transaction, because another node already sent it to you (every node has its own `MempoolBehavior` instance) then you ask for that transaction again, right?

Pinging @molnard.

**Comment by dangershony** [comment]
Orphans are trasnactions that we don't know the input for, if a trx is spending an unconfirmed input and for some reason the child arrived before the parent it will go in to orphans, when the parent arrives it will then from orphans in to the mempool.

If you mean relay then yeah we relay all trx we received and validated to all peers, this should be the same logic applied in core

**Comment by nopara73** [comment]
I created a PR, I hope that explains what I think I've found.

**Comment by nopara73** [comment]
Actually the orphans do the job, they aren't just orphans: https://github.com/stratisproject/StratisBitcoinFullNode/pull/3958#discussion_r326110458
