### ISSUE TITLE
[POS] StakeValidator.CheckKernel accesses disposed coinview

### ISSUE THREAD

**Issue by Aprogiena** [stratisproject/StratisBitcoinFullNode#397]
```
      PosMining.Mine threw an unhandled exception
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'DBreezeSession'.
   at Stratis.Bitcoin.Utilities.DBreezeSingleThreadSession.AssertNotDisposed()
   at Stratis.Bitcoin.Utilities.DBreezeSingleThreadSession.Execute[T](Func`1 act)
   at Stratis.Bitcoin.Features.Consensus.CoinViews.DBreezeCoinView.FetchCoinsAsync(uint256[] txIds)
   at Stratis.Bitcoin.Features.Consensus.CoinViews.CachedCoinView.<FetchCoinsAsync>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Stratis.Bitcoin.Features.Consensus.StakeValidator.CheckKernel(ContextInformation context, ChainedBlock pindexPrev, UInt32 nBits, Int64 nTime, OutPoint prevout, Int64& pBlockTime)
   at Stratis.Bitcoin.Features.Miner.PosMinting.CreateCoinStake(List`1 stakeTxes, ChainedBlock pindexBest, Block block, Int64 nSearchInterval, Int64 fees, Transaction& txNew, Key& key)
   at Stratis.Bitcoin.Features.Miner.PosMinting.SignBlock(List`1 stakeTxes, Block block, ChainedBlock pindexBest, Int64 fees)
   at Stratis.Bitcoin.Features.Miner.PosMinting.GenerateBlocks(WalletSecret walletSecret)
   at Stratis.Bitcoin.Features.Miner.PosMinting.<>c__DisplayClass33_0.<Mine>b__0(CancellationToken token)
   at Stratis.Bitcoin.Utilities.AsyncLoop.<>c__DisplayClass8_0.<<StartAsync>b__0>d.MoveNext()
```

this happened when I pressed ctrl+C and it was probably this line in the code 

```
            FetchCoinsResponse coins = this.coinView.FetchCoinsAsync(new[] { prevout.Hash }).GetAwaiter().GetResult();
``` 

that accessed coinView that was disposed at that moment.
Mining should be terminated before coinviews are disposed.

**Comment by Aprogiena** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[POS] StakeValidator.CheckKernel accesses disposed coinview](https://trello.com/c/sSLsoEkz/188-pos-stakevalidatorcheckkernel-accesses-disposed-coinview)

**Comment by dangershony** [comment]
I think this is the case, its a bug and probably mining is not disposed properly.

**Comment by fassadlr** [comment]
Hi @Aprogiena! I've looked through the code and I believe that this issue has been fixed already.

In MiningFeature.cs we already properly dispose of both POW and POS loops when shutting down:

```
        ///<inheritdoc />
        public override void Stop()
        {
            this.powLoop?.Dispose();
            this.posLoop?.Dispose();
        }
```

I've also tested this and it works correctly.

HOWEVER, if I enable POW mining then the loop seems to go on forever? And there's now way to check for the cancellation token or anything to stop the while here (in PowMining.GenerateBlocks):

```
while (nHeight < nHeightEnd)
            {
                try
                {
                    if (this.chain.Tip != this.consensusLoop.Tip)
                    {
                        Task.Delay(TimeSpan.FromMinutes(1), this.nodeLifetime.ApplicationStopping).GetAwaiter().GetResult();
                        continue;
                    }

                    BlockTemplate pblockTemplate = this.blockAssemblerFactory.Create().CreateNewBlock(reserveScript.reserveSfullNodecript);

                    this.IncrementExtraNonce(pblockTemplate.Block, this.chain.Tip, nExtraNonce);
                    Block pblock = pblockTemplate.Block;

                    while ((maxTries > 0) && (pblock.Header.Nonce < InnerLoopCount) && !pblock.CheckProofOfWork())
                    {
                        ++pblock.Header.Nonce;
                        --maxTries;
                    }
```

That first while or the second doesn't check cancellation, so it might take days to complete? Or am I wrong here... ?

**Comment by Aprogiena** [comment]
The problem is probably there even with POS mining, although very minor. In POS mining loop if we do not mine the block we use Task.Delay, which throws on app end due to cancellation. However, in rare case that we would mine many blocks in a row, we would probably mine and mine and not end. 

So likely both POW and POS loops are not cancellable and a simple couple of IFs against the app end token would solve it. 

As for the crash issue - I think you are right, I do believe this issue was before this refactoring you mention and before the wait for the async loop. So let's just focus on finishing those loops when app ends and we're done.

**Comment by dangershony** [comment]
Hi guys I have added some places in POS loops this code
``` this.nodeLifetime.ApplicationStopping.ThrowIfCancellationRequested();```
But we probably need to also add such code in the POW code.
Also instead of using 
```while(true)```
use
```  while (!this.nodeLifetime.ApplicationStopping.IsCancellationRequested) ```

**Comment by dangershony** [comment]
yeah or maybe easier is to add to the body a `ThrowIfCancellation`

**Comment by Aprogiena** [comment]
@dangershony i can see those throws and frankly, i don't like them as they are now. first, one is unnecessary (it interrupts work that is quick even for very big miner). second, they disturb consistency of logs when they trigger.

the one here:
```
            this.logger.LogTrace("Trying to reduce our staking UTXO set by adding additional inputs to coinstake transaction...");
            foreach (StakeTx stakeTx in setCoins)
            {
                this.nodeLifetime.ApplicationStopping.ThrowIfCancellationRequested();
```

is imho completely unncessary, this loop finishes in no time even for very large miner

the other one in CreateCoinStake inner for loop is justified as that takes significant amount of time to complete, but i would suggest we handle the method exit correctly towards consistent logs

**Comment by Aprogiena** [comment]
@dangershony So I have created this tiny PR based on this argument I've presented. If you agree with the rationale, feel free to accept PR, if not, feel free to argue against and reject it.
