### ISSUE TITLE
[Wallet-POS] When mining, wallet is able to lose track of coins

### ISSUE THREAD

**Issue by Aprogiena** [stratisproject/StratisBitcoinFullNode#399]
Started mining on testnet with 500k coins, after some time I only have 340k coins

**Comment by dangershony** [comment]
I beleive this is related to #405.

**Comment by Aprogiena** [comment]
I don't know, #405 crashes the node. This one just loses coins over the time without any node stability issue.

**Comment by Aprogiena** [comment]
#405 has been resolved, but the staking wallet seems to still lose track of the coins.

**Comment by Aprogiena** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[Wallet-POS] When mining, wallet is able to lose track of coins](https://trello.com/c/48dciAz8/252-wallet-pos-when-mining-wallet-is-able-to-lose-track-of-coins)

**Comment by bokobza** [comment]
Is this still an issue @Aprogiena ?

**Comment by Aprogiena** [comment]
I believe so, because no one investigated the cause and no one fixed it yet and it was recently confirmed.

**Comment by dangershony** [comment]
I did fix the wallet crash on reorg in the wallet, but if you still get this bug we need to investigate.

**Comment by bokobza** [comment]
do you have a copy of your wallet file?
should be a *wallet.json file in %appdata%\StratisNode\stratis\StratisTest

**Comment by Aprogiena** [comment]
I do have that, but I think we don't have enough logs in the wallet part. I haven't focused on this issue yet. I believe a correct approach here is to add logs to wallet, then reproduce the issue, then check the logs and possibly compare with the wallet file. Just using the wallet file is probably too much work as it is almost 10k line file.

**Comment by bokobza** [comment]
yeah but the wallet file can give me some clues. Do you mind sending it to me @Aprogiena ?

**Comment by Aprogiena** [comment]
np, if you want to spend time on this, sending via slack

**Comment by Aprogiena** [comment]
Alright, so we've got something here. So, I've added couple more logs to test this issue. So, now I can see `Wallet contains {0} coins.` which is a total number of coins, coming from this call:

```
this.walletManager.GetSpendableTransactionsInWallet(walletSecret.WalletName, 0);
```

Then I have the set that is used for staking, which is coming from 
```
this.walletManager.GetSpendableTransactionsInWallet(walletSecret.WalletName, 1);
```
and is logged as `Wallet contains {0} confirmed coins.`.

So the first gives me total number of coins that the wallet is aware of and the second gives me how many coins in total can possibly be used in a new round for staking (those are then filtered even more as per their maturity).

So we were staking for some time:
```
[2017-10-07 14:53:51.5570 3222] TRACE: Stratis.Bitcoin.Features.Miner.PosMinting.GenerateBlocks ()
[2017-10-07 14:53:51.5570 3222] TRACE: Stratis.Bitcoin.Features.Miner.PosMinting.GenerateBlocks Current coinstake time 1507388016 is not greater than last search timestamp 1507388016.
[2017-10-07 14:53:51.5570 3222] TRACE: Stratis.Bitcoin.Features.Miner.PosMinting.GenerateBlocks (-)[NOTHING_TO_DO]
```

and then a new round of staking started:
```
...
[2017-10-07 14:53:53.3843 3235] TRACE: Stratis.Bitcoin.Features.Miner.PosMinting.GenerateBlocks Wallet contains 1000751.00450280 coins.
...
```
Then a list of UTXOs was in log from this thread 3235, which is the staking loop.

Then we can see in the log:

```
[2017-10-07 14:53:54.3166 6] TRACE: Stratis.Bitcoin.Features.Consensus.PosConsensusValidator.CheckBlockHeader ()
```

So suddenly a different thread (consensus loop) is coming with a new block validation.

The new block is validated and executed as expected in `AcceptBlock`. What is weird that we start to see the following warnings:

```
[2017-10-07 14:53:54.6011 6] WARN: Stratis.Bitcoin.Features.Wallet.WalletSyncManager.ProcessBlock Wallet is behind the best chain and the next block is not found in store
[2017-10-07 14:53:54.7881 6] WARN: Stratis.Bitcoin.Features.Wallet.WalletSyncManager.ProcessBlock Wallet is behind the best chain and the next block is not found in store
```
Something is wrong.

The previous state of chains and its transition:

```
[2017-10-07 14:53:52.6324 3221] INFO: Stratis.Bitcoin.FullNode.<StartPeriodicLog>b__70_0 ======Node stats====== 10/07/2017 14:53:52 agent StratisBitcoin:1.0.2
Headers.Height:        140152   Headers.Hash:         bfcc72b382af6ccafc8701ecce27938c55f93df5457a31999efec20796d054ce
Consensus.Height:      140152   Consensus.Hash:       bfcc72b382af6ccafc8701ecce27938c55f93df5457a31999efec20796d054ce
BlockStore.Height:     140152   BlockStore.Hash:      bfcc72b382af6ccafc8701ecce27938c55f93df5457a31999efec20796d054ce
Wallet.Height:         140152   Wallet.Hash:          bfcc72b382af6ccafc8701ecce27938c55f93df5457a31999efec20796d054ce

--->

[2017-10-07 14:53:57.6348 3276] INFO: Stratis.Bitcoin.FullNode.<StartPeriodicLog>b__70_0 ======Node stats====== 10/07/2017 14:53:57 agent StratisBitcoin:1.0.2
Headers.Height:        140153   Headers.Hash:         885054095fe7028d0912ea5fd3e678757eec122b483e0a402c3ac4542c273bbe
Consensus.Height:      140153   Consensus.Hash:       885054095fe7028d0912ea5fd3e678757eec122b483e0a402c3ac4542c273bbe
BlockStore.Height:     140151   BlockStore.Hash:      fc66f8964e2f118d672e2adf9741836f4c170bda1564ffe0c58051f1714f3cc1
Wallet.Height:         140151   Wallet.Hash:          fc66f8964e2f118d672e2adf9741836f4c170bda1564ffe0c58051f1714f3cc1

```



Meanwhile the staking thread is still analyzing UTXOs:

```
[2017-10-07 14:53:54.7881 3235] TRACE: Stratis.Bitcoin.Features.Miner.PosMinting.GenerateBlocks Wallet contains 1000751.00450280 confirmed coins.
```

So, what we can see here is that the coins available for staking are actually all the coins that the wallet holds. That is correct. We then try to find a solution:
```
[2017-10-07 14:53:54.8821 3235] TRACE: Stratis.Bitcoin.Features.Miner.PosMinting.StakeAndSignBlock Search interval set to 16, last coinstake search timestamp set to 1507388032.
```
and a filtering as per coin maturity is done, at which end we have:

```
[2017-10-07 14:53:56.3666 3235] INFO: Stratis.Bitcoin.Features.Miner.PosMinting.CreateCoinStake Node staking with 994885.64450280 (23.35 % of the network weight 4261015.23154583), est. time to find new block is 00:04:34.
```

This is absolutely fine. We did find some blocks recently, so not all coins are available for staking now.
However, staking code detects reorg:

```
[2017-10-07 14:53:56.3666 3235] TRACE: Stratis.Bitcoin.Features.Miner.PosMinting.CreateCoinStake Trying UTXO from address 'TTxekXWzTuqPfynmc2gaMPaizLUKNvHXhA', output amount 7813.48000000...
[2017-10-07 14:53:56.3666 3235] TRACE: Stratis.Bitcoin.Features.Miner.PosMinting.CreateCoinStake (-)[REORG]:false
```

Consensus loop gets another block:
```
[2017-10-07 14:53:56.3666 6] TRACE: Stratis.Bitcoin.Features.Consensus.PosConsensusValidator.ContextualCheckBlockHeader Height of block is 140153, block timestamp is 1507388032, previous block timestamp is 1507387984, block version is 0x7.
```

Then the next staking round starts, but there is nothing to do:
```
[2017-10-07 14:53:56.8703 3235] TRACE: Stratis.Bitcoin.Features.Miner.PosMinting.GenerateBlocks New block '885054095fe7028d0912ea5fd3e678757eec122b483e0a402c3ac4542c273bbe/140153' detected, setting last search time to its timestamp 1507388032.
[2017-10-07 14:53:56.8703 3235] TRACE: Stratis.Bitcoin.Features.Miner.PosMinting.GenerateBlocks Current coinstake time 1507388032 is not greater than last search timestamp 1507388032.
[2017-10-07 14:53:56.8703 3235] TRACE: Stratis.Bitcoin.Features.Miner.PosMinting.GenerateBlocks (-)[NOTHING_TO_DO]
```

that is normal. But as the time goes up, the next round starts and suddenly:

```
[2017-10-07 14:54:09.8666 2395] TRACE: Stratis.Bitcoin.Features.Miner.PosMinting.GenerateBlocks Wallet contains 999772.44450280 coins.
...
[2017-10-07 14:54:11.2012 2395] TRACE: Stratis.Bitcoin.Features.Miner.PosMinting.GenerateBlocks Wallet contains 999772.44450280 confirmed coins.
```

Coins are missing.

So we need to find which coins are actually missing. 

I just send this comment to avoid data loss and will continue.

**Comment by Aprogiena** [comment]
We can also see that at the time of the problem, this happened
```
[2017-10-07 14:53:53.9443 6] TRACE: Stratis.Bitcoin.Features.Consensus.CoinViews.CachedCoinView.Rewind ()
```

we know that thread 6 is the consensus loop thread.

**Comment by Aprogiena** [comment]
To recap chains:

```
140150 - 96e24257f5cc45b9883982448b84f4a8ab961d3aa5a76964d325b9e94e7e7143 (mined NOT by our node)
140151 - fc66f8964e2f118d672e2adf9741836f4c170bda1564ffe0c58051f1714f3cc1 (mined NOT by our node)
140152a - bfcc72b382af6ccafc8701ecce27938c55f93df5457a31999efec20796d054ce (mined **by our node**)
-> reorg
140152b - a125b4fc59368dc1fe0c66a522b3ad508e603f5f916e7c0f14710ed5dad1864f (mined NOT by our node)
140153b - 885054095fe7028d0912ea5fd3e678757eec122b483e0a402c3ac4542c273bbe (mined NOT by our node) 
-> reorg
140153c - beaab6420922fd0027ef87c192e64aa74dee5c2275affc4aeadc9f1ffd491b47 (mined NOT by our node)
140154c - 3fd5d9ce0aeaa9728178d0929c6bf0d6c597f8ac47344af99f1e5a0c355d3f2e (mined NOT by our node)
```

**Comment by Aprogiena** [comment]
Having a diff between UTXO sets before and after (while losing 978.56 coins meanwhile):
```
Comparing files list1b.txt and LIST2B.TXT
***** list1b.txt
UTXO '22b0f5454b017f12660f2ba2c43167a17c467c563779c8662981cafb692f04ab/1' with value 1954.12000000.
UTXO '23628d6bdb01d7f8012a082e21f26648b1cf523d90b2d3e16d2ad39c5e173e8e/1' with value 489.28000000.
UTXO '23628d6bdb01d7f8012a082e21f26648b1cf523d90b2d3e16d2ad39c5e173e8e/2' with value 489.28000000.
UTXO '2562cf7ae209960fa7d8fe26025f6165346f3ef2fbcef5197ee9767311508a9e/1' with value 977.56000000.
***** LIST2B.TXT
UTXO '22b0f5454b017f12660f2ba2c43167a17c467c563779c8662981cafb692f04ab/1' with value 1954.12000000.
UTXO '2562cf7ae209960fa7d8fe26025f6165346f3ef2fbcef5197ee9767311508a9e/1' with value 977.56000000.
*****
```

This reveals that two outputs from transaction `23628d6bdb01d7f8012a082e21f26648b1cf523d90b2d3e16d2ad39c5e173e8e` gone missing. Unsurprisingly, this is most likely the coinstake transaction of block 140152a which was then reorged to 140152b, which probably caused the coins to be missing.

**Comment by Aprogiena** [comment]
Therefore: **if you mine a block, which is reorged then, you lose track of coinstake transaction outputs**

**Comment by Aprogiena** [comment]
Not only that, it seems that if you sent any transaction (not just coinstake) to a block that was reorged, the wallet will lose track of it.

The only way for the wallet to be aware of a transaction is via `AddTransactionToWallet`. This method is only called when a new transaction is observed and propagated via signals.

When a reorg happens, `RemoveBlocks` is called. The interesting part of this method is this:
```
                IEnumerable<HdAddress> allAddresses = this.keysLookup.Values;
                foreach (HdAddress address in allAddresses)
                {
                    List<TransactionData> toRemove = address.Transactions.Where(w => w.BlockHeight > fork.Height).ToList();
                    foreach (TransactionData transactionData in toRemove)
                        address.Transactions.Remove(transactionData);
                }
```

As we can see this rolls backs transactions from the new blocks. This is correct approach except that you need not only to remove new transactions, but you also need to add transactions that were removed (i.e. spent in these new blocks). This is not happening anywhere in this method (or any other, but it belongs here). 

So, we mined a block, this means we spent UTXO as a coinstake transaction and created couple new outputs. Then this block was reorged and this method `RemoveBlocks` was called, which removed the new couple, but did not returned us the UTXO from coinstake. Therefore we lost track of those coins.

**Comment by dangershony** [comment]
If you notice `RemoveBlocks`  is called from sync manager in case of a reorg, after that call to `RemoveBlocks` we do indeed call `ProcesseBlock` which in turn calls `ProcessesTransaction`.

However you are very close, the way we mark an output as spent is by attaching additional data to the UTXO (the TransactionData object) I noticed that the code does not undo that (i.e we only remove reorged trx but we don't remove the data that mark the output as spent).

Good spot I will issue a fix.
However as part of this task I will also make the Consensus code that accepts a block sequential (thread safe)

**Comment by Aprogiena** [comment]
I don't really agree that the `ProcessBlock` called after `RemoveBlocks` is relevant. Unless I'm missing something, that `ProcessBlock` deals with blocks from the "new" chain, not from the old chain. But we need to process blocks from the old chain in order to get the UTXOs back.

But then basically we are talking about the same thing - with not undoing spent transactions.

**Comment by Aprogiena** [comment]
Oh, I can see you created a new issue. Yes exactly that was what I meant. I think we are talking about the same thing really.

**Comment by Aprogiena** [comment]
Oh, it is not an issue, it is a pull request :D
