### ISSUE TITLE
[POS] 3 or more peers are required for mining, but it is not enforced

### ISSUE THREAD

**Issue by Aprogiena** [stratisproject/StratisBitcoinFullNode#401]
The logic in `PosMinting.cs` in `GenerateBlocks` is weird:
```
if (tryToSync)
                {
                    tryToSync = false;
                    // TODO: This condition to have at least 3 peers is disqualifying us on testnet quite often.
                    // Yet the 60 secs delay does not prevent us to mine because tryToSync will be false next time we are here
                    // unless we are completely disconnected. So this is weird logic.
                    bool fewPeers = this.connection.ConnectedNodes.Count() < 3;
                    bool lastBlockTooOld = this.chain.Tip.Header.Time < (this.dateTimeProvider.GetTime() - 10 * 60);
                    if (fewPeers || lastBlockTooOld)
                    {
                        if (fewPeers) this.logger.LogTrace("Node is connected to few peers.");
                        if (lastBlockTooOld) this.logger.LogTrace("Last block is too old, timestamp {0}.", this.chain.Tip.Header.Time);

                        Task.Delay(TimeSpan.FromMilliseconds(60000), this.nodeLifetime.ApplicationStopping).GetAwaiter().GetResult();
                        continue;
                    }
                }
```

it seems like we want at least 3 peers, but we only wait 1 minute and don't check again (previously where was not even the wait). This is also a problem on testnet, it is not unusual to be connected to just one peer there. 

What to do with it? Do we want this condition at all? It kind of makes sense (for mainnet), but current implementation does not make sense (just wait 1 minute and don't check again?).

**Comment by dangershony** [comment]
This is probably related to the syncing of time with peers, maybe its not crucial thats why we wait a 1 and continue. If the node is not in the right time eventually when it will sync with peers the out of time mined blocks will be rejected.

**Comment by Aprogiena** [comment]
I think the code wants to prevent us mining if we are not well connected. I'm talking solely about `feePeers` condition here. So please consider the issue only in context of that condition.

**Comment by dangershony** [comment]
This is probably related to the syncing of time with peers, maybe its not crucial thats why we wait a 1 and continue. If the node is not in the right time eventually when it will sync with peers the out of time mined blocks will be rejected.

**Comment by Aprogiena** [comment]
I don't understand. How is this related to time syncing? The code just looks for how many nodes are we connected to. There is no time taken in account.

**Comment by Aprogiena** [comment]
To provide rationale why to open the bug - as it is now, it causes trouble on testnet, so at least, we should fix it for testnet. Although I am quite sure we want to fix this in general.

**Comment by dangershony** [comment]
Ah I think one should avoid posting from mobile (I didn't close this issue)

**Comment by dangershony** [comment]
Ah so I think the time delay is to allow more nodes to connect, when we connect to a node I suspect the time sync will start and if sever nodes have a different time a message will be sent to the user.

I think the logic is ok, as on testnet we will just wait a bit longer before the m staking starts.

**Comment by Aprogiena** [comment]
the delay is there every time a new block is mined, as such it has a great negative effect, it is not one time event

we should agree on what is desirable - do we want the node to be well connected before it starts mining? if yes, make it requirement (except for testnet), otherwise remove this code

i can't see a benefit of waiting after each new block

**Comment by dangershony** [comment]
As discussed this code needs to be refactored a bit:
We need two loops
- First happens only once, if not many peers are connected then wait a bit (use cancellation token).
- Second waits indefinitely for the node to be in staking state if:
-- not in IBD 
-- connected to at least one peer
-- consensus tip equals header tip
-- cancellation is signaled

**Comment by Aprogiena** [comment]
the second wait is there already, so just the first one,
but it needs a bit refactoring for sure

the problem is how do we implement the only once wait? 
it seems odd to use static variable for that, but current design does not allow anything else
and it seems odd to change current design because of just that

**Comment by dangershony** [comment]
This can be closed right?

**Comment by Aprogiena** [comment]
I would rather leave it open until it is implemented. If this is closed now, we will forget we want to improve that part.

**Comment by Aprogiena** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[POS] Three or more peers are required for mining, but it is not enforced](https://trello.com/c/NJTf3S3k/253-pos-three-or-more-peers-are-required-for-mining-but-it-is-not-enforced)

**Comment by dangershony** [comment]
Ah I was asking if this was implemented already, yeah keep open.

**Comment by Aprogiena** [comment]
Rereading whole issue here again, I think we just want to remove the code and don't have this one time wait.

What are the pros and cons of having the one time wait?

Pros: 
- you are likely to have lower orphan rate if you start staking later

Cons:
- even if you are just connected to one node, it is a chance that your block will be propagated to whole network and accepted, so if you did not try, you could lose money

anything else? Because if there are no more pros, orphan rate can just be ignored, there is no penalty for the staker to find orphan. Your best strategy should be to start staking as soon as possible and as soon as it has any chance to succeed, which is once you have at least one connection and you are synced.

**Comment by Aprogiena** [comment]
So the only question here is probably what to do with the second check in this code that can produce `Last block is too old` message in the log. This is when the last block you are aware of is just too old (10 minutes). However, with the same arguments as before, the worst that can happen is that you find a block that won't be accepted. So I'd remove this as well.

**Comment by dangershony** [comment]
Another reason is the time stamp, to get an bigger time sample for time sync.
Yeah true worth case the block will be rejected.
