### ISSUE TITLE
[POS] Block rejected by peers

### ISSUE THREAD

**Issue by Aprogiena** [stratisproject/StratisBitcoinFullNode#403]
If at least one peer does not accept our new block in 100 seconds, we lost 100 seconds of mining, then we raise exception and start over. This should be optimized.

**Comment by dangershony** [comment]
Maybe however 100 seconds should not happen really, it means something went wrong. But lets look at what x is doing. I'll find the code.

**Comment by Aprogiena** [comment]
Regardless of what X is doing, I'd like to ask why are we waiting at all? If we continue staking from very next second, what could go wrong? We could find another block and present it to the network. Now provided that the first would be rejected, the second might also be rejected.

And the question is whether that leads to banning our node or not. If not, we will eventually get the best chain from our peers, or we will make them believe ours is best. 

So in this issue I'm looking for answering 
- will presentation of wrong chain block lead to banning the node?
- how the best chain is recognized? Is it like in POW - i.e. the chain with most work on it (i.e. sum of met difficulty targets)?

**Comment by dangershony** [comment]
- There are several banning points, if its a consensus reason the ban, I believe, is for the lifetime of the banning node (i.e. a restart is required).
- Yeah its same as POW, there is a target and a block with more work (stake) is selected.  
- Limits of a reorg is checkpoint, but there might also be a stop limit( if a Size > N reorg was detected stop processing and just notify the user to delete the db).

**Comment by Aprogiena** [comment]
New data coming - if one of the node's peers is in IBD, it is total disaster, because obviously that peer does not have its tip set to the block we just mined, so in such a case all our blocks are considered as "rejected by peers" because of this one node that is in IBD.

**Comment by dangershony** [comment]
Ahhh well that is certainly a bug, I'd even say the whole reason I added the wait for peers to reply is just when testing POS on the c# node perhaps we may want to remove that check all together.

**Comment by Aprogiena** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[POS] Block rejected by peers](https://trello.com/c/9awet2YL/254-pos-block-rejected-by-peers)

**Comment by mikedennis** [comment]
Hi guys, just to confirm what we want to do here. Try getting rid of the following code and see what happens? https://github.com/stratisproject/StratisBitcoinFullNode/blob/master/Stratis.Bitcoin.Features.Miner/PosMinting.cs#L405-L435

**Comment by Aprogiena** [comment]
Yes, I think exactly those lines should be removed and it will do no harm because there is nothing useful for us anymore.

**Comment by mikedennis** [comment]
Sounds good. I might have to get you to test as I don't think I'm set up to POS stake.

**Comment by Aprogiena** [comment]
We definitely need more ppl testing POS, so if you don't have it, just ask :) First what you need is testnet coins, ask @dangershony for those. You obviously need a wallet that the coins will be sent to, so start with that - for that you might appreciate installing Breeze wallet.

**Comment by mikedennis** [comment]
Ok - yeah I would like to get it working so I can see how it works.
