### ISSUE TITLE
add config option for CachedCoinView size

### ISSUE THREAD

**Issue by jlopp** [stratisproject/StratisBitcoinFullNode#4047]
The cache is [currently hard coded to 100,000 UTXOs](https://github.com/stratisproject/StratisBitcoinFullNode/blob/c0cb4c88e895a51e33d206941ddd8634fd5b6457/src/Stratis.Bitcoin.Features.Consensus/CoinViews/CachedCoinView.cs#L58), but when doing a sync on a beefy system with a ton of RAM it would be helpful if this number could be increased in order to speed up initial sync.

**Comment by dangershony** [comment]
While true unfortunately the given value does not represent UTXOs but whole transactions, Stratis coinview implementation is still based on the previous coinview design (per trx not UTXO).

Still I agree it's useful to be able to boost total cache count.
