### ISSUE TITLE
Update project to .net standard 2.0 and .net core 2.0?

### ISSUE THREAD

**Issue by joshua-mng** [stratisproject/StratisBitcoinFullNode#409]
This project has become one of the few projects I'm keeping eye on, can't wait it becomes more stable.

Since .NET core and standard 2.0 are released, should you upgrade?

Wouldn't mind helping in migrating!

**Comment by bokobza** [comment]
Hi @joshua-mng, yes, investigating the migration (and hopefully migrating) is in the plan for this sprint.
Are you in our code contributors channel on Slack?

**Comment by dangershony** [comment]
Thanks @joshua-mng for the support. 

You are welcome to help with contributing or even running a C# testnet node if you have a spare server lying around.

**Comment by dangershony** [comment]
We are now upgraded thanks.
