### ISSUE TITLE
[WatchOnlyWallet] Missing functionality to get balances

### ISSUE THREAD

**Issue by carlton355** [stratisproject/StratisBitcoinFullNode#410]
**objective**: to get the available and pending balances of a watched address.
**method**: our ideas is to implement a GetWatchOnlyBalance API exactly like this: Stratis.Bitcoin.Features.Wallet.Controllers.WalletController::GetBalance
**problem**: no account.GetSpendableAmount(); available in the watchonly version

zeptin adds some additional color: "so the root cause is that the watch only wallet stores complete transaction objects, but has no SpendableAmount methods.  because the TransactionData classes that linq is operating over have different fields to the TransactionData in the watch only wallet. it should be said that the meaning of 'spendable' for the watchonly is that a particular transaction output has not yet been included in a subsequent transaction. presumably the regular wallet, by definition, has the additional constraint that you need to be in possession of the private key in order for an output to be spendable"

**Comment by bokobza** [comment]
https://trello.com/c/j58HA1Q7/190-watchonlywallet-missing-functionality-to-get-balances

**Comment by bokobza** [comment]
@zeptin is this still relevant?

**Comment by bokobza** [comment]
Closed with #1100
