### ISSUE TITLE
Compiling on Linux error

### ISSUE THREAD

**Issue by einewton** [stratisproject/StratisBitcoinFullNode#4106]
Trying to update my node, and getting error.

OS: Ubuntu 18.04.3 LTS

_After installing the DotNet 2.1 SDK I do the following:_

1. git clone https://github.com/stratisproject/StratisBitcoinFullNode.git
2. cd StratisBitcoinFullNode/src/Stratis.StratisD/
3. dotnet run (Same result with dotnet build then running the dll)

**Error:**
```
There was a problem initializing the node. Details: 'System.IO.FileLoadException: Could not load file or assembly 'System.Runtime.Extensions, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'System.Runtime.Extensions, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at Stratis.Bitcoin.Configuration.Logging.LoggingConfiguration.AddConsoleWithFilters(ILoggerFactory loggerFactory)
   at Stratis.Bitcoin.Configuration.NodeSettings..ctor(Network network, ProtocolVersion protocolVersion, String agent, String[] args, NetworksSelector networksSelector) in /home/ubuntu/StratisBitcoinFullNode/src/Stratis.Bitcoin/Configuration/NodeSettings.cs:line 140
   at Stratis.StratisD.Program.Main(String[] args) in /home/ubuntu/StratisBitcoinFullNode/src/Stratis.StratisD/Program.cs:line 30
```

**Comment by FyreDemonyte** [comment]
@einewton my setup is using dotnet 2.2.8

**Comment by einewton** [comment]
I also have 2.2.8 with same result. Here is my dotnet info

.NET Core SDK (reflecting any global.json):
 Version:   3.1.100
 Commit:    cd82f021f4

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/3.1.100/

Host (useful for support):
  Version: 3.1.0
  Commit:  157910edee

.NET Core SDKs installed:
  2.1.802 [/usr/share/dotnet/sdk]
  2.2.402 [/usr/share/dotnet/sdk]
  3.1.100 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.14 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.14 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.14 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

**Comment by FyreDemonyte** [comment]
You should just have one version installed

**Comment by einewton** [comment]
Anyone else getting this error, I resolved by doing the following:

1. sudo apt-get remove dotnet-host
2. sudo apt-get install dotnet-sdk-2.2

And now everything is working.

Thank you @FyreDemonyte
