### ISSUE TITLE
Evaluate exact impact of logs in consensus (e.g. PosConsensusValidator and PowConsensusValidator)

### ISSUE THREAD

**Issue by Aprogiena** [stratisproject/StratisBitcoinFullNode#411]
What we want is to measure block processing times for juicy bitcoin blocks with and without those logs in place. This will help us to decide how significant is the performance impact of having them.

**Comment by dangershony** [comment]
This is going to be interesting

**Comment by Aprogiena** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[Performance] Evaluate exact impact of logs in consensus (e.g. PosConsensusValidator and PowConsensusValidator)](https://trello.com/c/zYajMlbF/255-performance-evaluate-exact-impact-of-logs-in-consensus-eg-posconsensusvalidator-and-powconsensusvalidator)

**Comment by Aprogiena** [comment]
I've tried to make some measurements on stratis mainnet without checkpoints and with fixed StopWatch (see #362 ) and for blocks at heights between 16000 and 26000 (these are POS blocks only) in Debug mode, on my local machine. `Validator.PerformanceCounter.BlockProcessingTime` was used.

I've tried 3 different rounds with logs enabled, but the results have such a great variance that they are absolutely unusable. 

Therefore this can't be measured with the full node running normally as there is too many other things that occupy the processors. So what we need here is probably having the blocks downloaded on disk and process/validate the whole chain and do just that and nothing else.

Any idea how to do that?

**Comment by dangershony** [comment]
I think core has a flag called -reindex that will rebuild the consensus db using the blocks in store, Instead of downloading we just pull from store our blocks.
This will help in perf of the consensus code (but we need to implement it first)

**Comment by Aprogiena** [comment]
I don't think we need an official feature for this measurement, just hack it somehow and measure it :-)

**Comment by dangershony** [comment]
ok I am fine with closing this now, its clearly not an issue in perf terms.

**Comment by Aprogiena** [comment]
As you wish
