### ISSUE TITLE
[POS] CheckSync is not implemented in C#

### ISSUE THREAD

**Issue by Aprogiena** [stratisproject/StratisBitcoinFullNode#413]
`Check against synchronized checkpoint` is in stratisX which prevents reorgs longer than 500 blocks

**Comment by dangershony** [comment]
Ah ok yeah we need to add that.

**Comment by Aprogiena** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[POS] CheckSync is not implemented in C#](https://trello.com/c/mzfQRdAl/269-pos-checksync-is-not-implemented-in-c)

**Comment by dangershony** [comment]
I would suggest we put this limit in to the `ChainHeadersBehavior`
Just before this part
```
	if (this._PendingTip.ChainWork > this.Chain.Tip.ChainWork)
	{
		this.Chain.SetTip(this._PendingTip);
	}
```

**Comment by Aprogiena** [comment]
Yes, but I'd still like to have the test for this working before I finish this.

**Comment by dangershony** [comment]
Ah the test is working do you have issues with the test?

**Comment by Aprogiena** [comment]
Yes, from day 1 the test does not work for me.

**Comment by dangershony** [comment]
Ah ok I realise that's because we need to pull a fix from NStratis.

**Comment by dangershony** [comment]
This test now works fine.

**Comment by Aprogiena** [comment]
Yes, it is now better, except that it does not use ConsensusOptions.MaxReorgLength, which it actually should use. 

Another thing is that the test don't pass even if I set MaxReorgLength manually to 10.

**Comment by Aprogiena** [comment]
So, could you please check the latest version of #492?

**Comment by Aprogiena** [comment]
I will probably introduce logs to ChainHeadersBehavior to see what's happening.

**Comment by Aprogiena** [comment]
I mean, we certainly need that test to use ConsensusOptions - so I'd like to ask you to update the test code. And my task is to see why it does not work. I will analyze that and let you know.

**Comment by Aprogiena** [comment]
OK, so I've advanced enough with the implementation (PR #492), so I believe that PR implements long reorg protection well now. However, the test `Given__NodesAreSynced__When__ABigReorgHappens__Then__TheReorgIsIgnored` does not currently work with this implementation. The test needs to be fixed:

1) There are two mining nodes and coincidentally as their mining tasks are run in parallel, they actually mine the same blocks. This prevents the two mined chains to be different enough (above the max reorg length). Therefore the reorg is accepted.

This seems to have an easy fix:
```
                    var t1 = Task.Run(() => stratisMiner.GenerateStratisWithMiner(10));
                    var t2 = Task.Run(() => stratisReorg.GenerateStratisWithMiner(12));
```
->
```
                    var t1 = Task.Run(() => stratisMiner.GenerateStratisWithMiner(10));
                    var t2 = Task.Run(async () => { await Task.Delay(2000); stratisReorg.GenerateStratisWithMiner(12); } );
```
A delay makes sure that first mined blocks won't be the same.

2) Once we fix the same mined block problem above, the test's WaitLoop fails (even in debug mode where it is given 15 minutes). The logs show why:

```
Node 1:

[2017-10-14 09:12:51.2312 33] INFO: Stratis.Bitcoin.FullNode.<StartPeriodicLog>b__70_0 ======Node stats====== 10/14/2017 09:12:51 agent StratisBitcoin:1.0.2
Headers.Height:        13       Headers.Hash:         c1ac14c3abbed3f8cac5fcab15348fc2cc8928b2c9cf5508d133fcba07bcde17
Consensus.Height:      13       Consensus.Hash:       c1ac14c3abbed3f8cac5fcab15348fc2cc8928b2c9cf5508d133fcba07bcde17
BlockStore.Height:     13       BlockStore.Hash:      c1ac14c3abbed3f8cac5fcab15348fc2cc8928b2c9cf5508d133fcba07bcde17
Wallet.Height:         No Wallet

------------------------------
Node 2:

[2017-10-14 09:12:54.8409 80] INFO: Stratis.Bitcoin.FullNode.<StartPeriodicLog>b__70_0 ======Node stats====== 10/14/2017 09:12:54 agent StratisBitcoin:1.0.2
Headers.Height:        13       Headers.Hash:         c1ac14c3abbed3f8cac5fcab15348fc2cc8928b2c9cf5508d133fcba07bcde17
Consensus.Height:      11       Consensus.Hash:       3eeb8ef82fbeac1b6b2bbfd06b7305c5df978cf3ce89d237e809f1a83f7324f9
BlockStore.Height:     11       BlockStore.Hash:      3eeb8ef82fbeac1b6b2bbfd06b7305c5df978cf3ce89d237e809f1a83f7324f9
Wallet.Height:         No Wallet

------------------------------
Node 3:

[2017-10-14 09:12:55.5154 80] INFO: Stratis.Bitcoin.FullNode.<StartPeriodicLog>b__70_0 ======Node stats====== 10/14/2017 09:12:55 agent StratisBitcoin:1.0.2
Headers.Height:        11       Headers.Hash:         3eeb8ef82fbeac1b6b2bbfd06b7305c5df978cf3ce89d237e809f1a83f7324f9
Consensus.Height:      11       Consensus.Hash:       3eeb8ef82fbeac1b6b2bbfd06b7305c5df978cf3ce89d237e809f1a83f7324f9
BlockStore.Height:     11       BlockStore.Hash:      3eeb8ef82fbeac1b6b2bbfd06b7305c5df978cf3ce89d237e809f1a83f7324f9
Wallet.Height:         No Wallet

```

As we can see the two mining nodes are where they should be, the problem is with the `stratisSyncer` node, which received (and rejected) the headers from `stratisReorg`, but it then did not receive any better headers from anyone. 

There are several ways how to fix this. Either we should fix the node as once it rejects the headers, it should reset its headers to something it trusts, OR maybe after certain time (to make sure the reorg has been seen by the syncer), we should mine extra blocks with both `stratisMiner` and `stratisSyncer` and once `stratisMiner`'s chain is longer than 13, the syncer's chain should switch to it (and should ignore `stratisSyncer`'s chain, if if it is longer).

**Comment by Aprogiena** [comment]
So, I've checked the second solution of problem 2) and it seems that it works - so I've basically mined blocks with both miners:
```
                    t1 = Task.Run(() => stratisMiner.GenerateStratisWithMiner(10));
                    t2 = Task.Run(() => stratisReorg.GenerateStratisWithMiner(12));
```
so the stratisMiner's chain is 21 blocks long and stratisReorg's chain is 25 in length and the stratisSyncer correctly follows stratisMiner's (i.e. shorter chain). So that fix would also work.

So I think it is possible to just update the test and it will work well.

**Comment by Aprogiena** [comment]
And previously I forgot:

3. the test also have to to set MaxReorgLength in ConsensusOptions to 10, otherwise the default value is 500 and it won't work.

**Comment by dangershony** [comment]
Ok sounds fine how you solved the test, you could also just trigger a sync from`stratisSyncer`
I will have a better look at the code on Monday

**Comment by Aprogiena** [comment]
bump

**Comment by dangershony** [comment]
Yes sorry this was delayed for Breeze.
