### ISSUE TITLE
Docker - Unable to run the StratisD Testnet

### ISSUE THREAD

**Issue by ranjancse26** [stratisproject/StratisBitcoinFullNode#4181]
I am unable to run the StratisD Testnet on Docket. Here's what I see.

![image](https://user-images.githubusercontent.com/2565797/82143704-73c9a300-9863-11ea-8e3c-37baf2badc87.png)

FROM microsoft/dotnet:2.1-sdk

RUN git clone https://github.com/stratisproject/StratisBitcoinFullNode.git \
    && cd /StratisBitcoinFullNode/src/Stratis.StratisD \
    && dotnet build
	
VOLUME /root/.stratisbitcoin

WORKDIR /StratisBitcoinFullNode/src/Stratis.StratisD

COPY stratis.conf.docker /root/.stratisnode/stratis/StratisTest/stratis.conf

EXPOSE 18444 18442 26174 26178 38221

CMD ["dotnet", "run", "-testnet"]

**Comment by StratisIain** [comment]
Hi @ranjancse26  - Judging from the above screen-print the node is syncing. The line you have highlighted is the node attempting to connect to itself over localhost.

Below you can see that you are indeed connected to a node (82.146153.146) and your performing IBD.

I would also recommend that you utilise the [latest release branch](https://github.com/stratisproject/StratisBitcoinFullNode/tree/release/3.0.8.0) for syncing one of the public chains.

**Comment by ranjancse26** [comment]
Sounds good. I will go with your instructions.
