### ISSUE TITLE
Dotnet SDK 3.1

### ISSUE THREAD

**Issue by FyreDemonyte** [stratisproject/StratisBitcoinFullNode#4188]
Noting here if Dotnet SDK 3.1 will be supported ?

**Comment by dev0tion** [comment]
It will be, already is on some development branches.

**Comment by fassadlr** [comment]
.NET 3.1 is implemented with the release of Stratis Full Node.

https://github.com/stratisproject/StratisFullNode/

**Comment by FyreDemonyte** [comment]
Seems, 5.0 is out already. That in the works ?

**Comment by dev0tion** [comment]
5.0 is not LTS so I don't think so.
FYI development is now on SFN not SBFN.

**Comment by FyreDemonyte** [comment]
Ok, and yup I noticed it's SFN now :+1: Thnx
