### ISSUE TITLE
[StakeChainStore] Crash

### ISSUE THREAD

**Issue by Aprogiena** [stratisproject/StratisBitcoinFullNode#426]
```
      WalletSyncManager initialized. wallet at block 100373.
info: Stratis.Bitcoin.Api.ApiFeature[0]
      Api starting on url http://localhost:5000/
fail: Stratis.Bitcoin.Builder.FullNodeFeatureExecutor[0]
      An error occurred starting the application

Unhandled Exception: System.AggregateException: One or more errors occurred. (Missing stake information, delete the data folder and re-download the chain) ---> Stratis.Bitcoin.Configuration.ConfigurationException: Missing stake information, delete the data folder and re-download the chain
   at Stratis.Bitcoin.Features.Consensus.StakeChainStore.<Load>d__9.MoveNext() in C:\StratisBitcoinFullNode\Stratis.Bitcoin\Features\Consensus\StakeChainStore.cs:line 81
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Stratis.Bitcoin.Features.Consensus.ConsensusFeature.Start() in C:\StratisBitcoinFullNode\Stratis.Bitcoin\Features\Consensus\ConsensusFeature.cs:line 97
   at Stratis.Bitcoin.Builder.FullNodeFeatureExecutor.<>c.<Start>b__3_1(IFullNodeFeature service) in C:\StratisBitcoinFullNode\Stratis.Bitcoin\Builder\FullNodeFeatureExecutor.cs:line 57
   at Stratis.Bitcoin.Builder.FullNodeFeatureExecutor.Execute(Action`1 callback, Boolean reverseOrder) in C:\StratisBitcoinFullNode\Stratis.Bitcoin\Builder\FullNodeFeatureExecutor.cs:line 102
   --- End of inner exception stack trace ---
   at Stratis.Bitcoin.Builder.FullNodeFeatureExecutor.Execute(Action`1 callback, Boolean reverseOrder) in C:\StratisBitcoinFullNode\Stratis.Bitcoin\Builder\FullNodeFeatureExecutor.cs:line 120
   at Stratis.Bitcoin.Builder.FullNodeFeatureExecutor.Start() in C:\StratisBitcoinFullNode\Stratis.Bitcoin\Builder\FullNodeFeatureExecutor.cs:line 62
   at Stratis.Bitcoin.FullNode.Start() in C:\StratisBitcoinFullNode\Stratis.Bitcoin\FullNode.cs:line 195
   at Stratis.Bitcoin.Utilities.FullNodeExtensions.Run(IFullNode node, CancellationToken cancellationToken, String shutdownMessage, String shutdownCompleteMessage) in C:\StratisBitcoinFullNode\Stratis.Bitcoin\Utilities\FullNodeExtensions.cs:line 69
   at Stratis.Bitcoin.Utilities.FullNodeExtensions.Run(IFullNode node) in C:\StratisBitcoinFullNode\Stratis.Bitcoin\Utilities\FullNodeExtensions.cs:line 53
   at Stratis.StratisD.Program.Main(String[] args) in C:\StratisBitcoinFullNode\Stratis.StratisD\Program.cs:line 52
info: Stratis.Bitcoin.FullNode[0]
      Closing node pending...
info: Stratis.Bitcoin.FullNode[0]
      MemoryPool.RelayWorker stopping
info: Stratis.Bitcoin.FullNode[0]
      wallet persist job stopping
```

**Comment by Aprogiena** [comment]
This is reproducible, contact me if you want to work on this.

**Comment by fassadlr** [comment]
Hi @Aprogiena, I can look at this :) Let me know the step you follow to reproduce.

**Comment by dangershony** [comment]
This is a complicated bug hmf...

**Comment by Aprogiena** [comment]
Yes, I can provide appdata folder for this. Just contact me on slack when i'm there.

**Comment by Aprogiena** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[StakeChainStore] Crash](https://trello.com/c/JIZQIfri/234-stakechainstore-crash)

**Comment by Aprogiena** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[StakeChainStore] Crash](https://trello.com/c/JIZQIfri/234-stakechainstore-crash)

**Comment by Aprogiena** [comment]
First analysis of this issue revealed that SCS DB contained last item with null BlockStake. This should not ever happen and we are currently trying to find out what is happening.

**Comment by Aprogiena** [comment]
I've analyzed SCS DB from another instance, which failed to sync due to problems with POS validation. This happened before checkpoints were implemented. The problem in this case was that SCS DB was full of BlockStake records that have zeroed HashProof and StakeModifierV2. This should not happen again and it was not the case of just one last record (as if the case with null BlockStake above).

**Comment by Aprogiena** [comment]
I've analyzed SCS DB from another instance, which failed to sync due to problems with POS validation. This happened before checkpoints were implemented. The problem in this case was that SCS DB was full of BlockStake records that have zeroed HashProof and StakeModifierV2. Again, this is something that should not happen (in pre-checkpointed code) and it was not the case of just one last record (as if the case with null BlockStake above).

PreviousStake and StakeTime, however, were filled in correctly.

Whether these two problems with SCS DB are related is unknown, but there are certainly problems with SCS DB.

**Comment by fassadlr** [comment]
@dangershony I've gone though the code and confirm that, taking into account the current code base, it is impossible that BlockStake can be null before pushing to stake store.

@Aprogiena are you sure that we aren't debugging an issue that isn't applicable any more? Like you said, after you introduced the check point code, it is impossible for the stake store to have null block stake entries as either the logger or something else would have cause the node to crash to a null reference exception. I just synced on test net again and the issue wasn't there any more.

I'm of the opinion that this is a issue that we cant reproduce at the moment. 

However, to future safeguard the store, I propose that we add some Guards to ensure that we validate the StakeItem before pushing here:

https://github.com/stratisproject/StratisBitcoinFullNode/blob/305e0617ab31d9a1880bfb113d5734169761c12d/Stratis.Bitcoin.Features.Consensus/StakeChainStore.cs#L127

Relying on the logger to throw an exception or make it responsible for letting us know that something is null isn't good practice as if we remove it the StakeItem can be potentially pushed with a null BlockStake value. StakeItem should be responsible for itself being valid.

I propose that we construct StakeItem with all the values, so that when its valid before we push to the repo. i.e:

`StakeItem item = new StakeItem { BlockId = chainedBlock.HashBlock, Height = chainedBlock.Height, BlockStake = blockStake, InStore = false };`

will change to:

`StakeItem item = new StakeItem(chainedBlock.HashBlock, chainedBlock.Height, blockStake, false);`

and in the constructor

```
        public StakeItem(uint256 blockId, BlockStake blockStake, long height, bool inStore)
        {
            Guard.NotNull(blockId, nameof(blockId));
            Guard.NotNull(blockStake, nameof(blockStake));

            this.BlockId = blockId;
            this.BlockStake = blockStake;
            this.Height = height;
            this.InStore = inStore;
        }
```

So now I see that we also use half-populate StakeItem when we load them here:

https://github.com/stratisproject/StratisBitcoinFullNode/blob/305e0617ab31d9a1880bfb113d5734169761c12d/Stratis.Bitcoin.Features.Consensus/StakeChainStore.cs#L83

and

https://github.com/stratisproject/StratisBitcoinFullNode/blob/305e0617ab31d9a1880bfb113d5734169761c12d/Stratis.Bitcoin.Features.Consensus/StakeChainStore.cs#L58

This isnt good practise either as we should be passing just an ID or a "view"  or query class to the repo so that the returns the StakeItems. As in public Task GetStake(IEnumerable<StakeItem> blocklist) should take in a StakeItemView or something like so:

```
        public Task<List<StakeItem>> GetStake(IEnumerable<StakeItemView> blocklist)
        {
            return this.session.Execute(() =>
            {
                this.logger.LogTrace("({0}.Count():{1})", nameof(blocklist), blocklist.Count());

                List<StakeItem> stakeItems = new List<StakeItem>();

                foreach (StakeItemView blockStakeView in blocklist)
                {
                    this.logger.LogTrace("Loading POS block hash '{0}' from the database.", blockStakeView.BlockId);
                    Row<byte[], BlockStake> stake = this.session.Transaction.Select<byte[], BlockStake>("Stake", blockStakeView.BlockId.ToBytes(false));
                    StakeItem stakeItem = new StakeItem(blockStake.BlockId, blockStake.BlockStake, blockStake.Height, true);
                    stakeItems.Add(stakeItem);
                }

                this.logger.LogTrace("(-)");

                return stakeItems;
            });
        }
```

This is a MUCH safer implementation as we know now that regardless of logging or who calls SetAsync, StakeItem will be valid before pushing.

**Comment by Aprogiena** [comment]
@fassadlr i'm quite sure there still is a problem in stake store - the fact that we can't reproduce it is irrelevant, it is just rare condition. but if there was everything OK, i would not get the second problem (with non-null blockstake but zero hashproofs and stakemodifiers) 

actually we are not trying to reproduce the issue on the daily basis, so that is probably the reason why it is not reproduced. or it can be that some changes in code already fixed one instance (the first problem - null BS) while the second instance is still there 

the checkpoint code is actually making this worse as it prevents this to happen with early blocks - thus the ability to reproduce is lower than without checkpoint code - so we need to implement the switch to disable checkpoints to be able to normally try to reproduce this kind of stuff

reproducing this consists of 
- disabling checkpoints
- running the node, let it sync couple thousands of block and then press ctrl+c
- if all OK, do all again until you find it  


> Relying on the logger to throw an exception or make it responsible for letting us know that something is null isn't good practice

We are not doing that. The fact that the node crashes when this happens again is just coincidence. The contract of the method says that caller is responsible for passing non-null BlockStake as an argument.

Adding guards does not harm, but I would put them to the public interfaces of SCS, not to the constructor of StakeItem. However, adding a guard is not a solution to either problem, it is just a way to crash the node if it happens next time, which is fine, but the issue itself still need to be found.

**Comment by Aprogiena** [comment]
I think only if we make actual effort to reproduce it and fail for the long time (e.g. 100+ runs), we should consider this issue as "potentially no longer an issue" and leave it open for couple of months. Only then close it as "unable to reproduce". 

Some tips on how to test quickly: 
1) run more instance at once with separated ports and data folders
2) make sure you have enabled trace level logs, but possibly make some instances not log some log-heavy classes (e.g. blockpuller)
3) try to press ctrl+c in different chain heights, and try to do it when not all components are synced together

**Comment by fassadlr** [comment]
@Aprogiena if issue #2 is something else to BlockStake being null, why dont we create another issue for that? As this one purely related to BlockStake bieing null, which we know cannot be reproduced and based on the current code base cannot happen?

Regardless of this, I'm still going to submit a PR to future proof us potentially storing null BlockStakes when pushing to the Stake Chain Store. We can never assume or be too safe. @dangershony can then decide if we should merge it or not.

**Comment by Aprogiena** [comment]
@fassadlr i agree with adding guards, i think we just differ in that where to put them. i believe they should go to the entry of the public interface; can you argue on why the public interface is not a good place to add those guards? i think this is in general where you try to place the guards - on the very edge of your component so that your internals can then work with those contracts without additional checking; if you instead put them to the constructor, you are making checks against code that does not need it - this is kind of paranoid and with the same rationale, you would have guards in every method of the module, which does not seem to me like a good idea 

as for issue 2 - actually both are impossible (and were even before logs were introduced), which is good enough for me to consider that they can be related; it is perfectly OK not to have an issue solved on github and leave it open to grab more knowledge over time. as both of these issues have similar characteristics (both seem to be impossible and both are in the same component), it suggests that there is something fishy and weird in this component, so we need to leave this open and concentrate all data into one place - this issue; having another issue won't help, it will just split the effort

**Comment by fassadlr** [comment]
@Aprogiena, when it comes to storing data in a database, it is always considered good practice to validate your object to ensure its validity before pushing it to the repository. Ive been in database programming for roughly 10 year and trust me, Ive seen things go horribly wrong when asserting the validity of objects too early in the chain. You want to make the entity that you are storing responsible for itself. That way regardless of what happens around the entity on methods or whatever, you will be 100% sure that the object is always valid. This is also  part of SOLID principles, stating that you should never mix responsibility between objects and classes.

If you go and read up about defensive programming techniques and styles you'll see what I'm talking about.

You are making that classic assumption that something will be always be valid. And by building Guards into the constructor, it will never NOT be valid.

Anyway dude, I cant explain myself anymore. @dangershony will have to step in here and decide whats best. I can only talk from a lot of experience in these matters.

**Comment by Aprogiena** [comment]
OK, so @fassadlr I'm OK with the refactoring you suggested

Then for Issue #2 I have a plausible explanation, which is that I could have possibly switched from non-checkpointed version to checkpointed version and back while testing someguys's .NET core 2.0 PR, I was able to reproduce the problem with that. Although I can't remember switching, it is possible that it happened without me noticing. So if this is the case then issue #2 is non-issue.

For Issue #1, the latest research suggests (tx @fassadlr) that there is no broken stake item written to the disk. Instead `StakeChainStore.Load` calls `await this.dBreezeCoinView.GetStake(load);`, which executes 

```
                    Row<byte[], BlockStake> stake = this.session.Transaction.Select<byte[], BlockStake>("Stake", blockStake.BlockId.ToBytes(false));
                    blockStake.BlockStake = stake.Value;
                    blockStake.InStore = true;

```

This will set blockStake.BlockStake to null if the database on disk does not contain such a row with given BlockId. This is actually what is happening in this Issue #1 scenario. It remains to find out how is that possible.

This would mean that the coinview (Consensus) on disk is ahead of StakeChainStore, but so far we are unable to find out in the code how this could be. There is `FlushAsync` in CachedCoinView that executes SCS.Flush before it saves unsaved coinview data to disk. So this is why it seems SCS can't be behind on disk compared to coinview on disk.

**Comment by Aprogiena** [comment]
Mystery solved: what i've done here is that i've created static manual reset event

and used it like this:
```
            this.logger.LogInformation("XXX - execute block start");
            FullNodeExtensions.xxxx.Set();
            System.Threading.Thread.Sleep(5000);
            FullNodeExtensions.xxxx.Reset();
            this.logger.LogInformation("XXX - execute block end");

            // TODO: A temporary fix till this methods is fixed in NStratis.
            (this.stakeChain as StakeChainStore).Set(context.BlockResult.ChainedBlock, context.Stake.BlockStake);
```
this is ExecuteBlock in POS validator

and then in FullNodeExtensions
```
               Action shutdown = () =>
                {
                    if (!cts.IsCancellationRequested)
                    {
                        Console.WriteLine("Waiting XXXX");
                        xxxx.WaitOne();
                        Console.WriteLine("Application is shutting down...");

```

so i've given myself a signal when to press ctrl+C and gave myself 5 seconds to do that
and once i've done that, the next time node was run, it crashed with Issue #1 here

This means there is a race condition between Ctrl+C handler and the ConsensusLoop thread. If a new block is accepted in a block and Ctrl+C handler is executed at the right point, it calls ConsensusFeature.Stop method, which leads to 
```
                cache.FlushAsync().GetAwaiter().GetResult();
```

which executes 
```
                await this.stakeChainStore.Flush(true);
```
and if then `CachedCoinView.blockHash` is changed by the other thread, this issue #1 occurs

**Comment by dangershony** [comment]
Wowoo I didn't see you had such a long discussion here.
We came to the conclusion the problem was with a bad should down so do we really need to refactor the stake store further?

**Comment by Aprogiena** [comment]
Refactoring StakeItem is somehow orthogonal to fixing this issue. As it was discussed, this issue was NOT caused by saving invalid value to the database, but by logic in loading in combination with a race condition of previous run. 

Refactoring StakeItem is thus extra thing to do and it is probably not so important, but could be beneficial for having cleaner code and prevent future mistakes of certain kind. It is WIP already and PR is being reviewed in these days.
