### ISSUE TITLE
[POS] Implement checkpointing similarly to StratisX

### ISSUE THREAD

**Issue by Aprogiena** [stratisproject/StratisBitcoinFullNode#438]
these are long term checkpoints that make IBD much faster as the block validation takes a lot of time

**Comment by Aprogiena** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[POS] Implement checkpointing similarly to StratisX](https://trello.com/c/4JPKjiDt/231-pos-implement-checkpointing-similarly-to-stratisx)

**Comment by dangershony** [comment]
We will probably do it a bit differently as we want to support checkpoint for more then one network right?

**Comment by Aprogiena** [comment]
well the stratisX part is similar, but it is not the same, bitcoin part will be ready (checkpoints defined) with this update, but not used (i.e. new task will be needed to implement checkpointing for bitcoin)
