### ISSUE TITLE
[Stratis.Bitcoin] DefaultConfig creates 'rpcallowedip' with 'allowed' not 'allow'.

### ISSUE THREAD

**Issue by carlton355** [stratisproject/StratisBitcoinFullNode#453]
The keyname in bitcoin is 'rpcallowip', you might consider changing it.

NodeSetting.cs: 328, GetDefaultConfigurationFile()

builder.AppendLine("#rpcallowedip=127.0.0.1");

**Comment by bokobza** [comment]
Thanks @carlton355

**Comment by bokobza** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[NodeSettings] In the creation of config file in nodeSettings, replace rpcallowedip with rpcallowip](https://trello.com/c/pnRTR1JE/218-nodesettings-in-the-creation-of-config-file-in-nodesettings-replace-rpcallowedip-with-rpcallowip)

**Comment by bokobza** [comment]
Fixed with https://github.com/stratisproject/StratisBitcoinFullNode/pull/467
