### ISSUE TITLE
[Wallet-Bug] First transactions sent to wallet never got confirmed

### ISSUE THREAD

**Issue by zeptin** [stratisproject/StratisBitcoinFullNode#457]
Steps that were performed to encounter this:

0. Shut down fully synced node
1. Backed up and deleted 2 existing wallet files
2. Started up daemon and UI
3. Created two wallets via the UI, named xxxx and yyyy
4. Sent 6 faucet transactions to the first unused address in wallet xxxx
5. These transactions are all confirmed according to the block explorers, but do not appear as confirmed in the wallet json & are lacking merkle proofs
6. Sent a transaction to the second address in the wallet with a breakpoint in the WalletManager ProcessTransaction function
7. The transaction got initially saved with no blockhash and merkleproof as expected
8. The next testnet block arrived and the breakpoint was hit
9. The block parameter to the ProcessTransaction looked normal, stepping through the function confirms that the merkle proof is generated for this transaction

This seemed to only affect the first batch of transactions, which were all included in block 1195713.

The initial 6 transactions were:
992db2722cdb8ef50a36ac728617c80a42f91382c2fe71130b8acf2a9383e8ab
91b9989dda7382b8e7c3f6aac31282d7d2d0b09114edbf10addaaf53479da589
b3b1478dce83891b5a7fc52227c0c0348fd5223cd9eab8c11e7a36ffef0575cc
6e2adec18e3777c090c843f16dfd9a15d11f6e40db3478b4c6043a7f65beb3ad
52e53bc002ad3a5e8b56aeea32e46d722c9b26bbf9b9fb4a435309288d69ed74
24c46e73fb64cbe3cbed61e2264f3175205f40d57bd9852b7510ee4771b856ed

Transaction sent to second address: 3d9a9a372d70c717c8040dc311b181ba40d70a8e98e6af9b0c2e67fbf4805d4c
(confirmed in block 1195713)

[xxxx.txt](https://github.com/stratisproject/StratisBitcoinFullNode/files/1300222/xxxx.txt)
[yyyy.txt](https://github.com/stratisproject/StratisBitcoinFullNode/files/1300223/yyyy.txt)

**Comment by dangershony** [comment]
Is this on Bitcoin testnet?

**Comment by zeptin** [comment]
Yes. It is possible this is also due to testnet miners not putting mempool transactions into blocks properly. Additional investigation is needed.

**Comment by dangershony** [comment]
This should be fixed with this commit
https://github.com/stratisproject/StratisBitcoinFullNode/commit/2fe1d99b14c53d7f86f615038f30ebd6e3bcf0d2

**Comment by bokobza** [comment]
@zeptin can you confirm that this is fixed?

**Comment by bokobza** [comment]
I think this is fixed.
