### ISSUE TITLE
[AsyncLoop] Identify all AsyncLoops in the code and dispose them correctly

### ISSUE THREAD

**Issue by Aprogiena** [stratisproject/StratisBitcoinFullNode#462]
We have made IAsyncLoop disposable, so that on shutdown we the code using the loop can wait correctly for the loop completion. 

Next step is to identify all AsyncLoops in all the code and dispose them correctly.

**Comment by Aprogiena** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[AsyncLoop] Identify all AsyncLoops in the code and dispose them correctly](https://trello.com/c/FwFhsreL/228-asyncloop-identify-all-asyncloops-in-the-code-and-dispose-them-correctly)

**Comment by dangershony** [comment]
This is complete
