### ISSUE TITLE
[POS] Get rid of V1 POS code

### ISSUE THREAD

**Issue by Aprogiena** [stratisproject/StratisBitcoinFullNode#494]
We want to get rid of all POS v1 related code from the code base as we don't need it on Stratis chain. These versions of POS consensus are from old coins project that Stratis evolved from.

**Comment by Aprogiena** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[POS] Get rid of V1 POS code](https://trello.com/c/R38uWvBE/256-pos-get-rid-of-v1-pos-code)

**Comment by Aprogiena** [comment]
@dangershony The question here is - do we also want to get rid of V2 code? As you mentioned, we are V3 only as per this analysis:

```
inline bool IsProtocolV3(int64_t nTime) { return TestNet() || nTime > 1470467000; }
```

and that timestamp is GMT: Saturday, 6 August 2016 07:03:20
and our genesis block on mainnet is 1470467000 (Saturday, 6 August 2016 07:03:20)
and our genesis block on testnet is 1493909211 (Thursday, 4 May 2017 14:46:51)

so it actually seems that all our blocks except for mainnet genesis are V3 blocks

**Comment by dangershony** [comment]
Hmm yeah for sure, we can add a special case for genesis but perhaps we also remove the V2 code I agree.

**Comment by Aprogiena** [comment]
Excellent. Actually, I think this should be the highest priority task before we attempt to fix those bugs in other issues as this can affect (reduce) the complexity of some code parts.
