### ISSUE TITLE
[Consensus] Couple of omissions

### ISSUE THREAD

**Issue by Aprogiena** [stratisproject/StratisBitcoinFullNode#495]
1) in PowMining when block is found, there is a sequence AcceptBlock, Puller.SetLocation, consensusLoop.FlushAsync, blockRepository.PutAsync and signals.SignalBlock
while in PosMining, i can only see AcceptBlock, Puller.SetLocation, blockRepository.PutAsync and signals.SignalBlock, i am missing consensusLoop.FlushAsync there, i guess these two sequences should be similar

2) `this.UTXOSet.SaveChangesAsync(context.Set.GetCoins(this.UTXOSet), null, this.Tip.HashBlock, context.BlockResult.ChainedBlock.HashBlock);` in AcceptBlock in ConsensusLoop should use await or GetResult to wait for it, because otherwise we rely on the fact that the cached coin view that is used here is synchronous

**Comment by dangershony** [comment]
1. yes we need to add that as well.
2. You are right in general, but in this case it is sequential so we dodged this one (good spot).

**Comment by Aprogiena** [comment]
Both should be trivial to fix, can do that soon.
