### ISSUE TITLE
How to start?

### ISSUE THREAD

**Issue by leegod** [stratisproject/StratisBitcoinFullNode#497]
Hi.
I read gettingstarted.md , but I don't know where to start. I tried to input texts on CMD console window in windows10, but git order does not work.

**Comment by Aprogiena** [comment]
Hi, I suggest you come on Slack for little faster support. Otherwise, it may take some time before someone replies here.

**Comment by dangershony** [comment]
Hi @leegod did you manage?
If you think we need to modify our getting started then please suggest how form your experience (or submit a PR).

**Comment by leegod** [comment]
@dangershony No not yet. Thx for reply. I still need help. And from 3 days ago, I left 7~10 messages to Stratis site's contact, but no replies so far. Why?

I have many questions.

These are part of it.

--------

Hi.So I have interest in Stratis because it uses C#. 1. So How to make business model using blockchain tech?Maybe I should make own mobile app? or?2. Then where blockchain data that my app and its users generates stored?Phone can't store it, then this means I should also make window application like bitcoin core?Thanks. | Hi.So I have interest in Stratis because it uses C#. 1. So How to make business model using blockchain tech?Maybe I should make own mobile app? or?2. Then where blockchain data that my app and its users generates stored?Phone can't store it, then this means I should also make window application like bitcoin core?Thanks. | Hi.So I have interest in Stratis because it uses C#. 1. So How to make business model using blockchain tech?Maybe I should make own mobile app? or?2. Then where blockchain data that my app and its users generates stored?Phone can't store it, then this means I should also make window application like bitcoin core?Thanks.
-- | -- | --
Hi.So I have interest in Stratis because it uses C#. 1. So How to make business model using blockchain tech?Maybe I should make own mobile app? or?2. Then where blockchain data that my app and its users generates stored?Phone can't store it, then this means I should also make window application like bitcoin core?Thanks. | Hi.So I have interest in Stratis because it uses C#. 1. So How to make business model using blockchain tech?Maybe I should make own mobile app? or?2. Then where blockchain data that my app and its users generates stored?Phone can't store it, then this means I should also make window application like bitcoin core?Thanks.
Hi.So I have interest in Stratis because it uses C#. 1. So How to make business model using blockchain tech?Maybe I should make own mobile app? or?2. Then where blockchain data that my app and its users generates stored?Phone can't store it, then this means I should also make window application like bitcoin core?Thanks.


------------

**Comment by dangershony** [comment]
Hi you can come to our slack for more answers (not the site).
To answer your questions.
1. you need to think of a problem that requires trust and can be replaced with blockchain.
2. Blockchain can probably not run on mobile, its too heavy.

**Comment by leegod** [comment]
@dangershony  Slack need to be invited. But I don't know how to contact their admin, stratis site's contact doesn't reply to my request or questions. Can you help me to get invited?

**Comment by dangershony** [comment]
Its auto invite https://stratis-invite.herokuapp.com/ 
Seems offline right now, if you don't manage to get an invite ask me again.

**Comment by leegod** [comment]
@dangershony I ask get me invited plz.

**Comment by Aprogiena** [comment]
It is online again now.

**Comment by leegod** [comment]
@Aprogiena  it says failed, User disabled. Can't you do manually?

**Comment by Aprogiena** [comment]
I was told to ask you if you can try with another email address and report the result back.

**Comment by dev0tion** [comment]
Or if you can get me your username I will enable the account.

**Comment by leegod** [comment]
@dev0tion My username is 'creatoree' maybe I remember.

**Comment by dev0tion** [comment]
@leegod I can't find a user with that name.

**Comment by leegod** [comment]
@dev0tion then maybe 'leegod' or I don't remember..

**Comment by dev0tion** [comment]
@leegod also unknown. I suggest you try with another e-mail address.

**Comment by dev0tion** [comment]
Ok, I see you got in :)! 
@dangershony you can close the issue (I have no permission to).
