### ISSUE TITLE
[Checkpoints] Investigate the delay during IBD when reaching the latest checkpoint

### ISSUE THREAD

**Issue by Aprogiena** [stratisproject/StratisBitcoinFullNode#522]
There is a significant delay in IBD when the node's consensus reaches the height of the last checkpoint. Eventually, the node advances, but something weird is going on at that very moment and it is certainly worth exploring. However, it is likely that fixing other issues that are open already might fix this as well, so this should be examined not too early.

**Comment by Aprogiena** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[Checkpoints] Investigate the delay during IBD when reaching the latest checkpoint](https://trello.com/c/B80yYdXl/271-checkpoints-investigate-the-delay-during-ibd-when-reaching-the-latest-checkpoint)

**Comment by Aprogiena** [comment]
Examination done on the top of PR https://github.com/stratisproject/StratisBitcoinFullNode/pull/534 and it produced no such result. It may be the case that the problem was mitigated. Testing once more on the top of this PR and then will do with the current master.

**Comment by Aprogiena** [comment]
Second run on top of PR 534 - no such result again and it seems like the previous idea of connection to #525 was not correct. Running once more to confirm and then one last time on current master (without PR 534)

**Comment by Aprogiena** [comment]
Third run, no such result.

**Comment by Aprogiena** [comment]
Fourth run on master revealed the problem. The delay is most likely present due to stake modifier v1 calculations that require loading block stake information from the disk, which takes a lot of time. Block stake database is not used for checkpointed blocks and it is thus needed to reload a lot of data from disk to count the next block stake modifier v1. PR 534 removes calculation and thus seems to solve the issue in full.

**Comment by dangershony** [comment]
Ha wowowo nice spot away with you V1

**Comment by Aprogiena** [comment]
Reading the logs I can confirm this was the issue. With last checkpoint set at 50k, it was loading 46k block stake entries from the disk, one by one.

**Comment by Aprogiena** [comment]
This issue was fixed by #534
