### ISSUE TITLE
[CoinView] Investigate no flush during IBD

### ISSUE THREAD

**Issue by Aprogiena** [stratisproject/StratisBitcoinFullNode#525]
It seems to me that CV has no flushing during IBD, which makes the memory to grow extremely during IBD.

Note that if we implemented flush, we have to add lock and be careful not to introduce #426 again due to race condition between Ctrl+C handler which executes the flush and this new flush.

**Comment by dangershony** [comment]
Yes there is a flush but it  has very big intervals (every 100k blocks or something).

**Comment by Aprogiena** [comment]
Are you talking about `CacheMaxItemsDefault` or something else?
If this, we should preserve this as we probably don't want to lower the cache size, but we should introduce some flushing while leaving cache full of those entries ...

Also, it does not really explain, why the memory goes so wild during IBD. 100k transactions should not occupy 1 GB of memory. Maybe there is more to the problem than just unflushed data.

Anyway, for the cache and flushing I would suggest
- we have some flushing limit, much lower than max cache item count
- we also time limit for flushing (maybe this is the only thing we need and not the second limit on item count)

**Comment by Aprogiena** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[CoinView] Flush during IBD](https://trello.com/c/Jck2MxDD/295-coinview-flush-during-ibd)
