### ISSUE TITLE
Node Test wallet file copy

### ISSUE THREAD

**Issue by dangershony** [stratisproject/StratisBitcoinFullNode#533]
The class StratisBitcoinPowRunner is copying the wallet file to the test folder in methodBuildFullnode
```
  // TODO: this code should be moved to the tests that use it
            if (node.NodeService<WalletFeature>(true) != null)
            {
                var testWalletPath = Path.Combine(node.DataFolder.WalletPath, "test.wallet.json");
                if (!File.Exists(testWalletPath))
                    File.Copy("Data/test.wallet.json", testWalletPath);
            }
```

This code should be move to the tests that needs it.

**Comment by bokobza** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[Testing] Node Test wallet file copy](https://trello.com/c/D65vMCDd/315-testing-node-test-wallet-file-copy)
