### ISSUE TITLE
Refactor/Remove sendtransaction tests

### ISSUE THREAD

**Issue by nopara73** [stratisproject/StratisBitcoinFullNode#542]
The concept of sendtransaction had been changed. 7 tests those would've been broken, partly had been commented out: https://github.com/stratisproject/StratisBitcoinFullNode/pull/541  

These tests can be identified by searching for this todo comment:  
```
// [SENDTRANSACTION TODO] Conceptual changes had been introduced to tx sending
// These tests don't make sense anymore
// It must be either removed or refactored
```

**Comment by bokobza** [comment]
these tests are in WalletManagerTest.cs.

**Comment by bokobza** [comment]
@noescape00 this is probably gonna be for you.

**Comment by noescape00** [comment]
@bokobza ok, will do as soon as I finish with issue #862
