### ISSUE TITLE
[WalletSyncManager] ProcessBlock race condition

### ISSUE THREAD

**Issue by Aprogiena** [stratisproject/StratisBitcoinFullNode#556]
On this line https://github.com/stratisproject/StratisBitcoinFullNode/blob/d35ecdd20bf3585f224d510ff1766b4887bbfdf2/Stratis.Bitcoin.Features.Wallet/WalletSyncManager.cs#L111 the `walletTip` can be assigned `null` if the concurrent chain changes just before it to earlier reorg.

**Comment by Aprogiena** [comment]
Why it is not `walletTip = fork` ?

**Comment by Aprogiena** [comment]
And just below that 
```
ChainedBlock incomingBlock = this.chain.GetBlock(block.GetHash());
```
again, this can produce `null` in `incomingBlock` for the very same reason.

**Comment by Aprogiena** [comment]
And once more 
```
next = this.chain.GetBlock(next.Height + 1);
```
Again, this can produce `null` in `next`.

**Comment by dangershony** [comment]
Yes very good points, we sould indeed use this ` walletTip = fork`.
As for the other issues I guess we do want to call chain but if we get back null then the current block received in the wallet is not valid and the wallet should return execution (let the next block sort the reorg issue). 

Any fix here should also be ported tot he light wallet

**Comment by Aprogiena** [comment]
There are two options here, either fix every line of code that works with the chain like that, or make a big change in a way that ConcurrentChain is not used like this anywhere. I believe that a better design to work with would be each instance working with its own copy of chain headers (now there is a shared copy called ConcurrentChain). And you could always be sure your own copy won't change over time and thus the code is safe. And the copy should provide a mechanism for you to check if the local copy is the best chain the node knows.

**Comment by dangershony** [comment]
ConcurrentChain is really just holding the pointer to the best TIP (we don't need every feature to hold an entire copy of it just the TIP)

So I agree we should not use ConcurrentChain (almost anywhere but only at the point where the feature determines if its on the right chain).

All other checks must be done against the features current TIP.
That way if a reorg happened the internals of a feature wont know about it and will not be subject to the race condition, then the feature can control the reorg time and place.

**Comment by Aprogiena** [comment]
Not every feature, but the Tip is usually not the only thing they use. Many features use GetBlock as a way to check if they are on the right chain, that usage is prone to problems. And basically any walking through the headers should be done on a local copy. With a good implementation, this is not heavy at all. Note that your local copy only needs to be an actual copy for the headers that are different.

**Comment by dangershony** [comment]
@Aprogiena closing this
