### ISSUE TITLE
Consider refactoring based on "Async/Await - Best Practices in Asynchronous Programming"

### ISSUE THREAD

**Issue by nopara73** [stratisproject/StratisBitcoinFullNode#565]
https://msdn.microsoft.com/en-us/magazine/jj991977.aspx

**Comment by dangershony** [comment]
That's a good idea we should try to start removing the usages of GetAwaiter().Getresult()
It should be done in small commits, all our loops are already async supported so adding this should be fairly easy, However it might mean changing method signatures which will make this task a bit longer.

**Comment by nopara73** [comment]
Do you think it is a better practice to use [async unit tests](http://bradwilson.typepad.com/blog/2012/01/xunit19.html)?

**Comment by dangershony** [comment]
It depends on the unit test, some of our unit tests are async already

**Comment by Aprogiena** [comment]
Yes, this is known issue. I am very much towards changing it, my first attempt should be #553
