### ISSUE TITLE
[NBitcoin] Handle and memory leaks

### ISSUE THREAD

**Issue by Aprogiena** [stratisproject/StratisBitcoinFullNode#569]
Diagnostic tools in MSVS revealed a lot of leaks in full node. Some of them are in full node.

One of the confirmed leaks seems to be in 
```
internal Node(NetworkAddress peer, Network network, NodeConnectionParameters parameters)
```

which creates 
```
				var completed = new ManualResetEvent(false);
				var args = new SocketAsyncEventArgs();
```
and dispose neither.

Another possibility is not using `SetBuffer(null, 0, 0)` on `SocketAsyncEventArgs`, which is necessary according to some sources (but does it still apply?).

Then there are lots of `CancellationTokenSource` (and related `ManualResetEvent`) objects that just increase in memory. Also lots of `IPAddress` (and related `IPEndPoint`). 

And many others (`Socket`, `Timer`, ...).

**Comment by Aprogiena** [comment]
It might be the case that if we just release `SocketAsyncEventArgs` and dispose all `CancellationTokenSource`, other objets will be freed as well. We should start with these two.

**Comment by dangershony** [comment]
We also need to make sure we dispose of LinkedCancellationTokenSource  (a stated in https://lowleveldesign.org/2015/11/30/catch-in-cancellationtokensource/ and https://docs.microsoft.com/en-us/dotnet/standard/threading/cancellation-in-managed-threads)

Either I or @quantumagi  will try to work on this (as he already made commit to NBitcoin)

**Comment by Aprogiena** [comment]
yes, great, this will count a lot towards overall stability of the node

**Comment by fassadlr** [comment]
Hey guys, has any work been done on this? @bokobza mentioned I can look at this.

**Comment by fassadlr** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[NStratis] Handle all memory leaks](https://trello.com/c/TUuLPP8p/298-nstratis-handle-all-memory-leaks)

**Comment by fassadlr** [comment]
With regards to the obvious fixes as set out by Apro, I fixed the ManualResetEvent not being disposed properly with a "using" statement. 

I created a NodeSocketEventManager class that now handles and disposes of the SocketAsyncEventArgs instance properly after the node is connected.

Also, I cleaned up the Node.cs class as it was really messy to work with. Not a lot, but just enough to make it a bit more workable. 

I moved the properties and variables to the top and just applied some of our code standards, e.g. private variable naming etc.

I also needed to fix an issue with a unit test failing (CanConnectToRandomNode) that was calling code on line 341 in the new Node.cs. It should be pretty self explanatory.

**The main part that should be reviewed and fixed the memory leak is from line 493 in the new Node.cs file.**

**Comment by dangershony** [comment]
hi @fassadlr ok thank I will check it out now, one of the reason I don't encourage changing too much in NBticoin is to make merges easier, if we will need to merge from NBitcoin it will be very messy if the classes are different.

**Comment by bokobza** [comment]
@dangershony @fassadlr Are you guys happy for me to close this?
If we find some more we can reopen a new issue.

**Comment by fassadlr** [comment]
@bokobza I haven't seen any leaks for weeks. I'm happy to close and re-open should new ones occur 👍

**Comment by fassadlr** [comment]
Closing this as Node has been refactored and we havent seen any new memory leaks for some time. Can raise a new issue if any new leaks appear.

**Comment by Aprogiena** [comment]
There still are, but I'm working on it :-)
