### ISSUE TITLE
[WalletManager] Test ProcessBlock_NewBlock_PreviousHashNotSameAsWalletTip_WalletTipNotOnBestChain_RemovesBlocksAfterForkOnOldChainFromWalletManager_CatchUpWalletManagerUsingBlockStoreCache Failing

### ISSUE THREAD

**Issue by mikedennis** [stratisproject/StratisBitcoinFullNode#572]
Some of the refactoring has broken this test. Need to investigate whether this is a problem with the WalletManager refactoring or whether the test needs to get fixed.

These two verify methods are failing:
```
            //verify manager processes each missing block until caught up.
            // height 3
            this.walletManager.Verify(w => w.ProcessBlock(ExpectBlock(result.RightForkBlocks[2]), ExpectChainedBlock(this.chain.GetBlock(3))));
            // height 4
            this.walletManager.Verify(w => w.ProcessBlock(ExpectBlock(result.RightForkBlocks[3]), ExpectChainedBlock(this.chain.GetBlock(4))));
```

**Comment by Aprogiena** [comment]
Also please consider renaming the test. Describe it in the comment, avoid such long names. Not sure if it is the case in this test, but some test tend to create directories or files on disk and names of those file objects are based on the names of the tests. Those directories are then unusable for some programs that work with old 260 character limit.

**Comment by mikedennis** [comment]
#561 fixes this
