### ISSUE TITLE
[WalletManger] Thread safe refactoring

### ISSUE THREAD

**Issue by mikedennis** [stratisproject/StratisBitcoinFullNode#573]
@bokobza 
I think we should remove the locks around the wallet, and rather go with a solution that involves
making the lists in the wallet object concurrent
add a lock only on ProcessTransaction so that this method is only accessed by one thread
make history a pre-computed object that we just retrieve when GetHistory gets called
ComputeHistory() is called in Initialize()
UpdateHistory is called when we found a transaction (in TransactionFoundInternal)

@dangershony 
That's a possibility, I prefer code without locks, infect when I was working on this PR I started with a branch that has ConcurrentBag in the Wallet, however that required big changes in the tests (and some changes in the wallet code), I made the changes but then it broken many of the tests (for some reason was not sure why).

I decided to use locks as that would not require any changes to tests and all I need is tests to pass to be sure I did not break anything.

Making such a change is welcome but it will be a big one, as many tests will need to change as well.

Regarding history, that's an option for sure, after refactor of the history code its now faster (but still limited to only top 100 entries), I tend to prefer to try to refactor the history calculation then to have a pre-computed instance just because it will introduce more complexity, but if we remove the top100 limit and find history to be slow we will have to recompute it.

**Comment by mikedennis** [comment]
This issue was sourced from the discussion in https://github.com/stratisproject/StratisBitcoinFullNode/commit/61c3b92f12afd3fc2b3904af990f73781a6ede69#commitcomment-24845666

**Comment by Aprogiena** [comment]
I am very much against the idea of avoiding locks and making the objects concurrent. This leads to race conditions, so please do not do that. I've already fought many battles with races in Stratis caused just because of concurrent objects. Just please don't do that.

**Comment by Aprogiena** [comment]
It might also be a good idea that we first introduce the puller to the wallet, because that will change a lot of code and only then try to refactor it.

**Comment by dangershony** [comment]
Lets wait for Jeremy to come back and discuss further in a video meeting. 
You are probably right we should first make the wallet stand alone before refactoring any further.

**Comment by bokobza** [comment]
Closing this as we have a proposed improvement of making the wallet stand alone here: https://github.com/stratisproject/StratisBitcoinFullNode/issues/1103
