### ISSUE TITLE
NStratis - extend the method FindAncestorOrSelf

### ISSUE THREAD

**Issue by dangershony** [stratisproject/StratisBitcoinFullNode#585]
This method will go all the way to genesis and might be useless in some cases when (when a reorg is checked and checkpoints are in place, or reorg is not allowed beyond a certain size)  

As part of this task we should bring the checkpoints in to the Network class.  
The method can take an additional overload bottom height `FindAncestorOrSelf(hash, bottomHeight)` and stop at that height.

Once its done this can be applied to the WalletSyncManager (and maybe also ChainHeaderBehaviour)

**Comment by Aprogiena** [comment]
I've created #659 to aim at the core problem in this, which is inefficient implementation of basic chain functions. Fixing that would make this a non-issue (speaking solely about extension of FAOS).

**Comment by dangershony** [comment]
#659

**Comment by dangershony** [comment]
I think this can be closed right?

**Comment by Aprogiena** [comment]
@mikedennis ?

**Comment by mikedennis** [comment]
Well FindAncestorOrSelf is now fast (uses skiplist) but will still go to genesis if the header isn't found. So not sure if we still want to add an bottomHeight parameter or not. How would we know what to set it to?

**Comment by Aprogiena** [comment]
the specific use case is for stratis network that has a maximal reorg length defined
therefore in some cases, it does not make sense to try to look any further than that
the perf gain from that, however, would be negligible in any foreseeable future
OTOH, it is very trivial to add
so :-|

**Comment by noescape00** [comment]
what is the status of this issue? Wasn't it done on master already?

**Comment by zeptin** [comment]
Just to put a clarifying note here for future reference - there are two versions of the function, and the skip list version is not the one being referred to in this issue.

It may be worth seeing if the few places the non-skiplist version is used can be changed to the other version, with the corresponding performance benefit if the height parameter is not being used to limit the search.

**Comment by noescape00** [comment]
Fixed with activation merge.

**Comment by noescape00** [comment]
@dangershony I think it can be closed
