### ISSUE TITLE
[Wallet] Make wallet name check case sensitive?

### ISSUE THREAD

**Issue by dev0tion** [stratisproject/StratisBitcoinFullNode#596]
As reported by @mtaipe, the current check for the same wallet name is not case sensitive.
E.g. you can create a wallet called "test", another one called "Test", etc...

Should we change this?
@bokobza @nopara73 @dangershony

**Comment by D3m0nKingx** [comment]
I would say yes to this, because a user may unbeknownst to accidentally  utilize a wallet and make transactions they didn't intend in doing so, etc etc. (Although, that's considering they used the same password in both wallets), otherwise this wouldn't matter so much.

**Comment by dev0tion** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[Wallet] Make wallet name check case sensitive?](https://trello.com/c/bMGAfZ84/292-wallet-make-wallet-name-check-case-sensitive)

**Comment by nopara73** [comment]
I agree, yes.

**Comment by bokobza** [comment]
yep

**Comment by nopara73** [comment]
On a second thought, making it case insensitive might bring additional issues.

**Comment by bokobza** [comment]
actually, having `wallet1` and `Wallet1` as wallet is not a problem because the api will either relate to `wallet1` or `Wallet1`, whether it's for creating a transaction or retrieving history etc..
I'd rather leave it as it is for now.

**Comment by bokobza** [comment]
@dev0tion Are you happy for me to close this?

**Comment by bokobza** [comment]
actually no, on Windows you can't name 2 files with the same name but for the casing (for example "testwallet" and "Testwallet").
So I guess on creation and restoration, we need to check that there isn't another wallet with the same name (but for the casing).
Assigned to @mikedennis .

**Comment by Neurosploit** [comment]
Would it also be a good suggestion to include moving from the current concurrentbag on the walletmanager to a concurrentdictionary<string, Wallet> if the wallet names are case insensitive?

**Comment by mikedennis** [comment]
This is not a problem on Windows. File.Exists() already handles case insensitivity and errors if you try to use the same wallet name but with different case (I tested to verify).

So the tester in question was either using linux or mac where File.Exists() will be case sensitive.

I agree that case sensitivity could be a bit confusing but I'm more a windows guy - aren't unix/mac users used to worrying about case sensitivity already?

I think I have a fix for it but it's a bit ugly (involves wildcard search in folder) but I want to make sure our unix guys are going to be cool with us making wallet names case insensitive.

**Comment by bokobza** [comment]
I guess we'll have to go with the lowest common denominator here: if on Windows you can't have 2 files with the same name but different casing, no one can! :-)
instead of a wildcard, you can compare the newwallet in lower case to the already loaded ones in lower case I guess. (instead of solely relying on File.Exists)

**Comment by mikedennis** [comment]
Alrighty - will do! Yes you are correct I should be able to just use the loaded wallet names for comparison instead of rescanning the folder. Thanks, will do that!
