### ISSUE TITLE
[Wallet] Wallet too big

### ISSUE THREAD

**Issue by Aprogiena** [stratisproject/StratisBitcoinFullNode#598]
I've got wallet JSON file that is currently 190 MB. In whole history I'd estimate cca 3200 UTXOs and cca 1800 transactions. That is cca 5000 objects. That would mean that each such object requires cca 38 kb of data. It seems too much to me. Half of it is due to inefficient encoding in hexa, OK, but still 19 kb per object?

**Comment by bokobza** [comment]
wow yes that's a lot.
We can probably make it more efficient when we make the wallet independant of coinsensus.

**Comment by nopara73** [comment]
A keymanger solves it. https://github.com/nopara73/StratisBitcoinFullNode/tree/keymanagement/Stratis.Bitcoin.Features.Wallet/KeyManagement

**Comment by Aprogiena** [comment]
@nopara73 could you pls just summarize it for me very very briefly, how that relates to this issue?

**Comment by nopara73** [comment]
@Aprogiena The keymanager only stores the stuff what's needed. For example the wallet currently stores for every key: a p2pk script, a p2pkh script and a p2pkh address, while the keymanager only stores a pubkey and derives the rest from it.

**Comment by nopara73** [comment]
It can be easily further optimized, by only storing extpubkeys of accounts. Unfortunately the work stopped, because right now the wallet stores everything in wallet file, transactions hexes, transaction outputs and in order to make this change this must also be refactored. While it's not that hard, reviewing such massive amount of change leads to a developer deadlock, so not sure what's the future of this.

**Comment by Aprogiena** [comment]
ok, tx for explanation, i also suspect (but i don't know it actually) that the whole file is loaded to the memory and it remains there

**Comment by dangershony** [comment]
This can be closed now I think.

**Comment by bokobza** [comment]
This will be further improved on but if you want to close it @dangershony, I'm happy with it.

**Comment by dangershony** [comment]
yeah the main issue of a too bi wallet was full hex stored in the wallet so this can be closed now.
