### ISSUE TITLE
[Settings] DefaultMaxTipAge is 1 day, is it not too much?

### ISSUE THREAD

**Issue by Aprogiena** [stratisproject/StratisBitcoinFullNode#605]
There are couple of rules for consensus to consider itself in IBD, the last one is checking MaxTipAge, which default value is 24 hours. It seems quite a lot and the question is, for the purpose of considering itself as in IBD, is 24 hours value justified? 

On Bitcoin network with just 144 blocks per day, this could make some sense, but on Stratis network with 1350 block per day, it seems that a lower value would make better sense. 

However, currently, we use one value regardless the network, so we would need to make this part of consensus options if we wanted to preserve 24 hours for Bitcoin and have separated value for Stratis.

**Comment by bokobza** [comment]
I agree that we could in theory lower the value of DefaultMaxTipAge as we have many more blocks per day.
Maybe 12h, 6h, a tenth of 24h? How do we fix that? @Aprogiena @dangershony thoughts?

In any case I think it's probably good to split the values for the different networks.
I'll look to do this with https://trello.com/c/VdIJjjtt/55-nodesettings-use-a-different-way-to-add-settings-to-the-node

**Comment by Aprogiena** [comment]
The value should be different for each network. So once it is part of network options it is easy to say 24h for Bitcoin and I'd say 1 hour for Stratis should be very safe valye

**Comment by dangershony** [comment]
Agreed, we need to put it in Network (or ConsensusOptions)
