### ISSUE TITLE
[AsyncLoop] There are still some async loops that are not disposed.

### ISSUE THREAD

**Issue by Aprogiena** [stratisproject/StratisBitcoinFullNode#616]
It is probably from code written before the dispose was introduced to AsyncLoop.

`TimeSyncBehavior.StartWarningLoop` has one and `FullNode.StartPeriodicLog` has one.

**Comment by dangershony** [comment]
@nopara73 you are already dong the async stuff so this one is for you I guess.

**Comment by Aprogiena** [comment]
This is quite trivial, newly the Run method of factory returns IAsyncLoop, in these two cases I've found that the return value is not saved to variable and then disposed. So really, just introduce a variable, save the return value and dispose during shutdown.
