### ISSUE TITLE
Staking and mining should depend on the store feature

### ISSUE THREAD

**Issue by dangershony** [stratisproject/StratisBitcoinFullNode#622]
Currently if the node is in pruned mode staking can still happen.
This is problematic as peers will not be able to ask for the found block.

Staking and mining must depend on the store feature, and make sure the feature is active.

**Comment by bokobza** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[BlockStore] Staking and mining should depend on the store feature](https://trello.com/c/eILni3WU/314-blockstore-staking-and-mining-should-depend-on-the-store-feature)
