### ISSUE TITLE
[ConsensusLoop] PR 609 followup

### ISSUE THREAD

**Issue by Aprogiena** [stratisproject/StratisBitcoinFullNode#624]
PR #609 comes with a big set of changes in ConsensusLoop and related code, there are still number of improvements we would like to do. This issue is about the following improvements:

- in ChainHeadersBehavior - CheckAnnouncedBlocks should be removed
- in ChainState: `internal ConcurrentDictionary<uint256, uint256> InvalidBlocks` should be private HashSet protected by lock
- ConsensusLoop.ValidateBlock should be split into two methods, one which does the checking, and second that calls it and does the rest and block assembler should no longer call the later method 
- consider (do not implement) options in https://github.com/stratisproject/StratisBitcoinFullNode/pull/609/files#r145926967 and possibly create a new issue for that if needed

**Comment by dangershony** [comment]
Also I am not sure this commit will make it async, if it does not then add ti this list 
- Making consensus loop async

**Comment by Aprogiena** [comment]
actually no, the "make it async" is much bigger task that should go neither to 609 nor here, it should be separated task

**Comment by Aprogiena** [comment]
I'm dedicating #633 for that "make it async" affort.

**Comment by Aprogiena** [comment]
CheckAnnouncedBlocks will be removed as part of PR #492

**Comment by Aprogiena** [comment]
As for the last part here, I like the solution 

```
Just disconnect the peer and don't change Chain.Tip and let issue #229 rewind the header chain to the most recent best height. this will never set chain to 100 but have it directly set to 150 slightly delays
```

this means that if the attacker gave us the longest chain, say 200 in  height, then provided invalid block, then it will be disconnected and #229 will make sure that after disconnection of the longest chain will be discarded and replaced with chain of an actively connected peer. 

We just have to make sure that if there is no actively connected peer, we have to replace the chain when the next new peer is connected.
