### ISSUE TITLE
Bitcoin testnet, mempool rejecting witness txs

### ISSUE THREAD

**Issue by mikedennis** [stratisproject/StratisBitcoinFullNode#631]
I'm not sure if this is an issue with bitcoin testnet or with nbitcoin but when I'm running stratis.bitcoind on bitcoin testnet I'm getting lots of tx rejected to mempool because of this condition.

https://github.com/MetacoSA/NBitcoin/blob/master/NBitcoin/ScriptEvaluationContext.cs#L586 The txs are have witness.PushCount == 0 so this condition is failing.

Is this a problem with testnet or this nbitcoin check?

**Comment by dangershony** [comment]
@NicolasDorier what do you think?

**Comment by mikedennis** [comment]
One other interesting thing is this sets the context to 'Fail' not 'Invalid' because it is launched from here https://github.com/stratisproject/StratisBitcoinFullNode/blob/master/Stratis.Bitcoin.Features.MemoryPool/MempoolValidator.cs#L1107 - So we don't even get a log of it occuring because Fails are not logged because it ends up here https://github.com/stratisproject/StratisBitcoinFullNode/blob/master/Stratis.Bitcoin.Features.MemoryPool/MempoolBehavior.cs#L445 

There are a few Todo's along this path what do you think is the proper way of handling this @dangershony ?

**Comment by NicolasDorier** [comment]
The problem likely come from the fact that stratis bitcoind is not asking segwit transactions to the network.

Stratis.bitcoind should ask for blocks only to nodes supporting segwit, and then use

```
invPayload.Inventory.Add(new InventoryVector(node.AddSupportedOptions(InventoryType.MSG_TX), hash));
```

Same things when asking for Blocks. I remember I did that initially,

**Comment by NicolasDorier** [comment]
Issue is likely

```
https://github.com/stratisproject/StratisBitcoinFullNode/blob/master/Stratis.Bitcoin.Features.MemoryPool/MempoolBehavior.cs#L468
```

The witness flag is not added.

**Comment by mikedennis** [comment]
Thanks Nicolas that makes sense. I will look into that. What are these  Program.Length == 20 txs, are they some sort of pre-segwit txs?

**Comment by NicolasDorier** [comment]
It is a segwit scriptPubkey program version 0, p2wpkh as described by https://github.com/bitcoin/bips/blob/master/bip-0141.mediawiki

Because the stratis full node enforce segwit, it needs the segwit data for validating a segwit program.
Since the mempool was not asking for it, the transaction were rejected.

**Comment by mikedennis** [comment]
I added the **AddSupportedOptions** call to the mempool inventory message and I am now getting this happening a lot less but it still happens on occasion. I'm wondering whether this is do to with the second part of Nicolas' suggestion "make sure you are asking to a segwit compatible node".

I looked at block puller and it's does a peer requirements check prior to communicating with the node via https://github.com/stratisproject/StratisBitcoinFullNode/blob/master/Stratis.Bitcoin/BlockPulling/BlockPullerBehavior.cs#L152 Should we be doing the same thing in mempool?

**Comment by NicolasDorier** [comment]
so the rule should be:

* Allow a peer to connect (outbound and inbound) only if: It is whitelisted OR support segwit.
* Any case, never ask transactions and blocks to non segwit peers.

**Comment by dangershony** [comment]
Thank you Nicolas for the input.
This is true for the Bitcoin network, and we are making the check for activated deployments and only connecting to segwit nodes once its activated (I believe) which it is.

**Comment by NicolasDorier** [comment]
> only connecting to segwit nodes once its activated (I believe) which it is.

You can simplify now, and assume segwit is always activated.

**Comment by mikedennis** [comment]
I did a bit more research into this, and I believe we are already only connecting to segwit nodes. I believe this call in consensus should force the connection manager to only connect to segwit nodes: https://github.com/stratisproject/StratisBitcoinFullNode/blob/master/Stratis.Bitcoin.Features.Consensus/ConsensusFeature.cs#L116-L118 

Also I found this reference https://bitcoincore.org/en/segwit_wallet_dev/#network-services-optional that states:

> Transactions without any witness data (and therefore serialized in original format) may be sent to nodes with or without NODE_WITNESS support

So I am now thinking that my assumption that we shouldn't be receiving these TXs stripped segwit txs at all is invalid. Sounds like we will get them regardless if we are only connected to segwit nodes or not. I just want to confirm with you guys this is correct and then I'll close this issue.

**Comment by NicolasDorier** [comment]
You should still allow inbound connection to nodes not supporting NODE_WITNESS. You should just not ask them about transaction data.

If you ask tx only to node with NODE_WITNESS, and use `new InventoryVector(node.AddSupportedOptions(InventoryType.MSG_TX), hash)`, then you will always be able to validate all transactions.

**Comment by dangershony** [comment]
I think this is the case already, we only ask witness data from wit enabled nodes.
@mikedennis is this still a bug?

Perhaps we need to fix the MempoolBehaviour to look at the node service if its `NODE_WITNESS` or not.

**Comment by mikedennis** [comment]
@dangershony I think this needs some further debugging as I believe I was still seeing it rejecting some witness txs when I last tried it.

**Comment by mikedennis** [comment]
I will give it another try this weekend and see if I can provide some further info for analysis.

**Comment by mikedennis** [comment]
Re-tested this. I added some additional info to the log to identify whether the node has SegWit flag or not as well as logged the segwit error. See log info below. We think the node is Segwit but it is still sending us a transaction that fails with a Segwit program mismatch error.

```       ======Connection======
      Peer:::ffff:54.154.44.169:18333,         connected (outbound),      agent /Satoshi:0.15.0/, SEGWIT height=1259840
      Peer:::ffff:217.75.49.11:18333,          connected (outbound),      agent /Satoshi:0.15.0.1/, SEGWIT height=1259840
      Peer:::ffff:144.217.233.218:18333,       connected (outbound),      agent /libbitcoin:3.4.0/, SEGWIT height=unknown
      Peer:::ffff:54.153.41.74:18333,          connected (outbound),      agent /Satoshi:0.15.1/, SEGWIT height=1259840
      Peer:::ffff:35.187.74.199:18333,         connected (outbound),      agent /Satoshi:0.14.1/, SEGWIT height=1259840


warn: Stratis.Bitcoin.Features.MemoryPool.MempoolBehavior[0]
      Transaction ID '17a689d2bd478473e33b646cb3fd4447c7ff36c9661c73a087b867327cde8b95' rejected to memory pool from peer '[::ffff:217.75.49.11]:18333'. WitnessProgramMissmatch

**Comment by dangershony** [comment]
Ah ok so there could be two problems here wither we dont tell the peer we are segwit enabled or don't read segwit trx properly

**Comment by dangershony** [comment]
@mikedennis whats the update on this?

**Comment by mikedennis** [comment]
Haven't tried in a long time. Syncing testnet bitcoin right now - will take a look again once I'm synced.

**Comment by mikedennis** [comment]
Yes this is still occurring frequently on bitcoin testnet. Getting this error frequently:
``` MempoolErrorException:'WitnessProgramMissmatch' ErrorCode:'mandatory-script-verify-flag-failed',ErrorMessage:'WitnessProgramMissmatch' ```

And this one occasionally:
``` MempoolErrorException:'WitnessProgramEmpty' ErrorCode:'mandatory-script-verify-flag-failed',ErrorMessage:'WitnessProgramEmpty' ```
