### ISSUE TITLE
[ConsensusLoop] PR 609 followup 2 - Sequential consensus logic still not perfect on concurrent events

### ISSUE THREAD

**Issue by Aprogiena** [stratisproject/StratisBitcoinFullNode#636]
**Motivation:**

when this if triggered in ConsensusLoop
```
                    if (blockValidationContext.Error == ConsensusErrors.InvalidPrevTip)
                    {
                        this.logger.LogTrace("(-)[INVALID_PREV_TIP]");
                        return;
                    }
```
the chain stopped advancing

**Previous Work:**
Discussion took place here - https://github.com/stratisproject/StratisBitcoinFullNode/pull/609#discussion_r145900436 - the original implementation was resetting consensus tip and chain tip when InvalidPrevTip happened and we argued that this is not the right thing to do, so we changed it not to reset anything. 

That seems to be the right thing to do for the block collision at the tip, but then for next block the problem is that consensus tip is not reset anywhere.

**Scenarios:**
 We have 3 sources of new blocks to consensus
- puller loop
- pow mining
- pos mining

We could possibly reduce this to 2 sources if we disregard pow mining in sidechains, which is possible. Neither in Stratis testnet or mainnet pow mining is no longer possible. But if we find solution that works for 3 sources, why not to use it ...

Notation: 
- block chain is formed with upper cases blocks A -> B -> C-> D -> E, last in the sequence is the tip
- each block has an index `p`, `w` or `s` depending on how we obtained it, so we can have `Ap -> Bp -> Cs -> Dp -> Ew`
- if there are two blocks from different sources at the same height, we add index number: `B1p` vs `B2s` and which one we processed first in AcceptBlock depends on which one more to the left:

```
Ap -> Bp -> C1p        -> Dp
                -> C2s
```
this means that block C from puller came first and then block C from PoS mining arrived (before block D arrived and block D extended C1p)

_Scenario 1a_

```
Ap -> Bp -> C1p        -> Dp
                -> C2s
           
```
here we called AcceptBlock(C1p) and then AcceptBlock(C2s), block C1p was processed, block C2s returned InvalidPrevTip
this situation is currently handled well because InvalidPrevTip does not change puller tip nor consensus tip
therefore the following AcceptBlock(Dp) is processed without problem as Dp's prev hash is our tip C1p (C2s was just discarded)

_Scenario 1b_

```
Ap -> Bp -> C1s        -> Dp
                -> C2p
```
here we called AcceptBlock(C1s) and then AcceptBlock(C2p), block C1s was processed, block C2p returned InvalidPrevTip
this situation is currently handled well because InvalidPrevTip does not change puller tip nor consensus tip
therefore the following AcceptBlock(Dp) is processed without problem as Dp's prev hash is our tip C1s (C2p was just discarded)

_Scenario 2_

```
Ap -> Bp -> C1s
                -> C2p -> Dp
           
```
here we called AcceptBlock(C1s) and then AcceptBlock(C2p) and then AcceptBlock(Dp), block C1s was processed, block C2p returned InvalidPrevTip
and was just discarded, but then Dp arrived, which is now longer chain, but its previous tip is C2p, which is not our tip and hence 
InvalidPrevTip was returned and the block was discarded
this is currently not handled well

_Scenario 3_

```
Ap -> Bp -> C1s        -> D1s 
                -> C2p        -> D2p -> Ep
           
```
Here we mined a block C1s and then received C2p, which was discarded on InvalidPrevTip, then we mined another block on the top of C1s, 
but then D2p arrived form puller and was discarded on InvalidPrevTip again, then Ep came and was discarded
this is currently not handled well

_Scenario 4_

Puller can return null in case it detected reorganization, this happens when 

```
this.Chain.GetBlock(this.location.Height + 1);
```

this returns null and subsequently this

```
if (!this.Chain.Contains(this.location.HashBlock))
```

returns true

that can happen when a new peer provides its headers or when existing peer provides different chain than before

let's call this operation `pR`
the problem is that between the detection of the reorg and the reorg itself in `PullerLoop`, new AcceptBlock can be called from PoS or PoW, thus we can have:

```
Ap -> Bp -> pR_detected        -> pR_executed
                        -> C1s
```

this will result in rewind being made on consensus even if it shouldn't be done and the final state is going to be 

```
Ap -> Bp 
```

this situation is not handled optimally as we lost the block we just mined even if there is no longer chain available (consider the reorg was for `Ap -> B'p -> C'p`)
 

-----

We need to find a solution that at least fixes scenarios 2 and 3 and if possible, fixes 4 as well, although that is not critical. 
And we do not want to disrupt scenarios 1a and 1b (nothing should happen in that case and that is correct). However, it is possible to have alternative resolution for scenario 1a, which makes `C2s` the tip 
(as a preference for our own blocks over remote block. But then the scenario 1b must be handled without any changes of the tip.

Feel free to add more scenarios using the given notation.

**Comment by Aprogiena** [comment]
To solve scenario 2, we could extend logic in that InvalidPrevTip branch. At that point we probably can't accept the block because we rejected its previous block. So we would like to detect that our consensus chain is shorter than and in that case we would like to make a reset of the consensus up to the fork. 

So starting here

```
Ap -> Bp -> C1s
                -> C2p -> Dp
```

when we received Dp, we would reject the block and jump into InvalidPrevTip branch, there we should check whether our consensus tip is on the chain. 

We would find that our tip is C1s and it is not on the longest chain. Therefore we would find a fork point - Bp and reset our consensus tip and puller (but not chain tip) to Bp. 

This should immediately solve scenario 3 as well:

```
Ap -> Bp -> C1s        -> D1s 
                -> C2p        -> D2p -> Ep
```
here when we receive D2p, we still have longest chain with D1s, so D2p would go to InvalidPrevTip and our new code would find out that our consensus tip STILL IS on our best chain. But then we would receive information about Ep (i.e. header) and then we would receive Ep block. At that point we would again end in InvalidPrevTip but now we would find out that consensus tip is not on the best chain anymore. We would find the fork point and that would be Bp again. We would reset consensus and the puller to Bp and all should be OK.

This does not solve scenario 4, however.

**Comment by Aprogiena** [comment]
To solve scenario 4, we could consider saving the consensus loop status in front of this line:
```
blockValidationContext.Block = this.Puller.NextBlock(cancellationToken);
```
i.e. have something like
```
ChainedBlock consensusTip = this.Tip;
blockValidationContext.Block = this.Puller.NextBlock(cancellationToken);
```
and then to check that this is still the case when we are in the lock:

```
if (blockValidationContext.Block == null)
                    {
                        lock (this.consensusLock)
                        {
                           HERE CHECK this.Tip against consensusTip, if it is not equal, it means that meanwhile a new block was delivered by PoS or PoW
```

because a new block was delivered we don't want to rewind
we probably should reset puller tip to match consensus (although this should have been done by AcceptBlock on that new block), but just to be sure, we should set puller tip and then call continue to go next round

**Comment by dangershony** [comment]
I want to go back to scenario 2:
```
Ap -> Bp -> C1s
                -> C2p -> Dp
```

Our consensus tip, chain tip and puller tip are now C1s (C2p was rejected), next Dp was found and received form one of the peers and chain tip is updated, the puller will detect that its tip C1s is no longer on the chain and trigger a rewind back to Bp and we will download again C2p (we could actually keep in cache such rejected blocks to avoid redownload) and then we will download Dp.

So it seems to me the code should be able to recover unless I missed something. 

Scenario 3:
```
Ap -> Bp -> C1s        -> D1s 
                -> C2p        -> D2p -> Ep
```
Same as my previous assumption Ep will change chain tip and trigger a reorg back to Bp.  

>. But then we would receive information about Ep (i.e. header) and then we would receive Ep block

I would like to correct your flow here, Ep header would update chain, then the puller would trigger a reorg to rewind back to Bp, and only then the Ep block will be pushed to consensus.  

As you suggested perhaps we should check if consensus tip is still on the best chain, but I am not sure how we will act on that, this will be handled inside the reorg lock (when it gets triggered).  

From your analysis you assume blocks will arrive in to consensus directly when they are found but you need to remember that first chain tip is updated then a block is pulled based on that.  
So I think there might wrong behavior (or inefficiency) in the LookaheadblockPuller at the point where we ask for the next block header.
```
                ChainedBlock header = this.Chain.GetBlock(this.location.Height + 1);
                DownloadedBlock block;

                bool isDownloading = false;
                bool isReady = false;
                if (header != null) CheckBlockStatus(header.HashBlock, out isDownloading, out isReady);
```

If the network reorged `header` will be on a different chain, it wont be downloaded so we go down the `else` path, header is not null and we will download the block
```
                else
                {
                    // Otherwise we either have reorg, or we reached the best chain tip.
                    if (header == null)
                    {
                        if (!this.Chain.Contains(this.location.HashBlock))
                        {
                            this.logger.LogTrace("Blockchain reorganization detected.");
                            break;
                        }

                        this.logger.LogTrace("Hash of the next block is not known.");
                    }
                    else
                    {
                        this.logger.LogTrace("Block not available.");

                        // Or the block is still being downloaded or we need to ask for this block to be downloaded.
                        if (!isDownloading) this.AskBlocks(new ChainedBlock[] { header });

                        this.OnStalling(header);
                    }
``` 
When header is downloaded we will hit this code and return null (to indicate a reorg)
```
                if (isReady && TryRemoveDownloadedBlock(header.HashBlock, out block))
                {
                    this.logger.LogTrace("Consuming block '{0}'.", header.HashBlock);

                    if (header.Previous.HashBlock != this.location.HashBlock)
                    {
                        this.logger.LogTrace("Blockchain reorganization detected.");
                        break;
                    }
```

This could be improved as we will know a reorg happened already when we have the header.  
So we could potentially change the the header check and trigger the reorg already when we have the header, consensus reorg will anyway ask to download that block again.
```
                bool isDownloading = false;
                bool isReady = false;
                if (header != null)
                {
                    if (header.Previous.HashBlock != this.location.HashBlock)
                    {
                        this.logger.LogTrace("Blockchain reorganization detected.");
                        break;
                    }

                    this.CheckBlockStatus(header.HashBlock, out isDownloading, out isReady);
                }
```

**Comment by Aprogiena** [comment]
I should add that in the proposed solution 2 and 3 I forgot to rewind UTXO set.

**Comment by Aprogiena** [comment]
> I want to go back to scenario 2:

``` 
Ap -> Bp -> C1s
                -> C2p -> Dp
```
> Our consensus tip, chain tip and puller tip are now C1s (C2p was rejected), next Dp was found and received form one of the peers and chain tip is updated, the puller will detect that its tip C1s is no longer on the chain and trigger a rewind back to Bp and we will download again C2p (we could actually keep in cache such rejected blocks to avoid redownload) and then we will download Dp.

You say here that the puller will detect that its tip is no longer on the chain. Where?
I think what happens here is 

1. C1s mined -> AcceptBlock(C1s) -> enters critical section -> goes up to SignalBlock
2. C2p found -> AcceptBlock(C2p) -> waits for lock
3. C1s finishes and leaves critical section, chain.Tip == puller.location == consensus.tip == C1s
4. C2p enters critical section -> leaves with InvalidPrevTip
5. puller NextBlock is called, lookaheadLocation and everything is fine, so directly goes to NextBlockCore
6. `header = this.Chain.GetBlock(this.location.Height + 1);` this is just height, not actual tip check, so the height + 1 is the same for C1s as for C2p
7. Dp is asked and arrives

**Comment by Aprogiena** [comment]
```
Ap -> Bp -> C1s        -> D1s 
                -> C2p        -> D2p -> Ep
```
>Same as my previous assumption Ep will change chain tip and trigger a reorg back to Bp.

  >>  . But then we would receive information about Ep (i.e. header) and then we would receive Ep block

>I would like to correct your flow here, Ep header would update chain, then the puller would trigger a reorg to rewind back to Bp, and only then the Ep block will be pushed to consensus.

If the longer chain is just 1 longer than our current chain, I don't think that puller detects this.
However, after inspection of logs, it seems that the puller is very inefficient and behaves erratically when IBD is finished. 

I can see this log:
```
[2017-10-24 13:05:53.7406 11] TRACE: Stratis.Bitcoin.BlockPulling.LookaheadBlockPuller.NextBlockCore Consuming block '8187d729f8b2f2b95628ea2c10ce1cf342f4a36c068fdd100c4041fbc680dacd'.
[2017-10-24 13:05:53.7406 11] TRACE: Stratis.Bitcoin.BlockPulling.LookaheadBlockPuller.NextBlockCore (-):'NBitcoin.Block'
[2017-10-24 13:05:53.7406 11] TRACE: Stratis.Bitcoin.BlockPulling.LookaheadBlockPuller.NextBlock Recalculating lookahead: Last request block height is 161281, last processed block height is 161283, ActualLookahead is 4.
```

So what just happened is that we downloaded block at height 161283, yet tour ActualLookahead is still 4 (this is the minimum) and our `this.lookaheadLocation.Height` is 161281. This leads to nonsensual call

```
[2017-10-24 13:05:53.7406 11] TRACE: Stratis.Bitcoin.BlockPulling.BlockPuller.AskBlocks (downloadRequests:[161282,161283])
```
when we request blocks 161282 and 161283. 

All the time before, when we touched the puller, we've focused on good IBD performance and correctness and we haven't reviewed how it behaves after IBD. And it seems that it behaves poorly. It seems like blocks are downloaded more than once. It does not really damage anything, it is just brutally inefficient and maybe the blocks are also leaking there, not sure about that, but I can easily imagine that could be the case.

But that is just a side note that we do have inefficient puller. It does not really affect the problem discussed in this issue.

**Comment by Aprogiena** [comment]
> From your analysis you assume blocks will arrive in to consensus directly when they are found but you need to remember that first chain tip is updated then a block is pulled based on that.
So I think there might wrong behavior (or inefficiency) in the LookaheadblockPuller at the point where we ask for the next block header.

I think that there is no such check in the puller and the fact that tip changes won't do anything to the puller. I think this is because we have there that `header = this.Chain.GetBlock(this.location.Height + 1);` which is OK regardless if the chain changed or not. However, I currently don't think this is the problem we should be solving.

After considering the all new information, what you wrote, and what I found in the logs. I still believe the proposed solutions I've presented are correct (would fix the problem and the problems are valid), except that I forgot to rewind UTXO sets there.

**Comment by dangershony** [comment]
Ok some more comments
>C1s finishes and leaves critical section, chain.Tip == puller.location == consensus.tip == C1s

This not entirely correct:
C1s came form the miner so at the end of AccpetBlock() chain.Tip == consensus.tip, however if chain.Tip advanced then this code `this.Tip.ChainWork > this.Chain.Tip.ChainWork` wont be called and chain will be on a different chain (longer) we should then expect the puller to signal a reorg. 

I just got the bug you where talking about after mining all night.
Consensus is behind chain and blocks are rejected.

```
info: Stratis.Bitcoin.FullNode[0]
      ======Node stats====== 10/25/2017 09:55:25 agent StratisBitcoin:1.0.2
      Headers.Height:        162358   Headers.Hash:         77094733ddf55c351e62f9af28117ad881538e1d14bd85ed5a3f877ac54b56e7
      Consensus.Height:      161754   Consensus.Hash:       f62217161c1dd22cb8336fcf647228e2d63a79ab99960b5a44f5ebd3515013e4
      BlockStore.Height:     161754   BlockStore.Hash:      b5666ecf179f84b01e9a466c0c30574ba643c7fa5279dbd8f642e5bd13990eda
      Wallet.Height:         161753   Wallet.Hash:          c8ceb2c73769912184599e8b0c5d583eb28c4dc192d30951fc4c99d353a4b632

      ======Mempool======
      MempoolSize: 5    DynamicSize: 7 kb   OrphanSize: 0

      ======Wallets======
      Wallet: multiwallet1,        Confirmed balance: 1003781.91509820
      Wallet: MultiWallet,         Confirmed balance: 20664999.04751829

      ======Connection======
      Node:::ffff:84.192.155.226:26178,        connected (outbound),      agent /Stratis:2.0.0.3/,  height=162358
      Node:::ffff:54.37.46.84:26178,           connected (outbound),      agent /Stratis:2.0.0.3/,  height=162344
      Node:::ffff:51.140.47.41:26178,          connected (outbound),      agent StratisBitcoin:1.0.2,  height=162358
      Node:::ffff:51.140.99.233:26178,         connected (outbound),      agent StratisBitcoin:1.0.2,  height=162358
      Node:::ffff:13.64.76.48:26178,           connected (outbound),      agent /Stratis:2.0.0.3/,  height=162059


fail: Stratis.Bitcoin.Features.Consensus.ConsensusLoop[0]
      Block '7d4a5f7e003773ada00a97a3def1e4d3aa7da818275d5a8d1ac304f25172aa24' rejected: invalid previous tip
info: Stratis.Bitcoin.FullNode[0]
      ======Node stats====== 10/25/2017 09:55:30 agent StratisBitcoin:1.0.2
      Headers.Height:        162359   Headers.Hash:         7d4a5f7e003773ada00a97a3def1e4d3aa7da818275d5a8d1ac304f25172aa24
      Consensus.Height:      161754   Consensus.Hash:       f62217161c1dd22cb8336fcf647228e2d63a79ab99960b5a44f5ebd3515013e4
      BlockStore.Height:     161754   BlockStore.Hash:      b5666ecf179f84b01e9a466c0c30574ba643c7fa5279dbd8f642e5bd13990eda
      Wallet.Height:         161753   Wallet.Hash:          c8ceb2c73769912184599e8b0c5d583eb28c4dc192d30951fc4c99d353a4b632

      ======Mempool======
      MempoolSize: 5    DynamicSize: 7 kb   OrphanSize: 0

      ======Wallets======
      Wallet: multiwallet1,        Confirmed balance: 1003781.91509820
      Wallet: MultiWallet,         Confirmed balance: 20664999.04751829

      ======Connection======
      Node:::ffff:84.192.155.226:26178,        connected (outbound),      agent /Stratis:2.0.0.3/,  height=162359
      Node:::ffff:54.37.46.84:26178,           connected (outbound),      agent /Stratis:2.0.0.3/,  height=162344
      Node:::ffff:51.140.47.41:26178,          connected (outbound),      agent StratisBitcoin:1.0.2,  height=162359
      Node:::ffff:51.140.99.233:26178,         connected (outbound),      agent StratisBitcoin:1.0.2,  height=162359
      Node:::ffff:13.64.76.48:26178,           connected (outbound),      agent /Stratis:2.0.0.3/,  height=162059
```

I realise perhaps the problem is the puller.Tip is out of sync with consensus.Tip and the reorg is never triggered.
**Your fix is probably correct**
>when we received Dp, we would reject the block and jump into InvalidPrevTip branch, there we should check whether our consensus tip is on the chain.

>We would find that our tip is C1s and it is not on the longest chain. Therefore we would find a fork point - Bp and reset our consensus tip and puller (but not chain tip) to Bp

**Comment by Aprogiena** [comment]
i know what you mean, but i did assume `this.Tip.ChainWork > this.Chain.Tip.ChainWork` this to be true, i.e. the puller delivers after this is executed, that's why i said
```
C1s mined -> AcceptBlock(C1s) -> enters critical section -> goes up to SignalBlock
```
and i said that exactly because SignalBlock is after that chain work check

**Comment by dangershony** [comment]
Did you consider this scenario?
`chain at Bp -> C1s mined -> AcceptBlock(C1s) -> enters critical section -> chain advance Dp  -> C1s try to update chain FAIL! `

**Comment by Aprogiena** [comment]
Do you mean that when C1s enters the CS then concurrent chain changes to Ap->Bp->C1p->Dp? That should not cause anything because InvalidPrevTip check is based on 
```
if (context.BlockValidationContext.Block.Header.HashPrevBlock != this.Tip.HashBlock)
```
and this is working with consensus tip, not concurrent chain tip.
As such C1s would NOT FAIL and would be accepted as new consensus. However, chain work would not advance, therefore it would not change the puller or concurrent chain tip. Therefore the next is that C1p would be returned from puller and would actually be rejected on InvalidPrevTip.

**Comment by dangershony** [comment]
Yes exactly and because we don't update the puller.Tip then the puller will assume success and keep on serving blocks that will all be rejected, your suggestion will fix this.
