### ISSUE TITLE
Implement getaddr similar to stratisX (and core)

### ISSUE THREAD

**Issue by dangershony** [stratisproject/StratisBitcoinFullNode#637]
This is how its done in core
```
    else if (strCommand == NetMsgType::GETADDR)
    {
        // This asymmetric behavior for inbound and outbound connections was introduced
        // to prevent a fingerprinting attack: an attacker can send specific fake addresses
        // to users' AddrMan and later request them by sending getaddr messages.
        // Making nodes which are behind NAT and can only make outgoing connections ignore
        // the getaddr message mitigates the attack.
        if (!pfrom->fInbound) {
            LogPrint(BCLog::NET, "Ignoring \"getaddr\" from outbound connection. peer=%d\n", pfrom->GetId());
            return true;
        }

        // Only send one GetAddr response per connection to reduce resource waste
        //  and discourage addr stamping of INV announcements.
        if (pfrom->fSentAddr) {
            LogPrint(BCLog::NET, "Ignoring repeated \"getaddr\". peer=%d\n", pfrom->GetId());
            return true;
        }
        pfrom->fSentAddr = true;

        pfrom->vAddrToSend.clear();
        std::vector<CAddress> vAddr = connman.GetAddresses();
        FastRandomContext insecure_rand;
        for (const CAddress &addr : vAddr)
            pfrom->PushAddress(addr, insecure_rand);
    }
```

**Comment by dangershony** [comment]
Note X has this logic
```
    // This asymmetric behavior for inbound and outbound connections was introduced
    // to prevent a fingerprinting attack: an attacker can send specific fake addresses
    // to users' AddrMan and later request them by sending getaddr messages. 
    // Making users (which are behind NAT and can only make outgoing connections) ignore 
    // getaddr message mitigates the attack.
    else if ((strCommand == "getaddr") && (pfrom->fInbound))
    {
        // Don't return addresses older than nCutOff timestamp
        int64_t nCutOff = GetTime() - (nNodeLifespan * 24 * 60 * 60);
        pfrom->vAddrToSend.clear();
        vector<CAddress> vAddr = addrman.GetAddr();
        BOOST_FOREACH(const CAddress &addr, vAddr)
            if(addr.nTime > nCutOff)
                pfrom->PushAddress(addr);
    }
```

**Comment by bokobza** [comment]
Is this related to the node discovery issue?

**Comment by dangershony** [comment]
To some extent yes, but this code might explain why discovery is quite hard in QT nodes, notice that with none inbound nodes getaddr is ignored (which is odd as I actually don't get addr replies when my node is inbound).

I suspect in our case discovery is not working for C# nodes because the servers are blocking connections for some reason.

**Comment by dangershony** [comment]
@fassadlr please comment on this, do we need to fix our logic a bit to fit the addr payload?

**Comment by dangershony** [comment]
>discourage addr stamping of INV announcements

We probably need to implement `pfrom->fSentAddr` 

>This asymmetric behavior for inbound and outbound connections was introduced to prevent a fingerprinting attack

I am not sure how valid this is @Aprogiena can do you have any comments?

**Comment by Aprogiena** [comment]
I think this touches @fassadlr  work in connector. But I am unsure whether we have this already or not

**Comment by fassadlr** [comment]
@dangershony I had a look at what we do, and it in PeerAddressManager it looks like we touch the peer (update timestamps) ONLY when NOT in -connect mode:

```
            if ((this.Mode & PeerAddressManagerBehaviourMode.Discover) != 0)
            {
                if (this.AttachedPeer.State == NetworkPeerState.Connected)
                    this.peerAddressManager.PeerConnected(this.AttachedPeer.PeerEndPoint, this.dateTimeProvider.GetUtcNow());
            }
```

I dont actually think that this is correct. PeerDiscovery should have it own PeerAddressManagerBehaviour instance where the mode is set to `discover ` sot that we don't set handshaked/connected timestamps.

> This asymmetric behavior for inbound and outbound connections was introduced to prevent a fingerprinting attack

If I understand this correctly, we need to prevent an IP X sending fake addresses and then later getting those fake addresses back? Effectively spamming the network with fake addresses?

**Comment by dangershony** [comment]
For the very least we have to implement `pfrom->fSentAddr` this is easy we just add a flag int he behaviour assigned to @ferdeen

**Comment by bokobza** [comment]
I think we have something already. Look here for the sending of `getaddr`: https://github.com/stratisproject/StratisBitcoinFullNode/blob/master/src/Stratis.Bitcoin/P2P/PeerDiscoveryLoop.cs#L180
and here for the receiving: https://github.com/stratisproject/StratisBitcoinFullNode/blob/master/src/Stratis.Bitcoin/P2P/PeerAddressManagerBehaviour.cs#L69 
Now maybe the implementation of what's returned by the receiving node is different.

**Comment by dangershony** [comment]
Yeah we just need to add a flag in the behaviour (the second link) to not respond twice for a GetAddr payload.

**Comment by Aprogiena** [comment]
but it does not say "not respond twice", it said "do not respond at all"

**Comment by bokobza** [comment]
@ferdeen can you comment on this?
