### ISSUE TITLE
[Tests] Tests with multiple nodes only delete last node's data folder

### ISSUE THREAD

**Issue by Aprogiena** [stratisproject/StratisBitcoinFullNode#641]
For example we have `TestData.Given__NodesAreSynced__When__ABigReorgHappens__Then__TheReorgIsIgnored` and in this folder we have subfolders `0`, `1` and `2` which each contains data folder for each of 3 nodes in this test. At the end of the test, the cleanup routines intend to delete those data directories, but fails to do so and only delete subfolder `2`.

**Comment by fassadlr** [comment]
@Aprogiena Yes I have noticed the same thing. This can be related to @mikedennis issue #702. I'll look into these.

**Comment by fassadlr** [comment]
OK Yeah I can confirm this is happening. Although not sure it is an issue as the NodeBuilder does in fact clean ALL the folder when the test starts up.

**Comment by Aprogiena** [comment]
i know it does, but that just means the bug is not fatal
still a bug though ;)

**Comment by Aprogiena** [comment]
i mean i am not sure this deleting feature is a good thing at all
because when i run test and it deletes its files, i have no chance to examine them (e.g. logs)

so i would vote for not to delete anything at all ...

so my original report was about that there is a bug
but maybe better than fixing the bug would be to avoid deleting anything

any issues with not deleting anything, anyone?

**Comment by fassadlr** [comment]
@Aprogiena in my  branch where I'm looking at these tests, I have actually taken out the deletion of the test data after the test completes. So I'm with you on this one. The test runner can cleanup before it starts.

**Comment by Aprogiena** [comment]
ok, so how about we change this issue to that removing the delete operation after the test is done

but i need @dangershony and @bokobza and @Neurosploit to confirm that there is no harm with that (i.e. that the deletion is not needed)

**Comment by Neurosploit** [comment]
With regards to starting off with a clean scenario you have two options: Cleanup before the test or delete after the test. If the delete after the test is missing out on deleting things then doing a cleanup before the test starts is a better way to handle things in my opinion.

**Comment by fassadlr** [comment]
@Neurosploit I agree!

**Comment by bokobza** [comment]
I agree, cleaning the test data **before** the tests run is a better way (the only way!) to have test data available for investigation after a test has run.

**Comment by fassadlr** [comment]
@bokobza Im going to do a quick PR to fix this.

**Comment by dangershony** [comment]
Was this fixed @fassadlr ?

**Comment by fassadlr** [comment]
@dangershony I have looked at the Dispose methods of the runners as well as the NodeBuilder class and it appears that we don't clean the folders any more AFTER the test has completed. This is what was discussed, so I'm closing this issue.
