### ISSUE TITLE
[PosConsensusValidator] Enforcing network split using timing attack

### ISSUE THREAD

**Issue by Aprogiena** [stratisproject/StratisBitcoinFullNode#644]
The following only applies for C# node, StratisX is safe.

There are these rules for time stamps in POS consensus validation (and executed in this order during validation flow):
- TimeTooNew - block header timestamp must not be greater than coinbase tx timestamp + 15 
- StakeTimeViolation - block header timestamp must be equal to coinstake tx timestamp & it must be divisible by 16 (represented as unix timestamp)
- BlockTimestampTooEarly - block header timestamp must be at least previous block header timestamp +1
- BlockTimestampTooFar - block header timestamp must not be greater than node's adjusted time +15
- BlockTimeBeforeTrx - each transaction (including coinbase/coinstake) timestamp must be lower than or equal to block header timestamp

If any of those errors occur, AcceptBlock in consensus loop uses `this.chainState.MarkBlockInvalid(rejectedBlockHash);` to mark such a block as invalid and will never sync with the chain based on this block again. 

This can be used by malicious attacker, who can find a new block with timestamp in the future - say 20 seconds from now. The malicious attacker will then propagate this block to 1 big miner (node that is known to have a big stake on the network and create lots of blocks). 

That node will reject the block and mark it as invalid. 

The malicious attacker then wait 6 seconds and propagates the block to the rest of the network, which accepts it (unless another block was found in the meantime). The network will then be split as the big miner (the target of this attack) will not be on the longest chain. Unless the big miner is super big, it is unlikely for it to mine longer chain on its own than the rest of the network. 

The attacker eliminated 1 competitor and can continue to attack another big miner. After a while, it should succeed to eliminate as many big miners as needed for itself to earn more coins.

-------

Solution is quite simple, BlockTimestampTooFar must be treated specially in AcceptBlock and must not lead to marking the block as invalid. The block should be rejected, but the rejection should be just for now and future chains built on the top of this block should be accepted.

**Comment by dangershony** [comment]
Excellent observation, I would not call it a network split rather an attack on a specific node.
Yes the fix you propose will work, I would suggest actually we add to the consensus errors a severity flag and failures that are not consensus errors will not mark-invalid/ban a node.

**Comment by Aprogiena** [comment]
it is just a detail of the name, but i think this does belong to the category of network splits, you can do it with one node, you can do it with 10 nodes at once, or more ... the end game is that the network splits into multiple parts

if you planned your targets very well and was aware of the network topology (which today is quite possible), then you could select what is called a bridge in graph theory and make the network graph split in two by just attacking tens of nodes instead of hundreds or thousands and have thousands nodes in each part, but that is just playing fun with the stuff

anyway, as for your proposal - in Bitcoin I believe it is not error specific, but rather context specific (i.e. single error happening on two different place can have two different types of penalty), which is probably easier to design (unless we carefully have strictly one error per context - i think we actually have that, but i'm not sure about it)

on one hand this is very clean in code that you have all the information about each error on one place. on the other hand, that information is suddenly out of context and invisible within the code that uses it. so i'm not sure about it

however, regarding marking invalid or not - this would be almost always true except for just very very few errors

**Comment by Aprogiena** [comment]
ok, thought about this again and it is not as trivial. or the fix is not. suppose we just reject the block, then the peer is not disconnected and is still allowed to present a longest chain. this means that such a malicious peer can effectively generate blocks in the future and we will still listen to it. this can imho be used to completely direct which chain we will sync to.

to fix this, i'd suggest creating a second list of blocks that are banned temporarily. so with each such block a timestamp will be set saying when does the ban expires. and what we do is we simply set the expiration of the ban to this rejected block time, when it becomes valid. this means that if we are provided with such a block when it is valid, all is ok, but before that, such peers will be banned
