### ISSUE TITLE
[Address Discovery] Refactor and bug fix

### ISSUE THREAD

**Issue by dangershony** [stratisproject/StratisBitcoinFullNode#650]
Currently there is a bug where address discovery is triggered on first time start will block the node connection loop for a long while (until then 1000 addresses are discovered).
Additionally addresses discovered in the addnode (and connect) nodes group will not be stored to disk (this might be intentional)

The obvious fix is to reduce the count to a lower number, however it might be a chance to refactor a bit the address manager and discovery.

There are several way this can be changed:
- Stop doing discovery form the NodesGroup loop, and instead create a new asyncloop that will trigger for one loop only and do the discovery (in this case we can keep the 1000 limit) the loop will only start if address db is empty.
- This is a chance to bring over some more components from NBticoin mainly AddressManager, AddressManagerBehaviour and apply to them styling and documentation we could also bring over NodesGroup. NodeServer.
- Apply styling and documentation to the remaining connection components.

**Comment by dangershony** [comment]
As part of this task we will also bring AddressManager and AddressManagerBehaviour to the fullnode.
This classes should probably get different names
I would suggest the address db (the file address.dat) will be changed to be a json file.

**Comment by fassadlr** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[NStratis] Bring over AddressManager](https://trello.com/c/BBrmUoVH/313-nstratis-bring-over-addressmanager)

**Comment by fassadlr** [comment]
Refactored and moved over with #740
