### ISSUE TITLE
[Bitcoin CoinView] Flushing takes long during IBD

### ISSUE THREAD

**Issue by Aprogiena** [stratisproject/StratisBitcoinFullNode#652]
so, the situation is as follows:

network: bitcoin mainnet
block: 278390
flushing frequency: 60 seconds

so, after one minute, we've advanced to 
block: 278813
number of blocks accepted during last minute: 423
number of coins in "all": 167272 coins (https://github.com/stratisproject/StratisBitcoinFullNode/blob/master/Stratis.Bitcoin.Features.Consensus/CoinViews/DBreezeCoinView.cs#L180)

then these two lines alone took 63 seconds: https://github.com/stratisproject/StratisBitcoinFullNode/blob/master/Stratis.Bitcoin.Features.Consensus/CoinViews/DBreezeCoinView.cs#L184-L185

from which removals took 20 second and inserts took 43 seconds

-----
another stats with 194274 coins:
19.1603185 seconds for 124052 tx removes, 44.4492368 seconds for 70222 tx inserts

so as we can see, removes are not that much of an issue, inserts are much worse

however, i am not sure where to go from here - either we need to do these inserts and removes or not, 
- if not, then obviously we need to improve it
- if yes, then we can only look at the performance of these inserts and removes - what each operation really does and is that best we can do (i.e. can't we do a bulk thing somehow to save something?)

**Comment by Aprogiena** [comment]
This is caused by not using DBreeze `Technical_SetTable_OverwriteIsNotAllowed` on transaction. The problem is that we have one open transaction for whole lifetime, which is wrong - see #656. This can be hacked around, but it is better to first fix #656 and then to fix this one with a trivial single call to Technical_SetTable_OverwriteIsNotAllowed. 

The speedup factor this brings is about 10x, which is especially noticeable on Bitcoin mainnet.

**Comment by Aprogiena** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[Bitcoin CoinView] Flushing takes long during IBD](https://trello.com/c/x02v5pz8/306-bitcoin-coinview-flushing-takes-long-during-ibd)

**Comment by dangershony** [comment]
Ok yes I think first we nee to address #656 and then this might become a none issue.

**Comment by Aprogiena** [comment]
Not a non-issue, but trivial to fix issue :-)
