### ISSUE TITLE
[DBreeze] Refactor all code touching DBreeze database to use it correctly

### ISSUE THREAD

**Issue by Aprogiena** [stratisproject/StratisBitcoinFullNode#656]
We are not using DBreeze correctly. There was a general assumption that DBreeze needs a single threaded context. This assumption is wrong. The correct restriction is

> one transaction can be run only in one .NET managed thread and can not be delegated to other threads.

What we currently have is DBreezeSingleThreadSession, which uses a single threaded scheduler and a single DBreeze transaction that is open for the entire app life. 

The correct usage is to create a transaction everytime we want to access the database and to dispose it when our work is done. This allows multithread access to DBreeze database, which we may or may not use.

The restriction mentioned above is enforced by the DBreeze engine itself. It is not necessary to do anything about it if the correct pattern is used, which is:

```
using (Transaction transaction = engine.GetTransaction())
{
    // do something here with the database
}
```

If we want to prevent parallel access, DBreeze has its own mechanism of locking that should be used instead of having our own thing.

**Comment by dangershony** [comment]
Ho my so the requirement to run in the thread it was created is not correct? can you confirm that in a test? this is great as we will not need to make any async calls to read from store (on a single thread)
Perhaps using a single Transaction was done for perf reasons?

I think we definitely need to refactor coinview for the fololowing reasons: 
- Remove the single thread requirement 
- Make it more extendable to allow to plug more data, like stake store, (and later) to add smart contract key value store etc... 
- Do the same changes that core did to their coinview (UTXO based instead of trx based).

**Comment by Aprogiena** [comment]
>Ho my so the requirement to run in the thread it was created is not correct?

Yes, the requirement is not correct. But it needs a little bit of thinking, I was too soft in my last comment here. What you can not do is to use `await` by default when you are working with a transaction. `await` does not guarantee you the same thread will be processing the code after the wait, so if you want to await something, you either need to make it little bit special (custom scheduler or custom synchronization context - and use it WITHOUT `ConfigureAwait(false)`. In other words DBreeze is not async friendly and needs little bit of consideration if you want to use it in async environment.


>  Perhaps using a single Transaction was done for perf reasons?
I can't presume the original reason, but if it was this, it is wrong. There is no perf gain in it.

> I think we definitely need to refactor coinview
This is not only about coinview, but of course, the major impact is on coinview. But this is about refactoring all code touching DBreeze.


> Do the same changes that core did to their coinview
I'm not sure how exactly they did it, but I would assume that all code touching UTXOs was changed as the basic structure was changed (is it correct?) If so, this is way beyond coinview, this affects brutally almost every component.

**Comment by Aprogiena** [comment]
Thinking about it little more. DBreeze seems async unfriendly. That custom context or scheduler won't really help. DBreeze uses the concept of thread not only for managing the transactions, but also for synchronization. So it seems that it won't be easy to come up with async-friendly version of DBreeze (should we try to modify it or ask its devs to do so).

Therefore it seems that the best approach is to keep transaction blocks without awaits, which means we want to have transaction blocks as short as possible and occasionally we will waste some thread time, but that's the requirement of working with DBreeze I guess. It is not a big deal though, just minor inefficiency.

**Comment by Aprogiena** [comment]
I should maybe add that the minor inefficiency is absolute, not relative. It can't be any worse than we have now.

**Comment by Aprogiena** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[DBreeze] Refactor all code touching DBreeze database to use it correctly](https://trello.com/c/llveb1Kr/307-dbreeze-refactor-all-code-touching-dbreeze-database-to-use-it-correctly)
