### ISSUE TITLE
[Security] Peer bans - low level

### ISSUE THREAD

**Issue by Aprogiena** [stratisproject/StratisBitcoinFullNode#658]
We have a general issue #400 to implement peer banning. I think this task should be divided into two tasks:

1. Low level code that enforces bans that are already in place + storage of those bans + removal of expired bans
2. High level code that adds new bans

The low level code is expected to to maintain the information about who is banned for what and for how long and use this information on both incoming and outgoing connections to prevent being connected to such nodes.

The high level code should then use the low level code when a new peer to ban is identified. This should be implemented in chain headers behavior (when we receive a new chain of headers from a peer) and in consensus validation (when we receive a new block from a peer).

So this issue is for the low level part. I'll change #400 to be for the high level part.

**Comment by Aprogiena** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[Security] Peer bans - low level](https://trello.com/c/2P5z9NLe/309-security-peer-bans-low-level)

**Comment by dangershony** [comment]
I think for the store of banned nodes we can reuse the add manager that @fassadlr is currently working on.
That has a db of peers with all kind of stats on it we can use that to add peers that are banned and a ban time.

**Comment by Aprogiena** [comment]
yes, and i would also store the reason for banning

**Comment by dangershony** [comment]
Adding this comments to the issue https://github.com/stratisproject/StratisBitcoinFullNode/pull/710#issuecomment-343860774

**Comment by dangershony** [comment]
@Aprogiena I am currently working on the consensus banning, I will submit a PR soon.

**Comment by Aprogiena** [comment]
ok

**Comment by dangershony** [comment]
@Aprogiena you made some additional changes on banning (to include reason) is this still valid?

**Comment by Aprogiena** [comment]
this issue was about implementing the feature. the feature on low level (this issue) is only half baked imho. i think we still need to persist the bans 

on high level (the other issue) it is a question whether we ban enough
