### ISSUE TITLE
[NodesGroup] Bring to the FN from NBitcoin

### ISSUE THREAD

**Issue by dangershony** [stratisproject/StratisBitcoinFullNode#671]
- This should be applied styling and documentation 
- Need to change to use the asyncloop
- Rename this component to avoid collisions with NBitcoin
- Remove not used methods

**Comment by D3m0nKingx** [comment]
sorry for asking here... is there a problem accessing slack? it's not loading for me on pc nor mobile

**Comment by dangershony** [comment]
Another one is to replace all the NBitcoin trace with the FN trace (ILogger)

**Comment by fassadlr** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[NStratis] Bring over and refactor NodeGroup](https://trello.com/c/3V52wxhP/317-nstratis-bring-over-and-refactor-nodegroup)

**Comment by fassadlr** [comment]
Refactored and moved over with #740
