### ISSUE TITLE
[Settings] -rpcport stopped to work

### ISSUE THREAD

**Issue by Aprogiena** [stratisproject/StratisBitcoinFullNode#690]
Just trying to spawn 2 instances on 1 machine and `-rpcport` on cmd line or in config does not make the rpc server to go elsewhere, still using default port.

**Comment by D3m0nKingx** [comment]
Confirmed here as well, RPC port stays at the default 26174 on testnet

**Comment by Aprogiena** [comment]
the whole rpc settings is very weird imho

1. rpc settings are respected only if `-server=1`, which makes no sense
2. there is this warning `WARNING: RPC bind selection (-rpcbind) was ignored because allowed ip's (-rpcallowip) were not specified, refusing to allow everyone to connect` which also makes little sense to me and is not really compatible with how bitcoin core works (or did they change it recently?)

**Comment by dangershony** [comment]
No I think core is like that if you don't specify allowed ip RPC will not work (if I remember correctly)
Perhaps we need to just remove the server=1 configuration, this was there for bitcoin compatibility but I guess it was there in bitcoin to disable RPC, our node is modular based so we can just not use the RPC feature.

**Comment by Aprogiena** [comment]
I think @D3m0nKingx was testing sX and Bitcoin Core and found out that it works differently. @D3m0nKingx could you add more?

But if you look at it, it is quite counterintuitive how is it now. Not very user friendly.

**Comment by bokobza** [comment]
@noescape00 can we close this?

**Comment by noescape00** [comment]
@bokobza sure.
