### ISSUE TITLE
[Networking] Too many open files on linux

### ISSUE THREAD

**Issue by Aprogiena** [stratisproject/StratisBitcoinFullNode#695]
There are unclosed sockets, which for public nodes on linux causes 16k file descriptors to be exhausted after couple of hours of running. Then the node just crashes. 

We need to find the leak and always close all sockets gracefully to avoid that.

**Comment by bokobza** [comment]
@fassadlr did your previous changes around closing sockets fix that?

**Comment by fassadlr** [comment]
@bokobza I cant confirm 100%. Maybe @Aprogiena can confirm if this is still happening on linux?

Anyway, the work he's doing with NetworkPeer should fix all of these issues. So we can actually close this?

**Comment by Aprogiena** [comment]
I am rewriting the low level network stuff, so it is likely this will be mitigated. This stuff I'm touching in PR parts 10 and 11. Currently 10 is under review, so after 11 is merged, it is possible that this issue will be fixed (so not yet).

We should have a positive test against the issue description before we close it. So I would like to ask e.g. @D3m0nKingx if he could test the latest master AFTER PR part 11 is merged.

**Comment by D3m0nKingx** [comment]
@Aprogiena @dangershony This doesn't seem to be an issue any longer. I have some 100+ connections between Stratis Main and Testnet running, no crashes occurring or excess FDs, neither any sockets in CLOSED_WAIT state, just SYN_SENT, TIME_WAIT and ESTABLISHED, which all are being disposed of timely if connections are closed, fail to establish etc.

**Comment by Aprogiena** [comment]
tx, seems like refactoring work was not completely useless :-)
