### ISSUE TITLE
[Tests] Fix broken unit tests

### ISSUE THREAD

**Issue by mikedennis** [stratisproject/StratisBitcoinFullNode#702]
I have the following tests failing for me, even if I run them by themselves:

**LightWalletSyncManagerTest.cs - SyncFromDate_ChainTipAfterGivenDate_StartsSyncFromHeightAtTime**

> Message: Moq.MockException : 
> Expected invocation on the mock at least once, but was never performed: b => b.SyncFrom(4d7c27e1f2ba8801f9a48f9d0c05a89b2481f8429b7448716a20ceebeee68736)
> No setups configured

**BlockStoreTests.cs - BlockBroadcastInv()**

> Message: System.OperationCanceledException : The operation was canceled.

**WalletTests.cs -Given__TheNodeHadAReorg_And_WalletTipIsBehindConsensusTip__When__ANewBlockArrives__Then__WalletCanRecover**
> Result Message:	System.OperationCanceledException : The operation was canceled.

**MinerTests.cs - MinerCreateBlockCoinbaseMempoolTemplateCreationFailsAsync()**

> Message: Assert.Throws() Failure
> Expected: typeof(Stratis.Bitcoin.Features.Consensus.ConsensusErrorException)
> Actual:   (No exception was thrown)

**MinerTests.cs - MinerCreateBlockSigopsLimit1000Async()**

> Message: Assert.Throws() Failure
> Expected: typeof(Stratis.Bitcoin.Features.Consensus.ConsensusErrorException)
> Actual:   (No exception was thrown)
>

**Comment by fassadlr** [comment]
Hi @mikedennis, I confirm they are also failing for me. I'll look at the miner tests 👍

**Comment by fassadlr** [comment]
@mikedennis 

The following tests are fixed now:

SyncFromDate_ChainTipAfterGivenDate_StartsSyncFromHeightAtTime
MinerCreateBlockCoinbaseMempoolTemplateCreationFailsAsync
MinerCreateBlockSigopsLimit1000Async

Still looking into the integration tests.

**Comment by mikedennis** [comment]
Unit tests mentioned in this issue are all now working, closing this issue.
