### ISSUE TITLE
[Node] Refactor

### ISSUE THREAD

**Issue by dangershony** [stratisproject/StratisBitcoinFullNode#721]
This is to discuss how to refactor node.

Currently node when created there is an internal NodeConnection that creates two threads one that listens to incoming messages and one that sends messages to peers.

I suggest we change that to use the AsyncLoop and use the `away` on incoming and outgoing messages.
Basically making node async. 

There are methods in Node that are not used bu the fullnode that can also e removed.

I would also propose to replace the event system of behaviours to us Rx signals.

**Comment by Aprogiena** [comment]
In this context, I was thinking about MessageReceived subscribers to define which messages they are interested in instead of being called for all messages. Most of the subscribers only want to see one or two types of messages. Currently everyone deals with every message ...

**Comment by Aprogiena** [comment]
Do Rx signals execute in parallel or in serial fashion?

**Comment by Aprogiena** [comment]
also what is the advantage of Rx signals, why would you like to use them?

**Comment by dangershony** [comment]
Rx is sequential, no solid preference to Rx, you just get a signalling system already built, I prefer to move away from events.

Yeah would be good to have some sort of subscriber per message type system.

**Comment by Aprogiena** [comment]
I can't see the reason of using a signalling that is not processing things in parallel. If we have serialized processing and we want it, it might be better to allow things like returning a result of a subscribed processor. This would allow you to, for example, end the propagation of the event to further subscribers if you decided to.

So basically you would do:
```
foreach (subscribed handler)
{
   should we stop := execute it
   if (should we stop) break;
}
```

**Comment by dangershony** [comment]
Ok this is not relevant anymore
