### ISSUE TITLE
[Validation] Invalid block cache vulnerable to attacks from IPv6 

### ISSUE THREAD

**Issue by Aprogiena** [stratisproject/StratisBitcoinFullNode#735]
The problem is described here - https://github.com/stratisproject/StratisBitcoinFullNode/pull/710#issuecomment-343866080

There are two solutions described there as well. This issue is about implementing the second simpler solution.

**Comment by Aprogiena** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[Validation] Invalid block cache vulnerable to attacks from IPv6](https://trello.com/c/dmPJa5PL/319-validation-invalid-block-cache-vulnerable-to-attacks-from-ipv6)

**Comment by dangershony** [comment]
As discussed in https://github.com/stratisproject/StratisBitcoinFullNode/pull/700
This fix will also combine the two collections for banning blocks (and possibly put them in the node banning area)

**Comment by Aprogiena** [comment]
so the idea here is only to maintain 1000 invalid block hashes, no more than that

now how to do it, several options:

1) have queue and dictionary + lock, all operations are O(1), add operation can cause removal of the oldest entry once the limit is reached

2) using one heap (not sure if there is concurrent heap available though, so worse case using lock around its operations) - this would have O(log N) for add/remove operations and again, oldest entry would be removed during add operation if limit is reached

3) using just one concurrent dictionary, no extra lock, if limit is reached, we would go through the whole dictionary and 
a) EITHER sort all entries and remove oldest 500 entries - there is extra cost of sorting operation
b) OR not sort anything and just randomly remove 50 % of entries - there is possibility of removing recent entries


i'd probably go with 1) as for me having extra lock is ok (queue and dictionary won't be concurrent)
i would probably avoid 2) as we do not have concurrent heap or any ready heap implementation 
3) is also OK, a) is heavier on time, b) can remove recent entries, so probably a) is better because that extra time is very small

**Comment by Aprogiena** [comment]
as the complexity raises, i'd remove the logic from ChainState and create InvalidBlockHashStore in Bitcoin.Base. There would be IInvalidBlockHashStore interface which would allow you to mark block invalid and check if it is invalid. And we can add unit tests for this InvalidBlockHashStore, which will be in-memory.

**Comment by Aprogiena** [comment]
i've somehow decided for 1) already :) hope it is ok
