### ISSUE TITLE
NBitcoin Refactoring locking thread - announce your locks here

### ISSUE THREAD

**Issue by Aprogiena** [stratisproject/StratisBitcoinFullNode#736]
This is to communicate which NBitcoin files or whole folders do you want other devs NOT TO TOUCH because you are working on them.

Syntax is simply, either you announce LOCK or you announce UNLOCK.
The question is when to unlock, I'd say AFTER your PR is merged, otherwise it would create conflicts.

I'll start with example and the first lock:

**LOCK** `External\NBitcoin\Protocol\Node*.cs` except for `NodesGroup.cs`

**Comment by fassadlr** [comment]
LOCK 
```External\NBitcoin\Protocol\AddressManager.cs```
```External\NBitcoin\Protocol\AddressManager\Behaviors\AddressManagerBehavior.cs```
```External\NBitcoin\Protocol\AddressManager\Behaviors\NodesGroupBehavior.cs```

**Comment by dangershony** [comment]
Lock
`Network.cs`
`Networks.cs`
`NetworkBuilder.cs`

**Comment by Aprogiena** [comment]
@dangershony full path pls :) to avoid confusions

**Comment by fassadlr** [comment]
@Aprogiena Im just going through my PR, I need to lock

```External\NBitcoin\Protocol\Node.cs```

too.

**Comment by Aprogiena** [comment]
@fassadlr you can't lock Node.cs because it is locked :D and my PR is already in the queue, so you will just have conflicts. i'll unlock it as soon as PR is merged

**Comment by fassadlr** [comment]
All good @Aprogiena I just saw it now :) Its ok I can merge your changes in after.

**Comment by Aprogiena** [comment]
unlocking my locks:
**UNLOCK** `External\NBitcoin\Protocol\Node*.cs` except for `NodesGroup.cs`

**Comment by dangershony** [comment]
UNLOCK 
Network.cs
Networks.cs
NetworkBuilder.cs

**Comment by mikedennis** [comment]
**LOCK** \NBitcoin\ChainedBlock.cs

**Comment by Aprogiena** [comment]
**LOCK**
- src/NBitcoin/RPC/RestClient.cs
- src/NBitcoin/RPC/RPCClient.cs
- src/NBitcoin/RPC/BlockRepository.cs
- src/NBitcoin/RPC/BlockValidator.cs
- src/NBitcoin/RPC/IBlockRepository.cs
- src/NBitcoin/RPC/NoSqlBlockRepository.cs
- src/NBitcoin/RPC/Utils.cs

**Comment by Aprogiena** [comment]
**UNLOCK**
- src/NBitcoin/RPC/RestClient.cs
- src/NBitcoin/RPC/RPCClient.cs
- src/NBitcoin/RPC/BlockRepository.cs
- src/NBitcoin/RPC/BlockValidator.cs
- src/NBitcoin/RPC/IBlockRepository.cs
- src/NBitcoin/RPC/NoSqlBlockRepository.cs
- src/NBitcoin/RPC/Utils.cs

**Comment by Aprogiena** [comment]
@mikedennis i guess you could unlock right?

**Comment by mikedennis** [comment]
**UNLOCK** \NBitcoin\ChainedBlock.cs

Will be doing more work on this later but for now it's open.

**Comment by fassadlr** [comment]
UNLOCK 
```External\NBitcoin\Protocol\AddressManager.cs```
```External\NBitcoin\Protocol\AddressManager\Behaviors\AddressManagerBehavior.cs```
```External\NBitcoin\Protocol\AddressManager\Behaviors\NodesGroupBehavior.cs```

**Comment by Aprogiena** [comment]
@fassadlr Node.cs also free now?

**Comment by fassadlr** [comment]
Ah yes @aprogiena Node.cs is unlocked.

**Comment by Aprogiena** [comment]
Thank you, in which case I

**LOCK** `src/NBitcoin/Protocol/Node*.cs`

**Comment by Aprogiena** [comment]
**UNLOCK** 
- `src/NBitcoin/Protocol/*`
- `src/NBitcoin/Utils.cs`
- `src/NBitcoin/UInt256.cs`

**Comment by dangershony** [comment]
Ok I think we can close this right?

**Comment by Aprogiena** [comment]
good for me to close
