### ISSUE TITLE
[StratisBitcoinFullNode] BoundedDictionary

### ISSUE THREAD

**Issue by martinhoule** [stratisproject/StratisBitcoinFullNode#741]
FILE : https://github.com/stratisproject/StratisBitcoinFullNode/blob/master/src/NBitcoin/Utils/BoundedDictionary.cs

```
int _MaxItems;
		ConcurrentDictionary<TKey, TValue> _Dictionnary = new ConcurrentDictionary<TKey, TValue>();
		ConcurrentQueue<TKey> _Queue = new ConcurrentQueue<TKey>();
		public BoundedDictionary(int maxItems)
		{
			_MaxItems = maxItems;
		}
```

`int _MaxItems` should be uint, can cause infinite loop if set to -1 and Clean function

```
private void Clean()
		{
			while(_Queue.Count > _MaxItems)
			{
				TKey result;
				if(_Queue.TryDequeue(out result))
				{
					TValue result2;
					_Dictionnary.TryRemove(result, out result2);
				}
			}
		}
```

_MaxItems should be readonly  and renamed to respect naming convention

`private readonly uint maxItems = default(uint)`

**Comment by dangershony** [comment]
Are you up to fix this and submit a PR?
