### ISSUE TITLE
[BaseFeature-ChainRepository] Possible node starting time speedup 

### ISSUE THREAD

**Issue by noescape00** [stratisproject/StratisBitcoinFullNode#747]
ChainRepository.LoadAsync takes 14 sec to execute (out of total 14.9 sec for node.Start()) because it calculates sha256 hash a few thousand times in order to set ConcurrentChain's Tip. 
Maybe consider cashing tip and starting from that point instead of recalculating all hashes every time app launches?

**Comment by bokobza** [comment]
Is that what's happening? Looking to improve this method has been at the back of my mind for months.
Do yo want to have a go at it @noescape00 ?

**Comment by noescape00** [comment]
@bokobza sure, assign this to me. I'll finish current one that aprogiena suggested (making global comments for a few PoS\PoW classes) and start this one.

**Comment by bokobza** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[BaseFeature-ChainRepository] Possible node starting time speedup](https://trello.com/c/NVKTh9CP/323-basefeature-chainrepository-possible-node-starting-time-speedup)

**Comment by dangershony** [comment]
>Maybe consider cashing tip and starting from that point 
Can you explain more what you mean?

**Comment by noescape00** [comment]
>Can you explain more what you mean?

I haven't thought through the solution for this very well, just bumped into it because it significantly slowed down debugging process. 
By a first glance it looks like when the chain gets loaded from dbreeze db every block's hash gets recalculated in order to verify that blocks are valid. So I guess we don't need to verify the same stuff over and over again and we can start from the same point where verification ended on the next launch.

**Comment by noescape00** [comment]
I guess I'll also need to check how loading chain and setting tip was approached by the other projects. I am almost completely sure that they came up with a solution because current approach dont scale. On my machine it takes 14 sec for this process and stratis only has ~600k blocks. So the launching time will increase linearly with the blocks count

**Comment by dangershony** [comment]
Ah I see you mean hashing the header to get the block id, hashing the header I believe has a very small perf impact but if it does not I guess we can defo work around that (by storing to disk the block hash, it will bloat the store a bit but its negligent).
You can easily test that by building a second chain (as headers are cashed so you will get an idea of the perf improvement).
