### ISSUE TITLE
[ConnectionManager] SocketException while attempting to start node if stratis-qt wallet is launched

### ISSUE THREAD

**Issue by noescape00** [stratisproject/StratisBitcoinFullNode#750]
Throws at ConnectionManager:167 "SocketException: Only one usage of each socket address (protocol/network address/port) is normally permitted"

Bug appears if 16178 port is already taken by the stratis-qt wallet that was launched before the full node.

**Comment by dangershony** [comment]
Is this a bug though?
If the port is taken we cannot start the node on the same port (you can specify a different port in config).

**Comment by noescape00** [comment]
It's not. But I'm pretty sure there will be a lot of people who would run node (when it get released) in parallel with qt wallet and that's not UX they should get. 
So maybe the port should be changed automatically instead of shutting down the node in case default one is taken.

**Comment by dangershony** [comment]
I would be reluctant to just randomly select a port, rather we should give a proper error message maybe something like
 >P2P port is used (is a StratisX QT running?) please use a different port using the -port config argument

**Comment by noescape00** [comment]
Sounds like a good idea. I'll make a PR.
