### ISSUE TITLE
[Mempool] Missing inputs error

### ISSUE THREAD

**Issue by noescape00** [stratisproject/StratisBitcoinFullNode#751]
I don't know how exactly I got this bug but  Headers.Height and BlockStore.Height were behind  Consensus.Height and there was one persisted mempool entry that caused that error. It was loaded by MempoolManager.AddMempoolEntriesToMempoolAsync and caused exception that was thrown at MempoolValidator:670. Clearing mempool (not loading persisted entries) and letting node sync fixes the error. Without clearing mempool full node would always fail to start and throw that exception.

**Comment by dangershony** [comment]
>Without clearing mempool full node would always fail to start and throw that exception.  

This is probably a bug we need to fix

Did you play around with the chain db? maybe thats how your Header.Height was behind.
And yes the node should recover

**Comment by noescape00** [comment]
>Did you play around with the chain db? maybe thats how your Header.Height was behind.
>And yes the node should recover

I only paused the app on breakpoints but no code was changed when I caught the bug. So I'm not really sure if that's the way the bug appeared.

**Comment by noescape00** [comment]
No longer reproducible.
