### ISSUE TITLE
The -assumevalid=0 node setting throw exception

### ISSUE THREAD

**Issue by mikedennis** [stratisproject/StratisBitcoinFullNode#755]
It is suppose to turn off assumevalid checking but currently throws a configuration exception.

This is because because its currently using ```uint256.TryParse()``` to parse the config file which has this check in it:		
```
if (hex.Length != WIDTH_BYTE * 2)
   return false;
```
So currently you have to do a string with 64 zeros in order to get past the TryParse. I believe the fix is to interpret the 0 before doing the try parse for assumevalid.

**Comment by dangershony** [comment]
Sounds correct and simple, go for it.
