### ISSUE TITLE
Docker containers are 6+ months old

### ISSUE THREAD

**Issue by andrasfuchs** [stratisproject/StratisBitcoinFullNode#761]
I've tried to run a few nodes using Docker and Stratis containers from here: https://hub.docker.com/r/stratisplatform/. These containers are not updating automatically because of an error and their last push was 6 months ago.

Could you make sure those are getting updated?

The build error is 

> Build failed: The command '/bin/sh -c git clone https://github.com/stratisproject/StratisBitcoinFullNode.git && cd StratisBitcoinFullNode && dotnet restore && cd Stratis.BitcoinD && dotnet build' returned a non-zero code: 2

and you can see [the full log here](https://hub.docker.com/r/stratisplatform/fullnode/builds/bq5spjc2wuvgbttsmetbyhj/).

**Comment by dangershony** [comment]
Hi @andrasfuchs yes this is really old, as we are still strong in to dev I did not get the time to fix it.

**Comment by dangershony** [comment]
I think someone recently updated the docker containers.

**Comment by bokobza** [comment]
All up to date now.
https://hub.docker.com/r/stratisplatform/fullnode/
