### ISSUE TITLE
[BreezeD] Starting BreezeD with default parameters ends with error

### ISSUE THREAD

**Issue by andrasfuchs** [stratisproject/StratisBitcoinFullNode#764]
Running the BreezeD project with the default parameters (stratis -testnet) in Visual Studio ends up with the following error:

crit: Stratis.Bitcoin.Configuration.NodeSettings[0]
      Feature LightWalletFeature cannot be configured because it depends on other features that were not registered
There was a problem initializing the node. Details: 'Dependency feature WalletFeature cannot be found.'

Side note: the profile "Bitcoin Main" is selected by default, I suppose the parameters should not be "stratis -testnet" for it then. The other profiles (Bitcoin Test, Stratis Main and Test) look fine.

**Comment by bokobza** [comment]
Fixed in https://github.com/stratisproject/StratisBitcoinFullNode/pull/768
