### ISSUE TITLE
Error when using light wallet & watch only wallet together

### ISSUE THREAD

**Issue by zeptin** [stratisproject/StratisBitcoinFullNode#765]
Initialising the node with the light wallet & watch only wallet leads to an error on startup.

The watch only wallet appears to explicitly depend on the wallet feature:

https://github.com/stratisproject/StratisBitcoinFullNode/blob/master/src/Stratis.Bitcoin.Features.WatchOnlyWallet/WatchOnlyWalletFeature.cs#L70

The WoW does not seem to require the full wallet in its actual implementation, only in the feature startup. Removing the DependOn line seems to allow the node to start up normally.

Also see #764, possibly related.

**Comment by bokobza** [comment]
Absolutely. It's a mistake.
Fix is in https://github.com/stratisproject/StratisBitcoinFullNode/pull/768
