### ISSUE TITLE
[API] Capitalization, naming and description of parameters

### ISSUE THREAD

**Issue by andrasfuchs** [stratisproject/StratisBitcoinFullNode#771]
There are a few API parameters that start with lowercase, some with uppercase.
The wallet name is passed as `name` or `walletName` depending on the method, this should be consistent, I think.
The `create` API method needs a `folderPath` and a network parameter, but they seem to be not used in [WalletController.cs](https://github.com/stratisproject/StratisBitcoinFullNode/blob/master/src/Stratis.Bitcoin.Features.Wallet/Controllers/WalletController.cs). Similarly for the `load` method and its `folderPath` parameter.

The parameter descriptions are never filled on Swagger.

To see these, open http://localhost:37221/swagger while running the Breeze client.

**Comment by dangershony** [comment]
@bokobza can probably comment son this best

**Comment by dangershony** [comment]
I am closing this, as some commits where done around name fixing of the api models.
