### ISSUE TITLE
[CLI] CLI doesn't parse RPC connection parameters

### ISSUE THREAD

**Issue by andrasfuchs** [stratisproject/StratisBitcoinFullNode#775]
I tried to reach the StratisD through RPC with the following command line in the Stratis.Bitcoin.Cli folder:
`dotnet run stratis listmethods -rpcuser=stratistestuser -rpcpassword=stratistestpassword -rpcconnect=127.0.0.1 -rpcport=26174 -rpcbind=127.0.0.1:26174`

The CLI still tried to reach the http://127.0.0.1:8332 without providing the rpcuser and rpcpassword values, so the connection attempt failed.

CLI should parse those passed values, and also should probably set the RPC port to the default 26174 if stratis was selected as the target network.

(In StratisD's `startis.conf` `server`, `rpcbind`, `rpcallowip`, `rpcuser`, `rpcpassword` values were set accordingly.)

**Comment by andrasfuchs** [comment]
Here is my pull request to accomplish this: https://github.com/stratisproject/StratisBitcoinFullNode/pull/785

**Comment by bokobza** [comment]
Closed with https://github.com/stratisproject/StratisBitcoinFullNode/pull/793
