### ISSUE TITLE
[POS Validation] Analyze block flood attack

### ISSUE THREAD

**Issue by Aprogiena** [stratisproject/StratisBitcoinFullNode#776]
`PosConsensusValidator.ContextualCheckBlock` has a commented out code that mentions block flood attack. We don't know what this is at the moment and we need to investigate this and decide whether this attack is still valid for our networks. If it is, we should review the proposed code there (it is commented out).

So first, analyze what this is about and write it here. Then we decide what to do next.

**Comment by Aprogiena** [comment]
also StakeValidator code contains this: 
```
          // TODO: Investigate:
          // The POS protocol should probably put a limit on the max amount that can be staked
          // not a hard limit but a limit that allow any amount to be staked with a max weight value.
          // the max weight should not exceed the max uint256 array size (array size = 32).
```
let's find out what it is and if it is not relevant, let's remove this todo from codebase, otherwise let's implement it

**Comment by noescape00** [comment]
Fixed with activation merge.
