### ISSUE TITLE
[ScriptReader] Undisposed -> Leak?

### ISSUE THREAD

**Issue by Aprogiena** [stratisproject/StratisBitcoinFullNode#801]
`NBitcoin.ScriptReader` is not `IDisposable`, but it contains inner `Stream`, often `MemoryStream`. Should not this inner stream be disposed?

**Comment by fassadlr** [comment]
@Aprogiena  I suppose ScriptReader should be made IDisposable so that you can dispose of the Stream when Dispose gets called?

```
using(var reader = new ScriptReader(_Script)
{
}
```

**Comment by Aprogiena** [comment]
yes that's what i was thinking, but as always, this will require change in quite a lot of code
but what can you do :-)
