### ISSUE TITLE
Main net and Test net cannot be run simultaneously

### ISSUE THREAD

**Issue by D3m0nKingx** [stratisproject/StratisBitcoinFullNode#806]
FN cannot be initialized on both main and testnets simultaneously due to the FN requesting binding to 127.0.0.1:37221 for the swagger api, that's already in use by another instance of the Node running (either main/testnet whichever is started first)

```bash
There was a problem initializing the node. Details: 'One or more errors occurred. (Failed to bind to address http://127.0.0.1:37221: address already in use.)'
Application is shutting down...
The CancellationTokenSource has been disposed.
```

**Comment by bokobza** [comment]
Hmm good one.
I guess we'd be better off defining some new ports for testing.
