### ISSUE TITLE
[BlockStore] Big reorg bug

### ISSUE THREAD

**Issue by dangershony** [stratisproject/StratisBitcoinFullNode#808]
I think we have a small bug on the store
```info: Stratis.Bitcoin.FullNode[0]
      ======Node stats====== 11/27/2017 12:42:39 agent StratisBitcoin:1.0.5
      Headers.Height:        204552   Headers.Hash:         ed78980759fd6428266f59cedac8a3cf7f74a4fb9f423741e69678542bdd2990
      Consensus.Height:      204552   Consensus.Hash:       ed78980759fd6428266f59cedac8a3cf7f74a4fb9f423741e69678542bdd2990
      BlockStore.Height:     204655   BlockStore.Hash:      53986d75513aebe178fa73ce11fef052e3116f71915bb8b5ab01a2fc2ee869d1
      Wallet.Height:         No Wallet

      ======Mempool======
      MempoolSize: 0    DynamicSize: 0 kb   OrphanSize: 0

      ======Connection======
      Node:::ffff:13.64.76.48:26178,           connected (outbound),      agent /Stratis:2.0.0.3/,  height=204546
      Node:::ffff:84.192.155.226:26178,        connected (outbound),      agent /Stratis:2.0.0.3/,  height=204552

```
See the store is ahead after a big reorg, and it did not reorg itself.
I suspect its because the reorg was so big and store is still ahead once it will reach the same highet the reorg will happen

**Comment by Aprogiena** [comment]
This is actually not possible :-) (kind of is, but not in real world)
You can't reorg to shorter chain. So ...

**Comment by dangershony** [comment]
Hmmm thats true, so this is very odd.
I guess we will need to try to reproduce the error with logs enabled.

**Comment by Aprogiena** [comment]
Things like this happened before when your node crashed (or its part, consensus here) before it was flushed to disk. But even before, i think, when you were at the tip, the flushes were after every block. So yes, weird.

**Comment by Aprogiena** [comment]
i've got better one
```
Headers.Height:        496694
Consensus.Height:      249693
BlockStore.Height:     313529
```

this seems like blocks are downloaded but not added to consensus

**Comment by noescape00** [comment]
@Aprogiena 
I had this one a few times. 
Though wasn't sure how someone can get this in a normal scenario. All cases when I got this bug were when I paused and started the node during debugging all the time.

**Comment by dangershony** [comment]
Ok so defo something to investigate further

**Comment by Aprogiena** [comment]
we've fixed a bug in long reorg, we should monitor whether this is still an issue
if anyone sees this, pls confirm that you've seen this

**Comment by D3m0nKingx** [comment]
#938 was likely the same reoccurring bug as reported here which I filed (just a day ago). I had also noticed the same thing where blockstore.height was ahead of consensus. However the node didn't crash, just stayed online but blocks did not advance.  

@Aprogiena which commit was the fixed bug in long reorg? I'm still trying to repro this issue.

**Comment by Aprogiena** [comment]
#918

**Comment by dangershony** [comment]
Can I close this?

**Comment by Aprogiena** [comment]
possibly

**Comment by D3m0nKingx** [comment]
I concur as well. I run the node on Straits ( Main and Testnet ) for days at a time since this bug report and haven't seen this one reproduced.

**Comment by dangershony** [comment]
Awesome
