### ISSUE TITLE
[FullNode] enum for node states instead of bunch of bool variables. 

### ISSUE THREAD

**Issue by noescape00** [stratisproject/StratisBitcoinFullNode#826]
I think it will be a good idea to have Node's state in single enum instead of several bool variables (Stopped, IsDisposed, HasExited) that don't even cover all states.

```
    public enum FullNodeState
    {
        Created,
        Initialized,
        Starting,
        Started,
        Stopping,
        Stopped,
        Disposing,
        Exited
    }
```

**Comment by dangershony** [comment]
I would wait with this while @Aprogiena is refactoring the node code

**Comment by noescape00** [comment]
Ok, totally agree.
