### ISSUE TITLE
Peer Selection Improvements

### ISSUE THREAD

**Issue by fassadlr** [stratisproject/StratisBitcoinFullNode#838]
Hi Guys,

I wanted to better understand how peers are selected and dug a bit into the old code. I'm not too happy with how the current selection "algorithm" works and have devised one of my own (there are some some similarities with the old and current code). Please feel free to comment and/or suggest changes and/or different scenarios.

The selection logic is meant to be read (**executed**) from top to bottom, as set out below:

**New Peers**
If new peers exist

- Return a random peer from the new peer set

**Tried Peers [Attempted but never connected to]**
If the peer has **never** had a successful connection attempt:

- **_And_** if the peer was added more than 7 days ago - delete from peer file.
- **_And_** if the peer was added less than 7 days ago and has had more than 10 connection attempts - delete from peer file.

If a peer is found from the filtered list above, check that it wasn’t attempted less than 60 sec ago.
If a peer is found from the filtered list above, pick a random peer.

**Tried Peers [Successful connections has been made]**
If the peer has had a **successful** connection attempt:

- Prefer peers that was last connected to more than 60 seconds ago but less than 30 days.
- If the peer was last connected to more than 30 days in the past - delete from peer file (this causes the peer to be re-discovered, should it be still online).

Pick randomly from the **Tried Peers [Attempted but never connected to]** and **Tried Peers [Successful connections has been made]** list and from _that_ list pick a random peer.

**Notes:**

1. Add `peerAdded` date to the peer file (another PR)
2. Add `peerfileVersion` to the peer file (another PR) (This is so that we can makes changes to the peer file, and delete older versions from disk by checking the peer file version)
3. If a peer fails to connect - reset last successful connect and handshake dates (It then effectively goes into attempted but not successful "group".

**Comment by noescape00** [comment]
Awesome idea. 
Right now I am usually waiting around 3-5 minutes on strat mainnet till I get at least 1 connection if my peers file was created ~1-2 weeks ago. So with current peer selection I am forced to recreate peer file (delete old one so blank can be generated) every few days.

**Comment by fassadlr** [comment]
@noescape00 thank you! Exactly my problem as well, especially on MainNet. I want to fix those issues first before changing the selection algo.

**Comment by fassadlr** [comment]
Once @dangershony reviews and OKs #837 I can fix those "bugs".

**Comment by Aprogiena** [comment]
I'm missing the description of current alg, so it is hard to immediately see that this one is better ...

**Comment by dangershony** [comment]
As apro said its hard to decide if we don't know how it works currently.

Your suggestions seems fine, I would just not be so in favor of deleting peers form the file, we can just keep the list and let it grow indefinitely no? I dont think it will occupy too much space in memory or in disk, worth case we can built in a limit of 10k peers (maybe less).

Bitcoin currently has several thousand peers  online, I don't think it will be so bad to keep a list of all of them in memory (I think an address is roughly about 0.3kb in size so 10k would be around 3 mb of data)

We could however give sort of a high priority to N first addresses in to the algo. 
So say you selection would be on the top 100 addresses, and if any qualifies to be deleted we instead push it to the bottom of the big list and push another, the next in line to the top ranking for selection.

Example we have a list of 1000 peers
Selection is 
- Take first 100
- On this list apply your selection algo
- Any that need to be deleted push back to the end of the 1000 list queue
- Promote up same number of demoted items to the 100 list

**Comment by fassadlr** [comment]
Thanks @dangershony for your input! I'm busy testing another version of the algorithm but I am going to incorporate your idea of selecting the top 100 most preferred peers and randomly selecting from that set 👍

**Comment by fassadlr** [comment]
PS I am thinking that we implement a IPeerSelector and PeerSelector class as the logic is getting a bit complex now. This will enable better unit testing and the interface allows to mock out randomness should we wish to do so. I.e. If we want to select a peer without using the algorithm and/or plugging a different one.

WDYT?

**Comment by dangershony** [comment]
Sounds alike a good idea `IPeerSelector`

**Comment by noescape00** [comment]
Potentially having this `IPeerSelector` can be a cool feature for the wallets- it could choose of 2 options: 
1) Totally random selection - slower getting new connections but best security
2) Partially random (your algho)- mix of security and speed of getting new connections and propagating txes.

Potentially I'd like something like that somewhere deep in my wallet's settings.

**Comment by fassadlr** [comment]
Closing this issue as a new peer selection algorithm was implemented in #927 .

If we want to look at this again,  a new issue can be created.
