### ISSUE TITLE
Propagation & validation algorithm for light node.

### ISSUE THREAD

**Issue by noescape00** [stratisproject/StratisBitcoinFullNode#851]
This issue is created for discussing the propagation & validation algorithm for light node.
As it was mentioned by @Aprogiena in slack's PM new algorithm that I'd like to implement have a potential problem (I'll explain it below). 

Old algorithm and new one are described in [PR 844](https://github.com/stratisproject/StratisBitcoinFullNode/pull/844).  

A potential problem on new algorithm is that if we are the only ones who ask for a specific transaction then probably the nodes that we ask about it can assume that  our node is the one who produced that transaction. And it's basically means that certain nodes can potentially link addresses that this tx uses to our IP. 
Though it's a good question if it's a really big deal since we do this only on light node. 

Potentially we can change the algo so instead of asking for 1 tx we will be asking nodes for every tx in their mempool and when we get peer's mempool we can look for our own tx and if we find it we are assuming that it's validated and propagated. 
But asking for the whole mempool is slower and requires more resources. 
> "no one sane will give you a copy of the mempool for free"

As it was mentioned by @Aprogiena.

I'm not sure yet if it's technically possible to request the whole mempool and easily receive it from the peer we asked. 

So this issue is created for discussing that. 
Please share your thoughts.

**Comment by Aprogiena** [comment]
first a question
- what is the expected purpose of the light node (what it even is?)

then couple of points related to this
- dandelion project 
- bloom filters
- can't we just stick to the old method, just polish edge cases?

**Comment by noescape00** [comment]
>what is the expected purpose of the light node (what it even is?)

Light node is basically what we use for Breeze wallet as far as I know. 
Light node don't have a mempool or block store- it can't validate incoming or outcoming transactions. 
 ```
 .UseNodeSettings(nodeSettings)
                    .UseLightWallet()
                    .UseBlockNotification()
                    .UseTransactionNotification()
                    .UseApi();
```

>can't we just stick to the old method, just polish edge cases?

We can. But old one is slow by design. It REQUIRES at least 2 peers by design to work properly. And it also can be potentially exposed to the same vulnerability but to a lower degree.

**Comment by Aprogiena** [comment]
also 
- how bitcoin core does it

**Comment by Aprogiena** [comment]
> Light node is basically what we use for Breeze wallet as far as I know.

then i think the privacy is critical property

**Comment by noescape00** [comment]
>how bitcoin core does it

They don't have it. I mean light nodes in general. 
And the approach they take for the full node is identical to the one we use for our full node.

**Comment by noescape00** [comment]
>then i think the privacy is critical property

For sure. 
Meanwhile I'll check if we actually can get a whole mempool from peers easily and in reasonable time. If we can there wont be any privacy issues.

**Comment by Aprogiena** [comment]
whole mempool is not a good idea imho

i'd be interested how bitcoin core does it for whatever they have, this is general problem and even with full node, our alg is probably not optimal at the moment

**Comment by bokobza** [comment]
@noescape00 the purpose of the light node is that we don't save the blocks we download, we merely parse them to see if they contain transactions affecting our wallets.
Downnloading the whole mempool is not a good idea and something we definitely don't want to do.
We already started talking about this in this issue: 
https://github.com/stratisproject/StratisBitcoinFullNode/issues/597
I suggest we continue there.

**Comment by noescape00** [comment]
Ok. 
Let's continue there, I'm closing this one.
