### ISSUE TITLE
[ChainHeadersBehavior] Refactor message received

### ISSUE THREAD

**Issue by Aprogiena** [stratisproject/StratisBitcoinFullNode#856]
As suggested in this comment https://github.com/stratisproject/StratisBitcoinFullNode/pull/853#discussion_r154658338

**Comment by Aprogiena** [comment]
so optimally the body of the method would just be a simple switch and actual code of each case would be in a method

**Comment by fassadlr** [comment]
Thank you @Aprogiena !
