### ISSUE TITLE
[Network sync] Investigate occasional problem with node being not synced with its peers

### ISSUE THREAD

**Issue by Aprogiena** [stratisproject/StratisBitcoinFullNode#862]
The testing scenario looks like this:
- run a node with just `-testnet` argument
- run a second node that will have `-testnet -stake=1 -walletname=yourwallet -walletpassword=yourpassword -connect=firstnode -`, this will make sure that the second node is only connected to the network via the first node and that the second node is staking
- now sometimes it seems that when the second node mines a block, the first node does not accept it, it does not even advance its headers, so the situation is that the second node sends the headers to the first node, say height of the new block is `X`, and then you can see the first node to be at height `X-1` for quite a long time and then it even accepts competitive block from another peer at height `X` - this is what we want to investigate why this happens (it should not)
- this log settings can help with investigation:
dedicated target:
```
    <target name="debugInvestigateFile" xsi:type="AsyncWrapper" queueLimit="10000" overflowAction="Block" batchSize="1000">
      <target xsi:type="File" fileName="investigate.txt" layout="[${longdate:universalTime=true} ${threadid}${mdlc:item=id}] ${level:uppercase=true}: ${callsite} ${message}" encoding="utf-8" /> 
    </target>
```
rules for the target:
```
    <logger name="Stratis.Bitcoin.Base.ChainHeadersBehavior" minlevel="Trace" writeTo="debugInvestigateFile" />
    <logger name="Stratis.Bitcoin.Features.BlockStore.*" minlevel="Trace" writeTo="debugInvestigateFile" />
    <logger name="Stratis.Bitcoin.P2P.Peer.*" minlevel="Trace" writeTo="debugInvestigateFile" />
    <logger name="Stratis.Bitcoin.Features.Miner.*" minlevel="Trace" writeTo="debugInvestigateFile" />
```

**Comment by Aprogiena** [comment]
note that the described behavior only occurs sometimes, not always, so you might need to wait several blocks to be mined by the second node

**Comment by dangershony** [comment]
I would like to get to the bottom of this.

**Comment by Aprogiena** [comment]
we have logs setup, it will be easy to find out, @noescape00 is on that

**Comment by noescape00** [comment]
@dangershony
I'm investigating it. If you'd like to join I can send you everything I've found so far.

**Comment by noescape00** [comment]
Here are some interesting custom logs: 

[connector_investigate.txt](https://github.com/stratisproject/StratisBitcoinFullNode/files/1539853/connector_investigate.txt)
[miner_investigate.txt](https://github.com/stratisproject/StratisBitcoinFullNode/files/1539854/miner_investigate.txt)

It looks like miner won't send the block he mined or connector won't receive\validate it from the miner. 

I'm gathering more detailed logs to see what's going on.

**Comment by noescape00** [comment]
Woah, this is a tough one. 

So I also found 2nd bug: miner node would sometimes get behind the connector node. Miner receives new block's hashes from the connector but for some reason it won't download them for a while. And while it's behind it would mine a new block. When it's mined and announced miner would sync and reorg in a moment. 

As of this issue's bug: 

I've noticed that mentioned behavior happens in this scenario (I'm not sure yet if ONLY in this scenario): 
1) Miner and connector are at the same height
2) Connector get's new block's hash announced by some other node on the network
3) Miner mines the block and announces it's hash to the connector
4) Eventually connector downloads block which hash he got first (competitive node's from the network)
5) After sometime connector receives a new block from the network, sends it to the miner and miner reorgs

some more custom logs: 
[connector_investigate.txt](https://github.com/stratisproject/StratisBitcoinFullNode/files/1540886/connector_investigate.txt)
[miner_investigate.txt](https://github.com/stratisproject/StratisBitcoinFullNode/files/1540887/miner_investigate.txt)

**Comment by noescape00** [comment]
Also sometimes connector shows that chainHeadersBehavior.PendingTip.Height of the miner is 3-4 blocks behind when both of the nodes have the same tips (same height and hash).

**Comment by Aprogiena** [comment]
Do you need help with the investigation or are you positive to find the problem yourself with reasonable effort?

**Comment by noescape00** [comment]
I've answered on slack but coping it here to keep everyone else updated: 

I’m positive to find the problem, just will spend more time investigating it than I expected. 
The next step for figuring it out is to learn how exactly node decides what blocks to download if it received a few new headers. 
Looks like at some point connector has miner’s hash and few others and it cant decide what blocks to get. And that leads to connector getting behind the miner for a long time.

**Comment by noescape00** [comment]
I've found it. 

```
connector (receives header from the network):
[2017-12-08 15:28:17.9818 59]  Received headers from [::ffff:54.37.46.84]:26178. Count: '2'    headers: dd86c03422cfc2c752269862ecfab77f1c569fb4b14cf45e0f4bf113896ced44  e094d001b1a641b08d58b63eb01710ee79e5e038c6b75cea27db53ca7a1e99fc  .
...
[2017-12-08 15:28:17.9818 59]  [CHECK_HEADER] header e094d001b1a641b08d58b63eb01710ee79e5e038c6b75cea27db53ca7a1e99fc.   It's prev hash: dd86c03422cfc2c752269862ecfab77f1c569fb4b14cf45e0f4bf113896ced44
[2017-12-08 15:28:17.9818 59]  [CHECK_HEADER] header e094d001b1a641b08d58b63eb01710ee79e5e038c6b75cea27db53ca7a1e99fc VALIDATED
[2017-12-08 15:28:17.9818 59]  Pending tip changed from '218746-4110490cb62d5318b5e68090de87cd540177a440c93982fac7f46273303b963b' to '218748-e094d001b1a641b08d58b63eb01710ee79e5e038c6b75cea27db53ca7a1e99fc'.
[2017-12-08 15:28:17.9818 59]  New chain tip '218748-e094d001b1a641b08d58b63eb01710ee79e5e038c6b75cea27db53ca7a1e99fc' selected.
[2017-12-08 15:28:18.0556 163] Ask peers for block 'e094d001b1a641b08d58b63eb01710ee79e5e038c6b75cea27db53ca7a1e99fc'
[2017-12-08 15:28:18.3745 34]  Received block e094d001b1a641b08d58b63eb01710ee79e5e038c6b75cea27db53ca7a1e99fc from [::ffff:51.141.45.80]:26178
[2017-12-08 15:28:19.0738 3] Added to the repository block e094d001b1a641b08d58b63eb01710ee79e5e038c6b75cea27db53ca7a1e99fc   time 1512746896
[2017-12-08 15:28:19.1399 3]  Current height is e094d001b1a641b08d58b63eb01710ee79e5e038c6b75cea27db53ca7a1e99fc at height 218748
[2017-12-08 15:28:19.5447 14] SendAsBlockInventoryAsync.Announcing blocks : e094d001b1a641b08d58b63eb01710ee79e5e038c6b75cea27db53ca7a1e99fc    to peer: ::ffff:84.192.155.226
[2017-12-08 15:28:19.5447 48] SendAsBlockInventoryAsync.Announcing blocks : e094d001b1a641b08d58b63eb01710ee79e5e038c6b75cea27db53ca7a1e99fc    to peer: ::ffff:13.64.76.48
[2017-12-08 15:28:19.5447 44] SendAsBlockInventoryAsync.Announcing blocks : e094d001b1a641b08d58b63eb01710ee79e5e038c6b75cea27db53ca7a1e99fc    to peer: ::ffff:40.76.18.114
[2017-12-08 15:28:19.5447 40] SendAsBlockInventoryAsync.Announcing blocks : e094d001b1a641b08d58b63eb01710ee79e5e038c6b75cea27db53ca7a1e99fc    to peer: ::ffff:51.140.47.104
[2017-12-08 15:28:19.5447 56] SendAsBlockInventoryAsync.Announcing blocks : e094d001b1a641b08d58b63eb01710ee79e5e038c6b75cea27db53ca7a1e99fc    to peer: ::ffff:94.12.20.163

>DID NOT ANNOUNCE TO MINER?!

>and after some time we receive 218 749 and announce it to miner: 

connector: [2017-12-08 15:29:38.1376 169]  AnnounceBlocks.Announcing blocks : 8a8f77cc25f8ac75b5e63a9b7e2b3ec4c630fca42e0b90f1af70dc08f1bb9b85    to peer: ::ffff:127.0.0.1

>but miner won't validate this because previews header wasn't announced and so miner have no idea about it!
miner: [2017-12-08 15:29:38.1389 32]  [CHECK_HEADER] header 8a8f77cc25f8ac75b5e63a9b7e2b3ec4c630fca42e0b90f1af70dc08f1bb9b85.   It's prev hash: e094d001b1a641b08d58b63eb01710ee79e5e038c6b75cea27db53ca7a1e99fc
miner: [2017-12-08 15:29:38.1871 32]  [CHECK_HEADER_ERROR] header 8a8f77cc25f8ac75b5e63a9b7e2b3ec4c630fca42e0b90f1af70dc08f1bb9b85.

and connector would announce a few more headers one by one that wont be validated as well. Eventually in 5 minutes connector sends all headers miner don't have and miner is finally able to validate them and start pulling them

miner: [2017-12-08 15:33:24.6037 32]  Received headers from [::ffff:127.0.0.1]:57003. Count: '6'    headers: e094d001b1a641b08d58b63eb01710ee79e5e038c6b75cea27db53ca7a1e99fc  8a8f77cc25f8ac75b5e63a9b7e2b3ec4c630fca42e0b90f1af70dc08f1bb9b85  559b36b6e109ebb840fd02e19d01da1b3e908b3c288ba8c1a9e4ccb5b9700f65  77b88fe0e6c482dd3c6c4f493bef39b1390e17d0b6485d22339c5bc225598287  dcfcbd23398a68de6ba742674061cb369519ff391964d66f673ad964be324712  7318b6e92345116f59ed76fd2b6b400e508310f1dd88f3f18f5a3eacac573cc6  .
```

So the problem is that at some point connector node fails to announce a single hash to the miner for some reason. After that miner is starting getting behind. 

And the same problem happens when connector and miner are synced and miner would mine the block. Miner announces it just once and if node didn't receive that announce it will never know about it. This is what you saw- connector didn't advance because it didn't know about the mined block and eventually it received a block from someone else. 

Full custom logs in case someone is interested: 

[miner.txt](https://github.com/stratisproject/StratisBitcoinFullNode/files/1543434/miner.txt)
[connector.txt](https://github.com/stratisproject/StratisBitcoinFullNode/files/1543435/connector.txt)

**Comment by noescape00** [comment]
And just to be sure I've got some logs from the lowest level of abstraction: 

Connector node : BlockStoreBehavior
```
[2017-12-08 20:12:03.9971 33] BlockStoreBehavior+<SendAsBlockInventoryAsync>d__24.MoveNext (-)
[2017-12-08 20:12:03.9971 33]  (blockHashesToAnnounce.Count:1)
[2017-12-08 20:12:03.9971 33]  announce to [::ffff:127.0.0.1]:54519 this hashes: e04ecf831deace839fd2e1cc239f12272af47fcc8b27162a7b99e997947b7bb3   
[2017-12-08 20:12:03.9971 33]  (-)
```

Miner's ChainHeadersBehavior : 

```
[2017-12-08 20:12:02.4009 31] BlockStoreBehavior+<AttachedNode_MessageReceivedAsync>d__20.MoveNext (-)
[2017-12-08 20:12:03.4166 10] BlockStoreSignaled.<RelayWorker>b__14_0 ()
[2017-12-08 20:12:03.4166 10] BlockStoreSignaled.<RelayWorker>b__14_0 (-)[NO_BLOCKS]
[2017-12-08 20:12:04.4168 47] BlockStoreSignaled.<RelayWorker>b__14_0 ()
[2017-12-08 20:12:04.4168 47] BlockStoreSignaled.<RelayWorker>b__14_0 (-)[NO_BLOCKS]
[2017-12-08 20:12:05.4321 42] BlockStoreSignaled.<RelayWorker>b__14_0 ()
[2017-12-08 20:12:05.4321 42] BlockStoreSignaled.<RelayWorker>b__14_0 (-)[NO_BLOCKS]
[2017-12-08 20:12:06.4329 42] BlockStoreSignaled.<RelayWorker>b__14_0 ()
```

So miner indeed never got the headers that were announced by the connector node. 


I think we can solve this by announcing headers with interval of 0.5-1 seconds until recipient answers that it got the headers or until we've broadcasted it 10 times already.

On average this bug happens once in 30-40 blocks so we can get away by just rebroadcasting it 2-3 times without any response but if this kind of behavior will be used in sidechains I'd suggest going full-secure and adding sending a response message that recipient indeed got the headers.

**Comment by noescape00** [comment]
@Aprogiena @dangershony 
Please let me know your opinion on how this should be handled.

**Comment by Aprogiena** [comment]
hmm, you might not realize that but the information you provided is not very useful, and the amount of new information we get from the analysis is very little. let me explain

first, the logs you are using might mean something to you, but not so much for the rest of us. the problem is that you created a custom logs and you even created a custom log format. especially the fact that you took off the callsite makes it hard for us to guess what is the meaning of those logs. the callsite information is crucial, but it is also important to know the exact line of the code where the particular log line was generated.

so it would be very beneficial for all of us if you used the logs that are in the master. if you think those logs are insufficient in some components, it is better to suggest a PR that would fix that rather than adding custom logs that we can't really check and think about.

the summary of your analysis is that the miner never got the headers, but we actually don't get the information why that happened. 

the suggested solution is a mistake, the only correct way to fix this is to fix this, not to repeat the broken code couple of times. when i have the information about the headers and i send it to you and the TCP connection does not collapse in the middle of the process, it is not possible for you not to receive the information. so if i am able to rebroadcast the information, it implies that if we fixed the code, you are able to receive the headers in the first place and rebroadcast is not needed.

so i'd suggest using the logs that are in the master - those logs i've mentioned should be enough to investigate the issue - esp. they are enough to document the actual network messages that the nodes send between each other and receive from each other, which should show the fundamental problem or at least should eliminate most of the possibilities where the problem could be.

**Comment by noescape00** [comment]
Hm, makes sense. 
I'll remake it with master's logs.

**Comment by Aprogiena** [comment]
Actually the logs themselves are not that important to share. What we care about is where is the bug. So if it helps you to have your own custom logs, feel free to use them (although it still would be beneficial to learn to work with the master logs), but present the results pointing to the code, not mentioning the logs that we don't know where they come from.

**Comment by noescape00** [comment]
> but present the results pointing to the code

Sure. I didn't come that deep to the root to the bug, just discovered that it's about not receiving the headers. I'll get to the bottom of that and find exactly what piece of code works not as it was intended.

**Comment by noescape00** [comment]
I've came a bit closer to the root. The bug is inside 
`BlockStoreBehavior's.AnnounceBlocks(List<uint256> blockHashesToAnnounce)`

The only not master's log line is 'announce to {0} this hashes: {1}', this line is at the very beginning of the AnnounceBlocks function and needed to find when we're sending hash that was not received.

This is a normal announce scenario: 

```
[2017-12-09 17:27:14.3021 39] TRACE: Stratis.Bitcoin.Features.BlockStore.BlockStoreBehavior.AnnounceBlocks (-)
[2017-12-09 17:27:14.3021 39] TRACE: Stratis.Bitcoin.Features.BlockStore.BlockStoreBehavior.AnnounceBlocks (blockHashesToAnnounce.Count:1)
[2017-12-09 17:27:14.3021 39] TRACE: Stratis.Bitcoin.Features.BlockStore.BlockStoreBehavior.AnnounceBlocks announce to [::ffff:127.0.0.1]:61319 this hashes: 2c4858919960637fcc977393863d34028108c02fd707164341b9ff6463c073a9   
[2017-12-09 17:27:14.3021 39] DEBUG: Stratis.Bitcoin.Features.BlockStore.BlockStoreBehavior.AnnounceBlocks Sending header 2c4858919960637fcc977393863d34028108c02fd707164341b9ff6463c073a9 to peer '[::ffff:127.0.0.1]:61319'.
[2017-12-09 17:27:14.3021 39] TRACE: Stratis.Bitcoin.Features.BlockStore.BlockStoreBehavior.AnnounceBlocks (-)[SEND_HEADERS_PAYLOAD]
```

This is a announce scenario that causes a bug: 

```
[2017-12-09 17:56:51.2057 39] TRACE: Stratis.Bitcoin.Features.BlockStore.BlockStoreBehavior+<SendAsBlockInventoryAsync>d__24.MoveNext (-)
[2017-12-09 17:56:51.2057 39] TRACE: Stratis.Bitcoin.Features.BlockStore.BlockStoreBehavior.AnnounceBlocks (blockHashesToAnnounce.Count:1)
[2017-12-09 17:56:51.2057 39] TRACE: Stratis.Bitcoin.Features.BlockStore.BlockStoreBehavior.AnnounceBlocks announce to [::ffff:127.0.0.1]:61319 this hashes: 13c9d5b7db35e3526e2f2becceae9c3f2874fd12638acef3c668534432a4b2e7   
[2017-12-09 17:56:51.2057 39] TRACE: Stratis.Bitcoin.Features.BlockStore.BlockStoreBehavior.AnnounceBlocks (-)
```

I'll add more detailed logging to understand why exactly connector decides not to send a hash, looks like it depends on several factors.

**Comment by Aprogiena** [comment]
excellent, now we are getting somewhere, i was aware of AnnounceBlocks method but it's intended logic is unknown to me and it is even more unclear if it's intended logic is actually implemented well

there is a known (to me) bug in this method that the node will sometimes consider the peer to be at certain height (to advance to the height of the header we want to send) even if we have no confirmation of that (we just send the header and assume that will be accepted, which might not be the case obviously). but this itself does not seem to be able to cause the problem we are looking for

**Comment by noescape00** [comment]
Scenario of how this bug is happening: 

1) Let's say connector and miner are at height : 5, they are synced. 
2) Connector get's 6th block's hash from the network. 
3) Miner mines a block with height 6 and adds it to it's chain. 
4) Miner announces his block but it's hash get's denied by the connector because connector already has a hash at this height that he got from the network. 
5) Connector pulls 6th block. 
6) Connector tries to announce 6th block to the miner but because of the bug he end up not announcing it.
So now miner and connector are at the same height but the tip is different. 
7) Connector gets 7th block from the network. It announces now two blocks to the miner- 6 and 7. but only 7th actually get announced. 
7) Miner receives 7th block hash and denies it because it depends on 6th hash which is not known to the miner. 

More about step 6:
Here
`BlockStoreBehavior.AnnounceBlocks(List<uint256> blockHashesToAnnounce)`

blockHashesToAnnounce list has 1 hash. Inside the AnnounceBlocks we move some of them to the inner 'hashes' list and items from it actually get sent. And apparently at step 6 none of 1 hashes got to that list. 

And at step 7 blockHashesToAnnounce had 2 hashes but only the last one got to that list. 

The code that decides what subset of 'blockHashesToAnnounce' list should be actually announced is inside a `foreach (var hash in blockHashesToAnnounce)` statement. 


Now I'm adding some more logging to that method to see why exactly it throws that hash away.

**Comment by Aprogiena** [comment]
note that i believe that in step 4, this should not get denied
at least i understand CHB (ChainHeadersBehavior) that it is a view of a node of its peer. i.e. it should reflect the state of the peer regardless of the state of the node. so if the peer claims chain A with height 6 and node is on different chain B with height 7, this is all fine
and so is fine if the peer claims chain A with height 6 and node is on different chain B with height 6. if the chain is valid (we are talking chain of headers only!) then it should be accepted

**Comment by noescape00** [comment]
Sorry, by denied I meant that connector wont accept it to his best chain view and won't ask miner for that block to download. I didn't mean that it will just throw it away.

But thanks for clarifying how this part works exactly.

**Comment by noescape00** [comment]
Inside that foreach loop in AnnounceBlocks we are choosing if certain header should be sent or not. 


```
ChainedBlock chainedBlock = this.chain.GetBlock(hash); //this is a connector's chained block with HashBlock == hash that we should announce 
....

// In this line we are checking if miner has a block at the same height as the chained block that we want to announce. 
// Ofc it does, but they are different blocks! Miner has one that he mined and connector has one from the network. And because we assume that those blocks are the same we think that miner already knows that hash and we will not send it
// So we need to compare not only by height but also check if those are THE SAME BLOCKS. Because if they are not peer (miner) needs that hash!

else if (chainBehavior.PendingTip.GetAncestor(chainedBlock.Height) != null)
{
      continue;
}
```





So if my assumptions are correct replacing 

```
else if (chainBehavior.PendingTip.GetAncestor(chainedBlock.Height) != null)
{
      continue;
}
```

with 

```
else if (chainBehavior.PendingTip.GetAncestor(chainedBlock.Height) != null)
{
      var ancestor = chainBehavior.PendingTip.GetAncestor(chainedBlock.Height);
      if (ancestor.HashBlock != chainedBlock.HashBlock)
             headers.Add(chainedBlock.Header);
}
```

will actually fix the bug.

I'll test it.

**Comment by noescape00** [comment]
>On average this bug happens once in 30-40 blocks

Now I get why. This bug is possible only when miner produced an orphan.

**Comment by Aprogiena** [comment]
> Now I get why. This bug is possible only when miner produced an orphan.

This does not make much sense to me. I'll have to carefully read your analysis above, but this seems wrong.

**Comment by noescape00** [comment]
I've checked it and now I'm positive that this change affects only the bugged scenario and fixes it. 

I've added logging at the place where hash gets added instead of being discarded and ran the nodes for a night. Every time when hash was added instead of replacing I was able to see in miner's logs that miner mined a block just a few seconds (1-3) before that. 

And hash was never added in any other type of scenario.

**Comment by noescape00** [comment]
I'd also suggest adding the same change to this line:
`else if (chainBehavior.PendingTip.GetAncestor(chainedBlock.Previous.Height) != null)`

Because here we again are not checking if the ancestor of this height has the same block hash as we do.

**Comment by noescape00** [comment]
>This does not make much sense to me.

**Comment by noescape00** [comment]
>This does not make much sense to me.

I'll try to explain my reasoning: 

When we are announcing blocks we are checking every hash if we should indeed send it. If the peer we want to announce to has hash at the same height as our hash we won't send it to him because we assume that the peer has the same hash as we do. 
And now we found a scenario when this is not correct- when peer is a miner and he mined an orphaned block. So in this case he would have a hash at the same height as we do but it will be different. 

What I've proposed is that instead of assuming that hashes are equal we are checking if they are. And if they are we do what we did before. But if they don't we are sending the hash that we would normally skip assuming that peer already has it.

**Comment by Aprogiena** [comment]
i'll review tomorrow or on Tuesday then I'll let you know
if you ARE sure, you can, at your own risk, prepare a PR
if you are not sure, just wait for me to review :-)

**Comment by noescape00** [comment]
>i'll review tomorrow or on Tuesday then I'll let you know

Awesome, thx. 

>if you ARE sure, you can, at your own risk, prepare a PR

Yes, I'm sure. I've been running fixed version whole night yesterday and 5 hours today. Studied the logs- no sign of bug happening again (with the bugged code I'd usually get the bug after just 20-40 minutes of running connector-node scenario).
So I'll make a PR today.

**Comment by Aprogiena** [comment]
very good then, i'll review the PR then including this
