### ISSUE TITLE
[Tests] Integration tests that can't be ran in batch

### ISSUE THREAD

**Issue by mikedennis** [stratisproject/StratisBitcoinFullNode#867]
The following tests failed when running them with all the other integration tests but passed when ran alone, one at a time.

- BlockBroadcastInv
- Given__NodesAreSynced__When__ABigReorgHappens__Then__TheReorgIsIgnored
-
 Given__TheNodeHadAReorg_And_WalletTipIsBehindConsensusTip__When__ANewBlockArrives__Then__WalletCanRecover
- WalletCanReceiveAndSendCorrectly

I also had to manual shutdown orphan msbuild.exe tasks in task manager prior to running these tests. There was typically 3 orphan msbuild.exe tasks left after running these integration tests.

**Comment by dangershony** [comment]
I am closing this as lots have changed now.
