### ISSUE TITLE
[Tests] NBitcoin tests that currently fail

### ISSUE THREAD

**Issue by mikedennis** [stratisproject/StratisBitcoinFullNode#868]
These ones fail all the time (are from RPC Client Tests and REST Client Tests):

- CanGetBlockHeader
- CanGetRawMemPool
- CanGetTransaction
- CanGetTxOutAsyncFromRPC
- CanGetTxOutFromRPC
- CanGetUTXOsMempool
- CanUseAsyncRPC
- EstimateFeeRate
- TestFundRawTransaction

These ones I was able to get to pass by running alone but failed originally when running with full batch:

- CheckBlockProofOfStake
- IndexTheFullChain
- RawTransactionIsConformsToRPC

**Comment by mikedennis** [comment]
Some of the RPC test failures appear to be related to code commented out in this commit https://github.com/stratisproject/StratisBitcoinFullNode/pull/794

For example CanGetTxOutFromRPC needs this code https://github.com/stratisproject/StratisBitcoinFullNode/blob/master/src/NBitcoin.Tests/NodeBuilder.cs#L538

**Comment by dangershony** [comment]
If this is because of the removal of Node then perhaps @Aprogiena can comment, NetworkPeer (previously Node) is now much more flexible for testing as it makes more uses Interfaces.
@Neurosploit might also be interested in this.

**Comment by Neurosploit** [comment]
Thanks for the heads up @dangershony.

**Comment by Aprogiena** [comment]
interfaces on NP will be implemented soon (TM)

**Comment by bokobza** [comment]
All good now :-)
