### ISSUE TITLE
[Shutdown] Waiting for PeerConnectorDiscovery.ConnectAsync to finish. - takes too long

### ISSUE THREAD

**Issue by Aprogiena** [stratisproject/StratisBitcoinFullNode#874]
Sometimes this takes quite a long time on shutdown. It would be great if we could improve it to "immediately".

**Comment by Aprogiena** [comment]
@fassadlr I think I have improved this a little bit in the node job PR part 14. So not sure if it is worth investigating this until PR part 14 is merged. I'm not sure if I just improved it or fixed it. So it should not be closed, some investigation should be done after that PR is merged.

**Comment by fassadlr** [comment]
@Aprogiena I'm closing this issue as it was fixed with "Node Job 15"  #923 .

This issue was that the cancellation token wasn't being checked properly when trying to connect, causing a 20sec delay in peer discovery after each connection attempt failed.
