### ISSUE TITLE
WalletFilePath returns Null

### ISSUE THREAD

**Issue by D3m0nKingx** [stratisproject/StratisBitcoinFullNode#883]
Per conversation with @mikedennis we determined the Wallet Controller isn't filling the parameter for WalletFilePath in https://github.com/stratisproject/StratisBitcoinFullNode/blob/15d3ddcbf9a0da23ab8e5c775c893c26f269f515/src/Stratis.Bitcoin.Features.Wallet/Models/WalletGeneralInfoModel.cs#L10

Resulting in general-info api request to the node returning null:
```bash
{
  "walletFilePath": null,
  "network": "Main",
  "creationTime": "1512431701",
  "isDecrypted": true,
  "lastBlockSyncedHeight": 498757,
  "chainTip": 498757,
  "isChainSynced": true,
  "connectedNodes": 8
}
```

Possibly the Name Parameter should be the name of the Wallet?

**Comment by mikedennis** [comment]
I'll fix this.

**Comment by mikedennis** [comment]
There that is better

``` 
{
  "walletFilePath": "C:\\Users\\Test\\AppData\\Roaming\\StratisNode\\bitcoin\\TestNet\\mytest.wallet.json",
  "network": "TestNet",
  "creationTime": "1506484292",
  "isDecrypted": true,
  "lastBlockSyncedHeight": 1228403,
  "chainTip": 1254623,
  "isChainSynced": true,
  "connectedNodes": 2
} 
```
