### ISSUE TITLE
Refactor GetPowHash of Consensus class

### ISSUE THREAD

**Issue by quantumagi** [stratisproject/StratisBitcoinFullNode#888]
This issue relates to the GetPowHash delegate of the Consensus class:

"I dont like this delegate I would rather have an abstract (or an override on NetworkOptions that returns the POWHash() then stratis can override with its own part.
We can leave it to another PR but please create an issue for this." - Dan

**Comment by bokobza** [comment]
I'll close this as it's part of another issue.
