### ISSUE TITLE
[Commenting Style Change Proposal] Allow blank comments 

### ISSUE THREAD

**Issue by dangershony** [stratisproject/StratisBitcoinFullNode#892]
Comments are very valuable and we need good comment, various places in the code are proof for that.

However sometimes find good comments is not so easy to write and can take some time and discussion to complete, this should not stop the developer tough from completing her PR.
Either the comment is good or it should not be there.

And for that I propose I propose: 
- Simple and self explanatory code we can allow no comments. (for example the ILoggerFactory property is a repetitive comments on many implementations and I find myself just copy pasting form other places such a trivial piece of code, its also quite clear what it does and any more details a user can just navigate to the interface)
- Not simple code we allow blank comments as a temporary state.
- Comments can be a task on their own (as was before).
- Devs best practice should to fill comments and not postpone that to later.

**Comment by Aprogiena** [comment]
NACK

**Comment by bokobza** [comment]
Agree on these:
* Comments can be a task on their own (as was before).
* Devs best practice should to fill comments and not postpone that to later.

**Comment by fassadlr** [comment]
> Simple and self explanatory code we can allow no comments.

This just needs to be agreed upon by the dev and reviewer. Should they not agree, a third party can be introduced to help with the decision, although this should rarely be the case.

> Not simple code we allow blank comments as a temporary state.

We shouldn't allow not simple code to be committed without comments, unless agreed by the developer and the reviewer.

I want to add to this:

- Comment duplication shouldn't be required, i.e. if you have a property with proper comments, then a backing field shouldn't have to be documented again.
- You can refer to the explanation of enums by using the <see> tag, unless the enum's purpose is somehow used differently.

**Comment by dangershony** [comment]
>We shouldn't allow not simple code to be committed without comments

Comments can always be added later, the problem is if we don't have good comments the PR is stuck.

**Comment by Aprogiena** [comment]
@bokobza i'm no longer requiring ppl to write those comments, but i'll still write them, so if you want to write them too, i'm more than happy :-)
