### ISSUE TITLE
[PosMinting] Block mined during IBD

### ISSUE THREAD

**Issue by Aprogiena** [stratisproject/StratisBitcoinFullNode#896]
The following happened: 

```
info: Stratis.Bitcoin.Features.Miner.PosMinting[0]
      ==================================================================
info: Stratis.Bitcoin.Features.Miner.PosMinting[0]
      Found new POS block hash 'f8230171080cb3113b6ca46c57752874b8d6c81b9591a8546d1bd4d2650ebe0d' at height 223610.
info: Stratis.Bitcoin.Features.Miner.PosMinting[0]
      ==================================================================
info: Stratis.Bitcoin.FullNode[0]
      ======Node stats====== 12/13/2017 10:14:11 agent StratisBitcoin:1.0.5
      Headers.Height:        224454   Headers.Hash:         f207188bd53a9e0e2d8793908cc5ff7c501f86fd3d1d4487d90e0b811a85c1fb
      Consensus.Height:      223610   Consensus.Hash:       f8230171080cb3113b6ca46c57752874b8d6c81b9591a8546d1bd4d2650ebe0d
      BlockStore.Height:     223609   BlockStore.Hash:      09b6f955e4a110a8a4411cbfd0470edee847316b9c6c8e94b5280a7354a640ac
      Wallet.Height:         223609   Wallet.Hash:          09b6f955e4a110a8a4411cbfd0470edee847316b9c6c8e94b5280a7354a640ac

```

This should not happen.

**Comment by Aprogiena** [comment]
this is not solved, neither understood why it happened

only one clue - node made no connection for very long time when it was started, is this related?

**Comment by Aprogiena** [comment]
OK I think this could be caused by #921

**Comment by noescape00** [comment]
Since MaxTipAge is 24h (1300 blocks) it wasn't considered IBD (we have a check for IBD in PoSMinting). 
So even if we set MaxTipAge to smth lower it is still possible to mine a block until we're fully synced. 

Actually I think that it's ok to mine a block if our tip is synced with the network but we don't have the missing blocks. We're still sending those mined blocks to the network so why not consider mining in this state to be a correct thing?

**Comment by Aprogiena** [comment]
if we don't have missing blocks we can't mine, that's not ok
you need latest utxo set to be able to mine

**Comment by noescape00** [comment]
Ok. So we shell add a check if block store height reached the headers tip.

**Comment by dangershony** [comment]
>Ok. So we shell add a check if block store height reached the headers tip.

Hi why is this required?

As far as I can see the only two things we need to check to start mining is Consensus.Tip == Chain.Tip if that's true we can mine on top of Consensus.Tip

**Comment by noescape00** [comment]
>we need to check to start mining is Consensus.Tip == Chain.Tip

It is possible to have Consensus.Tip to be equal to Chain.Tip if we're not fully synced. Not very plausible though since consensus tip almost never reaches the chain tip until all the headers are downloaded. 

So probably having this + IBD check will do fine instead of checking the last block we have in the block store.

**Comment by dangershony** [comment]
In theory you should be able to mine on a pruned node in which case store wont be available.
However we are not there yet as then propagation will fail, we will nee to come up with a mechanism to store latest mined blocks in memory (perhaps separating the store cache from the store feature in some way) or even adding a new behaviour for pruned mining, that's a task later down the line.

>It is possible to have Consensus.Tip to be equal to Chain.Tip if we're not fully synced. 

Indeed but the mined block will not get propagated until the not synced block in the queue is propagated and we don't propagate until its persisted right?

**Comment by dangershony** [comment]
But if this was a problem I would add a new field in ChainState.StoreTip (or something similar)

**Comment by noescape00** [comment]
> and we don't propagate until its persisted right?

Until it's cached- after the recent block store cache improvements we're no longer waiting for the block to be persisted. 

>In theory you should be able to mine on a pruned node in which case store wont be available.

Ah, yeah, didn't think about that one. So for sure using block store is not the best way to do this.

**Comment by dangershony** [comment]
>Until it's cached- after the recent block store cache improvements 

Yes and my point still applies
