### ISSUE TITLE
[Connectors] -addnode and -connect don't work together as they should

### ISSUE THREAD

**Issue by Aprogiena** [stratisproject/StratisBitcoinFullNode#898]
so i have `-connect=IP` on command line and in conf i have couple of `addnode` lines, the expected behavior is that the node should only attempt to connect to that one IP and ignore knowledge from addnodes

**Comment by fassadlr** [comment]
@Aprogiena I've had a bit of a look through the history of ConnectionManager and it appears that we always executed AddNode connections even if -connect args was specified?

[Old ConnectionManager](https://github.com/stratisproject/StratisBitcoinFullNode/blob/a512de09f03841c74fee75368d5a42a4064569ab/src/Stratis.Bitcoin/Connection/ConnectionManager.cs)

So either it was always wrong and we should fix it or this is expected behaviour.

IMO I agree with you,  if -connect args is specified then we should only connect to that peer.

We should maybe think to rename those args to:

-connectexclusive
-connectinclude

**Comment by Aprogiena** [comment]
we should implement `-connect` just as bitcoin core has it
then we can add any other arguments if we want to but that connect one should be without name change and behave as in bitcoin core

currently it seems that we don't know how bitcoin core behaves
we have not checked it and i think it behaves differently than we have it now but i have not verified

**Comment by fassadlr** [comment]
Bitcoin Core's documentation on the subject:

`strUsage += HelpMessageOpt("-connect=<ip>", _("Connect only to the specified node(s); -connect=0 disables automatic connections (the rules for this peer are the same as for -addnode)"));`

`strUsage += HelpMessageOpt("-addnode=<ip>", _("Add a node to connect to and attempt to keep the connection open (see the `addnode` RPC command help for more info)"));`

My assumption is that they ONLY connect to the nodes specified in -connect if that arg is specified.

Thoughts?

**Comment by Aprogiena** [comment]
documentation is not clear, we need to investigate the code

**Comment by fassadlr** [comment]
Oh man, Im scared to go dig in that code base :P

**Comment by Aprogiena** [comment]
better lost your virginity sooner than later ;)

**Comment by Aprogiena** [comment]
So, I've examined the bahavior of Bitcoin Core clone and my understanding of how `-connect` should work was wrong.

It behaves like this. If you set `-connect=address` then the node will attempt to connect to that address and it DISABLES peer discovery, BUT it will attempt to connect to all your `addnode`s as well (this is the part that I thought is different). There was no difference to whether it was specified on command line or conf file.

So the difference between `connect` and `addnode` is only that using `connect` will disable discovery of other peers and you will attempt to connect only to those addresses specified by connect or addnode.

So, very likely our current implementation works exactly like that. @fassadlr could you confirm that and if it does, please close the issue as non-issue.

**Comment by fassadlr** [comment]
> So the difference between connect and addnode is only that using connect will disable discovery of other peers and you will attempt to connect only to those addresses specified by connect or addnode.

@Aprogiena I confirm the above.

**Comment by Aprogiena** [comment]
Thanks, appreciate.
