### ISSUE TITLE
Bug: PoS mining eventually stops and never starts after that. 

### ISSUE THREAD

**Issue by noescape00** [stratisproject/StratisBitcoinFullNode#900]
I've noticed this bug when was running a node on the test net in default configuration. It once stopped mining after around 12 hours and never started again until I restarted the node. It was connected and synced with the network. 

Unfortunately I can provide no more info about this, I'll try to recreate the bug and will update this issue in the future.

**Comment by bokobza** [comment]
I think this will be fixed in my next PR.

**Comment by noescape00** [comment]
This problem was fixed but we forgot about the issue, therefore I'm closing this.
