### ISSUE TITLE
[NetworkPeerClient] ConnectAsync timeout not working properly

### ISSUE THREAD

**Issue by fassadlr** [stratisproject/StratisBitcoinFullNode#913]
Hi @Aprogiena, I've noticed that the timeout that gets set in the PeerConnector's ConnectAsync method isn't getting honoured:

```
    var clonedConnectParamaters = this.CurrentParameters.Clone();
    timeoutTokenSource.CancelAfter(5000);
    clonedConnectParamaters.ConnectCancellation = timeoutTokenSource.Token;

    peer = this.networkPeerFactory.CreateConnectedNetworkPeer(this.network, peerAddress.NetworkAddress, clonedConnectParamaters);
    peer.VersionHandshake(this.Requirements, timeoutTokenSource.Token);
```

It takes about 20secs normally for the connect to timeout. I had a look at the connect code in NetworkPeerClient's ConnectAsync method. I changed this line:

```
await Task.Run(async () => await this.tcpClient.ConnectAsync(endPoint.Address, endPoint.Port), cancellation);
```

to:

```
this.tcpClient.ConnectAsync(endPoint.Address, endPoint.Port).Wait(cancellation);
```

And it instantly picked up the correct timeout. I know it makes the call synchronous but can you please look at this asap as we can't have the node taking 20secs to timeout before moving onto the next peer to connect to.

**Comment by fassadlr** [comment]
This will affect PeerDiscovery as well, which is probably the culprit behind #874.

**Comment by Aprogiena** [comment]
tx i'll check it although as mentioned in 874, some improvements have been made in part 14, but i'll check it

**Comment by Aprogiena** [comment]
i can see the connect cancellation is not always bound with shutdown, so that is missing, that i will fix
but that's different thing than you report, so i'll check that

**Comment by fassadlr** [comment]
@Aprogiena that IS the issue that needs fixing ;) the connect cancellation token is to set to X seconds in the peer connector... but that timeout isn't honored.

**Comment by Aprogiena** [comment]
no i mean component shutdown

**Comment by Aprogiena** [comment]
i'm testing the 5 second cancellation token now

**Comment by fassadlr** [comment]
Component shut down was working 💯 , its the issue with the peer connector's timeout thats not working.

**Comment by Aprogiena** [comment]
we are each talking  about something else, nevermind

anyway, i can't reproduce what you are saying, can you give me some more information or tell me how do i reproduce it?

**Comment by Aprogiena** [comment]
ok maybe i found a way

**Comment by fassadlr** [comment]
1: Run MainNet
2: Put a breakpoint here:

https://github.com/stratisproject/StratisBitcoinFullNode/blob/master/src/Stratis.Bitcoin/P2P/PeerConnector.cs#L218

3: Put a break point here:

https://github.com/stratisproject/StratisBitcoinFullNode/blob/master/src/Stratis.Bitcoin/P2P/PeerConnector.cs#L231

You'll see that if the connection fails due to timeout, it take about 20 seconds to throw the exception.

**Comment by Aprogiena** [comment]
little offtopic, but worth mentioning - i found that there are multiple attempts to connect to the peer that the other thread is trying to connect to before that connection attempt is completed
this could very well cause problems with completing the connection as if we connect more than once to the peer, we could get disconnected

**Comment by Aprogiena** [comment]
ok got it, tx, will fix in PR part 15

**Comment by fassadlr** [comment]
Is it possible that we can possibly push afix this sooner? IF you can though?

**Comment by Aprogiena** [comment]
might port it to PR 14 if trivial
