### ISSUE TITLE
File System dependencies not externalized

### ISSUE THREAD

**Issue by seanmobrien** [stratisproject/StratisBitcoinFullNode#914]
While reviewing the solution for code that needs unit tests, I noticed that file system access has not been externalized (IE, file system is accessed directly in code via calls to static methods instead of abstracted through an interface).  This makes it very difficult to write unit tests for many methods, as there is no way to mock these static calls.   I'd like to externalize these dependencies by writing a simple FileSystem class / IFIleSystem interface that wraps calls like Directory.DirectoryExists and File.ReadAllText, etc, and then leverage that interface to add unit tests for currently untested code.

**Comment by quantumagi** [comment]
We could consider extending the existing Stratis.Bitcoin.Utilities.FileStorage to form the basis for handling all file storage requirements.

**Comment by dangershony** [comment]
@seanmobrien this sounds like a great idea, indeed we are limited by the concrete static implementation.

**Comment by fassadlr** [comment]
@seanmobrien If you ever get around to do this, please submit a PR 👍
