### ISSUE TITLE
Project cannot load in VS2015 when VS2017 is installed

### ISSUE THREAD

**Issue by Derrick-** [stratisproject/StratisBitcoinFullNode#92]
In order for developers to open and build this solution in VS2015 when VS2017 is installed, a global.json file must be added to the project which specifies the core version to use.

![image](https://cloud.githubusercontent.com/assets/3766117/24520463/8deb11bc-1556-11e7-860c-3011791a4bae.png)

According to:
http://stackoverflow.com/questions/40674393/visual-studio-2017-install-breaks-visual-studio-2015-asp-net-core-projects

Is there any plan to upgrade this project to VS2017 in the near future?

**Comment by dangershony** [comment]
There is definitely a plan to upgrade, I don't think the next version of core will support xproj

**Comment by Derrick-** [comment]
Great. I've been really pleased with the improvements to .Net core in vs2017.
Thanks for the merge.
