### ISSUE TITLE
Make PeerConnectorDiscovery.MaximumNodeConnections a configurable option

### ISSUE THREAD

**Issue by noescape00** [stratisproject/StratisBitcoinFullNode#931]
Right now MaximumNodeConnections is set to 8 on initialization. 
Maybe it will be a good idea to make it configurable?

**Comment by fassadlr** [comment]
@noescape00 I'm also for removing hard coded values in the solution. Currently we pass a lot of values via command line args... but maybe we can have settings.json file?

**Comment by noescape00** [comment]
@fassadlr Yeah, having a single settings.json with all the constant's stat we're currently passing via args is a way to go. Could also make it very well structured and auto generated from the default values on the first node run. 

This is though pretty much out of scope of this issue so I'll create a new one.
