### ISSUE TITLE
Support building with latest .net sdk (2.1.2)

### ISSUE THREAD

**Issue by mikedennis** [stratisproject/StratisBitcoinFullNode#933]
If you only install the latest .net SDK (by itself) you can't build the full node. You either have to go back and install 2.0 or bump the version in global.json to the installed SDK version

You get this error:

"The current .NET SDK does not support targeting .NET Core 2.0. Either target .NET Core 1.1 or lower, or use a version of the .NET SDK that supports .NET Core 2.0"

This has been reported both by @D3m0nKingx  (on linux) and @MithrilMan (on Windows)

**Comment by D3m0nKingx** [comment]
I confirm this running in Linux the error reported is:

```
The specified SDK version [2.0.0] from global.json [/home/ader/coins/StratisBitcoinFullNode/src/global.json] not found; install specified SDK version
Did you mean to run dotnet SDK commands? Please install dotnet SDK from: 
  http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
```

I am able to build if i change the versioning in the global.json file to 2.1.3 that I have installed: 

```bash
ii  dotnet-host                                                 2.0.4-1                                                      amd64        Microsoft .NET Core Host - 2.0.4
ii  dotnet-hostfxr-2.0.4                                        2.0.4-1                                                      amd64        Microsoft .NET Core Host FX Resolver - 2.0.4 2.0.4
ii  dotnet-runtime-2.0.4                                        2.0.4-1                                                      amd64        Microsoft .NET Core Runtime - 2.0.4 Microsoft.NETCore.App 2.0.4
ii  dotnet-sdk-2.1.3      
```

**Comment by mikedennis** [comment]
I think we should remove the global.json file and let the default tooling take care of itself. Looking at the history it seems that this was added in order to support VS2015 in side by side installation with VS2017. See this commit back in March https://github.com/stratisproject/StratisBitcoinFullNode/commit/9debb6cd11e4720643f683127ad5d08d28c5b0b8  I have both VS2015 & VS2017 installed so will try removing and see if this is still an issue.
