### ISSUE TITLE
RPC behavior and folder structure

### ISSUE THREAD

**Issue by Derrick-** [stratisproject/StratisBitcoinFullNode#94]
If it is intended that the RPC responses be compliant with Bitcoin Core, serializable Model based formatters for the output structure can be created.

Project structure:
Currently a folder Controllers is in the Project root. As these controllers will only be used by the RPC feature, can we move the Controllers into the RPC folder? This would allow us to group RPC response formatters under the RPC folder as well.

**Comment by dangershony** [comment]
Yes we probably need to move Controllers.

Things to consider, at a later stage the mempool and store (and RPC) might become standalone features in their own nuget package, my initial intention was to place controllers in their respected features, this will be hard to achieve in the case of rawtransaction as its served from both store and mempool.

For now I support your plan for moving controllers to a folder under RPC

@NicolasDorier may want to be involved

**Comment by Derrick-** [comment]
Yes, I can see reorganizing under the individual features once possible.
All of the current controllers rely on FullNode, so perhaps creating a FullNodeController base class is a good step toward segregating the controllers based on dependencies.

**Comment by NicolasDorier** [comment]
I wanted to move them. Problem is that weird MVC rules (which can probably be override given enough time spent on it), enforce the controller folder structure by convention.

**Comment by Derrick-** [comment]
> place controllers in their respected features, this will be hard to achieve in the case of rawtransaction as its served from both store and mempool.

I think we can eventually vary the capabilities of the RPC controllers based on which features have been injected. If there's no store, getrawtransaction can just check the mempool and vice-versa.

> weird MVC rules 

The controllers were picked up in the new folder, perhaps this restriction has been eliminated in .Net Core.

**Comment by NicolasDorier** [comment]
> I think we can eventually vary the capabilities of the RPC controllers based on which features have been injected.

Yes that we the plan.

The plan is to have modular design so people can create plugins. Indeally we would inject controllers at runtime.
I have not managed to do it though..

**Comment by bokobza** [comment]
@nicolasdorier @derrick- have a look at how I'm registering controllers located in different assemblies here: https://github.com/stratisproject/Breeze/blob/master/Breeze/src/Breeze.Api/MvcBuilderExtensions.cs
Does this help?

**Comment by NicolasDorier** [comment]
@bokobza where have you find how to do ? I spent hours disassembling MVC Core libraries to know how to do it, and failed.

**Comment by bokobza** [comment]
@nicolasdorier la chance du débutant!
I guess I got lucky with my search (not always the case). 😀
