### ISSUE TITLE
[ChainHeadersBehavior] null reference bug

### ISSUE THREAD

**Issue by Aprogiena** [stratisproject/StratisBitcoinFullNode#940]
```
fail: Stratis.Bitcoin.P2P.Peer.NetworkPeer[0]
      [[::ffff:100.75.61.137]:16178] Exception occurred: System.NullReferenceException: Object reference not set to an instance of an object.
         at Stratis.Bitcoin.Base.ChainHeadersBehavior.AttachedPeer_MessageReceived(NetworkPeer peer, IncomingMessage message) in /home/stratis/StratisBitcoinFullNode/src/Stratis.Bitcoin/Base/ChainHeadersBehavior.cs:line 239
```

it is on this line

```
 tip = new ChainedBlock(header, header.GetHash(this.AttachedPeer.Network.NetworkOptions), prev);
```
AttachedPeer is null

**Comment by Aprogiena** [comment]
introcued by https://github.com/stratisproject/StratisBitcoinFullNode/commit/f45714fb76aef516fbfd6a5789a408828b64969f#diff-4d8e1fb5d08c565382444084e832b67d

@quantumagi how to fix this?

**Comment by dangershony** [comment]
If peer is null node got disconnected.
But the fix is probably to take a local variable of node (or options)

**Comment by Aprogiena** [comment]
you mean to save NetworkOptions when peer is attached to a private field of CHB and then use it? if so, sounds good

**Comment by D3m0nKingx** [comment]
Just an FYI, this occurred on Node Shutdown (after executing `Ctrl+c`)

**Comment by quantumagi** [comment]
Addressed in https://github.com/stratisproject/StratisBitcoinFullNode/pull/926/commits/f0dee9f60ca6b5620ecb768590a45965b03677b2

**Comment by D3m0nKingx** [comment]
I just reproduced this again on Node shutdown. My source is at  [f39d4bb](https://github.com/stratisproject/StratisBitcoinFullNode/commit/f39d4bbde622249ec81a39e616b3ec6a89181de8)

```bash
info: Stratis.Bitcoin.Connection.ConnectionManager[0]
      Stopping peer discovery...
info: Stratis.Bitcoin.FullNode[0]
      Waiting for DiscoverPeersAsync to finish.
info: Stratis.Bitcoin.FullNode[0]
      Waiting for PeerConnectorAddNode.ConnectAsync to finish.
info: Stratis.Bitcoin.Connection.ConnectionManagerBehavior[0]
      Peer '[::ffff:73.189.67.223]:16178' offline, reason: 'unknown'.
fail: Stratis.Bitcoin.P2P.Peer.NetworkPeer[0]
      [124-[::ffff:73.189.67.223]:16178] Exception occurred: System.NullReferenceException: Object reference not set to an instance of an object.
         at Stratis.Bitcoin.Base.ChainHeadersBehavior.AttachedPeer_MessageReceived(NetworkPeer peer, IncomingMessage message) in /home/stratis/StratisBitcoinFullNode/src/Stratis.Bitcoin/Base/ChainHeadersBehavior.cs:line 239
```
Log file:
[p2p-peer.txt](https://github.com/stratisproject/StratisBitcoinFullNode/files/1567710/p2p-peer.txt)

**Comment by Aprogiena** [comment]
As commented here https://github.com/stratisproject/StratisBitcoinFullNode/pull/926#commitcomment-26340710 the commit that @quantumagi mentioned only fixes the problem partially. There is more to this issue and it should be resolved by checking the attached peer at the start of the method and save it to local variable. 

Then those two lines where the network is obtained should be replaced.

**Comment by Aprogiena** [comment]
I believe I fixed this with my latest PR merged yesterday.
