### ISSUE TITLE
[PeerConnector] Discovery loop is resource heavy

### ISSUE THREAD

**Issue by Aprogiena** [stratisproject/StratisBitcoinFullNode#955]
FindPeerToConnectTo in PeerConnectorDiscovery repeates 50 times something that may always fail.
This is when 
- peer is null, OR
- peer is not null but is wrong one (one of the continue branch is executed), which happens when the node knows few peers

then we loop up to 50x without doing anything new or waiting for anything new.
And because this seems to be called again after 1 second, it seems that it can be very heavy on CPU.

Lowering this constant to something like 5 should be sufficient.

Also, that 50 is magic hardcoded constant, should be defined as constant and documented.

**Comment by fassadlr** [comment]
Fixed with #959
