### ISSUE TITLE
Should Propagation Algo be changed from 50% to 100% of Peers

### ISSUE THREAD

**Issue by D3m0nKingx** [stratisproject/StratisBitcoinFullNode#973]
>The propagation algorithm works like this:
>
>select half of the peers and send them the transaction
wait other half to propagate it back. if they did or we received a block with out tx- consider it propagated.

@noescape00 @fassadlr we can continue this matter on this thread.

Imho 100% of connected peers should have transactions broadcasted, giving more likelihood for a them to be propagated, and furthermore making it less likely for an attacker to be able to cripple the network. 

However, at this time this is theoretical and a stress test should be performed to monitor the performance/functionality of the network.

**Comment by zeptin** [comment]
I am jumping in here without any context, but I think the reason for the 50% figure is because the light wallet needs to know that the transaction has been broadcast (as it does not have a mempool). If the transaction is broadcast to 100% of light wallet peers, none of them will (I believe) send it back to the light wallet node, so you have no straightforward way to track if the transaction has actually propagated until it appears in a block.

**Comment by D3m0nKingx** [comment]
> If the transaction is broadcast to 100% of light wallet peers, none of them will (I believe) send it back to the light wallet node

@zeptin do you mean the whole light wallet network of peers or just the ones connected to a single node?

**Comment by noescape00** [comment]
@D3m0nKingx 

All the nodes (no matter full or light) on average have a target of 8 outbound connections. 

On light wallet you don't have a consensus and a mempool so you are not able to validate even your own transaction. So if we send a tx to 50% and get it propagated back from any node from the other 50% it not only means that tx was propagated but also that the tx was validated by the network. 

If we send the tx to 100% of the peers we have no way of knowing if it even was valid.

**Comment by D3m0nKingx** [comment]
Validated, meaning included in a block, which is also confirmed? not simply cause a node says "I got the transaction". 

Also wouldn't both the first half and the other half of the connected peers report back the tx was propagated/validated?  

Actually, being this is a POS system, that means the highest stakers are the only nodes that actually are reporting the official transaction validations... so not sure the logic here of using 50 / 50. Unless I'm not exactly understanding how the nodes are communicating, but I'm thinking which ever node forges the block then broadcasts it to all connected peers, and those peers broadcast it to theirs, so on and so forth.

So if block propagation is 100%, why not transactions....

**Comment by noescape00** [comment]
>Validated, meaning included in a block,

No. If a peer receives a tx and it spends inputs that the sender didn't have this peer won't validate the tx => the peer won't propagate the tx. 

So we assume that the tx is valid if it's included in the block AND\OR if the peers propagate it forward to other peers.

**Comment by noescape00** [comment]
>Also wouldn't both the first half and the other half of the connected peers report back the tx was propagated/validated?

The ones who receive the tx do not report if it was validated to the sender. 

And obviously we can't ask the peers about a specific tx because that would De-anonymize us. Also we can't ask about every single transaction (not ours included) because it makes too much overhead.

**Comment by noescape00** [comment]
> that means the highest stakers are the only nodes that actually are reporting the official transaction validations.

They just include the txes in the block. Every node with a mempool does the validation.

**Comment by noescape00** [comment]
>So if block propagation is 100%, why not transactions....

Because we wanna know if tx was validated\propagated before it was included to the block. 
And this information is extremely important in case it wasn't validated and propagated- so we can resend\remove it instead of waiting for a block with that tx that will never come.

**Comment by bokobza** [comment]
Like I said in https://github.com/stratisproject/StratisBitcoinFullNode/issues/957,

> The reason we send to half the peers is because in the case of the light wallet, where we don't have the mempool, we can't verify transactions.
> When we send the transaction to half the peers and that we receive it back from another peer, we know that it's been validated and passed on.
> For the full node wallet, this could probably be increased to 100%.
>

**Comment by bokobza** [comment]
Maybe we can see whether we have a mempool or not, and if we do, we propagate to 100% of our peers.

**Comment by noescape00** [comment]
>Maybe we can see whether we have a mempool or not, and if we do, we propagate to 100% of our peers.

No reason for that. 
On a light wallet we use LightWalletBroadcasterManager.cs and on a full node- FullNodeBroadcasterManager.cs

So in order to change the algho to 100% for the full node we need to change 

FullNodeBroadcasterManager => BroadcastTransactionAsync => PropagateTransactionToPeersAsync(tx,bool skipHalfOfThePeers) (line 34) from 

` await this.PropagateTransactionToPeersAsync(transaction, true);`

to 

`  await this.PropagateTransactionToPeersAsync(transaction, false);`

**Comment by bokobza** [comment]
I forgot about that, thanks @noescape00
