### ISSUE TITLE
[ChainHeadersBehavior] Use StartHeight of VersionPayload to initialize peer's pending tip

### ISSUE THREAD

**Issue by Aprogiena** [stratisproject/StratisBitcoinFullNode#995]
Is it a good idea or not? We don't have any hash, so we could only assume it is on the same chain. Would that harm?

**Comment by noescape00** [comment]
Imho this is only reasonable for the console output to have that start header instead of "unknown" until we've updated the pendingTip

**Comment by Aprogiena** [comment]
interesting idea, that's probably the best solution

**Comment by bokobza** [comment]
is this for the inbound/outbound connections with an "unknown" height?

**Comment by noescape00** [comment]
>is this for the inbound/outbound connections with an "unknown" height?

It's for every connection. 

"unknown" height basically means that we didn't send or receive any headers from the peer yet so we don't know the peer's height. To avoid that we can use StartHeight until the moment we exchange the headers.

**Comment by dangershony** [comment]
Hmm how did this change? initially we used the StartingHeight until pending tip was updated.

Besides we cant initialise pending tip just with a height we need the previous headers.

**Comment by Aprogiena** [comment]
there was some refactoring that introduced unknown instead of what was "bogus random" value that had nothing to do with the peer. 

the idea here is to use StartHeight not as pending tip, but to display where the new peer is before it sends headers

**Comment by noescape00** [comment]
>initially we used the StartingHeight until pending tip was updated.

We'were assuming peer's tip to be equal to ours which was not really correct so in the chain headers 
behavior refactoring a couple of weeks ago this assumption was deleted and instead we started using "unknown" in cases when pendingTip is null.

**Comment by Aprogiena** [comment]
yes and it seems like a good idea to use this StartHeight for the console info (and only for that), so that we reduce the display of "unknown" on the console
