### ISSUE TITLE
[Sync] Double IBD problem

### ISSUE THREAD

**Issue by Aprogiena** [stratisproject/StratisBitcoinFullNode#997]
Could be related to #938

Node 1 is at block 1900 (consensus), Node 2 is at block 2000 (consensus), best chain height is 2100 (both nodes headers tip). 

Node 1 will use LookaheadBlockPuller to ask for blocks from Node 2. Node 1 will use "getdata" message from BlockPullerBehavior.StartDownload to ask for block 2001. Node 2 will receive this in BlockStoreBehavior where is this sequence:

```
                // TODO: check if we need to add support for "not found"
                Block block = await this.blockStoreCache.GetBlockAsync(item.Hash).ConfigureAwait(false);

                if (block != null)
                {
                    this.logger.LogTrace("Sending block '{0}' to peer '{1}'.", item.Hash, peer?.RemoteSocketEndpoint);

                    //TODO strip block of witness if node does not support
                    await peer.SendMessageAsync(new BlockPayload(block.WithOptions(peer.SupportedTransactionOptions))).ConfigureAwait(false);
                }

``` 

This means that if Node 2 does not have this block, it will ignore "getdata" message.

Node 1 will have this block assigned to the Node 2 and marked as "pending download".

If Node 2 is the only peer that Node 1 is connected to, Node 1 is stuck and won't advance in consensus.

There are three things that should be implemented to fix this:
- node 2 should be polite and not to ignore "getdata" message, it should reply with "notfound" message
- node 1 should be able to understand "notfound" message and remove the assignment from the peer based on that
- node 1 should have timeout on block download, the mechanism is there in form of quality score, but it is not used if there is only one peer connected, therefore in this case (which can be well intended setup), it is normal that node 1 will stop syncing at some point. it should eventually timeout, it could be after couple of minutes, but it should be possible

**Comment by dangershony** [comment]
Investigate how this is done in bitcoin core.

**Comment by dangershony** [comment]
This will be fixed by the design of the refactor.

**Comment by noescape00** [comment]
Fixed with activation merge.
